edgelesssys/constellation

.github/docs/development.md
.lycheeignore

- Update verification dev docs to reference new tool

Update verification dev docs to reference new tool

---

.github/docs/README.md
.github/docs/development.md
.github/docs/release.md
docs/docs/workflows/create.md
docs/docs/workflows/recovery.md
docs/docs/workflows/scale.md
docs/docs/workflows/ssh.md
docs/docs/workflows/storage.md
docs/docs/workflows/terminate.md
docs/docs/workflows/trusted-launch.md
docs/docs/workflows/upgrade.md
docs/docs/workflows/verify-cluster.md
docs/sidebars.js
docs/versioned_docs/version-2.0/workflows/create.md
docs/versioned_docs/version-2.0/workflows/recovery.md
docs/versioned_docs/version-2.0/workflows/scale.md
docs/versioned_docs/version-2.0/workflows/ssh.md
docs/versioned_docs/version-2.0/workflows/storage.md
docs/versioned_docs/version-2.0/workflows/terminate.md
docs/versioned_docs/version-2.0/workflows/trusted-launch.md
docs/versioned_docs/version-2.0/workflows/upgrade.md
docs/versioned_docs/version-2.0/workflows/verify-cluster.md
docs/versioned_sidebars/version-2.0-sidebars.json

More concise language and re-ordering in the workflow section.

Re-wording in docs/workflows

---

.github/actions/build_cli/action.yml
.github/actions/generate_measurements/action.yml
.github/docs/release.md
.github/workflows/e2e-test-azure.yml
.github/workflows/e2e-test-gcp.yml
.github/workflows/e2e-test-manual.yml
.github/workflows/generate-measurements.yml
.github/workflows/release-cli.yml

- Build E2E CLIs as OSS
- Don't sign E2E artifacts

AB#2415: Don't sign & measure E2E artifacts

---

.github/workflows/test-govulncheck.yml
README.md

- Add [govulncheck](https://go.dev/blog/vuln)
- Fix links of e2e badge in README, now points to workflow instead of svg.

Add govulncheck action

---

docs/docs/getting-started/first-steps.md
docs/docs/workflows/verify-cluster.md
docs/versioned_docs/version-2.0/getting-started/first-steps.md
docs/versioned_docs/version-2.0/workflows/verify-cluster.md

Most changes should be self-explanatory.
Take a look at the echo commands in the two scripts. I changed it because when copy-pasting it in my terminal, output and commands were mixed and thus the output wasn't easy to read. Is it okay to use echo like this?

docs: minor fixes in first steps and wording improvements

---

.github/docs/README.md

- Explain the required (missing) secerts in the E2E README.md
- Write *act* in italics in the README.md text (in order for the reader to not confuse it with the verb *to act*)
- Follow up from #148

E2E: Add missing secrets to README.md

---

image/runner/cloud-init.txt

- No changes, just c&p content from GCP

Ensure cloud-init is up-to-date with GCP

---

hack/go.mod
hack/go.sum

Upgrade go-tuf

---

go.mod
go.sum

- Upgrade go-tuf in main go.mod
- [Unit tests](https://github.com/edgelesssys/constellation/actions/runs/3069775231)
- [Integration tests](https://github.com/edgelesssys/constellation/actions/runs/3069776441/jobs/4958806470)

Upgrade go-tuf in main go.mod

---

.github/actions/e2e_test/action.yml
.github/workflows/e2e-test-manual-macos.yml

- Pin GitHub action against specific hash (only noticed this right after merging #159 :/)

Pin cache action against specific commit

---

.github/workflows/build-binaries.yml
.github/workflows/check-licenses.yml
.github/workflows/check-links.yml
.github/workflows/docs-vale.yml
.github/workflows/test-govulncheck.yml
.github/workflows/test-integration.yml
.github/workflows/test-lint.yml
.github/workflows/test-shellcheck.yml
.github/workflows/test-tidy.yml
.github/workflows/test-unittest.yml

- Add go-tidy-check action
- Checkout last commit instead of merge commit on pull_request event

Add go-tidy-check workflow

---

README.md
docs/docs/overview/license.md
docs/versioned_docs/version-2.0/overview/license.md

Extend the community license to evaluation purposes and non-commercial use.

Extend community license

---

docs/docs/getting-started/first-steps.md
docs/docs/getting-started/install.md
docs/versioned_docs/version-2.0/getting-started/first-steps.md
docs/versioned_docs/version-2.0/getting-started/install.md

Rewording in "Getting started"

---

terraform/aws/iam/main.tf
terraform/aws/iam/output.tf
terraform/aws/iam/variables.tf
terraform/aws/main.tf
terraform/aws/modules/instance_group/main.tf
terraform/aws/modules/instance_group/variables.tf
terraform/aws/modules/load_balancer/main.tf
terraform/aws/modules/load_balancer/output.tf
terraform/aws/modules/load_balancer/variables.tf
terraform/aws/variables.tf

- Terraform to create instance IAM roles (aka. serivce accounts attached to the instances)
- Terraform to create a Constellation look-alike infrastructure

initial AWS terraform

---

internal/versions/versions.go

Upgrade operator version

---

.github/workflows/test-tidy.yml

- Leads to frequent failures in "Post Setup Go" step, like in [this run](https://github.com/edgelesssys/constellation/actions/runs/3195486834/jobs/5216222994)

Deactivate cache for tidycheck workflow

---

cli/internal/cmd/create.go
cli/internal/cmd/init.go
cli/internal/cmd/terminate.go

- Reduce the movement in the CLI output a little, deactivating the spinner dots for now

Reduce activation indication movement

---

.github/workflows/e2e-test-azure-weekly.yml
.github/workflows/e2e-test-azure.yml
.github/workflows/e2e-test-gcp-weekly.yml
.github/workflows/e2e-test-gcp.yml
CHANGELOG.md
bootstrapper/internal/kubernetes/k8sapi/resources/node_maintenance_operator.go
bootstrapper/internal/kubernetes/k8sapi/resources/node_operator.go
internal/versions/versions.go
internal/versions/versions_test.go

- Move Kubernetes version window, v1.22 is removed, v1.24 is now default
- Bump Kubernetes and related dependencies versions

Upgrade Kubernetes versions

---

docs/docs/getting-started/first-steps.md
docs/docs/getting-started/install.md
docs/docs/getting-started/mini-constellation.md
docs/sidebars.js
docs/styles/Vocab/constellation/accept.txt

- Add documentation for `constellation mini`

Constellation mini docs

---

docs/docs/getting-started/first-steps.md
docs/docs/getting-started/install.md

- Make the mini Constellation references a bit more visible by wrapping them in a tip box

Wrap references to mini Constellation in tip boxes

---

docs/docs/architecture/attestation.md
docs/docs/architecture/keys.md
docs/docs/architecture/networking.md
docs/docs/architecture/orchestration.md
docs/docs/architecture/overview.md
docs/docs/architecture/versions.md
docs/sidebars.js
docs/versioned_docs/version-2.0/architecture/attestation.md
docs/versioned_docs/version-2.0/architecture/keys.md
docs/versioned_docs/version-2.0/architecture/networking.md
docs/versioned_docs/version-2.0/architecture/orchestration.md
docs/versioned_docs/version-2.0/architecture/overview.md
docs/versioned_docs/version-2.0/architecture/versions.md
docs/versioned_docs/version-2.0/getting-started/first-steps.md
docs/versioned_docs/version-2.1/architecture/attestation.md
docs/versioned_docs/version-2.1/architecture/keys.md
docs/versioned_docs/version-2.1/architecture/networking.md
docs/versioned_docs/version-2.1/architecture/orchestration.md
docs/versioned_docs/version-2.1/architecture/overview.md
docs/versioned_docs/version-2.1/architecture/versions.md
docs/versioned_sidebars/version-2.0-sidebars.json
docs/versioned_sidebars/version-2.1-sidebars.json

A few fixes and some wording simplifications of the architecture pages.

docs: fixes and rewording of architecture

---

.github/workflows/build-gcp-guest-agent.yml
.github/workflows/e2e-test-manual-macos.yml
3rdparty/gcp-guest-agent/Dockerfile
CHANGELOG.md
CMakeLists.txt
cli/internal/cmd/create.go
cli/internal/cmd/create_test.go
cli/internal/cmd/init.go
cli/internal/cmd/init_test.go
cli/internal/cmd/miniup.go
cli/internal/cmd/spinner.go
cli/internal/cmd/spinner_test.go
cli/internal/cmd/terminate.go
cli/internal/cmd/terminate_test.go
hack/qemu-metadata-api/Dockerfile
internal/config/images_enterprise.go
internal/versions/versions.go
operators/constellation-node-operator/Dockerfile

- Cherry-picked changes from branch `release/v2.1`

Release v2.1

---

.github/actions/constellation_create/az-logs.sh
.github/actions/constellation_create/gcp-logs.sh
.github/docs/development.md
cli/internal/helm/generateCilium.sh
cli/internal/libvirt/start.sh
hack/azure-jump-host/jump-host-create
hack/check-licenses.sh
hack/fetch-broken-e2e/fetch.sh
hack/fetch-broken-e2e/find.sh
hack/importAzure.sh

- As `/bin/bash` doesn't exist on all *nixes. :snowflake:

Use env to find bash in shebang

---

.github/actions/constellation_create/action.yml
.github/actions/e2e_test/action.yml
.github/actions/pseudo_version/action.yml
.github/workflows/e2e-test-azure-weekly.yml
.github/workflows/e2e-test-azure.yml
.github/workflows/e2e-test-manual-macos.yml
.github/workflows/e2e-test-manual.yml
.github/workflows/generate-measurements.yml
.github/workflows/test-govulncheck.yml
.github/workflows/test-lint.yml
.github/workflows/test-tidy.yml

Fix replace deprecated set-output syntax

---

cli/internal/terraform/terraform/aws/main.tf
cli/internal/terraform/terraform/aws/modules/load_balancer_target/main.tf
cli/internal/terraform/terraform/aws/modules/load_balancer_target/variables.tf
cli/internal/terraform/terraform/aws/modules/private_public_subnet/main.tf
cli/internal/terraform/terraform/aws/modules/private_public_subnet/variables.tf

- Add the `constellation-uid` tag to all created resources
- See the [Terraform documentation](https://www.hashicorp.com/blog/default-tags-in-the-terraform-aws-provider) for more details
- Create a cloudwatch log group for the Constellation
- Required by https://github.com/edgelesssys/constellation/pull/232

Add UID tag to all resources and create log group

---

docs/docs/overview/performance.md

Based on feedback from @laralaske & @thomasstrottner:
- We should choose a more neutral title for the further performance comparison since the results show speed gains for Constellation in our scenarios
- Consistent heading level for Storage section

Wording in performance docs

---

docs/docs/getting-started/first-steps.md
docs/docs/getting-started/install.md
docs/docs/getting-started/mini-constellation.md
docs/docs/reference/cli.md
docs/docs/workflows/create.md
docs/sidebars.js
docs/versioned_docs/version-2.1/getting-started/first-steps.md
docs/versioned_docs/version-2.1/getting-started/install.md
docs/versioned_docs/version-2.1/getting-started/mini-constellation.md
docs/versioned_docs/version-2.1/reference/cli.md
docs/versioned_sidebars/version-2.1-sidebars.json

- Use MiniConstellation instead of mini Constellation or Mini Constellation
- Use "First steps (local)" sidebar
- Reference from "Create your cluster"

Update wording for MiniConstellation in docs

---

.github/workflows/test-tf.yml
.github/workflows/test-tfsec.yml
cli/internal/terraform/terraform/qemu/main.tf
cli/internal/terraform/terraform/qemu/modules/instance_group/main.tf
terraform/aws/variables.tf

- Add Terraform validation workflow
- Add tfsec workflow
**TODO:**

Setup Terraform CI

---

cli/internal/terraform/terraform/azure/main.tf

- `confidential_vm` wasn't passed to submodule.

Fix Azure Terraform for non-CVMs

---

.github/docs/nfs.md

- Document Rook/CephFS deployment on Constellation
You can use `[...]Microsoft.Compute/galleries/Constellation_Testing/images/leo-test/versions/2022.0927.211132` for testing. 
Currently just for internal purposes because of the issues with the current main VM image.

add documentation for Rook/CephFS

---

renovate.json

- Group update of github-action versions

Renovate: group action upgrades

---

.github/workflows/e2e-test-azure-weekly.yml
.github/workflows/e2e-test-azure.yml

- Terraform provider doesn't work with the az CLI login, so use env vars for the credentials.

Change Azure auth method for e2e test

---

.github/workflows/azure-snp-reporter.yml
.github/workflows/build-binaries.yml
.github/workflows/build-ccm-gcp.yml
.github/workflows/build-gcp-guest-agent.yml
.github/workflows/test-govulncheck.yml
.github/workflows/test-integration.yml
.github/workflows/test-lint.yml
.github/workflows/test-shellcheck.yml
.github/workflows/test-tf.yml
.github/workflows/test-tfsec.yml
.github/workflows/test-tidy.yml
.github/workflows/test-unittest.yml

Actions are free for public repos and we want to see every CI failure
- Allow concurrent actions on the same branch.

Allow concurrent actions on the same branch.

---

docs/versioned_docs/version-2.0/overview/performance.md
docs/versioned_docs/version-2.1/getting-started/mini-constellation.md
docs/versioned_docs/version-2.1/overview/performance.md
docs/versioned_docs/version-2.1/workflows/create.md

Publish those changes of *next* that are already released.

publish doc changes

---

renovate.json

Group etcd dependency upgrades

---

kms/Dockerfile
operators/constellation-node-operator/Dockerfile

Use nonroot distroless container for KMS

---

renovate.json

Group updates of Google cloud dependencies

---

.github/workflows/build-access-manager-image.yml
.github/workflows/build-binaries.yml
.github/workflows/build-constellation-node-operator.yml
.github/workflows/build-joinservice-image.yml
.github/workflows/build-kms-image.yml
.github/workflows/build-verification-service.yml
.github/workflows/check-links.yml
.github/workflows/docs-vale.yml
.github/workflows/test-govulncheck.yml
.github/workflows/test-helm-lint.yaml
.github/workflows/test-integration.yml
.github/workflows/test-lint.yml
.github/workflows/test-shellcheck.yml
.github/workflows/test-tf.yml
.github/workflows/test-tfsec.yml
.github/workflows/test-tidy.yml
.github/workflows/test-unittest.yml
.github/workflows/update-cli-reference.yml

Run tests on push to release branch

---

.github/workflows/build-binaries.yml
.github/workflows/check-licenses.yml
.github/workflows/check-links.yml
.github/workflows/docs-vale.yml
.github/workflows/test-govulncheck.yml
.github/workflows/test-integration.yml
.github/workflows/test-lint.yml
.github/workflows/test-shellcheck.yml
.github/workflows/test-tf.yml
.github/workflows/test-tfsec.yml
.github/workflows/test-tidy.yml
.github/workflows/test-unittest.yml

- Checkout branch instead of head commit, so git is not in detached state.
- Tidy Go mods and commit on renovate branches.

Tidy modules on renovate branches

---

docs/docs/getting-started/first-steps-local.md
docs/versioned_docs/version-2.1/getting-started/first-steps-local.md

- Add not dropping forwarded packages to system requirements for local setup

Add hint about problematic iptables rules to minic11n requirements

---

cli/internal/cmd/create.go
cli/internal/cmd/init.go
cli/internal/cmd/miniup.go
cli/internal/cmd/spinner.go
cli/internal/cmd/spinner_test.go
cli/internal/cmd/terminate.go
go.mod
hack/go.mod
hack/go.sum

- Fixes dots not being displayed correctly and hides the cursor while printing them

Hide cursor and fix dots

---

image/mkosi.conf.d/aws.conf
image/mkosi.reposdir/amzn2-core.repo
image/mkosi.skeleton/usr/lib/dracut/modules.d/39constellation-mount/module-setup.sh

- Add AWS nvme udev rules
- We will have to build new images and test with the disk-mapper if everything works as expected.

Add AWS nvme udev rules

---

rfc/updates.md

Thanks to @malt3 for the joint work on this!

initial draft for automatic updates

---

.github/actions/build_micro_service/action.yml
.github/actions/build_operator/action.yml
.github/actions/container_sbom/action.yml
.github/workflows/build-access-manager-image.yml
.github/workflows/build-constellation-node-operator.yml
.github/workflows/build-joinservice-image.yml
.github/workflows/build-kms-image.yml
.github/workflows/build-micro-service-manual.yml
.github/workflows/build-operator-manual.yml
.github/workflows/build-verification-service.yml
.github/workflows/release-cli.yml
CHANGELOG.md
docs/docs/workflows/sbom.md
docs/sidebars.js
docs/styles/Vocab/constellation/accept.txt

- SBOMs are now:
- Generated for each build (not just releases).
- Signed using cosign
- "attached to container image" and uploaded to ghcr.io. The verification step was added as documentation and test: `cosign verify-attestation ...`
- For CLI's SBOM a detached signature is added to release artifacts.
- Grype is used to automatically fail a build if a vulnerability with risk "high" is found in generated SBOMs.
Images
* https://github.com/edgelesssys/constellation/actions/runs/3274150228
* https://github.com/edgelesssys/constellation/actions/runs/3274150318
* https://github.com/edgelesssys/constellation/actions/runs/3274150407
* https://github.com/edgelesssys/constellation/actions/runs/3274150491
* …

AB#2508 Create signed SBOMs for each build

---

.github/workflows/build-os-image.yml

- Use versioned Azure login action
- Use versioned actions in build-os-image.yml
Accidental upgrade from renovate. Use composite action with v1.4.6 instead.
```
node:internal/modules/cjs/loader:936
throw err;
^
Error: Cannot find module '@actions/core'
Require stack:
- /home/runner/work/_actions/azure/login/642a43caaacadeef67ecede5930b25d56e8277af/lib/main.js
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
at Function.Module._load (node:internal/modules/cjs/loader:778:27)
at Module.require (node:internal/modules/cjs/loader:1005:19)
at require (node:internal/modules/cjs/helpers:102:[18](https://github.com/edgelesssys/constellation/actions/runs/3297740886/jobs/5439488426#step:6:19))
at Object.<anonymous> …
```

Use versioned Azure login action

---

.github/docs/nfs.md

- Now works with default Constellation image due to documented workaround

add Rook deployment workaround

---

internal/versions/versions.go

- Upgrade libvirt container image

Upgrade libvirt container image

---

image/mkosi.skeleton/usr/lib/dracut/modules.d/39constellation-mount/aws-nvme-disk.service
image/mkosi.skeleton/usr/lib/dracut/modules.d/39constellation-mount/aws-nvme-disk.sh
image/mkosi.skeleton/usr/lib/dracut/modules.d/39constellation-mount/module-setup.sh

- Manually create AWS state disk symlink

Manually create AWS state disk symlink

---

internal/versions/versions.go

Update operator image

---

bootstrapper/internal/helm/client.go
bootstrapper/internal/helm/client_test.go
bootstrapper/internal/kubernetes/k8sutil.go
bootstrapper/internal/kubernetes/kubernetes.go
bootstrapper/internal/kubernetes/kubernetes_test.go
cli/internal/cloudcmd/upgrade_test.go
cli/internal/cloudcmd/validators.go
cli/internal/cmd/upgradeplan_test.go
cli/internal/helm/loader.go
cli/internal/helm/values.go
cli/internal/terraform/variables.go
hack/pcr-reader/main.go
hack/qemu-metadata-api/server/server_test.go
internal/attestation/vtpm/attestation.go
internal/attestation/vtpm/attestation_test.go
internal/config/measurements.go
internal/config/measurements_test.go
internal/deploy/helm/helm.go

Replace interface{} -> any

---

internal/attestation/aws/validator.go
internal/attestation/aws/validator_test.go

Use indirection to create ec2 client on demand

Fix return value issue

---

bootstrapper/internal/kubernetes/k8sapi/constants.go
bootstrapper/internal/kubernetes/k8sapi/k8sutil.go
image/mkosi.finalize
image/mkosi.skeleton/usr/lib/systemd/system-preset/30-constellation.preset
image/mkosi.skeleton/usr/lib/systemd/system/kubelet.service
internal/versions/versions.go

- Preinstall kubelet systemd unit in OS images

Preinstall kubelet systemd unit in OS images

---

.github/workflows/test-operator-codegen.yml

- This new CI workflow checks that the generated code in the Constellation node operator is up to date.

Test operator code generation is up to date

---

.github/actions/gcp_login/action.yml

- Pin setup-gcloud action to git tag (for renovate)

Pin setup-gcloud action to git tag (for renovate)

---

.github/workflows/test-tidy.yml
renovate.json

- Use fine grained GitHub PAT to commit "go mod tidy" fixes

Use fine grained GitHub PAT to commit "go mod tidy" fixes

---

internal/versions/versions.go

Add AWS CCM versions

---

rfc/updates.md

- Add backup warning to update RFC

RFC: update updates RFC

---

renovate.json

- Group AWS and Azure SDKs for renovate

Group AWS and Azure SDKs for renovate

---

renovate.json

renovate: bundle Python dependencies

---

.github/docs/longhorn.md

- Document the changes needed if we want to support Longhorn.

Docs: image changes for Longhorn support

---

renovate.json

- fix previous commit, missed the group name

renovate: name Python package group

---

bootstrapper/internal/kubernetes/k8sapi/kubeadm_config_test.go
internal/versions/versions.go
renovate.json

- Use renovate to update versions.go
Thanks @katexochen!

AB#2505 Use renovate to update versions.go

---

.github/actions/e2e_test/action.yml
.github/workflows/e2e-test-manual-macos.yml
.github/workflows/e2e-test-manual.yml

e2e: add nop payload to only test infra creation

---

cli/internal/cloudcmd/clients_test.go
cli/internal/cmd/cloud_test.go
disk-mapper/internal/setup/setup_test.go
go.mod
go.sum
hack/pcr-reader/main_test.go
internal/attestation/vtpm/vtpm_test.go
internal/config/config_test.go
internal/watcher/validator_test.go

- The relevant fix: https://github.com/daniel-weisse/go-tpm-tools/commit/f2255501dfc41093191240c9f64778ed5fa03ff2

Update go-tpm-tools to fix AWS PCR selection

---

.github/actions/constellation_create/action.yml
.github/actions/constellation_create/gcp-logs.sh

- Boot log collection was broken since d973740b037441435472fd8e9ece999d6b46f078, is fixed with this PR.

e2e: fix collection of boot logs on GCP

---

verify/cmd/main.go

- similar to https://github.com/edgelesssys/constellation/pull/407 and https://github.com/edgelesssys/constellation/pull/406

verify: undefine -v flag due to glog collision

---

internal/versions/versions.go

bump verification service

---

README.md

Update e2e badges in README

---

.github/workflows/build-os-image.yml

- Update mkosi to version 14
https://github.com/systemd/mkosi/releases/tag/v14

Update mkosi to version 14

---

.github/workflows/e2e-test-weekly.yml

- Add k-bench to weekly e2e test run.

e2e: add k-bench to weekly run

---

internal/attestation/azure/snp/validator.go

- Played around with go's fuzz feature. Actually found a bug :D

Fix invalid slice access in validateAk

---

rfc/external-kms.md

My research on Vault and how we could go on with realizing the external KMS feature.
@datosh How well do you know Vault? Can you check my findings to see if I have missed something?

RFC: external KMS

---

.github/workflows/build-os-image.yml
image/upload/upload_aws.sh

AB#2571 Make AMI public on creation

---

README.md

Add "Demo" section with note on Rocket.Chat to README

Add demo section to README

---

internal/versions/versions.go

- bump verify image 
- this image is the first with AWS support

bump verify image 20221104

---

docs/docusaurus.config.js

- Add plausible.io metrics to docs
- Using the docusaurus integration (used by plausible docs themselves): https://plausible.io/docs/docusaurus-integration

Add plausbile to docusaurus

---

hack/terraform/aws/iam/main.tf

- extend permissions to allow logging
-

extend permissions to allow logging

---

cli/internal/cloudcmd/create.go
cli/internal/cmd/configgenerate.go
cli/internal/cmd/configinstancetypes.go
cli/internal/cmd/validargs.go

- Remove explicit opt-in for AWS
Not sure if we still want to warn about AWS because of missing cloud features.

cli: remove debug env check for AWS

---

docs/docs/workflows/verify-cluster.md

- Mention why there are more measurements than enforcedPCRs

Explain unenforced measurements in config

---

cli/internal/terraform/terraform/aws/modules/instance_group/main.tf
cli/internal/terraform/terraform/aws/modules/public_private_subnet/main.tf
cli/internal/terraform/terraform/azure/modules/scale_set/main.tf
cli/internal/terraform/terraform/gcp/modules/instance_group/main.tf

Mark externally managed terraform resources to make infrastructure terraform appliable throughout its lifetime

---

cli/internal/terraform/terraform/aws/main.tf

- Remove SSH target on the default AWS load balancer 
This was mainly just useful for early bringup and general verification if the LB setup works using ordinary OS images such as Ubuntu. Since we have Constellation images now with our own debug daemon, it's not necessary anymore (and even confusing as you don't have guarantees which worker node you'll actually hit without further configuration - it's behind a load balancer after all).

AWS: Don't expose SSH debugging ports on the load balancer

---

Dockerfile.build
access_manager/Dockerfile
joinservice/Dockerfile
kms/Dockerfile
verify/Dockerfile

see example: https://docs.docker.com/engine/reference/builder/#run---mounttypecache
Note this is cache is separate from your local go compiler cache.

docker: cache go compiler

---

rfc/image-discoverability.md
rfc/secure-software-distribution.md
rfc/updates.md

- RFC for image discoverability (description of image version uid)

AB#2566 RFC for image discoverability (description of image version uid)

---

.github/actions/generate_measurements/action.yml
.github/docs/release.md
.github/workflows/build-os-image.yml
.github/workflows/release-cli.yml
CHANGELOG.md
CMakeLists.txt
cli/internal/cmd/minidown.go
cli/internal/cmd/miniup.go
cli/internal/helm/charts/edgeless/constellation-services/Chart.yaml
cli/internal/helm/charts/edgeless/constellation-services/charts/autoscaler/Chart.yaml
cli/internal/helm/charts/edgeless/constellation-services/charts/ccm/Chart.yaml
cli/internal/helm/charts/edgeless/constellation-services/charts/cnm/Chart.yaml
cli/internal/helm/charts/edgeless/constellation-services/charts/join-service/Chart.yaml
cli/internal/helm/charts/edgeless/constellation-services/charts/kms/Chart.yaml
internal/config/config.go
internal/config/images_enterprise.go
internal/versions/versions.go

- Bump versions to v2.2.0
- Fix pipeline for release builds
- Update release docs
- Update mini constellation defaults
- raw image instead of qcow2
- fix `mini down` not parsing the `yes` override flag
- Update Changelog
- Please check if I missed anything in the changelog you would like to have added there

Bring in changes from release branch

---

hack/terraform/aws/iam/README.md

Following the link from the docs to the folder, it may not be obvious for everyone what to do next. So I suggest adding these instructions.

add brief instructions to AWS IAM Terraform script

---

.github/actions/constellation_destroy/action.yml
.github/actions/e2e_test/action.yml
.github/actions/k-bench/action.yml
.github/workflows/e2e-test-daily.yml
.github/workflows/e2e-test-manual-macos.yml
.github/workflows/e2e-test-manual.yml
.github/workflows/e2e-test-weekly.yml

- Deletion of persistent volumes failed in case where there wasn't a kubeconfig, and termination of Constellation didn't happen. Fixed by continuing on error and checking input. See https://github.com/edgelesssys/constellation/actions/runs/3413360699/jobs/5679984053
- Delete PV deletion in k-bench payload, so it's not done twice.

e2e: fix deletion of persisten volumes

---

.github/docs/development.md
README.md
docs/versioned_docs/version-2.0/workflows/recovery.md
hack/azure-jump-host/jump-host-create
hack/azure-jump-host/parameters.json

- I was hitting a resource not found error because I was using different locations. This patch should prevent that error from happening.

Take location from state file for az jump host

---

.github/actions/os_build_variables/action.yml
.github/workflows/build-os-image.yml
image/upload/upload_aws.sh

AB#2571 Only publish release AMIs

---

.github/docs/nfs.md

- Some more notes on how to verify that Ceph created the correct devices. 
- Also mention the Constellation CSI driver that offer more protection.

docs: verify Ceph encryption

---

.github/actions/os_build_variables/action.yml

- Set azureImageOffer for debug images

Set azureImageOffer for debug images

---

cli/internal/cloudcmd/upgrade.go
cli/internal/cloudcmd/upgrade_test.go
cli/internal/cmd/configfetchmeasurements.go
cli/internal/cmd/configinstancetypes.go
cli/internal/cmd/create.go
cli/internal/cmd/init.go
cli/internal/cmd/miniup.go
cli/internal/cmd/readconfig.go
cli/internal/cmd/recover.go
cli/internal/cmd/terminate.go
cli/internal/cmd/upgradeplan.go
cli/internal/cmd/upgradeplan_test.go
cli/internal/cmd/verify.go
cli/internal/cmd/version.go

- Consistently use
- stderr for warnings and errors
- stdout for all other messages

consistently use stdout and stderr

---

renovate.json

- Major version upgrades shouldn't be grouped so one can decide for each action whether to upgrade or not.

deps: don't group major ver upgrades of actions

---

README.md
SECURITY.md

see https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability for background info

promote new github security reporting feature

---

bootstrapper/internal/kubernetes/k8sapi/install.go
bootstrapper/internal/kubernetes/k8sapi/install_test.go
bootstrapper/internal/kubernetes/k8sapi/k8sutil.go
go.mod
go.sum

- Remove unused code and dependencies

Remove transformers from k8sutil downloader

---

hack/check-licenses.sh

- Fix unboud variable
- Remove `\`

Fix license check unbound variable

---

.github/actionlint.yaml
.github/actions/generate_measurements/action.yml
.github/workflows/azure-snp-reporter.yml
.github/workflows/build-micro-service-manual.yml
.github/workflows/build-os-image.yml
.github/workflows/e2e-test-daily.yml
.github/workflows/e2e-test-manual-macos.yml
.github/workflows/e2e-test-manual.yml
.github/workflows/e2e-test-weekly.yml
.github/workflows/generate-measurements.yml
.github/workflows/release-cli.yml
.github/workflows/test-actionlint.yml
.github/workflows/test-govulncheck.yml
.github/workflows/test-lint.yml
.github/workflows/test-operator-codegen.yml
.github/workflows/test-tf.yml
.github/workflows/test-tfsec.yml
.github/workflows/test-tidy.yml
.github/workflows/update-cli-reference.yml

Add actionlint

---

.github/workflows/test-shellfmt.yml

ci: improve shellfmt workflow code

---

bootstrapper/cmd/bootstrapper/main.go
cli/internal/cloudcmd/clients_test.go
cli/internal/cmd/cloud_test.go
disk-mapper/cmd/main.go
disk-mapper/internal/setup/setup_test.go
go.mod
go.sum
hack/pcr-reader/main_test.go
internal/attestation/vtpm/vtpm_test.go
internal/config/config_test.go
internal/watcher/validator_test.go
joinservice/cmd/main.go
verify/cmd/main.go

- Update `go-tpm-tools` to remove dependency on `glog`

Update go-tpm-tools dependency

---

.github/actions/e2e_sonobuoy/action.yml

- Changelog: https://github.com/vmware-tanzu/sonobuoy/releases/tag/v0.56.11

ci: bump sonobuoy version

---

.github/workflows/test-shellfmt.yml

- Allow listing files as separate args for shfmt

Allow listing separate args for shfmt

---

image/mkosi.skeleton/usr/lib/dracut/modules.d/38azure-provision/module-setup.sh

- Undo shell options for dracut module-setup

Undo shell options for dracut module-setup

---

image/upload/upload_azure.sh

- Do not quote azure image upload parameters

Do not quote azure image upload params

---

CHANGELOG.md
CMakeLists.txt
cli/internal/helm/charts/edgeless/constellation-services/Chart.yaml
cli/internal/helm/charts/edgeless/constellation-services/charts/autoscaler/Chart.yaml
cli/internal/helm/charts/edgeless/constellation-services/charts/ccm/Chart.yaml
cli/internal/helm/charts/edgeless/constellation-services/charts/cnm/Chart.yaml
cli/internal/helm/charts/edgeless/constellation-services/charts/join-service/Chart.yaml
cli/internal/helm/charts/edgeless/constellation-services/charts/kms/Chart.yaml
internal/config/images_enterprise.go
internal/versions/versions.go

- Merge v2.2.1 changes back to main

Merge v2.2.1 changes back to main

---

.github/workflows/test-shellfmt.yml
.github/workflows/test-tidy.yml
image/mkosi.postinst
image/mkosi.prepare
image/mkosi.skeleton/etc/profile.d/constellation.sh
image/mkosi.skeleton/usr/lib/dracut/modules.d/38azure-provision/module-setup.sh
image/mkosi.skeleton/usr/lib/dracut/modules.d/39constellation-mount/module-setup.sh

Fixes an issue where the serial console is not accessible on debug images:
```fedora login: root (automatic login)
Last login: Thu Nov 17 11:21:56 on ttyS0
-bash: LC_ALL: unbound variable
Fedora Linux 36 (Thirty Six)
Kernel 6.0.8-200.fc36.x86_64 on an x86_64 (ttyS0)
PCR state:
sha256:
0 : 0x7D08997028F34F6CCDD2ED9BD31804CF0B0C7FFF9A4D05299E33620001510281
1 : 0xEE07102D1418518024110872A713A9824BC7F6AE47D62FD0CDE0918C0E249B7E
2 : 0x72001A25201B263BC60F869ACE2F728B09DC4BE78B9C80ADCA87A013C2D26950
3 : 0x3D458CFE55CC03EA1F443F1562BEEC8DF51C75E14A9FCF9A7234A13F198E7969
4 : 0xC7BE9E9BD3366D200BEDBE71B04CA3555D2317D0AD90C18AA6A06808EAA47F34
5 : 0x04C3865286BFCBC735785EFE27DFDCCC29D48AE704CEA6F774E5D8D7BBECEF60
6 : 0x3D458CFE55CC03EA1F443F1562BEEC8DF51C75E14A9FCF9A7234A13F198E7969
7 : …
```

Fix shellcheck related issued

---

.github/workflows/test-shellcheck.yml
.github/workflows/test-shellfmt.yml

- Shfmt didn't recognize files like `mkosi.finalize` because of the dot in the filename. Upstream issue: https://github.com/mvdan/sh/issues/944
- Also using shfmt for shellcheck input to ensure these files are checked, too.

ci: use shfmt fork

---

.github/actions/os_build_variables/action.yml
.github/workflows/build-os-image.yml
image/README.md
image/upload/upload_qemu.sh
rfc/image-discoverability.md

- Move image artifacts "/v1/" => "/constellation/v1"

Move image artifacts "/v1/" => "/constellation/v1"

---

renovate.json

deps: bundle libvirt dependencies

---

.github/docs/release.md
CHANGELOG.md
CMakeLists.txt
cli/internal/helm/charts/edgeless/constellation-services/Chart.yaml
cli/internal/helm/charts/edgeless/constellation-services/charts/autoscaler/Chart.yaml
cli/internal/helm/charts/edgeless/constellation-services/charts/ccm/Chart.yaml
cli/internal/helm/charts/edgeless/constellation-services/charts/cnm/Chart.yaml
cli/internal/helm/charts/edgeless/constellation-services/charts/join-service/Chart.yaml
cli/internal/helm/charts/edgeless/constellation-services/charts/kms/Chart.yaml
internal/config/images_enterprise.go
internal/versions/versions.go

- merge back changes from v2.2.2 release
-

Merge back changes from v2.2.2 release

---

debugd/README.md
hack/find-image/find-image.sh

- Add hack script to locate latest debug image

Add hack script to locate latest debug image

---

hack/terraform/gcp/iam/.terraform.lock.hcl
hack/terraform/gcp/iam/README.md
hack/terraform/gcp/iam/main.tf
hack/terraform/gcp/iam/output.tf
hack/terraform/gcp/iam/variables.tf

- Implementing a Terraform configuration to setup GCP IAM for Constellation

AB#2577 Implement GCP IAM in terraform

---

.dockerignore

- Actually ignore image and build path.

build: fix ignoring image folder

---

cli/internal/helm/charts/edgeless/constellation-services/charts/azuredisk-csi-driver/templates/storageclass_integrity.yaml
cli/internal/helm/testdata/Azure/constellation-services/charts/azuredisk-csi-driver/templates/storageclass_integrity.yaml
docs/docs/workflows/storage.md

- Update docs to not describe manual installation steps for CSI

AB#2615 Update docs to new CSI installation method

---

.github/actions/e2e_sonobuoy/action.yml

deps: upgrade sonobuoy version

---

.github/workflows/test-lint.yml
.golangci.yml

Reverts edgelesssys/constellation#558

Revert "warn about function argument count over 5"

---

bootstrapper/cmd/bootstrapper/run.go
bootstrapper/internal/helm/client.go
bootstrapper/internal/kubernetes/k8sapi/k8sutil.go
bootstrapper/internal/kubernetes/kubernetes.go
cli/internal/cloudcmd/create.go
cli/internal/cmd/cloud_test.go
cli/internal/cmd/spinner.go
cli/internal/cmd/upgradeplan.go
csi/cryptmapper/cryptmapper.go
disk-mapper/internal/setup/setup.go
internal/attestation/vtpm/attestation.go
joinservice/internal/server/server.go
kms/kms/gcp/gcp.go

- Since we removed the rule we don't need these comments anymore.

Remove obsolote revive comments

---

cli/internal/helm/loader.go

- Struct is unused and makes revive unhappy because of missing comment.

Remove unused LoadConfig type

---

rfc/updates.md

While discussing the reasons for the separation between `microserviceVersion`  and `kubernetesServicesVersion` we realized that it is not necessary to distinguish between the two, since images for each service are set in the CLI anyways. Deployments were similar for all versions up until now.
Because it seems to me that it will make things easier for us and the user I propose to remove the separation.

Remove kubernetesServicesVersion from upgrade RFC.

---

cli/internal/cmd/init.go
cli/internal/cmd/init_test.go

- Add a simple warning about `constellation init` being non retriable if the command fails at a certain step
- I currently marked only one error as non retriable, if there are any others we should catch please say so
- Additional information for failures during other steps of `init` might be helpful
-  If you notice any let me know, or create a PR in the future

AB#2645 Add warning about non retriable error during init

---

cli/internal/helm/charts/edgeless/operators/charts/constellation-operator/crds/nodeimage-crd.yaml
cli/internal/helm/charts/edgeless/operators/charts/constellation-operator/templates/deployment.yaml
cli/internal/helm/testdata/Azure/constellation-operators/charts/constellation-operator/templates/deployment.yaml
cli/internal/helm/testdata/GCP/constellation-operators/charts/constellation-operator/templates/deployment.yaml
cli/internal/helm/testdata/QEMU/constellation-operators/charts/constellation-operator/templates/deployment.yaml
operators/constellation-node-operator/api/v1alpha1/nodeimage_types.go
operators/constellation-node-operator/config/crd/bases/update.edgeless.systems_nodeimages.yaml
operators/constellation-node-operator/config/manager/manager.yaml
operators/constellation-node-operator/internal/deploy/deploy.go
operators/constellation-node-operator/internal/deploy/deploy_test.go
operators/constellation-node-operator/internal/deploy/imageinfo.go
operators/constellation-node-operator/internal/deploy/imageinfo_test.go
operators/constellation-node-operator/main.go

- Constellation Operator: Add image version field
- The CLI still needs to be extended to use this new field for OS image version selection during upgrades

Constellation Operator: Add image version field

---

cli/internal/helm/charts/edgeless/constellation-services/charts/autoscaler/templates/azure-secret.yaml
cli/internal/helm/charts/edgeless/constellation-services/charts/join-service/templates/configmap.yaml
cli/internal/helm/loader_test.go
cli/internal/helm/testdata/Azure/constellation-services/charts/autoscaler/templates/azure-secret.yaml
cli/internal/helm/testdata/Azure/constellation-services/charts/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
cli/internal/helm/testdata/Azure/constellation-services/charts/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
cli/internal/helm/testdata/Azure/constellation-services/charts/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
cli/internal/helm/testdata/Azure/constellation-services/charts/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
cli/internal/helm/testdata/GCP/constellation-services/charts/gcp-compute-persistent-disk-csi-driver/templates/cluster_setup.yaml
cli/internal/helm/testdata/GCP/constellation-services/charts/gcp-compute-persistent-disk-csi-driver/templates/controller.yaml
cli/internal/helm/testdata/GCP/constellation-services/charts/gcp-compute-persistent-disk-csi-driver/templates/node.yaml

Previously only the first document was compared due to an [issue](https://github.com/stretchr/testify/issues/1281) in testify. Also update testdata to match the adjusted expectations.
e2e testrun: [azure](https://github.com/edgelesssys/constellation/actions/runs/3548542844)

Compares all documents in one yaml file in loader_test

---

cli/internal/helm/testdata/Azure/constellation-operators/charts/constellation-operator/templates/deployment.yaml
cli/internal/helm/testdata/Azure/constellation-operators/charts/node-maintenance-operator/templates/deployment.yaml
cli/internal/helm/testdata/GCP/constellation-operators/charts/constellation-operator/templates/deployment.yaml
cli/internal/helm/testdata/GCP/constellation-operators/charts/node-maintenance-operator/templates/deployment.yaml
internal/versions/versions.go

- Fix expected Helm charts. Those weren't updated last time we updated the images, with which we fill out Helm templates.

helm: fix expected helm charts

---

rfc/updates.md

- Add the discussed changes to the update rfc.

rfc: include upgrade check command

---

.github/workflows/test-tf.yml
hack/remove-tf-providers/remove.sh

Check hcl lock files are up to date

---

.github/docs/release.md
CHANGELOG.md
docs/docs/getting-started/first-steps.md
docs/docs/reference/config-migration.md
docs/docs/workflows/create.md
docs/docs/workflows/verify-cluster.md

- Update the docs to reflect the new format for measurements
- Remove `constellation config fetch-measurements` from the required steps for creating a new cluster.
- For new releases the expected measurements of the current release should be directly embedded in the CLI
- Add migration notice for measurements in the config

Update docs to new measurement format

---

.github/workflows/build-micro-service-manual.yml
.github/workflows/build-qemu-metadata-image.yml

- Add CI to manually and automatically build the qemu metadata api
Manual build: https://github.com/edgelesssys/constellation/actions/runs/3582591856

ci: build qemu-metadata api

---

docs/docs/reference/slsa.md

- add in feedback from @flxflx re. SLSA docs

improve wording

---

hack/add-version/main.go
internal/constants/constants.go
internal/update/update.go
internal/update/update_test.go

- Rename "updates" -> "versions"
- Add explicit "stream" in path to make API self-describing

Change path for versions API

---

rfc/updates.md

- Update RFC: use current config format in examples

Update RFC: use current config format in examples

---

internal/versions/versions.go

- Bumps qemu metadata image. This includes the clientInit verification now.

versions: bump qemu metadata image

---

debugd/README.md

- https://github.com/edgelesssys/constellation/pull/669#issuecomment-1332025201

debugd: add qemu logcollection memory requirement

---

rfc/reproducible-builds.md

- Create an RFC for our requirements for reproducible builds

rfc: reproducible-builds

---

.github/workflows/build-os-image.yml

- Print version in summary for easier access

ci: print image version in summary

---

.github/workflows/e2e-test-manual.yml

- Allow using a default image on e2e manual.

e2e: find default image if no input image specified

---

.github/actions/constellation_create/action.yml
.github/actions/e2e_test/action.yml
.github/docs/release.md
.github/workflows/e2e-test-manual-macos.yml
.github/workflows/e2e-test-manual.yml

-  manual e2e tests: Add option to keep embedded measurements

AB#2673 manual e2e tests: Add option to keep embedded measurements

---

debugd/internal/cdbg/cmd/deploy.go

- Fixes the timeout that occurd in https://github.com/edgelesssys/constellation/actions/runs/3589166308/jobs/6041327971

debugd: remove timeout for rpc calls

---

.github/workflows/build-joinservice-image.yml
.github/workflows/build-kms-image.yml
.github/workflows/build-qemu-metadata-image.yml
.github/workflows/build-verification-service.yml

ci: build microservices on change of pkg internal

---

hack/pseudo-version/internal/git/git.go

- pseudo-version: Use committer time
> A timestamp (yyyymmddhhmmss), which is the UTC time the revision was created. In Git, this is the commit time, not the author time.
https://go.dev/ref/mod#pseudo-versions

pseudo-version: Use committer time

---

cli/internal/cmd/upgradeplan.go
cli/internal/cmd/upgradeplan_test.go
hack/add-version/main.go
internal/versionsapi/versionsapi.go
internal/versionsapi/versionsapi_test.go

- rename pkg updates => versionsapi
- allow debug stream
- enable add-version hack tool to add versions to different streams

Add debug stream to versions API

---

.github/actions/build_micro_service/action.yml
.github/workflows/build-logcollector-images.yml
.github/workflows/build-micro-service-manual.yml
debugd/internal/debugd/logcollector/Makefile
debugd/internal/debugd/logcollector/filebeat/Dockerfile
debugd/internal/debugd/logcollector/logcollector.go
debugd/internal/debugd/logcollector/logstash/Dockerfile
debugd/internal/debugd/logcollector/logstash/config/log4j2.properties
debugd/internal/debugd/logcollector/logstash/config/pipelines.yml
internal/versions/versions.go

- Build logcollector container images on change or manually.

ci: build logcollector images

---

README.md

- temporarily disable e2e badges in the README.md 
Since the E2E test are flaky, which is at least partly due to external factors, we should remove them for now.

docs: disable e2e badges

---

.github/workflows/build-micro-service-manual.yml
internal/versions/versions.go

- Pipeline would build `filebeat-debugd` whereas version stated `filebeat-debug`

debugd: fix logcollector container image naming

---

.github/actions/e2e_sonobuoy/action.yml
.github/actions/e2e_test/action.yml

- Upload full sonobuoy logs (includes pod logs) until we have improved logs via OpenSearch. These changes can be reverted once that feature lands.
- Also upload logs with csp name included in artifact name so that there is one artifact per CSP.

Full sonobuoy logs

---

rfc/update-api.md
rfc/version-api.md

- Write version API RFC
- This is a really early draft idea. I am not proposing it at this point in time.
- The document exists as a PR so it is easier to comment on.
- Not every aspect has to be implemented right away

Write version API RFC

---

.github/workflows/release-cli.yml

- I've missed the comment and pinned the digest some days ago...

ci: unpin slsa-github-generator action digest

---

cli/internal/helm/charts/edgeless/constellation-services/charts/gcp-compute-persistent-disk-csi-driver/templates/node.yaml
cli/internal/helm/charts/edgeless/constellation-services/charts/gcp-compute-persistent-disk-csi-driver/values.yaml
cli/internal/helm/testdata/GCP/constellation-services/charts/gcp-compute-persistent-disk-csi-driver/templates/node.yaml
cli/internal/helm/update-csi-charts.sh

- Use release tag to pull in GCP CSI chart, instead of loading it from develop branch

Use csi chart from release tag

---

docs/package.json

- I'm not an expert in node. I tested this and it seems to work. Not sure if there are any downsides. Also unsure why renovate isn't suggesting this change but keeps opening PRs that break everything, like #681.

docs: update dependencies

---

docs/docs/getting-started/first-steps.md

- Adding an overview and / or tutorial on how to get the supported cloud provider regions to the documentation.

AB#2652 Add supported CP regions to Azure & GCP Docs

---

.gitignore

- Ignoring shell.nix files that belong to the local dev environment.

gitignore: add shell.nix files

---

.github/actions/constellation_create/action.yml

- No longer print constellation-id.json in e2e tests

E2E: No longer print constellation-id.json

---

rfc/updates.md

- labels do not work use annotations instead
+ minor updates and corrections

rfc: use hash annotation during upgrades

---

.github/workflows/check-links.yml

ci: no link checking on main

---

cli/internal/helm/charts/edgeless/constellation-services/charts/azuredisk-csi-driver/Chart.yaml
cli/internal/helm/charts/edgeless/constellation-services/charts/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
cli/internal/helm/charts/edgeless/constellation-services/charts/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
cli/internal/helm/charts/edgeless/constellation-services/charts/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
cli/internal/helm/charts/edgeless/constellation-services/charts/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
cli/internal/helm/charts/edgeless/constellation-services/charts/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
cli/internal/helm/charts/edgeless/constellation-services/charts/azuredisk-csi-driver/values.yaml
cli/internal/helm/testdata/Azure/constellation-services/charts/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
cli/internal/helm/testdata/Azure/constellation-services/charts/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
cli/internal/helm/testdata/Azure/constellation-services/charts/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
cli/internal/helm/testdata/Azure/constellation-services/charts/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
cli/internal/helm/testdata/Azure/constellation-services/charts/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
cli/internal/helm/testdata/Azure/constellation-services/charts/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
cli/internal/helm/testdata/Azure/constellation-services/charts/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
cli/internal/helm/update-csi-charts.sh

Use v1.1.0 release of Azure CSI driver

Pull in CSI chart from release tag

---

docs/versioned_docs/version-2.0/workflows/storage.md
docs/versioned_docs/version-2.1/workflows/storage.md
docs/versioned_docs/version-2.2/workflows/storage.md

We restructured the CSI repos, so the available documentation needs to be udated
- Don't merge before constellation-azuredisk-csi-driver v1.1.0 is released

Update CSI installation instructions in versioned docs

---

.github/actions/constellation_create/action.yml
.github/actions/constellation_create/aws-logs.sh
.github/actions/constellation_create/gcp-logs.sh

- We moved the Terraform state, that broke the upload.
- I've also added a csp suffix to the artifact name, so the artifacts can be distinguished in multi CSP workflows.
- Test run AWS: https://github.com/edgelesssys/constellation/actions/runs/3649911173
- Test run GCP: https://github.com/edgelesssys/constellation/actions/runs/3649913197

Fix serial log upload

---

docs/docs/architecture/cert-manager.md
docs/docs/workflows/installing-cert-manager.md
docs/sidebars.js

- Explain that cert-manager is preinstalled and what limitations this brings in regards to user-managed cert-manager.

Document cert-manager installation.

---

.github/actions/os_build_variables/action.yml

- Fix image build pipeline: Use braces to group complex expressions

Fix image build pipeline: Use braces to group complex expressions

---

.github/actions/constellation_create/action.yml

- Fix e2e test networking issue
- [Test run](https://github.com/edgelesssys/constellation/actions/runs/3683771030)

Fix e2e test networking issue

---

.github/docs/release.md

- Enhance release checklist with lessons from release v2.3

Enhance release checklist with lessons from release v2.3

---

.github/actions/find_latest_image/action.yaml
debugd/README.md
hack/api/find-image.sh
hack/find-image/find-image.sh

- Adding the ability to list version with the find image script
- Adding JSON output option
- Adding help option

List versions with find-image script

---

debugd/README.md
debugd/cmd/debugd/debugd.go
debugd/internal/debugd/logcollector/filebeat/Dockerfile
debugd/internal/debugd/logcollector/filebeat/filebeat.yml
debugd/internal/debugd/logcollector/filebeat/inputs.yml
debugd/internal/debugd/logcollector/logcollector.go
debugd/internal/debugd/logcollector/logstash/templates/pipeline.conf
debugd/internal/debugd/metadata/cloudprovider/cloudprovider.go
debugd/internal/debugd/metadata/cloudprovider/cloudprovider_test.go
debugd/internal/debugd/metadata/fallback/fallback.go
debugd/internal/debugd/metadata/fallback/fallback_test.go

- Collect pod logs to Opensearch
- Annotate logs with instance metadata

debugd: collect pod logs

---

.github/workflows/on-release.yml

- Release action: Do not fail if "latest" is not set
- [Failing run (before this PR)](https://github.com/edgelesssys/constellation/actions/runs/3684119422)
- [Run with fix](https://github.com/edgelesssys/constellation/actions/runs/3684109776)

Release action: Do not fail if "latest" is not set

---

.github/actions/e2e_mini/.gitignore
.github/actions/e2e_mini/.terraform.lock.hcl
.github/actions/e2e_mini/action.yml
.github/actions/e2e_mini/main.tf
.github/actions/e2e_mini/output.tf
.github/actions/e2e_mini/run-e2e.sh
.github/actions/e2e_mini/wait-for-ssh.sh
.github/docs/release.md
.github/workflows/build-binaries.yml
.github/workflows/e2e-mini.yml

- This PR depends on permissions and users configured in https://github.com/edgelesssys/edgeless-iam/pull/1
- Terraform is used to create an environment (VM with nested virt. support) in Azure.
- A long lived resource group is used to minimize permissions and avoid IAM replication delay.
- All resources are suffixed with a random ID to prevent naming collisions
- Currently only positive tests are executed on MiniConstellation
- Does the CLI command work `constellation mini up`
- Are two nodes available?
- Are the expected deployments available?
- These tests are only to be executed when a release is prepared to verify MiniConstellation functionality
- An additional (nightly/weekly) test for QEMU will be implemented in a separate PR

E2E Test Mini Constellation

---

docs/versioned_docs/version-2.3/getting-started/first-steps.md
docs/versioned_docs/version-2.3/workflows/config.md

we need to publish this to 2.3 so that users will actually notice this

docs: publish gcp zone fix

---

CODEOWNERS
docs/docs/getting-started/first-steps.md
docs/versioned_docs/version-2.0/getting-started/first-steps.md
docs/versioned_docs/version-2.1/getting-started/first-steps.md
docs/versioned_docs/version-2.2/getting-started/first-steps.md
docs/versioned_docs/version-2.3/getting-started/first-steps.md

- add disclaimer for potentially long inits on Azure
- add @flxflx as codeowner for docs (you were not automatically added as reviewer, let's see if it works once it landed in `main`)

Azure disclaimer

---

.github/actions/find_latest_image/action.yaml
.github/workflows/e2e-test-manual.yml

ci: enable manual e2e runs on any git ref

---

docs/docs/getting-started/first-steps.md
docs/versioned_docs/version-2.0/getting-started/first-steps.md
docs/versioned_docs/version-2.1/getting-started/first-steps.md
docs/versioned_docs/version-2.2/getting-started/first-steps.md
docs/versioned_docs/version-2.3/getting-started/first-steps.md

- Fix linter issues from #805 
-

fix linter issues

---

.github/workflows/test-go-generate.yml
.github/workflows/test-tidy.yml

- Fixing recent workflow fails:
- https://github.com/edgelesssys/constellation/actions/runs/3761317663/jobs/6399520050#step:2:13
- https://github.com/edgelesssys/constellation/actions/runs/3761317669/jobs/6399520667#step:3:12

ci: fix workflows with tokens running on forks

---

.github/actions/e2e_sonobuoy/action.yml

- Release notes v0.56.14: https://github.com/vmware-tanzu/sonobuoy/releases/tag/v0.56.14
- Release notes v0.56.13: https://github.com/vmware-tanzu/sonobuoy/releases/tag/v0.56.13

deps: update sonobuoy to v0.56.14

---

bootstrapper/internal/kubernetes/k8sapi/k8sutil.go
bootstrapper/internal/kubernetes/k8sutil.go
bootstrapper/internal/kubernetes/kubernetes.go
bootstrapper/internal/kubernetes/kubernetes_test.go
cli/internal/helm/charts/edgeless/constellation-services/charts/join-service/templates/clusterrole.yaml
cli/internal/helm/testdata/Azure/constellation-services/charts/join-service/templates/clusterrole.yaml
cli/internal/helm/testdata/GCP/constellation-services/charts/join-service/templates/clusterrole.yaml
cli/internal/helm/testdata/QEMU/constellation-services/charts/join-service/templates/clusterrole.yaml
joinservice/internal/kubernetes/kubernetes.go
joinservice/internal/server/server.go
joinservice/internal/server/server_test.go

- Remove components migration fallback for the next release as a manual migration to 2.3 has prepared everything needed for a seamless manual upgrade to 2.4.

join: deprecate components migration fallback

---

.github/actions/build_upgrade_agent/action.yml
.github/workflows/build-os-image.yml
cli/internal/helm/charts/edgeless/constellation-services/charts/ccm/templates/gcp-daemonset.yaml
cli/internal/helm/charts/edgeless/operators/charts/constellation-operator/templates/deployment.yaml
cli/internal/helm/testdata/Azure/constellation-operators/charts/constellation-operator/templates/deployment.yaml
cli/internal/helm/testdata/GCP/constellation-operators/charts/constellation-operator/templates/deployment.yaml
cli/internal/helm/testdata/GCP/constellation-services/charts/ccm/templates/gcp-daemonset.yaml
cli/internal/helm/testdata/QEMU/constellation-operators/charts/constellation-operator/templates/deployment.yaml
image/Makefile
image/mkosi.skeleton/usr/lib/systemd/system-preset/30-constellation.preset
image/mkosi.skeleton/usr/lib/systemd/system/constellation-upgrade-agent.service
operators/constellation-node-operator/config/manager/manager.yaml

- Add the upgrade-agent to the image, start it on boot, and mount the unix domain socket into our operator.
For a working CI run + images see: https://github.com/edgelesssys/constellation/actions/runs/3794552695

image: add upgrade-agent

---

internal/versions/versions.go

Bump microservies from latest release to latest pseudo version.

bump microservice versions

---

internal/versions/versions.go

- Picked the minor ver update for 1.24 from #799, which is still blocked
- Updated major ver for k8s v1.26 to ccm v1.26.0

deps: update AWS cloud controller manager

---

rfc/apis.md
rfc/image-api.md
rfc/image-discoverability.md
rfc/secure-software-distribution.md
rfc/updates.md
rfc/version-api.md

Changes to include: https://gist.github.com/katexochen/4f8a51117b8d68c0dcd880ac51c8a41b

rfc: update documentation of new versions/image API

---

.lycheeignore

- Add failing but working links to ignore list.

ci: ignore ntia.gov and twitter checking links

---

go.mod
internal/versionsapi/cli/list.go

- tiny fix for a wrong auto-import

versionsapi: fix semver dependency

---

.github/workflows/build-joinservice-image.yml
.github/workflows/build-kms-image.yml
.github/workflows/build-qemu-metadata-image.yml
.github/workflows/build-verification-service.yml

- Currently a dependabot upgrade of microservice versions in versions.go triggers a new build of these and so on.

ci: fix rebuild loop of microservice images

---

image/Makefile
image/mkosi.conf.d/mkosi.conf
image/mkosi.files/mkosi.azure.conf
image/mkosi.files/mkosi.gcp.conf

- Downgrade azure kernel to 5.19.4

Downgrade azure kernel to 5.19.4

---

.github/actions/e2e_lb/lb.yml
e2e/internal/lb/lb_test.go

ci: increase verbosity of load balancer e2e test

---

internal/versions/versions.go

- Patch version upgrade from blocked #799

deps: upgrade AWS cloud controller manager

---

.github/actions/constellation_verify/action.yml
.github/actions/e2e_test/action.yml
.github/workflows/e2e-test-manual.yml
.github/workflows/e2e-test-weekly.yml

- Adding an e2e test for `constellation verify`.
- Test fetches the measurements for the used debug image, pastes them into the config file and executes the command.

AB#2564 add e2e test for constellation verify

---

.github/docs/conventions.md

devdocs: pr title conventions

---

.github/workflows/purge-branch.yml
.github/workflows/versionsapi.yml

- Delete images on branch deletion
- Note that workflows with delete trigger cannot be tested on a branch

ci: add purge branch workflow

---

.github/workflows/purge-branch.yml

ci: add missing secrets to purge branch workflow

---

.github/workflows/purge-branch.yml
.github/workflows/versionsapi.yml

ci: fix versionsapi workflow remove cmd

---

dev-docs/conventions.md

Adds documentation for logging conventions in our code.
Not sure if I wrote too much for quick documentation or if there is still information missing that should be there.
Also, this mostly covers my personal opinions on logging, so there might be some disagreements I would be happy to discuss.

devdocs: documentation of logging conventions

---

internal/versionsapi/cli/rm.go

- Log AWS region so the manual validation of the deletion is easier.

versionsapi: log aws region

---

.github/workflows/test-shellcheck.yml
.github/workflows/test-shellfmt.yml

deps: update and pin github.com/katexochen/sh

---

rfc/external-kms.md

rfc: mention required IAM secrets for recovery in eKMS rfc

---

go.mod
internal/versions/generateHashes.go
internal/versions/hash-generator/generate.go
internal/versions/hash-generator/generate_test.go
internal/versions/versions.go

- Hash generator was broken, as the Go file/ast changed
- Moving the generator into an own package and removing the build tag, so it can be linted

versions: repair hash generation

---

.github/workflows/purge-branch.yml

- deactivate dryrun of image deletion

ci: deactivate dryrun of image deletion

---

operators/constellation-node-operator/controllers/autoscalingstrategy_controller_env_test.go
operators/constellation-node-operator/controllers/nodeversion_controller_env_test.go
operators/constellation-node-operator/controllers/scalinggroup_controller_env_test.go

- Don't use `Consistently()` if we do a `Eventually()` before. 
- Also `Eventually()` update the NodeVersion.

operator: make test more resilient

---

cli/internal/image/image.go

- cli: include search paths for image info json in error message printed to user
Creates an error message like this:
```shell-session
constellation create -c 1 -w 1 --name malte -y
WARNING: Creating a debug cluster. This cluster is not secure and should only be used for debugging purposes.
DO NOT USE THIS CLUSTER IN PRODUCTION.
Creating  
Error: fetching image reference: image info file not found locally at "constellation_v1_ref_-_stream_stable_v2.6.0_image_info.json" or remotely at https://cdn.confidential.cloud/constellation/v1/ref/-/stream/stable/v2.6.0/image/info.json
```

cli: include search paths for image info json in error message printed to user

---

operators/constellation-node-operator/controllers/autoscalingstrategy_controller.go
operators/constellation-node-operator/controllers/nodeversion_controller.go
operators/constellation-node-operator/controllers/nodeversion_controller_env_test.go
operators/constellation-node-operator/controllers/pendingnode_controller.go

- The `Eventually()` should fix: https://github.com/edgelesssys/constellation/actions/runs/3910465909/jobs/6682700255
Also tested this again in this PR's CI a few times: https://github.com/edgelesssys/constellation/actions/runs/3912132783/jobs/6686728753
Currently not sure what caused: https://github.com/edgelesssys/constellation/actions/runs/3910331345/jobs/6682410865

operator: reliability and simplification

---

image/mkosi.postinst

- Shellcheck just became unhappy with my commit and suggested the changes in the commit if I am not mistaken.
- Failed run: https://github.com/edgelesssys/constellation/actions/runs/3929664064/jobs/6718744137

image: apply shellfmt suggestions

---

internal/versionsapi/cli/main.go
internal/versionsapi/client/client.go
internal/versionsapi/fetcher/fetcher.go
internal/versionsapi/versionsapi.go

- Documented some of the packages owned by me in more detail.

dev-docs: add Go package docs

---

.github/workflows/build-keyservice-image-ko.yml
.github/workflows/release.yml
.ko.yaml

- Missed the ko merge; rename remaining references to "kms".

ci: remove residual references to "kms"

---

.github/workflows/test-shellcheck.yml
.github/workflows/test-shellfmt.yml
image/mkosi.postinst

- Some errors slipped through lately

ci: run shellfmt and shellcheck on changes in /image

---

internal/versions/versions.go

- Presumably because of the missed ko PR.

versions: rename KmsImage to KeyServiceImage

---

.github/actions/versionsapi/action.yml

ci: fix versionsapi action output

---

.github/actions/e2e_test/action.yml
.github/actions/login_gcp/action.yml
.github/workflows/build-os-image.yml
.github/workflows/e2e-test-daily.yml
.github/workflows/e2e-test-manual.yml
.github/workflows/e2e-test-weekly.yml
.github/workflows/generate-measurements.yml
.github/workflows/versionsapi.yml

- ci: switch gcp accounts to oidc [AB#2618](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/2618)
- [Test run image build pipeline](https://github.com/edgelesssys/constellation/actions/runs/3931200548/jobs/6722585006)
- [Test run e2e](https://github.com/edgelesssys/constellation/actions/runs/3931538663)

ci: switch gcp accounts to oidc

---

.github/actions/versionsapi/action.yml

- There was another bug in the if statement

ci: fix versionsapi action

---

.github/actions/e2e_kbench/action.yml
.github/actions/e2e_kbench/evaluate/requirements.txt
.github/runners/azure-cvm/azure-function/requirements.txt
.github/workflows/build-os-image-requirements.txt
.github/workflows/build-os-image.yml
.github/workflows/check-licenses.yml
.github/workflows/test-actionlint.yml
.github/workflows/test-go-generate.yml
.github/workflows/test-govulncheck.yml
hack/azure-snp-report-verify/Dockerfile
renovate.json

Fix findings reported by scorecard:
```
scorecard --repo=https://github.com/edgelesssys/constellation --show-details --checks=Pinned-Dependencies
Starting [Pinned-Dependencies]
Finished [Pinned-Dependencies]
RESULTS
-------
Aggregate score: 7.0 / 10
Check scores:
|--------|---------------------|--------------------------------|--------------------------------------------------------------------------------------|--------------------------------------------------------------------------------|
| SCORE  |        NAME         |             REASON             |                                       DETAILS                                        |                           DOCUMENTATION/REMEDIATION                            | …
```

ci: fix scorecard/pinned-dependencies findings

---

.github/workflows/test-actionlint.yml
.github/workflows/test-go-generate.yml
.github/workflows/test-tidy.yml

ci: install shellcheck using the action

---

.github/workflows/codeql.yml

ci: run CodeQL only on Go/Python changes

---

.github/workflows/codeql.yml

ci: only run CodeQL on main

---

cli/cmd/root.go
cli/internal/cloudcmd/cloudcmd.go
cli/internal/cmd/cmd.go
cli/internal/image/image.go

dev-docs: document cmd and subpackages

---

.github/actions/build_apko/action.yml
.github/workflows/build-apko-image.yml
.ko.yaml
apko/alpine-base-user-65532.yaml
apko/alpine-base.yaml
apko/alpine-libcryptsetup.yaml
apko/alpine-qemu-metadata-api.yaml

- Pinning the base images. I'm working on also pinning the downloads when building new base images...

ko: pin base image

---

.ko.yaml

ko: fix typo

---

.github/workflows/check-licenses.yml
.github/workflows/check-links.yml
.github/workflows/test-govulncheck.yml
.github/workflows/test-integration.yml
.github/workflows/test-lint.yml
.github/workflows/test-operator-codegen.yml
.github/workflows/test-shellcheck.yml
.github/workflows/test-shellfmt.yml
.github/workflows/test-tf.yml
.github/workflows/test-tfsec.yml
.github/workflows/test-tidy.yml
.github/workflows/test-unittest.yml

ci: run tests on workflow file change

---

image/Makefile
image/mkosi.files/mkosi.azure.conf

- image: upgrade azure kernel to 6.1.7
- [image build](https://github.com/edgelesssys/constellation/actions/runs/3957321312)
- [e2e test](https://github.com/edgelesssys/constellation/actions/runs/3957652775)
- [Includes MTRR Fix](https://lore.kernel.org/all/16740399191863@kroah.com/) (reason we downgraded azure kernel in #862)

image: upgrade azure kernel to 6.1.7

---

.github/actions/build_apko/action.yml
.github/actions/build_apko/build_and_sign.sh

- Moving the huge part into a script for better maintainability

ci: move apko building into separate script

---

.github/actions/build_cli/action.yml
.github/actions/constellation_create/az-logs.sh
.github/actions/e2e_mini/run-e2e.sh
.github/actions/e2e_sonobuoy/action.yml
.github/actions/e2e_verify/action.yml
.github/actions/install_operator_sdk/action.yml
.github/actions/setup_linux/action.yml
.github/workflows/generate-measurements.yml
.github/workflows/release-cli.yml
debugd/internal/debugd/logcollector/logstash/Dockerfile
image/Makefile
image/secure-boot/azure/extract_vmgs.sh
image/secure-boot/genkeys.sh
image/secure-boot/signed-shim.sh

- Use consistent flags, especially let curl fail and print error

ci: curl flags

---

debugd/README.md

- debugd: adapt README to set global image field in config

debugd: adapt README to set global image field in config

---

internal/versions/versions.go

- update to new gcp image for k8s v1.26

deps: update cloud provider gcp image for k8s v1.26

---

operators/constellation-node-operator/controllers/nodeversion_controller.go
operators/constellation-node-operator/controllers/nodeversion_controller_env_test.go

- Before you could trigger errors by e.g. adding a `time.Sleep(1 * time.Second)` in the first line of the pendingNode `Reconcile()`.

operator: cleanup resources between tests

---

cli/internal/terraform/terraform/iam/azure/main.tf

- Fixing (creating) dependencies between Terraform resources for Azure IAM creation. This should prevent the 404's occasionally happening before.

cli: fix Terraform resource group dependencies

---

internal/versions/versions.go

versions: update key-service name

---

cli/internal/iamid/id.go

- Add package godoc to the `iamid` package.

cli: add godoc to iamid package

---

cli/internal/terraform/terraform/aws/variables.tf
docs/docs/getting-started/first-steps.md
docs/docs/workflows/create.md
docs/docs/workflows/terminate.md

- Minimal Terraform documentation

docs: document terraform support

---

.github/workflows/test-proto.yml
disk-mapper/recoverproto/recover.pb.go
disk-mapper/recoverproto/recover_grpc.pb.go
joinservice/joinproto/join.pb.go
joinservice/joinproto/join_grpc.pb.go
verify/verifyproto/verify.pb.go
verify/verifyproto/verify_grpc.pb.go

- Currently the proto generation isn't checked for being up to date.

ci: add workflow for proto code generation check

---

docs/docs/overview/clouds.md

docs: add missing asterisk reference

---

.github/workflows/test-unittest.yml

- Also run unittests on testdata changes

ci: add testdata trigger to unittest

---

rfc/updates.md

- In order to properly reason about the `constellation-upgrade` cmd UX it's helpful to define the constraints that should apply during an upgrade. This extension to the RFC describes our initial constraints.

rfc: extend updates rfc with constraints section

---

cli/internal/cloudcmd/validators.go
cli/internal/cloudcmd/validators_test.go
internal/config/config.go
internal/config/config_doc.go
internal/config/config_test.go
internal/config/testdata/configAWSV2.yaml
internal/config/testdata/configAzureV2MultipleIDKeyDigest.yaml
internal/config/testdata/configAzureV2SingleIDKeyDigest.yaml
internal/config/testdata/configGCPV2.yaml

- Restore backwards compatibility of the config by re-naming the `idkeydigests` key back to `idkeydigest`.

config: fix digest naming

---

internal/attestation/vtpm/attestation.go
joinservice/internal/server/server.go

- Improve logging of the JoinService in case of error
- Add a log message to tpm attestation validator in case of validation failure

join-service: more logging on error

---

.github/workflows/release.yml

ci: fix value substitution in pr messages

---

.github/release.yml
.github/workflows/release.yml
.github/workflows/update-cli-reference.yml

ci: improve readability of GitHub lables

---

.github/workflows/e2e-test-weekly.yml
internal/versions/versions.go

- Active support for Kubernetes v1.23 ended 4 weeks ago

versions: remove Kubernetes v1.23

---

debugd/internal/filetransfer/filetransfer.go
debugd/internal/filetransfer/filetransfer_test.go

- debugd: keep mutex locked while receiving files

debugd: keep mutex locked while receiving files

---

.github/actions/e2e_sonobuoy/action.yml

deps: update sonobuoy version

---

.github/actions/e2e_kbench/evaluate/requirements.txt

- Update python3 `requirements.txt` to pin all new required dependencies 
- [failing pip3 requirements install](https://github.com/edgelesssys/constellation/actions/runs/4029874578/jobs/6928150491)
- [failing `kbench` mod install](https://github.com/edgelesssys/constellation/actions/runs/4042544274/jobs/6950377530)(but python works)

ci: pin kbench python dependencies 

---

.github/actions/build_micro_service/action.yml
.github/workflows/azure-snp-reporter.yml
.github/workflows/build-os-image-scheduled.yml
.github/workflows/build-os-image.yml
.github/workflows/e2e-mini.yml
.github/workflows/release.yml
.github/workflows/scorecard.yml
.github/workflows/test-lint.yml
.github/workflows/test-tfsec.yml

- Use miniaml token permissions for all GitHub workflows
[azure-snp-reporter.yml](https://github.com/edgelesssys/constellation/actions/runs/3958245867)
[build-apko-image.yml](https://github.com/edgelesssys/constellation/actions/runs/3958377033)
[build-binaries.yml](https://github.com/edgelesssys/constellation/actions/runs/3958402676)
[build-ccm-gcp.yml](https://github.com/edgelesssys/constellation/actions/runs/4043755893)
[build-constellation-node-operator-ko.yml](https://github.com/edgelesssys/constellation/actions/runs/4044683784)
[build-constellation-node-operator.yml](https://github.com/edgelesssys/constellation/actions/runs/3966649536)
[build-gcp-guest-agent.yml](https://github.com/edgelesssys/constellation/actions/runs/3966711944) …

ci: minimal GitHub workflow token permissions

---

.github/workflows/purge-branch.yml

- fix: https://github.com/edgelesssys/constellation/actions/runs/4045639464

ci: fix purge branch permissions

---

.github/workflows/test-unittest.yml
cli/internal/helm/testdata/Azure/constellation-operators/charts/constellation-operator/templates/deployment.yaml
cli/internal/helm/testdata/GCP/constellation-operators/charts/constellation-operator/templates/deployment.yaml
cli/internal/helm/testdata/QEMU/constellation-operators/charts/constellation-operator/templates/deployment.yaml
internal/versions/versions.go

- Update operator image. Necessary because helm charts expect ko image, but current image is not a ko image.

versions: update constellation operator image

---

.github/workflows/purge-main.yml

fix: https://github.com/edgelesssys/constellation/actions/runs/4052877460

ci: fix purge-main permissions

---

.github/workflows/package-hasher.yml

- Fixing: https://github.com/edgelesssys/constellation/actions/runs/4045179888/jobs/6956304157
- Successful run: https://github.com/edgelesssys/constellation/actions/runs/4045312635/jobs/6956614027

ci: fix oras download in package hasher

---

.github/actions/e2e_kbench/action.yml

- Installing updated version of k-bench fork manually and pinned

ci: don't use k-bench install script

---

.github/workflows/build-keyservice-image.yml

Seems like the rename did not make it to the right ko branch ^^

ci: fix manual keyservice build workflow

---

.github/workflows/build-apko-image.yml
.github/workflows/build-constellation-node-operator.yml
.github/workflows/build-joinservice-image.yml
.github/workflows/build-keyservice-image.yml
.github/workflows/build-qemu-metadata-image.yml
.github/workflows/build-verification-service.yml

ci: trigger builds on workflow change

---

.github/workflows/package-hasher.yml

ci: fix hasher permissions

---

.bazelrc
WORKSPACE.bazel

- build: specify C toolchains correctly
All toolchains should be registered in the Workspace.
Also, static toolchains should enforce musl (instead of not having any constraint for the libc).

build: specify C toolchains correctly

---

.github/workflows/update-cli-reference.yml

- Bug detected in https://github.com/edgelesssys/constellation/pull/1134

ci: fix location of cli docgen output

---

cli/internal/cmd/create.go
cli/internal/cmd/iam.go
cli/internal/cmd/iam_test.go

- Add support for the `--debug` flag (which enables debug logging) to the iam create command.
- I was unsure which things are worth to log as the command output is quite verbose already. Let me know if there are any objections to the choices I made.

cli: add debug logging to iam create command

---

.github/actions/build_apko/action.yml
.github/actions/build_apko/build_and_sign.sh
.github/workflows/build-apko-image.yml

- Failed run: https://github.com/edgelesssys/constellation/actions/runs/4122960481
- Successful run on this branch: https://github.com/edgelesssys/constellation/actions/runs/4145325292

ci: fix workdir of apko base image build

---

.github/workflows/docs-vale.yml

ci: better naming for spelling check workflow

---

renovate.json

renovate: group hashicorp/go-kms-wrapping upgrades

---

.github/workflows/build-os-image.yml

- Fix that we uploaded measurement twice instead of signature.

ci: fix: upload signature of measurements.

---

.github/workflows/build-joinservice-image.yml

- Is currently pushed to "joinservice", should be pushed to "join-service"

ci: use correct container name to tag joinservice

---

docs/docs/workflows/config.md

- Extend the docs on Terraform IAM resource destruction; Before, they didn't mention that removing the state directory is necessary to be able to create a new cluster in the same wd

docs: extend docs on Terraform iam resource destruction

---

docs/docs/workflows/terminate.md

- Change the required files for cluster termination from `terraform.tfstate` to the Terraform state directory defined in `constants.go`
- As mentioned in #1154

docs: fix terminate docs filename

---

.lycheeignore
docs/docs/architecture/components.md
docs/docs/architecture/images.md
docs/docs/architecture/keys.md
docs/docs/architecture/networking.md
docs/versioned_docs/version-2.0/architecture/components.md
docs/versioned_docs/version-2.0/architecture/images.md
docs/versioned_docs/version-2.0/architecture/keys.md
docs/versioned_docs/version-2.0/architecture/networking.md
docs/versioned_docs/version-2.1/architecture/components.md
docs/versioned_docs/version-2.1/architecture/images.md
docs/versioned_docs/version-2.1/architecture/keys.md
docs/versioned_docs/version-2.1/architecture/networking.md
docs/versioned_docs/version-2.2/architecture/components.md
docs/versioned_docs/version-2.2/architecture/images.md
docs/versioned_docs/version-2.2/architecture/keys.md
docs/versioned_docs/version-2.2/architecture/networking.md
docs/versioned_docs/version-2.3/architecture/components.md
docs/versioned_docs/version-2.3/architecture/images.md
docs/versioned_docs/version-2.3/architecture/keys.md
docs/versioned_docs/version-2.3/architecture/networking.md
docs/versioned_docs/version-2.4/architecture/components.md
docs/versioned_docs/version-2.4/architecture/images.md
docs/versioned_docs/version-2.4/architecture/keys.md
docs/versioned_docs/version-2.4/architecture/networking.md
docs/versioned_docs/version-2.5/architecture/components.md
docs/versioned_docs/version-2.5/architecture/images.md
docs/versioned_docs/version-2.5/architecture/keys.md
docs/versioned_docs/version-2.5/architecture/networking.md

* Cilium moved pages in new docs version
* sigstore blog post no longer exists
* Some link check exceptions aren't needed anymore
* Link to our gitlab is correctly reported as broken. Someone should fix this ;)

Fix links and clean lycheeignore

---

dev-docs/workflows/release.md

- As discussed during standup we should promote the label `needs-backport` more so relevant bug fixes make it into the release.

docs: mention 'needs-backport' label in release process

---

.github/workflows/test-go-generate.yml
.github/workflows/test-tf.yml
.github/workflows/test-tidy.yml

- Workflow couldn't push commits, see https://github.com/edgelesssys/constellation/actions/runs/4207409299/jobs/7302161303

ci: add missing ci token

---

renovate.json

- Feature was added in https://github.com/renovatebot/renovate/pull/19431
- Documented in https://docs.renovatebot.com/modules/manager/gomod/#additional-information

renovate: update transitive Go dependencies

---

.github/actions/versionsapi/Dockerfile
hack/qemu-metadata-api/Dockerfile

- Fixes: https://github.com/edgelesssys/constellation/actions/runs/4225658181/jobs/7338215355
- Successful run: https://github.com/edgelesssys/constellation/actions/runs/4225823491/jobs/7338567018

ci: add missing replaced mod files to docker build

---

.github/workflows/codeql.yml
.github/workflows/test-govulncheck.yml
.github/workflows/test-integration.yml
.github/workflows/test-lint.yml
.github/workflows/test-shellcheck.yml
.github/workflows/test-shellfmt.yml
.github/workflows/test-tf.yml
.github/workflows/test-tfsec.yml
.github/workflows/test-tidy.yml
.github/workflows/test-unittest.yml

- current path was wrong and wouldn't trigger

ci: fix self trigger paths of workflows

---

.grype.yaml

- Test run :green_circle: https://github.com/edgelesssys/constellation/actions/runs/4234070882
- Created via hints from @datosh and @malt3. Taken from #1233.
- Opening extra PR as I am not sure about katexochen's availability

ci: ignore GHSA-r2h5-3hgw-8j34 in grype

---

.github/actions/build_ko/action.yml

- Containers weren't pushed with latest tag on main as the comparison failed

ci: fix comparision of ref name

---

.github/actions/build_ko/action.yml

- https://github.com/edgelesssys/constellation/actions/runs/4261462682/jobs/7415814692

ci: fix build-ko action bash

---

cli/internal/cmd/init.go

- fix force flag debug print in Constellation init

cli: fix force flag debug print in init

---

.ko.yaml

ko: update apko base images

---

.github/actions/versionsapi/action.yml

- run: https://github.com/edgelesssys/constellation/actions/runs/4263846730

ci: fix quoting of versionsapi flags

---

bootstrapper/cmd/bootstrapper/main.go
disk-mapper/cmd/main.go
internal/attestation/aws/issuer.go
internal/attestation/azure/azure.go
internal/attestation/azure/snp/issuer.go
internal/attestation/azure/trustedlaunch/issuer.go
internal/attestation/azure/trustedlaunch/trustedlaunch_test.go
internal/attestation/gcp/issuer.go
internal/attestation/qemu/issuer.go
internal/attestation/vtpm/attestation.go
internal/attestation/vtpm/attestation_test.go
verify/cmd/main.go

- Enable easier debugging by adding logging to attestation issuer

internal: add logging to attestation issuer

---

internal/config/config.go
internal/config/config_test.go

config: use toPtr func to get pointers

---

.github/actions/build_ko/action.yml
.github/workflows/build-keyservice-image.yml

- Failed run: https://github.com/edgelesssys/constellation/actions/runs/4295215370
- Run on this branch: https://github.com/edgelesssys/constellation/actions/runs/4295713726

ci: pin ko version

---

disk-mapper/cmd/main.go

disk-mapper: make openstack image bootable

---

docs/docs/workflows/troubleshooting.md
docs/versioned_docs/version-2.2/workflows/troubleshooting.md
docs/versioned_docs/version-2.3/workflows/troubleshooting.md
docs/versioned_docs/version-2.4/workflows/troubleshooting.md
docs/versioned_docs/version-2.5/workflows/troubleshooting.md

Pressed "Merge" but forgot the versioned docs :/
Plus also removed "step" in the other sentence.

docs: adjust wording for resource provider troubleshooting

---

.github/actions/constellation_create/action.yml

- Sometimes we have situations where debug logging would be helpful. Esp during init.

ci: run constellation commands with `--debug`

---

.github/workflows/package-hasher.yml
.github/workflows/release.yml
.github/workflows/test-go-generate.yml
.github/workflows/test-tf.yml
.github/workflows/test-tidy.yml
.github/workflows/update-cli-reference.yml

ci: change push/pr token

---

renovate.json

without prefix
- Currently the gcp-guest-agent isn't updated correctly

renovate: fix versioning for containers

---

cli/internal/cloudcmd/create.go
cli/internal/terraform/terraform/openstack/main.tf
cli/internal/terraform/terraform/openstack/modules/instance_group/main.tf
cli/internal/terraform/terraform/openstack/modules/instance_group/variables.tf
cli/internal/terraform/terraform/openstack/variables.tf
cli/internal/terraform/variables.go
internal/config/config.go
internal/config/config_doc.go
internal/config/config_test.go
internal/constants/constants.go

- cli: set OpenStack service account credentials

cli: set OpenStack service account credentials

---

.github/actions/e2e_sonobuoy/action.yml

- release notes: https://github.com/vmware-tanzu/sonobuoy/releases/tag/v0.56.16

deps: update sonobuoy

---

hack/go.mod
operators/constellation-node-operator/go.mod

- These are fixed on main because of the local replace rules but dependabot doesn't recognize this.

deps: fix dependabot security warnings

---

.github/actions/e2e_benchmark/README.md
.github/actions/e2e_benchmark/evaluate/compare.py

- Missed these in the previous PR, sorry about that

ci: fix typo in benchmark actions

---

docs/docs/architecture/orchestration.md
docs/docs/architecture/versions.md
docs/docs/reference/terraform.md
docs/docs/workflows/config.md
docs/sidebars.js
docs/versioned_docs/version-2.0/architecture/orchestration.md
docs/versioned_docs/version-2.1/architecture/orchestration.md
docs/versioned_docs/version-2.2/architecture/orchestration.md
docs/versioned_docs/version-2.2/getting-started/install.md
docs/versioned_docs/version-2.3/architecture/orchestration.md
docs/versioned_docs/version-2.3/getting-started/install.md
docs/versioned_docs/version-2.3/workflows/config.md
docs/versioned_docs/version-2.4/architecture/orchestration.md
docs/versioned_docs/version-2.4/getting-started/install.md
docs/versioned_docs/version-2.4/workflows/config.md
docs/versioned_docs/version-2.5/architecture/orchestration.md
docs/versioned_docs/version-2.5/getting-started/install.md
docs/versioned_docs/version-2.5/workflows/config.md

Some fixes and rewording in view of the upcoming release.

docs: few fixes and rewording

---

.github/workflows/build-os-image.yml
image/secure-boot/aws/create_uefivars.sh

- pin aws uefivars version
- install new deps
- 🟢 [build pipeline](https://github.com/edgelesssys/constellation/actions/runs/4341516757)
- 🟢 [build pipeline (with git commit pinned)](https://github.com/edgelesssys/constellation/actions/runs/4342861973)

image: pin aws uefivars version and install new deps

---

bootstrapper/internal/initserver/initserver.go

bootstrapper: make sure InitServer is only shut down after Init has returned

---

.github/actions/versionsapi/action.yml

ci: use latest ver of versionsapi cli container

---

.github/actions/build_ko/action.yml
.github/actions/container_sbom/action.yml
.github/actions/install_syft_grype/action.yml
.github/workflows/build-os-image.yml

ci: fix labeling when building other branches than github.head_ref

---

cli/internal/helm/loader.go
internal/cloud/cloudprovider/cloudprovider.go

use any instead of interface{}

---

cli/internal/cmd/init.go
cli/internal/cmd/miniup.go
cli/internal/cmd/spinner.go

cli: add missing flag to miniConstellation

---

renovate.json

from constellation container group

renovate: exclude cloud-provider-gcp

---

.github/actions/build_measurement_reader/action.yml
.github/workflows/build-binaries.yml
.github/workflows/build-os-image.yml

fix: add measurement-reader to build pipeline

---

image/mkosi.conf.d/mkosi.conf

- image: increase esp size
Build pipeline currently fails since files for ESP grew slightly over the size of the ESP partition.

image: increase esp size

---

.grype.yaml
hack/go.mod
operators/constellation-node-operator/go.mod

- The code is replaced, so the last ghsa don't affect us

ci: ignore replaced ghsa

---

cli/internal/cmd/version.go
internal/constants/enterprise.go
internal/constants/oss.go

Edition is already contained in the VersionBuild

cli: remove Edition in version command, which contains duplicate info

---

.github/workflows/test-bazel.yml
.github/workflows/test-tidy.yml
BUILD.bazel
CMakeLists.txt
bazel/ci/BUILD.bazel
bazel/ci/tidy.sh
toolchains/go_module_deps.bzl

ci: adopt tidy workflow for Bazel

---

.github/workflows/build-gcp-guest-agent.yml

- Current versioning isn't handled by renovate

ci: tag GCP guest agent with semver

---

internal/versions/versions.go

deps: update GCP guest agent image

---

internal/versions/versions.go

deps: update containers to v2.7.0-pre

---

README.md
docs/docs/getting-started/first-steps-local.md
docs/docs/getting-started/first-steps.md
docs/docs/workflows/troubleshooting.md
docs/versioned_docs/version-2.6/getting-started/first-steps-local.md
docs/versioned_docs/version-2.6/getting-started/first-steps.md
docs/versioned_docs/version-2.6/workflows/troubleshooting.md

We want to maintain a list of known issues for the latest release. These should help users to work around a problem before we are able to bring a patch.
Please check if locations for the references make sense and if it should additionally be added elsewhere.

docs: refer to known issues

---

bazel/devbuild/BUILD.bazel
bazel/devbuild/prepare_developer_workspace.sh.in

- bazel: format devbuild files

bazel: format devbuild files

---

docs/screencasts/docker/Dockerfile

docs: pin base image of screencast container

---

cli/internal/terraform/terraform/azure/main.tf

- Add MAA URL to instance tags so it can be consumed by the instance to create MAA tokens

Add MAA URL to instance tags

---

internal/config/validation.go

config: set Azure-SEV-SNP as default azure attestation variant

---

cli/internal/cmd/init.go

cli: fix typo

---

cli/internal/helm/loader.go
internal/attestation/azure/snp/BUILD.bazel

- Use one `loadRelease` function instead of one function for each release.

cli: minor restructuring for loading helm charts

---

.bazelrc
.gitignore

- allows for user defined overwrite such as remote builder credentials

bazel: allow user defined overwrites

---

cli/internal/helm/client.go

- Temporarily add the attestationVariant key to the service values during upgrade. Normally this should not be modified during upgrade. However, since the field is introduced in v2.7, we need to add the field manually.

cli: add attestationVariant upgrade migration

---

cli/internal/terraform/terraform/gcp/main.tf
cli/internal/terraform/terraform/gcp/modules/instance_group/main.tf
cli/internal/terraform/terraform/gcp/modules/instance_group/variables.tf
hack/terraform/gcp/internal-loadbalancer/main.tf
hack/terraform/gcp/internal-loadbalancer/modules/instance_group/main.tf
hack/terraform/gcp/internal-loadbalancer/modules/instance_group/variables.tf

- Add a default "-1-" to the worker group naming on GCP
- correctly pass the alias cidr name

terraform: allow for multiple instance groups on gcp

---

3rdparty/node-maintenance-operator/go.mod
hack/go.mod
operators/constellation-node-operator/api/go.mod
operators/constellation-node-operator/go.mod

- Seems like these were forgotten when upgrading to Go 1.20

go: update submodules to Go 1.20

---

.github/actions/e2e_test/action.yml
.github/actions/e2e_verify/action.yml
.github/actions/shortname/action.yaml
.github/workflows/build-os-image.yml
.github/workflows/e2e-test-daily.yml
.github/workflows/e2e-test-manual.yml
.github/workflows/e2e-test-weekly.yml
.github/workflows/release.yml

ci: run e2e test weekly on last release

---

.github/actions/e2e_benchmark/evaluate/compare.py
.github/actions/e2e_benchmark/evaluate/parse.py
.github/actions/e2e_benchmark/evaluate/test-inputs/constellation-azure.json
.github/actions/e2e_benchmark/evaluate/test-inputs/fio-constellation-azure.json
.github/actions/e2e_benchmark/evaluate/test-inputs/knb-constellation-azure.json
.github/actions/e2e_benchmark/evaluate/test.py

- Fix the current problem with the compare method
- Refactor and add unit tests
- It's not the cleanest python code and unittests. Not sure how much engineering we want to put into this since our goal is to parse some numbers and put them into json files.

ci: add unittests for the benchmark actions

---

bazel/ci/BUILD.bazel
bazel/ci/buf.sh.in
bazel/toolchains/ci_deps.bzl
debugd/service/debugd.proto
disk-mapper/recoverproto/recover.proto
joinservice/joinproto/join.proto
keyservice/keyserviceproto/keyservice.proto
upgrade-agent/upgradeproto/upgrade.proto
verify/verifyproto/verify.proto

bazel: add buf as protobuf formatter to //:tidy

---

bazel/ci/shellcheck.sh.in
bazel/ci/shfmt.sh.in

- exclude node modules from shellcheck

bazel: exclude node modules from shellcheck

---

go.work

go: clean work file

---

README.md

- govulncheck was integrated into the bazel check target. happy to take other suggestions for fixing this. came up because the linkchecker is unhappy.

docs: update govulncheck badge to new workflow

---

internal/atls/README.md

- Fix link in README.md
- Make link-checker happy again :)

atls: fix link in README.md

---

rfc/attestation-config.md

Add RFC for attestation options in Constellation's config file.
Open Discussion: comments, suggestions and feedback are highly appreciated

rfc: attestation config options

---

.ko.yaml

deps: update ko base images

---

cli/internal/cmd/iamcreate.go

cli: remove duplicated print

---

cli/internal/cmd/iamcreate.go
docs/docs/reference/cli.md

cli: add missing -y short flag to iam create

---

renovate.json

- ci: fix grouping of renovate groups
- https://github.com/renovatebot/renovate/discussions/16419
- https://github.com/renovatebot/renovate/discussions/13226

ci: fix grouping of renovate groups

---

.github/workflows/purge-main.yml

- Was in dryrun mode until now, we should start deleting

ci: purge images on main

---

internal/license/checker_enterprise.go

- This was missed in #1539 and caused the e2e test's to fail on release: https://github.com/edgelesssys/constellation/actions/runs/4599070678/jobs/8123977627#step:8:1070

license: remove check for Azure.ConfidentialVM

---

internal/license/checker_enterprise.go

license: remove check for Azure.ConfidentialVM (#1602)

---

bazel/ci/BUILD.bazel

ci: run //:check and //:generate concurrently

---

.github/actions/constellation_create/action.yml
.github/actions/e2e_test/action.yml
.github/workflows/e2e-test-release.yml

- https://github.com/edgelesssys/constellation/actions/runs/4599745883/jobs/8125498554

ci: fix empty image input of verify e2e on release

---

bazel/ci/BUILD.bazel

ci: run //:check and //:generate concurrently (#1606)

---

.github/actions/constellation_create/action.yml
.github/actions/e2e_test/action.yml
.github/workflows/e2e-test-release.yml

* ci: fix empty image input of verify e2e on release
* ci: increase parallelism of e2e release workflow

ci: fix empty image input of verify e2e on release (#1604)

---

.github/workflows/release-cli.yml

ci: always release cli on release-cli workflow

---

bootstrapper/cmd/bootstrapper/main.go
cli/internal/cloudcmd/create.go
cli/internal/cloudcmd/create_test.go
cli/internal/cloudcmd/validators_test.go
cli/internal/helm/loader_test.go
cli/internal/helm/testdata/OpenStack/constellation-services/charts/join-service/templates/daemonset.yaml
cli/internal/helm/testdata/OpenStack/constellation-services/charts/verification-service/templates/daemonset.yaml
cli/internal/terraform/terraform/openstack/main.tf
debugd/cmd/debugd/debugd.go
image/mkosi.files/mkosi.openstack.conf
internal/attestation/measurements/measurements_oss.go
internal/config/config.go
internal/config/config_doc.go
internal/config/config_test.go
internal/config/validation.go

- Add OpenStack vTPM support
- Set attestation variant for OpenStack to qemu-vtpm

image: OpenStack vTPM

---

.github/workflows/e2e-upgrade.yml
cli/internal/kubernetes/upgrade.go
cli/internal/kubernetes/upgrade_test.go
e2e/internal/upgrade/BUILD.bazel
e2e/internal/upgrade/image.go
e2e/internal/upgrade/upgrade_test.go

cli: fix misleading error while applying kubernetes-only upgrade (#1630)

---

.github/actions/constellation_create/action.yml
.github/actions/constellation_iam_create/action.yml
.github/actions/e2e_sonobuoy/action.yml
.github/actions/e2e_test/action.yml
.github/workflows/e2e-upgrade.yml

ci: cleanup and refactoring

---

.github/actions/notify_failure/action.yml
.github/failure_project_template.md

ci: improve e2e failure reporting and checklist

---

.github/workflows/on-release.yml

- The workflow was broken, which caused the version upload to fail in the v2.7.0 release, see https://github.com/edgelesssys/constellation/actions/runs/4610414533
- Bug introduced in #1377 
- Successful run: https://github.com/edgelesssys/constellation/actions/runs/4701204382

ci: fix version publishing on release

---

.github/workflows/on-release.yml

ci: fix version publishing on release (#1658)

---

.github/actions/constellation_create/action.yml
.github/actions/constellation_destroy/action.yml
.github/workflows/build-os-image.yml
.github/workflows/e2e-test-release.yml
.github/workflows/e2e-upgrade.yml

ci: reduce number of steps with continue-on-error

---

.github/actions/e2e_sonobuoy/action.yml
.github/actions/e2e_test/action.yml

- Fixing stuff that caused failure due to bad naming in https://github.com/edgelesssys/constellation/actions/runs/4705664276
- AWS: https://github.com/edgelesssys/constellation/actions/runs/4706876674
- GCP: https://github.com/edgelesssys/constellation/actions/runs/4706875477
- Azure:https://github.com/edgelesssys/constellation/actions/runs/4706874289

ci: fix naming issues

---

cli/internal/terraform/terraform/azure/main.tf
docs/docs/getting-started/install.md

- Remove unused pod subnet
- Use dedicated NAT gateway instead of relying on egress rules inside the LB
please review first: https://github.com/edgelesssys/edgeless-iam/pull/13
This change is needed to adjust the CI permissions.
CI: https://github.com/edgelesssys/constellation/actions/runs/4701703640/jobs/8338081437

terraform: use nat gateway on azure

---

.github/actions/constellation_iam_create/action.yml
.github/actions/e2e_autoscaling/action.yml
.github/actions/e2e_test/action.yml
.github/actions/os_build_variables/action.yml
.github/actions/pseudo_version/action.yml
.github/actions/select_image/action.yml
.github/actions/versionsapi/action.yml
.github/workflows/build-gcp-guest-agent.yml
.github/workflows/build-os-image-scheduled.yml
.github/workflows/build-os-image.yml
.github/workflows/e2e-test-manual.yml
.github/workflows/e2e-test-release.yml
.github/workflows/e2e-test-weekly.yml
.github/workflows/purge-main.yml
.github/workflows/release.yml
.github/workflows/test-tidy.yml
.github/workflows/versionsapi.yml

ci: various improvements

---

operators/constellation-node-operator/controllers/autoscalingstrategy_controller_env_test.go
operators/constellation-node-operator/controllers/nodeversion_controller_env_test.go
operators/constellation-node-operator/controllers/nodeversion_controller_test.go
operators/constellation-node-operator/controllers/pendingnode_controller_env_test.go
operators/constellation-node-operator/controllers/scalinggroup_controller_env_test.go
operators/constellation-node-operator/controllers/scalinggroup_controller_test.go
operators/constellation-node-operator/controllers/suite_test.go

- We now reset the test environment by deleting all Kubernetes resources, as well as resetting all fakes.

operator: isolate integration tests

---

.github/workflows/e2e-test-daily.yml
.github/workflows/e2e-test-weekly.yml
.github/workflows/e2e-upgrade.yml

ci: fix notification trigger

---

docs/docs/reference/terraform.md

- Add docs on Terraform debugging / logging
- Should be merged into main once #1620 is merged.

docs: add docs on Terraform debugging

---

.github/workflows/e2e-test-daily.yml
.github/workflows/e2e-test-release.yml
.github/workflows/e2e-test-weekly.yml
.github/workflows/e2e-upgrade.yml

- Add `packages: write` and `checks: write` permissions to remaining workflows
- Relevant part of upgrade test went through: https://github.com/edgelesssys/constellation/actions/runs/4784859808/jobs/8506870746

ci: add missing permissions to workflows

---

.github/workflows/e2e-test-weekly.yml

ci: add missing permissions for e2e-upgrade job

---

.github/actions/install_operator_sdk/action.yml
.github/workflows/build-os-image.yml
.github/workflows/release-cli.yml
.github/workflows/test-tidy.yml
e2e/miniconstellation/test-remote.sh
hack/docgen-builder/build-and-upload.sh
hack/pseudo-version/pseudo_version_tool_freshness.sh.in
image/measured-boot/precalculate_pcr_12.sh
image/measured-boot/precalculate_pcr_9.sh
tools/update-pseudo-version-tool.sh

- misc: replace sha256sum with shasum -a 256
Darwin ships with shasum but without sha256sum so we should use the portable solution.
This is meant to extend #1680

misc: replace sha256sum with shasum -a 256

---

cli/internal/cmd/iamdestroy.go
cli/internal/terraform/terraform/azure/main.tf
cli/internal/terraform/terraform/iam/azure/main.tf
docs/docs/workflows/config.md

cli: force-delete Azure resource group (#1667)

---

cli/internal/terraform/terraform/iam/aws/main.tf

- Before the worker nodes had the control plane permissions attached
- Added the needed permissions for the bootstrapper to join the Constellation

terraform: fix aws worker node permission

---

dev-docs/workflows/build-test-run.md

To not confuse the user, this PR align the suggested value for container_prefix in the `.bazeloverwriterc` to the one mentioned above

docs: align container_prefix suggestion

---

.github/actions/constellation_create/action.yml
.github/actions/constellation_destroy/action.yml
.github/actions/constellation_iam_create/action.yml
.github/actions/constellation_iam_destroy/action.yml
.github/actions/e2e_test/action.yml
.github/actions/upload_terraform_logs/action.yml
.github/workflows/e2e-test-daily.yml
.github/workflows/e2e-test-manual.yml
.github/workflows/e2e-test-release.yml
.github/workflows/e2e-test-weekly.yml
.github/workflows/e2e-upgrade.yml

- Upload a Terraform log artifact at `DEBUG` level for manual inspection of Terraform failures.
- [AWS Run](https://github.com/edgelesssys/constellation/actions/runs/4718634933)
- [Azure Run](https://github.com/edgelesssys/constellation/actions/runs/4718638266)
- [GCP Run](https://github.com/edgelesssys/constellation/actions/runs/4718637100)
- Change to `JSON` level later on and upload the logs to OpenSearch.

ci: add Terraform logging

---

.github/workflows/build-os-image-scheduled.yml

- See failure in: https://github.com/edgelesssys/constellation/actions/runs/4824385950

ci: fix os image build schedule

---

.github/actions/install_operator_sdk/action.yml
.github/workflows/build-os-image.yml
.github/workflows/release-cli.yml
.github/workflows/test-tidy.yml
e2e/miniconstellation/test-remote.sh
hack/docgen-builder/build-and-upload.sh
hack/pseudo-version/pseudo_version_tool_freshness.sh.in
image/measured-boot/precalculate_pcr_12.sh
image/measured-boot/precalculate_pcr_9.sh
tools/update-pseudo-version-tool.sh
tools/workspace_status.sh

tools: use either sha256sum or shasum

---

.github/workflows/e2e-mini.yml
.github/workflows/e2e-test-release.yml

- ci: skip e2e tests if caller was not successful
- ci: add all required (transitive) permissions to release e2e test

ci: skip e2e tests if caller was not successful

---

.github/workflows/e2e-test-daily.yml
.github/workflows/e2e-test-release.yml
.github/workflows/e2e-test-weekly.yml
.github/workflows/e2e-upgrade.yml

ci: use uuidgen to get uuid, for macos compability

---

.github/workflows/e2e-mini.yml
.github/workflows/e2e-test-release.yml

ci: skip e2e tests if caller was not successful (#1714)

---

.github/workflows/e2e-mini.yml

ci: fix e2e miniconstellation abort condition

---

.github/actions/constellation_create/action.yml

- This came up in the daily tests. Config was updated, measurements field is in a new location.

ci: update measurement overwrite for config v3

---

.github/workflows/e2e-mini.yml

ci: fix e2e miniconstellation abort condition (#1728)

---

docs/docs/architecture/attestation.md

- Add short explanation on attestation config options
- See https://github.com/edgelesssys/constellation/pull/1623 for the changes documented here

docs: add short explanation on attestation config options

---

rfc/image-api.md

- define image info v2
- define measurements v2

rfc: image info v2

---

docs/docs/overview/clouds.md

- Update state of clouds
- Will backport these changes after the review to 2.7

docs: update state of clouds

---

rfc/reproducible-builds.md

- The blogpost from podman no longer exists
- Replacing with a link from the buildah github

rfc: fix broken link

---

.github/actions/e2e_verify/action.yml

- verify e2e test was still using the old format, this PR fixes the issue by selecting the correct config key depending on config version
Azure e2e test: https://github.com/edgelesssys/constellation/actions/runs/4915318043
GCP e2e test: https://github.com/edgelesssys/constellation/actions/runs/4915320377

ci: fix measurements injection in verify e2e test

---

.github/actions/e2e_mini/action.yml
.github/workflows/e2e-mini.yml
cli/internal/cmd/miniup.go

- fix minicon e2e test: https://github.com/edgelesssys/constellation/actions/runs/4959554676

ci: fix minicon e2e test

---

internal/osimage/gcp/gcpupload.go

- image: include stream in gcp image name
- [debug build](https://github.com/edgelesssys/constellation/actions/runs/4988813082)
- [console build](https://github.com/edgelesssys/constellation/actions/runs/4988814320)

image: include stream in gcp image name

---

bazel/ci/BUILD.bazel

- Run all jobs in the `check` target until they finish even if one encounters an error

bazel: dont stop check on error

---

bazel/toolchains/dnf_deps.bzl

- deps: update bazeldnf digest to v0.5.7

deps: update bazeldnf digest to v0.5.7

---

cli/internal/terraform/terraform.go

- Prevents the appearance of https://github.com/hashicorp/terraform/issues/32447 introduced in the tdx qemu changes when using version e.g. v1.3.7

deps: bump minimum terraform version

---

image/upload/internal/cmd/upload.go

- add `string.ToLower()` around the CSP's name

ci: fix os image archive path

---

docs/docs/getting-started/first-steps-local.md
docs/docs/reference/config-migration.md
docs/versioned_docs/version-2.7/getting-started/first-steps-local.md
docs/versioned_docs/version-2.7/getting-started/first-steps.md
docs/versioned_docs/version-2.7/overview/clouds.md
docs/versioned_docs/version-2.7/reference/config-migration.md
docs/versioned_docs/version-2.7/workflows/config.md
docs/versioned_docs/version-2.7/workflows/create.md

Publish docs on local cluster with QEMU provider, cloud SNP status, and minor things.

docs: publish

---

bazel/ci/golangci_lint.sh.in

- ci: explicitly disable cgo in golangci-lint

ci: explicitly disable cgo in golangci-lint

---

.github/workflows/on-release.yml
.github/workflows/release.yml
dev-docs/workflows/release.md

- ci: run release workflow on temporary branch
- [test run](https://github.com/edgelesssys/constellation/actions/runs/5001848452)

ci: run release workflow on temporary branch

---

bazel/toolchains/go_module_deps.bzl
cli/BUILD.bazel
cli/internal/cmd/BUILD.bazel
cli/internal/cmd/miniup.go
cli/internal/cmd/miniup_cross.go
cli/internal/cmd/miniup_linux_amd64.go
cli/internal/terraform/loader.go
go.mod
go.sum
hack/go.mod
hack/go.sum

- cli: add windows amd64 build target
- This only enables building the cli on Windows. We do not yet test or ship this variant!
- This does ensure the cli can be built on windows since it is a target of the CI

cli: add windows amd64 build target

---

internal/staticupload/BUILD.bazel
internal/staticupload/delete.go
internal/staticupload/staticupload.go
internal/staticupload/staticupload_test.go
internal/staticupload/upload.go

- ci: static file uploader with automatic cache invalidation
- To keep the PR smaller, I will add follow-up PRs where I replace any uses of the s3 client for uploads with this implementation

ci: static file uploader with automatic cache invalidation

---

.github/workflows/build-os-image.yml

- ci: do not sign & upload debug image measurements
- [image build (debug)](https://github.com/edgelesssys/constellation/actions/runs/5141973427)
- [image build (nightly)](https://github.com/edgelesssys/constellation/actions/runs/5141975777)

ci: do not sign & upload debug image measurements

---

hack/cli-k8s-compatibility/main.go
hack/configapi/cmd/root.go
image/upload/internal/cmd/aws.go
image/upload/internal/cmd/azure.go
image/upload/internal/cmd/flags.go
image/upload/internal/cmd/gcp.go
image/upload/internal/cmd/image.go
image/upload/internal/cmd/info.go
image/upload/internal/cmd/measurementsupload.go
image/upload/internal/cmd/nop.go
internal/api/attestationconfig/client/BUILD.bazel
internal/api/attestationconfig/client/client.go
internal/api/attestationconfig/client/client_test.go
internal/api/client/BUILD.bazel
internal/api/client/client.go
internal/api/versions/cli/add.go
internal/api/versions/cli/latest.go
internal/api/versions/cli/list.go
internal/api/versions/cli/rm.go
internal/api/versions/client/client.go
internal/osimage/archive/BUILD.bazel
internal/osimage/archive/archive.go
internal/osimage/imageinfo/BUILD.bazel
internal/osimage/imageinfo/imageinfo.go
internal/osimage/measurementsuploader/BUILD.bazel
internal/osimage/measurementsuploader/measurementsuploader.go
internal/staticupload/get.go
internal/staticupload/staticupload.go
internal/staticupload/staticupload_test.go

- ci: use aws s3 client that invalidates cloudfront cache
- [e2e test](https://github.com/edgelesssys/constellation/actions/runs/5134340654)

ci: use aws s3 client that invalidates cloudfront cache

---

.github/actions/versionsapi/Dockerfile

- paths were not updated during refactoring
- [testrun](https://github.com/edgelesssys/constellation/actions/runs/5153108633) :green_circle:

ci: fix versionsapi cli container Dockerfile

---

cli/internal/cmd/upgradecheck.go

- write target k8s version to config if new version is found on upgrade check

cli: write target k8s version to config if new version is found on upgrade check

---

e2e/internal/upgrade/upgrade_test.go

- Currently, the upgrade e2e calls `constellation status` after it finished executing `upgrade apply`. `status` may fail early on, if the control plane starts upgrading quickly and becomes unavailable. In that case we will have to retry a few times. Therefore, wrap the `status` invocation in a `require.Eventually`. Run this asynchronously and sync using a waitgroup.
- Needs https://github.com/edgelesssys/constellation/pull/1781/commits/2585baae1b593c02390bd6571f3e4827cb862027
[Azure, 1+1, K8s only](https://github.com/edgelesssys/constellation/actions/runs/5154246470)
Needs migration patch. In progress..

e2e: asynchronously check constellation status

---

docs/docs/workflows/upgrade.md

Incorporate customer feedback regarding the recommended commands when upgrading a Constellation cluster. Showing the full command "constellation upgrade check --write-config" is important to ensure only valid, safe upgrades are applied.
- docs: refine instructions for upgrade process

docs: refine instructions for upgrade process

---

internal/osimage/aws/awsupload.go

- image: choose unique AWS image names based on the attestation variant

image: choose unique AWS image names based on the attestation variant

---

.github/workflows/e2e-upgrade.yml
bazel/toolchains/go_module_deps.bzl
cli/internal/cmd/upgradeapply.go
e2e/internal/upgrade/BUILD.bazel
e2e/internal/upgrade/upgrade_test.go
go.mod
go.sum
operators/constellation-node-operator/internal/cloud/fake/client/BUILD.bazel
operators/constellation-node-operator/internal/cloud/fake/client/client.go
operators/constellation-node-operator/internal/constants/constants.go
operators/constellation-node-operator/internal/deploy/BUILD.bazel
operators/constellation-node-operator/internal/deploy/deploy.go

- operators: cleanup placeholder nodeversion

operators: cleanup placeholder nodeversion

---

dev-docs/conventions.md

doc: VS code hint

---

.github/actions/versionsapi/Dockerfile

- fix the broken ci build of the CLI:
https://github.com/edgelesssys/constellation/actions/runs/5201117022/jobs/9380801983
-

fix: ci build versionsapi-ci-cli

---

.github/actions/e2e_verify/action.yml

- ci: do not manually clear measurements on verify e2e
Output from pipeline:
```
Problems validating config file:
measurements is a required field
Fix the invalid entries or generate a new configuration using `constellation config generate`
Error: invalid configuration
```

ci: do not manually clear measurements on verify e2e

---

3rdparty/bazel/com_github_google_go_tpm_tools/ms_tpm_20_ref.need
3rdparty/bazel/com_github_google_go_tpm_tools/ms_tpm_20_ref.patch
3rdparty/bazel/org_openssl/BUILD.bazel
bazel/go/go_test.bzl
bootstrapper/internal/diskencryption/BUILD.bazel
csi/cryptmapper/BUILD.bazel
disk-mapper/internal/setup/BUILD.bazel
disk-mapper/internal/setup/interface.go
disk-mapper/internal/setup/mount_cross.go
disk-mapper/internal/setup/mount_linux.go
disk-mapper/internal/setup/setup.go
disk-mapper/internal/test/benchmark_test.go
hack/qemu-metadata-api/server/BUILD.bazel

- the source code had some linux specific code which was split to not cause errors on Mac OS
- the packages that require linux specific functionality are targeted only for linux in bazel and are therefore skipped on Mac
- attributions go to @malt3 (will co-author you in the commit)

local: fix mac issues in bazel

---

.github/workflows/release-cli.yml

- Add the necessary token permissions stated [here](https://docs.github.com/en/rest/overview/permissions-required-for-github-apps?apiVersion=2022-11-28), so that the action can [update](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#update-a-release) the release.

ci: fix changelog generation

---

bazel/toolchains/go_module_deps.bzl
go.mod
go.sum

- Update the `go-tpm-tools` fork from `v0.3.10` to `v0.3.12`

Update go-tpm-tools fork

---

hack/configapi/cmd/root.go
internal/api/attestationconfigapi/client.go
internal/api/attestationconfigapi/fetcher.go
internal/api/attestationconfigapi/fetcher_test.go

- change version format in parse to correctly read YYYY-MM-DD
- adjust tests to ensure that month parsing works
- [AB#3206](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3206)

config: fix parse azure version

---

.github/workflows/release-cli.yml
.github/workflows/release.yml

- ci: explicitly add CLI signature as release artifact

ci: explicitly add CLI signature as release artifact

---

.github/actions/pick_assignee/action.yml

- Update list of assignees to include Adrian. Removed Paul as he is currently not actively working on Constellation.

ci: replace katexochen with elchead in assignee list

---

.github/workflows/e2e-test-weekly.yml

- We released 2.8 so we need to test that 2.8 can upgrade to HEAD.

ci: upgrade fromVersion in e2e-upgrade

---

.github/pull_request_template.md

doc: add context to PR template

---

.github/actions/e2e_sonobuoy/action.yml

- Release notes: https://github.com/vmware-tanzu/sonobuoy/releases/tag/v0.56.17

deps: upgrade sonobuoy to v0.56.17

---

.github/pull_request_template.md

- The PR template misses a default bullet point in the `Context` section and a comment in the `Checklist` section creates a weirdly-rendered spacing between the bullet points of the checklist items.
See here:
- Add a default bullet point to the `Context` section.
- Remove the duplicate default bullet point in the `Proposed change(s)` section.
- Place the `dev-docs`-comment before the checklist items to fix the spacing.

ci: improve pr template

---

.github/actions/constellation_create/action.yml

https://github.com/edgelesssys/constellation/pull/1883 added more debug logs to `cdbg`, but they are currently not used since we don't run `cdbg` with debug verbosity in the CI
- Enable `cdbg` debug logging in the CI

ci: run cdbg with debug verbosity

---

.github/actions/build_cli/action.yml
.github/workflows/e2e-windows.yml

- Add a very basic test for the Windows CLI by creating and initializing a test cluster without any deployments.

ci: Windows cli tests

---

.github/actions/setup_bazel/action.yml
.github/workflows/reproducible-builds.yml
bazel/toolchains/ci_deps.bzl

- ci: add automated tests for reproducible builds

ci: add automated tests for reproducible builds

---

cli/internal/cmd/configmigrate.go
internal/config/config.go

- Fix capitalization for the error message returned by `UnsupportedAppRegistrationError`
- Add missing newline to output of `constellation config migrate` in case the config is already at the newest version

fix: small formating/spelling issues

---

docs/docs/workflows/storage.md

We're adding support for AWS encrypted storage but have not documented it so far.
- Add documentation for AWS encrypted storage.
- Additional small change: Remove the explicit notice for GCP snapshot support, as this is a feature of all the default drivers and documenting it indicates that it'd *only* be supported for GCP.

docs: document aws encrypted storage

---

.github/workflows/e2e-test-weekly.yml

We want to find potential breaks of miniconstellation quicker.
- add E2E miniconstellation to weekly pipeline

ci: add miniconstellation to e2e weekly

---

docs/docusaurus.config.js
docs/package.json

- Adds the google analytics plugin
- Enables the cookiebot banner

docs: enable ga and cookie banner

---

cli/internal/helm/charts/edgeless/constellation-services/charts/aws-csi-driver/values.yaml
cli/internal/helm/update-csi-charts.sh

- deps: upgrade AWS CSI driver to v1.1.1

deps: upgrade AWS CSI driver to v1.1.1

---

disk-mapper/cmd/main.go

If one of the function calls would fail, the logger would only log the function type of `zap.Err`
- Call the function with the error instead of passing the function.

diskmapper: fix zap.Error without err

---

.github/actions/notify_failure/action.yml
.github/teams_payload_template.json

feat: get notified in Teams on E2E test failure ticket

---

.github/actions/notify_failure/action.yml

ci: fix broken e2e notify failure

---

.github/workflows/release.yml

We want to have debug and console images available for the exact versions that are released.
This allows for easier reproduction of bugs.
- ci: build all streams on release

ci: build all streams on release

---

dev-docs/miniconstellation/README.md
dev-docs/miniconstellation/azure-terraform/.terraform.lock.hcl
dev-docs/miniconstellation/azure-terraform/cloud-init.yaml
dev-docs/miniconstellation/azure-terraform/create-vm.sh
dev-docs/miniconstellation/azure-terraform/main.tf
dev-docs/miniconstellation/azure-terraform/output.tf
dev-docs/miniconstellation/azure-terraform/variables.tf
dev-docs/miniconstellation/setup-miniconstellation.sh
docs/docs/getting-started/first-steps-local.md

The goal is to make the first use of Constellation easier for people who DON'T already have a Linux machine.
The easiest setup is MiniConstellation since it does not involve any creation of IAM resources or resource quotas to spin up a full cluster.
As of now MiniConstellation is only supported on Linux. We cannot expect everyone to use Linux locally, especially product managers or other higher level people.
We don't document AWS, since their supported bare-metal machines are very big and expensive.
- document how to set up Azure to run MiniConstellation
- [AB#3201](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3201)

docs: how to set up MiniConstellation on Azure

---

docs/docs/getting-started/first-steps-local.md

- Add a sentence about the option to use a VM. It's a bit redundant to the prerequisites, but I think it's better to have it more prominent.
- Minor reordering of the preqrequisites
- Install commands
- Add some sudos (I guess you copied that from the cloud-init ;)
- Simplify some commands
- Remove start of docker service. I think this works reliably when you install it on a shell. But I can re-add it if you'd prefer that.
- Other small changes

docs: suggest changes for first-steps-local

---

docs/docs/architecture/attestation.md
docs/docs/architecture/versions.md
docs/docs/getting-started/first-steps-local.md
docs/docs/getting-started/first-steps.md
docs/docs/reference/migration.md
docs/docs/workflows/config.md
docs/docs/workflows/troubleshooting.md
docs/docs/workflows/upgrade.md
docs/versioned_docs/version-2.6/architecture/attestation.md
docs/versioned_docs/version-2.6/architecture/versions.md
docs/versioned_docs/version-2.7/architecture/attestation.md
docs/versioned_docs/version-2.7/architecture/versions.md
docs/versioned_docs/version-2.7/getting-started/first-steps-local.md
docs/versioned_docs/version-2.7/getting-started/first-steps.md
docs/versioned_docs/version-2.7/workflows/troubleshooting.md
docs/versioned_docs/version-2.8/architecture/attestation.md
docs/versioned_docs/version-2.8/architecture/versions.md
docs/versioned_docs/version-2.8/getting-started/first-steps-local.md
docs/versioned_docs/version-2.8/getting-started/first-steps.md
docs/versioned_docs/version-2.8/reference/migration.md
docs/versioned_docs/version-2.8/workflows/config.md
docs/versioned_docs/version-2.8/workflows/troubleshooting.md
docs/versioned_docs/version-2.8/workflows/upgrade.md

docs: misc fixes

---

.github/actions/build_cli/action.yml
.github/workflows/release-cli.yml

The next Constellation release has experimental support for running the CLI on Windows natively.
Upload `constellation-windows-amd64.exe` as GitHub release artifact.
- ci: add constellation-windows-amd64.exe to release artifacts uploaded to GitHub
- https://github.com/edgelesssys/constellation/releases/tag/untagged-db7e8f9899670531f180
- [ci test run](https://github.com/edgelesssys/constellation/actions/runs/5488443598)
- experimental Windows variant of the Constellation cli

ci: add constellation-windows-amd64.exe to release artifacts uploaded to GitHub

---

bazel/toolchains/go_module_deps.bzl
go.mod
go.sum
hack/go.mod
hack/go.sum

- bump `github.com/hashicorp/go-secure-stdlib/awsutil` since the scanner finds GO-2022-0646

deps: bump go-secure-stdlib/awsutil

---

rfc/canonical-endpoint-dns.md

This is a required change to enable true multi-zone support for AWS. It also has other benefits discussed in the RFC.
As for any RFC, feel free to comment on any aspect including:
- soundness of the general idea
- edge cases that are not reflected
- improvements
- clarifications
If you feel like this RFC can be implemented in the way it is phrased, approve it.
I'll leave it open for a few days.
- rfc: canonical endpoint / custom dns

rfc: canonical endpoint / custom dns

---

.github/workflows/azure-snp-reporter.yml
.github/workflows/build-os-image-scheduled.yml
.github/workflows/build-os-image.yml
.github/workflows/codeql.yml
.github/workflows/release.yml
.github/workflows/test-integration.yml
.github/workflows/test-operator-codegen.yml
3rdparty/gcp-guest-agent/Dockerfile
WORKSPACE.bazel

deps: update to Go v1.20.6

---

internal/osimage/azure/azureupload.go

Azure CVMs are available in Southeast Asia so Constellation should OS images should be as well.
- ci: replicate Azure images to Southeast Asia

ci: replicate Azure images to Southeast Asia

---

cli/internal/cmd/upgradeapply.go

I forgot to remove this unused variable when making changes on the upgrade code in #2107 
- Remove the unused variable

cli: remove unused `file.Handler`

---

docs/docs/getting-started/install.md
docs/versioned_docs/version-2.2/getting-started/install.md
docs/versioned_docs/version-2.3/getting-started/install.md
docs/versioned_docs/version-2.4/getting-started/install.md
docs/versioned_docs/version-2.5/getting-started/install.md
docs/versioned_docs/version-2.6/getting-started/install.md
docs/versioned_docs/version-2.7/getting-started/install.md
docs/versioned_docs/version-2.8/getting-started/install.md
docs/versioned_docs/version-2.9/getting-started/install.md

I stumbled upon a missing permission to delete my IAM role.
- add missing permission to documentation
- permission was already added to dev profile and fixed the error

doc: add iam:DeletePolicyVersion

---

cli/internal/helm/client.go

Currently the csi and aws-lb charts are installed unconditionally.
-

cli: only install aws-lb and csi charts conditionally

---

cli/internal/helm/client.go

cli: fix add csi chart only conditionally

---

.github/workflows/build-bazel-container.yml
bazel/container/container.sh

- The v perfix was missing in the workflow, and the -0 suffix was to much in the script. :man_shrugging:

bazel: fix container versioning

---

.github/actions/versionsapi/Dockerfile
.github/workflows/azure-snp-reporter.yml
.github/workflows/build-os-image-scheduled.yml
.github/workflows/build-os-image.yml
.github/workflows/codeql.yml
.github/workflows/release.yml
.github/workflows/test-integration.yml
.github/workflows/test-operator-codegen.yml
3rdparty/gcp-guest-agent/Dockerfile
WORKSPACE.bazel

deps: bump go version

---

cli/internal/cmd/init.go
cli/internal/cmd/init_test.go
cli/internal/cmd/miniup.go

`constellation mini up` uses functions from different CLI commands, which requires updating the code for `mini up` whenever changes are made to these functions.
Since a change in the relevant functions does not immediately result in invalid code, these errors can be hard to detect.
- Fix missing parameters for the `init` part of `constellation mini up`
- Make invalid configurations more transparent by using a constructor for `*cmd.initCmd`
- Remove redundant pointer from `file.Handler` in `cli/cmd/init.go:initCmd`
- Remove redundant passing of `file.Handler` in `cli/cmd/init.go`

cli: fix missing init parameters in mini up

---

cli/internal/cmd/BUILD.bazel
cli/internal/cmd/configmigrate.go
internal/config/migration/BUILD.bazel
internal/config/migration/migration.go

This is a follow up for #2152. Automatically migrate config v3 to config v4.
- cli: update config migration to migrate v3 -> v4

cli: update config migration to migrate v3 -> v4

---

internal/config/validation.go

- Also allow non CVM types when nitro-tpm attestation is used in the config.

config: fix aws instance type validation

---

.github/actions/e2e_test/action.yml
.github/actions/e2e_verify/action.yml
internal/attestation/vtpm/attestation.go

- Currently, we are only verifying a random pod/node over the loadbalancer. Other nodes could have other measurements, so extending the test to verify all nodes.

ci: verify all pods in verify e2e 

---

docs/docs/reference/migration.md
docs/docs/workflows/config.md

As part of the migration to node groups ([AB#3100](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3100)), we need to document the changes for the end user that were introduced by #2152.
- docs: document node groups and migration from old config fields

docs: document node groups and migration from old config fields

---

.github/actions/constellation_create/action.yml
.github/actions/e2e_test/action.yml

Removing false as default value for better readability. Setting some things to required that are required.

e2e: cleanup test inputs

---

.github/workflows/e2e-test-daily.yml

e2e: use Kubernetes 1.26 in daily test

---

cli/internal/cmd/tfmigrationclient.go

During IAM migration, or Terraform upgrades, the proposed changes are printed followed by a message: "The <Upgrade-Kind> upgrade requires a migration by applying an updated Terraform template. Please manually review the suggested changes below."
- Remove the "below" from the Terraform hint

cli: don't refer to a message below, as it was printed above

---

.github/workflows/e2e-test-daily.yml

Test mini-constellation daily to detect breakages quicker.
- [AB#3330](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3330)

ci: add e2e-mini to daily test

---

cli/internal/kubernetes/upgrade.go

A little bug got introduced during review.
-

cli: fix configmap backup during upgrade

---

image/Makefile
image/README.md
image/mkosi.conf.d/mkosi.aws.conf
image/mkosi.conf.d/mkosi.azure.conf
image/mkosi.conf.d/mkosi.conf
image/mkosi.conf.d/mkosi.gcp.conf
image/mkosi.conf.d/mkosi.openstack.conf
image/mkosi.conf.d/mkosi.qemu.conf

Currently, we use different kernels on different clouds:
- Amazonlinux 2023 Kernel on AWS
- Held back 6.1 Fedora Kernel on Azure
- Stable Fedora Kernel everywhere else (6.4.10 at the time of writing)
With this PR, we build our own Kernel from upstream (kernel.org) and use the same Kernel everywhere.
We will track the latest [longterm release](https://www.kernel.org/) (currently tracking 6.1, currently at 6.1.45).
The srpm will live under https://github.com/edgelesssys/constellation-kernel and any modifications will be made there, in public.
I'm also working on build automation around new kernel releases and will follow up with a runbook for engineers to adopt a new version.
- image: use longterm release of the Linux kernel
You can use this image for testing: …

image: use longterm release of the Linux kernel

---

.aspect/workflows/config.yaml
.github/actionlint.yaml
.github/workflows/.aspect-workflows-reusable.yaml
.github/workflows/aspect-workflows-warming.yaml
.github/workflows/aspect-workflows.yaml

In an effort to improve velocity, we test aspect workflows.
This PR adds GitHub Actions workflows to trigger workflow runs on main. This should be a good starting point for evaluation.
- ci: add aspect workflows

ci: add aspect workflows

---

.aspect/workflows/config.yaml

The current settings are not good in terms of allowing good caching and building all targets.
- ensure stamping is disabled for better caching
- build everything (not only test targets)

ci: fine tune aspect workflows settings

---

bazel/container/container.sh

This fixes the output paths of builds within the container by mounting directories to paths that exist on the host. We also explicitly set the output path in a .bazelrc to the user specific path. The rc file is mounted into the container and overrides the host rc. Also adding automatic stop in case start is called and a containers is already running.
Sym links like bazel-out and paths bazel outputs should generally work with this change.

bazel: fix output paths of container

---

.github/actions/setup_bazel/action.yml

I tried to set `remote-header` to an empty string. This doesn't work.
- bazel: correctly set buildbuddy api key
- [Workflow that would fail before this PR](https://github.com/edgelesssys/constellation/actions/runs/5923230411)

bazel: correctly set buildbuddy api key

---

.github/workflows/e2e-test-weekly.yml
.github/workflows/e2e-windows.yml

Windows e2e test was broken due to a renaming of the artifacts. Furthermore it was running on a separate schedule compared to the weekly e2e test, which is not very intuitive. 
- Use the correct artifact name.
- Call the workflow from `e2e-test-weekly`.
- Add a Teams notification if the workflow fails.

ci: fix Windows e2e test

---

docs/docs/workflows/upgrade.md

Upgrade backup files previously were undocumented, possibly leaving a user confused on what to do with these files.
- Document that backup files are created, and briefly state what they can be used for. (I'm unsure about the wording here; It's unlikely that an upgrade destroys CRs, but not impossible. How should we best state this in the docs?)

docs: document upgrade backup files

---

.github/workflows/e2e-test-release.yml
dev-docs/workflows/release.md

ci: upgrade test from v2.10.1

---

docs/docs/workflows/sbom.md
docs/docs/workflows/verify-cli.md
docs/versioned_docs/version-2.0/workflows/verify-cli.md
docs/versioned_docs/version-2.1/workflows/verify-cli.md
docs/versioned_docs/version-2.10/workflows/sbom.md
docs/versioned_docs/version-2.10/workflows/verify-cli.md
docs/versioned_docs/version-2.2/workflows/sbom.md
docs/versioned_docs/version-2.2/workflows/verify-cli.md
docs/versioned_docs/version-2.3/workflows/sbom.md
docs/versioned_docs/version-2.3/workflows/verify-cli.md
docs/versioned_docs/version-2.4/workflows/sbom.md
docs/versioned_docs/version-2.4/workflows/verify-cli.md
docs/versioned_docs/version-2.5/workflows/sbom.md
docs/versioned_docs/version-2.5/workflows/verify-cli.md
docs/versioned_docs/version-2.6/workflows/sbom.md
docs/versioned_docs/version-2.6/workflows/verify-cli.md
docs/versioned_docs/version-2.7/workflows/sbom.md
docs/versioned_docs/version-2.7/workflows/verify-cli.md
docs/versioned_docs/version-2.8/workflows/sbom.md
docs/versioned_docs/version-2.8/workflows/verify-cli.md
docs/versioned_docs/version-2.9/workflows/sbom.md
docs/versioned_docs/version-2.9/workflows/verify-cli.md

Sigstore reverted the changes to their doc website again, so we also need to revert our links.
Revert commit ec1bba7a8b37e82bc0a1c930a1b41840ac4b9e17.

Revert "docs: fix sigstore doc links (#2272)"

---

cli/internal/cmd/init.go
docs/docs/workflows/create.md

-
- [AB#3320](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3320)

docs: document constellation-cluster.log file

---

.github/actions/constellation_iam_create/action.yml

`constellation iam create` in the CI previously ran without the `tf-log` flag, hence no debug output of the command was collected. This should help us in debugging [AB#3213](https://dev.azure.com/Edgeless/Edgeless/_workitems/edit/3213).
- Run the command with Terraform logging enabled on the `DEBUG` level.
- [e2e run](https://github.com/edgelesssys/constellation/actions/runs/5996478000)

ci: collect Terraform logs on `iam create`

---

.github/workflows/test-unittest.yml
CODEOWNERS
bazel/ci/BUILD.bazel
bazel/ci/gocoverage_diff.sh.in
bazel/ci/golangci_lint.sh.in
hack/gocoverage/BUILD.bazel
hack/gocoverage/main.go
hack/gocoverage/main_test.go

ci: comment Go coverage report on PR

---

image/Makefile
image/mkosi.conf.d/mkosi.conf

Update Linux to latest longterm release.
Based on https://github.com/edgelesssys/constellation-kernel/commit/4815b502da004294a5b33379f1c972fd6164266b
- image: update to Linux 6.1.46
- [build pipeline](https://github.com/edgelesssys/constellation/actions/runs/5924996684)
- [rerun with reverted fTPM patch](https://github.com/edgelesssys/constellation/actions/runs/6039426844)
- image for testing: `ref/feat-image-linux-6-1-46/stream/debug/v2.11.0-pre.0.20230821101850-89a51835b019`

image: update to Linux 6.1.46

---

docs/docusaurus.config.js
docs/package.json

Mermaid graphics rendering is flaky with the current mdx-mermaid implementation.
Graphics sometimes overlap.
- Switch to Docusaurus' native mermaid integration that has been available for a while now.

docs: switch to native mermaid support

---

3rdparty/bazel/org_openssl/BUILD.bazel
cli/internal/cloudcmd/create.go
cli/internal/cloudcmd/create_test.go
cli/internal/cmd/create.go
cli/internal/cmd/create_test.go
cli/internal/cmd/upgradeapply_test.go
cli/internal/kubecmd/backup.go
cli/internal/terraform/terraform/aws/modules/instance_group/main.tf
cli/internal/terraform/variables.go
dev-docs/miniconstellation/setup-miniconstellation.sh
internal/api/attestationconfigapi/fetcher.go
internal/config/config.go
internal/config/config_doc.go
internal/config/migration/migration.go

remove deprecated `constellation create` flags

---

docs/docs/workflows/troubleshooting.md
docs/docs/workflows/upgrade.md

The Constellation CLI saves helm charts on upgrade to disk
- Add note about the existence of the helm charts, and how they can be used to manually apply helm upgrades
- [AB#3413](https://dev.azure.com/Edgeless/Edgeless/_workitems/edit/3413)

docs: add troubleshooting notes for manually managing helm charts

---

.github/actions/deploy_logcollection/action.yml

- Bumping to the latest version of the install action as the old one tried to install essentially helm v2.
Now actually tested: https://github.com/edgelesssys/constellation/actions/runs/6184742123

ci: bump install helm action

---

cli/internal/state/state.go

- Omit some empty fields in `constellation-state.yaml`
It's expected that at least one or even both fields are empty. Therefore we should not print those to file.

cli: omitempty infrastructure fields

---

.github/pull_request_template.md

Mentioning Azure DevOps tickets in GitHub PRs links the ticket to the PR in Azure DevOps. This helps at backlog refinements and general mapping of tickets to PRs.
- Add a link to an AB ticket in the GitHub pull request template.

github: add AB ticket link to PR template

---

.github/pull_request_template.md

Link to AB ticket is not necessary as the GitHub bot automatically adds it. Thanks @elchead and sorry for my misunderstanding.
- Remove the unnecessary link.

github: remove unnecessary link

---

docs/docs/getting-started/install.md

- Align with https://github.com/edgelesssys/edgeless-iam/pull/30. #2152 
Necessary since https://github.com/edgelesssys/constellation/pull/2348

docs: document gcp permissions needed for upgrade

---

docs/docs/getting-started/first-steps.md
docs/versioned_docs/version-2.11/getting-started/first-steps.md

What do you think of this kind of note? Is it at the right place?

docs: add note about current AWS CVM issues

---

docs/docs/getting-started/examples/filestash-s3proxy.md
docs/versioned_docs/version-2.12/getting-started/examples/filestash-s3proxy.md
s3proxy/deploy/README.md
s3proxy/deploy/deployment-s3proxy.yaml

This is a leftover from development, right?

s3proxy: remove unnecessary pull secret

---

.github/actions/setup_bazel_nix/action.yml
.github/workflows/build-ccm-gcp.yml
.github/workflows/build-os-image-scheduled.yml
.github/workflows/codeql.yml
.github/workflows/release.yml
.github/workflows/test-integration.yml
.github/workflows/test-operator-codegen.yml
3rdparty/gcp-guest-agent/Dockerfile
WORKSPACE.bazel
bazel/go/go.nix
go.work

- Bump Go to 1.21.3
- Build Go from source via nix

Deps: bump Go to 1.21.3

---

.github/workflows/codeql.yml

The python linter checks always fail. We have almost no python code to begin with, so this should not be problem.
We also never saw any valid issues found by CodeQL.
- ci: remove python from codeql

ci: remove python from codeql

---

.github/workflows/test-tidy.yml
.github/workflows/test-unittest.yml

Ensure we have better cache hit rates.
- ci: execute unit tests and tidy check against merge of PR branch and main

ci: execute unit tests and tidy check against merge of PR branch and main

---

.github/workflows/update-rpms.yml

In #2461 i used the label `dependency`. The correct label is `dependencies`.
- ci: fix PR label for rpm updates

ci: fix PR label for rpm updates

---

image/base/mkosi.conf
image/initrd/mkosi.conf
image/system/mkosi.conf

mkosi now warns about what settings are defined in what sections. Soon, the config parsing might fail when settings are in the wrong sections.
- image: move mkosi settings into their actual sections

image: move mkosi settings into their actual sections

---

cli/internal/terraform/terraform/openstack/outputs.tf
cli/internal/terraform/terraform/qemu/outputs.tf

- Align the output of all CSPs to fix the parsing on the CLIs side.
E2E Minicon: https://github.com/edgelesssys/constellation/actions/runs/6563030346

align tf output vars with CLI parsing

---

README.md
docs/docusaurus.config.js

We changed the blog address, so we should updated it for our docs and README as well
- Update `blog.edgeless.systems/` to `edgeless.systems/blog`

docs: update link to our blog

---

.github/actions/e2e_test/action.yml
.github/actions/pick_assignee/action.yml
.github/actions/pick_azure_region/action.yml

The goal is to improve the resiliency of the Azure TCB version selection through probing various regions.
We might want to change the frequency of the verify test to daily instead of weekly, but I think we could keep as is for now and adjust when needed. 
- randomly select an Azure region
- [AB#3448](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3448)

ci: pick Azure region randomly

---

.github/workflows/e2e-windows.yml
WORKSPACE.bazel

The workflow was missing to install nix.
- install nix before building the CLI
- E2E passed https://github.com/edgelesssys/constellation/actions/runs/6610080677

ci: fix win build

---

cli/internal/cmd/init.go

cli: init should not call terraform

---

cli/internal/kubecmd/kubecmd.go

We have seen [occasional failures on AWS e2e tests](https://github.com/edgelesssys/constellation/actions/runs/6648935381/job/18066702705#step:3:5248) where the JoinConfig was not retrieved because of network issues.
https://github.com/edgelesssys/constellation/pull/2500 addressed some of these problems by increasing the retry limit.
However, this only applied to creating a new attestation config.
Just fetching it once was not retried.
- Retry fetching of JoinConfig in `kubecmd.GetClusterAttestationConfig`, similar to how it is done in `kubecmd.ApplyJoinConfig`.
- [AWS e2e test](https://github.com/edgelesssys/constellation/actions/runs/6650953170/job/18072016725)
- [See the retry in action](https://github.com/edgelesssys/constellation/actions/runs/6650953170/job/18072016725#step:6:5244)

cli: retry fetching of JoinConfig during init process

---

operators/constellation-node-operator/controllers/pendingnode_controller.go

The node operator creates a pending node resource for new nodes joining the cluster.
If that node for some reason gets terminated, the controller never cleans up the pending node resource.
Additionally, the operator may be unable to delete the pending node after a timeout period as the node is already deleted (terminated).
- Delete pending node resource if the backed instance was terminated
This does not fix the issue of new nodes joining the cluster, but not being paired with any existing outdated nodes.
Fixing this would require a more thorough rewrite of the operator logic.
But this PR fixes the deadlock during an image upgrade should a replacement node terminate before joining the cluster.

operator: always delete terminated pending nodes

---

.github/workflows/e2e-test-internal-lb.yml
.github/workflows/e2e-test-manual-internal.yml
.github/workflows/e2e-test-manual.yml
.github/workflows/e2e-test-self-managed.yml
.github/workflows/e2e-test.yml

We have multiple workflows sharing the code of the e2e-manual workflow. For example, we have a e2e-manual-internal workflow as an e2e test with an internal LB, which copies all the code in the main e2e-manual workflow but changes one input parameter. We don't get around having separate workflows, as GitHub only lets us have 10 parameters for a workflow to specify on the command line, but we should not copy the code.
- Call the main `e2e-test` (prev. `e2e-test-manual`) worfklow from the specialized workflows (i.e. self-managed infra, internal LB)
- [AB#3506](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3506)
- In a future PR, daily / weekly / release e2e test should be changed accordingly, but they require more changes due to the image version …

ci: share e2e workflow

---

docs/docs/getting-started/install.md
docs/docs/workflows/create.md
docs/versioned_docs/version-2.10/getting-started/install.md
docs/versioned_docs/version-2.10/workflows/create.md
docs/versioned_docs/version-2.11/getting-started/install.md
docs/versioned_docs/version-2.11/workflows/create.md
docs/versioned_docs/version-2.12/getting-started/install.md
docs/versioned_docs/version-2.12/workflows/create.md
docs/versioned_docs/version-2.5/workflows/create.md
docs/versioned_docs/version-2.6/workflows/create.md
docs/versioned_docs/version-2.7/workflows/create.md
docs/versioned_docs/version-2.8/workflows/create.md
docs/versioned_docs/version-2.9/workflows/create.md

#2503 broke the links to the TF files.
-

docs: fix Terraform file links

---

.github/actions/self_managed_create/action.yml
terraform/infrastructure/iam/gcp/README.md

The path to the Terraform configuration files got updated with the Terraform module being introduced.
- Fix the path.
- [E2E Test](https://github.com/edgelesssys/constellation/actions/runs/6826722234)

ci: fix path in self managed create test

---

bazel/toolchains/linux_kernel.bzl

Patch update of the Linux kernel.
- [Build pipeline run](https://github.com/edgelesssys/constellation/actions/runs/6850420103)
- Update Linux from 6.1.55 to 6.1.62
- Changelogs
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.56
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.57
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.58
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.59
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.60
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.61
- https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.62
Please also review [the kernel spec PR](https://github.com/edgelesssys/constellation-kernel/pull/6).

deps: update linux kernel to 6.1.62

---

.github/workflows/e2e-test.yml

#2566 missed checking out the branch before selecting the image, [causing the action not to be found](https://github.com/edgelesssys/constellation/actions/runs/6861152122).
- Check out the branch before selecting the image.
- [E2E Test](https://github.com/edgelesssys/constellation/actions/runs/6861379171)

ci: checkout before selecting image

---

bazel/release/BUILD.bazel
bazel/toolchains/oci_deps.bzl
e2e/malicious-join/BUILD.bazel

We pinned an older version due to missing features. The feature to stamp the repository name was reintroduced.
- deps: update rules_oci to 1.4.2

deps: update rules_oci to 1.4.2

---

.github/actions/constellation_create/action.yml

- remove a dash character
[e2e run](https://github.com/edgelesssys/constellation/actions/runs/6930240341)

ci: remove dash from create action

---

rfc/XXX-trusted-kubernetes-images.md

Discuss how to pin k8s control plane images.
- [AB#3565](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3565)

rfc: trusted k8s images

---

rfc/015-trusted-kubernetes-images.md

I forgot to enter a real RFC number before merging #2648 .

rfc: fix path of trusted images RFC

---

bazel/toolchains/linux_kernel.bzl

Changelogs:
https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.63 https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.64
If you review this, please also take a look at https://github.com/edgelesssys/constellation-kernel/pull/7
- image: update Linux to 6.1.64
- [e2e test](https://github.com/edgelesssys/constellation/actions/runs/7085068828)

image: update Linux to 6.1.64

---

.github/actions/versionsapi/Dockerfile
.github/workflows/build-ccm-gcp.yml
.github/workflows/build-os-image-scheduled.yml
.github/workflows/codeql.yml
.github/workflows/release.yml
.github/workflows/test-integration.yml
.github/workflows/test-operator-codegen.yml
3rdparty/gcp-guest-agent/Dockerfile
bazel/go/go.nix
go.work
terraform-provider-constellation/go.mod

Go 1.21.4 has vulnerabilities, so we need to upgrade.
- deps: bump Go to 1.21.5

deps: bump Go to 1.21.5

---

operators/constellation-node-operator/controllers/pendingnode_controller_env_test.go

The test for `PendingNode` objects includes a step to accelerate reconciliation by modifying the spec. Since the step we want to accelerate is deletion of the object, there's a race between the operator deleting the node and the test runner modifying the spec. The operator rarely wins the race, but it happened at least once. 
- Allow the acceleration step to fail with a `NotFound` error.
- Fixes edgelesssys/issues#141
- Fixes edgelesssys/issues#3

operators: fix flaky env test

---

dev-docs/workflows/release.md

The recent Terraform provider release makes a new manual step necessary to publish the provider.
-

docs: update release process

---

.github/actions/setup_bazel_nix/action.yml

- ci: update bash on darwin to support newer bash features

ci: update bash on darwin to support newer bash features

---

.bazelrc
cli/internal/cmd/apply.go
cli/internal/cmd/apply_test.go
cli/internal/cmd/init_test.go
cli/internal/cmd/license_enterprise.go
internal/constellation/apply.go
internal/constellation/apply_test.go
internal/license/BUILD.bazel
internal/license/checker_enterprise.go
internal/license/checker_enterprise_test.go
internal/license/checker_oss.go
internal/license/integration/BUILD.bazel
internal/license/integration/license_integration_test.go
internal/license/license.go
terraform-provider-constellation/docs/resources/cluster.md
terraform-provider-constellation/internal/provider/BUILD.bazel
terraform-provider-constellation/internal/provider/cluster_resource.go

The Terraform provider implementation currently does not run any license checks.
Additionally, we are lacking a way to differentiate between upgrades or first initializations.
Also, the license checker code needed a little clean up in general.
- Clean up license checker code
- Report a different action to the license checker depending on state of the cluster
- We log the action `init` if the cluster has not yet been set up, or `apply` if the init step is skipped
- Run license check in Terraform provider
- We differentiate between CLI and Terraform checks by appending `-terraform` to the action
- If no license is found, a warning is printed by Terraform informing the user, the community license will be used. This happens on `terraform plan` and `terraform apply`
- If the community license …

constellation-lib: run license check in Terraform provider and refactor code

---

.bazelignore

- bazel: add directories to ignore

bazel: add directories to ignore

---

bazel/mkosi/mkosi_image.bzl
bazel/toolchains/linux_kernel.bzl
cli/internal/cmd/configinstancetypes.go
flake.lock
flake.nix
image/base/BUILD.bazel
image/system/BUILD.bazel
image/system/variants.bzl
internal/attestation/measurements/overrides.go
internal/attestation/variant/variant.go
internal/config/config_test.go
internal/config/instancetypes/azure.go
internal/config/validation.go
internal/osimage/uplosi/uplosiupload.go

For Azure TDX support, we need OS images with a mainline kernel.
- image: add mainline kernel and azure tdx image target
- config: allow Azure TDX instance types

image: Azure TDX variant

---

terraform-provider-constellation/internal/provider/cluster_resource.go
terraform-provider-constellation/internal/provider/cluster_resource_test.go

In the E2E tests for the Terraform provider, we currently set the pod IP CIDR, even if the CSP isn't GCP. This causes problems in the validation, that requires the field to be unset.
- Validate the `ip_cidr_pod` field only if a GCP cluster is being created.
- Fixes https://github.com/edgelesssys/issues/issues/217
- [E2E test GCP](https://github.com/edgelesssys/constellation/actions/runs/7613735976)
- [E2E test Azure](https://github.com/edgelesssys/constellation/actions/runs/7613734445)

ci: fix pod ip cidr setting when not on GCP

---

bazel/toolchains/linux_kernel.bzl

Update LTS kernel to latest version.
As a reviewer, please also look at https://github.com/edgelesssys/constellation-kernel/pull/9.
Use `ref/deps-kernel-6-1-74/stream/debug/v2.15.0-pre.0.20240124145614-701e21f98b3b` for testing.
- image: update Linux to 6.1.74
- [6.1.69](https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.69)
- [6.1.70](https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.70)
- [6.1.71](https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.71)
- [6.1.72](https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.72)
- [6.1.73](https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.73)
- [6.1.74](https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.74)

image: update Linux to 6.1.74

---

.github/actions/notify_e2e_failure/action.yml

#2839 intended to fix the link, but single quotes around the query value were still missing as found today by @burgerdev in https://github.com/edgelesssys/issues/issues/296.
-
You can manually test the fix by copying the link from the above linked run and add quotes

ci: fix Opensearch link

---

docs/docs/getting-started/first-steps.md
docs/docs/workflows/config.md
flake.lock
flake.nix

- Add support for region Germany West Central (Frankfurt)

Add Azure region Germany West Central

---

flake.lock
flake.nix
internal/osimage/uplosi/uplosiupload.go

TDX and SNP have different regional availability on Azure.
- image: configurable replication for Azure

image: configurable replication for Azure

---

.github/workflows/e2e-test-provider-example.yml
.github/workflows/e2e-test-weekly.yml

Solves https://github.com/edgelesssys/issues/issues/325. 
- Set the corresponding fields in the test caller.

ci: set board fields for tf example test

---

.github/actions/self_managed_create/action.yml

The test is broken because the required change done here https://github.com/edgelesssys/constellation/commit/e350ca0f5708acc74295492dbfe13ecdf87ec8b9#diff-95f4946997931d93bde2bc26f629bfd2361e2164c89a22b488f6fb3aa5f420d7R160-R161 was not done for the test.
-

ci: fix self managed e2e for Azure TDX

---

terraform-provider-constellation/internal/provider/attestation_data_source_test.go

In #2881, I accidentally oversaw missing quotes, which broke the test.
- Add quotes.

terraform-provider: fix integration test

---

internal/constellation/helm/BUILD.bazel
internal/constellation/helm/loader_test.go
internal/constellation/helm/overrides.go

Fixes 26305e8f80c0f875334338d74671a589eb0f9076. During a refactor, we forgot to write all of the necessary helm values for stackit.
- helm: insert openstack secret for ccm

helm: insert openstack secret for ccm

---

cli/internal/cloudcmd/apply_test.go
cli/internal/cloudcmd/tfvars.go
image/system/variants.bzl

Enable use of OpenStack by end users.
- openstack: prepare for normal users

openstack: prepare for normal users

---

bazel/toolchains/linux_kernel.bzl

- LTS: 6.1.79 ([changelog](https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.79))
- stable: 6.7.6 ([changelog](https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.7.6))
- deps: update Linux LTS and stable kernel
Please also review the [kernel rpm PR](https://github.com/edgelesssys/constellation-kernel/pull/10).
Image for testing: `ref/deps-kerne-update-lts-and-mainline/stream/debug/v2.16.0-pre.0.20240226114338-3231b74a8811`

deps: update Linux LTS and stable kernel

---

.github/actions/build_cli/action.yml
.github/workflows/draft-release.yml
rfc/003-secure-software-distribution.md

We triggered this issue in the CI: https://github.com/edgelesssys/constellation/actions/runs/8082333313/job/22084762376
- release: use cosign sign-blob in non-interative mode

release: use cosign sign-blob in non-interative mode

---

docs/docs/workflows/config.md
docs/versioned_docs/version-2.16/workflows/config.md

The STACKIT flavors have been updated.
- docs: update STACKIT flavors

docs: update STACKIT flavors

---

cli/internal/cmd/apply.go
cli/internal/cmd/configgenerate.go
cli/internal/cmd/configgenerate_test.go
cli/internal/cmd/configinstancetypes.go
cli/internal/cmd/license_enterprise.go
cli/internal/cmd/license_oss.go
internal/config/config.go
internal/config/instancetypes/BUILD.bazel
internal/config/instancetypes/stackit.go
internal/imagefetcher/imagefetcher.go
internal/license/license.go
terraform-provider-constellation/docs/data-sources/attestation.md
terraform-provider-constellation/docs/data-sources/image.md
terraform-provider-constellation/docs/resources/cluster.md
terraform-provider-constellation/internal/provider/cluster_resource.go
terraform-provider-constellation/internal/provider/cluster_resource_test.go
terraform-provider-constellation/internal/provider/shared_attributes.go

Improvements for STACKIT. Small changes are collected here.
- cli: add STACKIT to constellation config instance-types
- misc: skip message about community license with marketplace image
- cli: correct measurements in `config generate stackit`

misc: various STACKIT related improvements

---

bootstrapper/internal/joinclient/joinclient.go
bootstrapper/internal/joinclient/joinclient_test.go

Failure to join after receiving a successful `IssueJoinTicketResponse`  is permanent. Until we have proper handling of such a situation, we want to still be able to recover from transient errors. 
- Retry the k8s join 2 times (i.e. run at most 3 times total).
- Papers over edgelesssys/issues#421
* [e2e Azure](https://github.com/edgelesssys/constellation/actions/runs/8152448073)

bootstrapper: bounded retry of k8s join

---

docs/docs/getting-started/install.md
docs/docs/workflows/verify-cli.md
docs/versioned_docs/version-2.16/getting-started/install.md
docs/versioned_docs/version-2.16/workflows/verify-cli.md

While the Windows CLI was already part of the release artifacts for some time, it was still missing from the documentation. We are adding it here.
As a reviewer with a Windows machine, please check if those steps actually work. I have no way of testing this.
- docs: add installation instructions for the Windows CLI variant

docs: add installation instructions for the Windows CLI variant

---

docs/docs/architecture/attestation.md
docs/docs/getting-started/install.md
docs/docs/overview/clouds.md
docs/docs/workflows/config.md
docs/docs/workflows/recovery.md
docs/styles/config/vocabularies/edgeless/accept.txt
docs/versioned_docs/version-2.16/architecture/attestation.md
docs/versioned_docs/version-2.16/getting-started/install.md
docs/versioned_docs/version-2.16/overview/clouds.md
docs/versioned_docs/version-2.16/workflows/config.md
docs/versioned_docs/version-2.16/workflows/recovery.md
internal/cloud/openstack/imds.go
internal/cloud/openstack/imds_test.go
terraform/infrastructure/openstack/modules/instance_group/main.tf

Some more polishing for STACKIT.
- move credentials to instance user data
- add all STACKIT availability zones
- explain recovery on STACKIT

stackit: docs and userdata

---

docs/versioned_docs/version-2.16/architecture/attestation.md

Forgot to add the table also to the versioned docs for v2.16.

docs: add runtime measurement table for Constellation v2.16

---

README.md
docs/docs/architecture/attestation.md
docs/docs/getting-started/first-steps.md
docs/docs/getting-started/install.md
docs/docs/workflows/config.md
docs/docs/workflows/recovery.md
docs/docs/workflows/scale.md
docs/docs/workflows/storage.md
docs/docs/workflows/terraform-provider.md
docs/versioned_docs/version-2.16/architecture/attestation.md
docs/versioned_docs/version-2.16/getting-started/first-steps.md
docs/versioned_docs/version-2.16/getting-started/install.md
docs/versioned_docs/version-2.16/workflows/config.md
docs/versioned_docs/version-2.16/workflows/recovery.md
docs/versioned_docs/version-2.16/workflows/scale.md
docs/versioned_docs/version-2.16/workflows/storage.md
docs/versioned_docs/version-2.16/workflows/terraform-provider.md

Order CSPs alphabetically and replace discord link with gh discussions.

docs: order csp strictly alphabetically

---

docs/src/css/custom.css

Change docs to new corporate font Inter
- Change docs font to Inter

docs: change to inter font

---

terraform-provider-constellation/BUILD.bazel

- Add missing build tag
- [AB#3982](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3982)

provider: Add build tag for Terraform provider

---

terraform/infrastructure/openstack/.terraform.lock.hcl
terraform/infrastructure/openstack/main.tf
terraform/infrastructure/openstack/modules/stackit_loadbalancer/main.tf

We received a hint saying that newer versions work more reliably.
- terraform: update terraform provider STACKIT

terraform: update terraform provider STACKIT

---

rfc/006-reproducible-builds.md

The file in the Distroless repository doesn't exist anymore, and I don't think it's crucial for the RFC, so it can be removed, still keeping the link to the Distroless repo.
- Remove the broken link from the RFC.

rfc: remove broken Distroless link

---

.github/workflows/draft-release.yml

slsa generator broke because rekor keys got updated.
A new version of the action fixes the problem.
- update slsa generator to v1.10.0

ci: fix slsa generator action by updating to new version

---

.github/workflows/draft-release.yml

old slsa-verifier is not compatible with current rekor public key format
- bump slsa-verifier to v2.5.1

ci: bump slsa-verifier to v2.5.1

---

.github/workflows/e2e-windows.yml

- Suppress license check for windows e2e 
- [e2e test](https://github.com/edgelesssys/constellation/actions/runs/8628061467/job/23649797873#step:8:21)

ci: suppress license check on windows e2e

---

dev-docs/workflows/security-patch.md

- Document how security advisories for Constellation should be handled.
- [AB#4035](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/4035)

dev-docs: document security advisory process

---

terraform/infrastructure/aws/main.tf
terraform/infrastructure/azure/main.tf
terraform/infrastructure/gcp/main.tf

Thought something was broken with the additional tag logic, but turned out I was just looking at the wrong instances on Azure.
Ended up going over the tagging logic nonetheless and should be more robust in applying them to all resources now
- Instead of merging additional tags at the resource with the predefined "constant" local tags, merge additional tags directly into the local tags.
- This makes it a lot harder to forget adding the additional tags to new resources added to the terraform files
- Adds the local tags to a couple resources that were missing them (They only had the additional tags previosuly)

terraform: simplify additional tagging logic to ensure they are always applied

---

.github/actions/artifact_delete/delete_artifact.sh
.github/actions/artifact_upload/action.yml
.github/actions/e2e_cleanup_timeframe/action.yml
.github/actions/e2e_cleanup_timeframe/e2e-cleanup.sh
.github/actions/update_tfstate/action.yml
.github/workflows/e2e-cleanup-weekly.yml
.github/workflows/e2e-test-daily.yml
.github/workflows/e2e-test-release.yml
.github/workflows/e2e-test-weekly.yml
.github/workflows/e2e-test.yml
.github/workflows/e2e-upgrade.yml
.github/workflows/e2e-windows.yml

E2E terraform resources aren't always cleaned up automatically and have to be deleted manually sometimes.
- Add a CI workflow that deletes leftover terraform resources of all e2e runs from the last week.
- This workflow runs at 00:00 of every Sunday of every week (UTC)
- At the moment this does not handle `e2e-mini.yml`.
A successful run of the action can be viewed [here](https://github.com/edgelesssys/constellation/actions/runs/8538526720/job/23391360817). (Please note that this run uses the fixed workflow run ID of 8452536438 since the e2e actions needed to be adjusted). The referenced workflow run cleans up a manual e2e test.
Further tests:
[weekly](https://github.com/edgelesssys/constellation/actions/runs/8831062968/job/24245477225) (only references run 8750778451) …

ci: Delete e2e terraform state

---

terraform/infrastructure/openstack/.terraform.lock.hcl
terraform/infrastructure/openstack/main.tf
terraform/infrastructure/openstack/modules/stackit_loadbalancer/main.tf

The STACKIT terraform provider has a new release.
- deps: upgrade terraform provider stackit to 0.16.0

deps: upgrade terraform provider stackit to 0.16.0

---

.github/actions/e2e_cleanup_timeframe/action.yml
.github/actions/e2e_test/action.yml
.github/actions/login_azure/action.yml
.github/actions/notify_e2e_failure/action.yml
.github/actions/update_tfstate/action.yml
.github/workflows/e2e-test-provider-example.yml
.github/workflows/e2e-test-weekly.yml

- Replace usage of `Ablestor/encode-uri-component-action` to URL encode the test payload with simple `jq` expression
- This action seems to be unmaintained, and throws a warning because there is a sample `action.yml` in the project root which has a different syntax than the actual action
- The action also performs a very basic task which can be handled by a single line of code
- This also removes a warning about outdated node versions
- Upgrade azure/login to `v2.1` to remove warnings about outdated node versions
- Replace two outdated `aws-actions/configure-aws-credentials` to `v4.0.2`
- This is the version we use everywhere else
- This removes a warning about outdated node versions
- Remove a warning when running an e2e test with nop payload
- Since this is the default for a lot of our …

ci: reduce noise from warnings

---

.github/actions/constellation_create/action.yml
.github/actions/update_tfstate/action.yml
.github/actions/upload_terraform_module/action.yml
.github/workflows/e2e-upgrade.yml

The conditional was inversed, trying to delete the state if nothing existed
- Fix the conditional
- Don't fail if `rm` tries to delete non existent files
- Fixes https://github.com/edgelesssys/issues/issues/575

ci: fix delete artifact conditional

---

.github/actions/artifact_download/action.yml
.github/actions/artifact_upload/action.yml
.github/actions/e2e_cleanup_timeframe/action.yml
.github/actions/e2e_cleanup_timeframe/e2e-cleanup.sh
.github/actions/update_tfstate/action.yml

- Use 7zip for creating archives
- Amends https://github.com/edgelesssys/issues/issues/575

ci: use 7zip for creating archives

---

.bazelrc
.github/actions/e2e_attestationconfigapi/action.yml
.github/actions/e2e_mini/action.yml
.github/actions/e2e_s3proxy/action.yml
.github/actions/e2e_test/action.yml
.github/actions/setup_bazel_nix/action.yml
.github/workflows/build-binaries.yml
.github/workflows/build-libvirt-container.yml
.github/workflows/e2e-attestationconfigapi.yml
.github/workflows/e2e-mini.yml
.github/workflows/e2e-test-daily.yml
.github/workflows/e2e-test-provider-example.yml
.github/workflows/e2e-test-release.yml
.github/workflows/e2e-test-weekly.yml
.github/workflows/e2e-test.yml
.github/workflows/e2e-upgrade.yml
.github/workflows/e2e-windows.yml
.github/workflows/on-release.yml
.github/workflows/reproducible-builds.yml
.github/workflows/test-integration.yml
.github/workflows/test-tidy.yml
.github/workflows/test-unittest.yml
.github/workflows/update-rpms.yml
dev-docs/workflows/bazel.md

We are trying out build performance without BuildBuddy. Should be simple enough to revert this if needed.
- ci: disable BuildBuddy

ci: disable BuildBuddy

---

bazel/toolchains/linux_kernel.bzl

New kernel releases are available.
Please also review https://github.com/edgelesssys/constellation-kernel/pull/11.
- deps: update LTS kernel 6.1.79 -> 6.1.90
- deps: update LTS kernel 6.7.6 -> 6.8.9
- [image build](https://github.com/edgelesssys/constellation/actions/runs/9033443738)

deps: update LTS and mainline kernels

---

terraform/infrastructure/openstack/.terraform.lock.hcl
terraform/infrastructure/openstack/main.tf
terraform/infrastructure/openstack/modules/stackit_loadbalancer/main.tf

- Update stackit terraform provider
* @malt3 
* @malt3

deps: bump stackit terraform provider to 0.17.0

---

bazel/toolchains/go_module_deps.bzl
go.mod
go.sum

The additional method we added to go-tpm has been merged upstream.
- remove replacement of go-tpm with fork
https://github.com/edgelesssys/constellation/actions/runs/9075572147

deps: remove replacement of go-tpm with fork

---

internal/constellation/applyinit.go

- cli: simplify log message on init call

cli: simplify log message on init call

---

.github/workflows/build-ccm-gcp.yml
.github/workflows/build-os-image-scheduled.yml
.github/workflows/codeql.yml
.github/workflows/release.yml
.github/workflows/test-operator-codegen.yml
MODULE.bazel
MODULE.bazel.lock
dev-docs/workflows/bump-go-version.md

New Go version which fixes some vulnerabilities (that don't affect us) 
- Bump Go version to v1.22.4

deps: bump Go version to v1.22.4

---

.github/workflows/build-os-image-scheduled.yml
.github/workflows/update-rpms.yml

Commits in scheduled PRs where committed by edgelessci, but authored by the person who created the workflow.
- Use edgelessci to author commits in scheduled PRs

ci: author scheduled PRs using edgelessci account

---

internal/constellation/helm/charts/edgeless/csi/Chart.yaml
internal/constellation/helm/charts/edgeless/csi/charts/azuredisk-csi-driver/Chart.yaml
internal/constellation/helm/charts/edgeless/csi/charts/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
internal/constellation/helm/charts/edgeless/csi/charts/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
internal/constellation/helm/charts/edgeless/csi/charts/azuredisk-csi-driver/values.yaml
internal/constellation/helm/charts/edgeless/csi/charts/gcp-compute-persistent-disk-csi-driver/Chart.yaml
internal/constellation/helm/charts/edgeless/csi/charts/gcp-compute-persistent-disk-csi-driver/values.yaml
internal/constellation/helm/charts/edgeless/csi/charts/snapshot-controller/Chart.yaml
internal/constellation/helm/charts/edgeless/csi/charts/snapshot-controller/templates/admission-configuration.yaml
internal/constellation/helm/charts/edgeless/csi/charts/snapshot-controller/templates/serving-cert.yaml
internal/constellation/helm/charts/edgeless/csi/charts/snapshot-controller/templates/snapshot-controller.yaml
internal/constellation/helm/charts/edgeless/csi/charts/snapshot-controller/templates/snapshot-webhook.yaml
internal/constellation/helm/charts/edgeless/csi/charts/snapshot-controller/values.yaml
internal/constellation/helm/charts/edgeless/csi/charts/snapshot-crds/Chart.yaml
internal/constellation/helm/charts/edgeless/csi/charts/snapshot-crds/templates/volumesnapshotclasses.yaml
internal/constellation/helm/charts/edgeless/csi/charts/snapshot-crds/templates/volumesnapshotcontents.yaml
internal/constellation/helm/charts/edgeless/csi/charts/snapshot-crds/templates/volumesnapshots.yaml
internal/constellation/helm/update-csi-charts.sh

- Update Azure CSI chart to v1.4.0: upstream v1.30.1
- Update GCP CSI chart to v1.4.0: upstream v1.14.0
- Update CSI snapshotter to v8.0.1

helm: update Azure CSI, GCP CSI, and CSI snapshotter charts

---

go.mod

- Remove obsolete replace statements for k8s dependencies
- [e2e test](https://github.com/edgelesssys/constellation/actions/runs/9612187711)
- [e2e upgrade](https://github.com/edgelesssys/constellation/actions/runs/9612193388)

deps: update k8s replace directive

---

docs/docs/workflows/troubleshooting.md
docs/versioned_docs/version-2.16/workflows/troubleshooting.md

Add  the credential ordering problem for policy patching to the troubleshooting guide
- Update troubleshooting
- Backport to 2.16

docs: add policy troubleshooting tip

---

.github/workflows/release.yml

We previously tried to commit measurements in the release CI even if no changes were present: https://github.com/edgelesssys/constellation/actions/runs/9746960273/job/26899959187
- Only try to commit the measurements if changes are present.

ci: only commit measurements if changes are present

---

terraform/infrastructure/openstack/.terraform.lock.hcl
terraform/infrastructure/openstack/main.tf
terraform/infrastructure/openstack/modules/stackit_loadbalancer/main.tf

StackIT releases their Terraform provider quite frequently, so we should try to keep up to date.
- Update StackIT Terraform provider.

terraform: update StackIT provider to v0.23.0

---

bootstrapper/cmd/bootstrapper/BUILD.bazel
bootstrapper/cmd/bootstrapper/run.go
bootstrapper/internal/etcdio/BUILD.bazel
bootstrapper/internal/etcdio/etcdio.go
bootstrapper/internal/etcdio/setioprio_cross.go
bootstrapper/internal/etcdio/setioprio_linux.go
bootstrapper/internal/reboot/BUILD.bazel
bootstrapper/internal/reboot/reboot_cross.go
bootstrapper/internal/reboot/reboot_linux.go

The Go linter has several issues because of non-existent SYSCALL flags and options on Mac. The easy solution is to simply stub that functionality, since we don't support builds for these components on non-linux systems.
-

ci: fix IDE setup on mac

---

terraform-provider-constellation/internal/provider/attestation_data_source_test.go

The attestation version numbers were hard-coded in the test but they are dynamically updated.
- soften version value assertion to be non-zero where applicable
- [AB#4381](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/4381)

ci: fix TF attestation version assertion in integration test

---

internal/osimage/uplosi/uplosiupload.go

In preparation for GPU support, we need to add a new region for SEV-SNP on Azure.
- image: replicate Azure images in eastus2

image: replicate Azure images in eastus2

---

.github/workflows/on-release.yml

Starting with v2.18.0, SEV-SNP will be the default for Constellation on GCP. Thus, we also want to offer our marketplace images on GCP for that.
- Upload SEV-SNP marketplace images on GCP, rather than SEV-ES. This means that all marketplace images on GCP >=2.18 will only support SEV-SNP and cannot be used for SEV-ES anymore.
- [AB#4424](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/4424)

ci: mirror GCP SEV-SNP marketplace images

---

docs/docs/workflows/recovery.md
docs/versioned_docs/version-2.17/workflows/recovery.md

Flag has been deprecated. The command gives an error if used this way.
- Remove flag from current and latest released docs

docs: remove deprecated master-secret flag from recovery

---

terraform-provider-constellation/docs/data-sources/attestation.md
terraform-provider-constellation/examples/full/azure/main.tf
terraform-provider-constellation/internal/provider/attestation_data_source.go

The [Terraform provider documentation](https://registry.terraform.io/providers/edgelesssys/constellation) did not mention that the MAA needs to be manually patched previously - only the [Constellation usage documentation](https://docs.edgeless.systems/constellation/workflows/terraform-provider#quick-setup) on the Terraform provider did. However, customers will most likely only look at the former.
- Link the Constellation documentation on how to patch the MAA in the Terraform provider documentation.

terraform-provider: document MAA patching more prominently

---

terraform-provider-constellation/examples/full/azure/main.tf

https://github.com/edgelesssys/constellation/pull/3330 didnt run `bazel run //:tidy`
- Tidy terraform files

terraform: tidy files

---

terraform-provider-constellation/examples/full/gcp/main.tf

https://github.com/edgelesssys/constellation/pull/3267 didn't set the correct `cc_technology` for GCP SEV-SNP.
- Set the correct `cc_technology`

terraform-provider-constellation: set correct cc_technology in GCP example

---

README.md

- Remove references to deprecated live demos.

readme: remove demo references

---

e2e/internal/upgrade/upgrade.go

We use a Go program to run our e2e upgrade tests.
The program calls other CLI tools that print to stdout and stderr. For the test, we want to capture both and print them in a way easily identifiable in the GH actions output.
https://github.com/edgelesssys/constellation/blob/46fcbb5ee8568a77fa63c64302006ef301a225e8/e2e/internal/upgrade/upgrade.go#L185-L206
While the function waits for the Command printing to sdout/stderr to finish execution, we don't wait for the Go routines collecting the output. This leads to a race condition when returning the collected output.
- Use a `sync.WaitGroup` to synchronize collection and returning of command output
- Fixes https://github.com/edgelesssys/issues/issues/1019

e2e-upgrade: guard function return values behind `sync.WaitGroup`

---

terraform/infrastructure/openstack/.terraform.lock.hcl
terraform/infrastructure/openstack/main.tf
terraform/infrastructure/openstack/modules/stackit_loadbalancer/main.tf

We were lacking quite a bit behind on updates for the [STACKIT Terraform provider](https://registry.terraform.io/providers/stackitcloud/stackit/latest), presumably due to [deps: update Terraform dependencies](https://github.com/edgelesssys/constellation/issues/245) being held up for quite some time.
- Update [terraform-provider-stackit](https://registry.terraform.io/providers/stackitcloud/stackit/latest) from `0.23.0` to `0.33.2`.
- Tests would be appreciated!

deps: update terraform-provider-stackit

---

docs/versioned_docs/version-2.19/reference/migration.md

In #3454, I missed adding the migration instructions to the v2.19 docs.
- add migrate instructions to v2.19 docs

docs: add migrate instructions to v2.19

---

docs/docs/getting-started/install.md
docs/versioned_docs/version-2.19/getting-started/install.md

* When setting up STACKIT deployments, users ran into errors because they've used the OpenStack Project ID instead of the STACKIT project ID
- Add warning in the documentation to us the right ID
- Add information about the right path for the `clouds.yaml` file on macOS.

docs: stackit improve clouds.yaml description

---

docs/docs/overview/clouds.md
docs/styles/config/vocabularies/edgeless/accept.txt
docs/versioned_docs/version-2.0/overview/clouds.md
docs/versioned_docs/version-2.1/overview/clouds.md
docs/versioned_docs/version-2.10/overview/clouds.md
docs/versioned_docs/version-2.11/overview/clouds.md
docs/versioned_docs/version-2.12/overview/clouds.md
docs/versioned_docs/version-2.13/overview/clouds.md
docs/versioned_docs/version-2.14/overview/clouds.md
docs/versioned_docs/version-2.15/overview/clouds.md
docs/versioned_docs/version-2.16/overview/clouds.md
docs/versioned_docs/version-2.17/overview/clouds.md
docs/versioned_docs/version-2.18/overview/clouds.md
docs/versioned_docs/version-2.19/overview/clouds.md
docs/versioned_docs/version-2.2/overview/clouds.md
docs/versioned_docs/version-2.3/overview/clouds.md
docs/versioned_docs/version-2.4/overview/clouds.md
docs/versioned_docs/version-2.5/overview/clouds.md
docs/versioned_docs/version-2.6/overview/clouds.md
docs/versioned_docs/version-2.7/overview/clouds.md
docs/versioned_docs/version-2.8/overview/clouds.md
docs/versioned_docs/version-2.9/overview/clouds.md

The link to the custom firmware preview on Azure expired, since the project is dead for a while
- I've update the part in the docs with the new roadmap for OpenHCL

docs: update azure firmware with openhcl

---

.github/actions/login_gcp/action.yml

We moved the workload pool to a different project
- Update the GCP workload identity provider URL

ci: update workload identity provider url

---

docs/docusaurus.config.js
docs/package-lock.json
docs/package.json
docs/static/gtagman.js

change gtag integration as requested by marketing department

docs: refactor gtag

---

.github/workflows/e2e-test-release.yml
.github/workflows/e2e-test-weekly.yml

New release
- Start upgrade e2e tests from v2.19.3 instead of v2.19.0
- https://github.com/edgelesssys/constellation/issues/3488

ci: update workflows to initialize upgrade tests with v2.19.3

---

dev-docs/howto/longhorn.md

Our [link checker CI is broken](https://github.com/edgelesssys/constellation/actions/runs/12769892318/job/35593468986?pr=3568) since we are referencing an old longhorn install requirements link in our docs.
- Update the docs to reference an up-to-date version (1.7.2) of longhorn instead of 1.5.3

fix(docs): reference up to date longhorn guide

---

go.mod
go.sum

Upstpream PR was merged
- Drop our forked version of google/go-sev-guest

dependencies: drop google/go-sev-guest fork

---

renovate.json5

Kubernetes replace directives updates should be grouped with other Golang dependency updates
- Group Go replace directive updates with other updates 
- Replace deprecated config options with their new counterparts
- Reformat the `renovate.json5` config file to proper json5 syntax
- Also see https://github.com/edgelesssys/constellation/pull/3533

renovate: reformat config file for json5

---

dev-docs/workflows/attestationconfigapi.md

The instructions on how to use the attestationconfigapi were outdated and didn't work with the current implementation of the CLI.
- Align the instructions to work with the current CLI.

dev-docs: fix attestationconfigapi instructions

---

dev-docs/workflows/marketplace-publishing.md
dev-docs/workflows/release.md

Publishing the marketplace images should be part of the regular Constellation release flow, and a guide on how to do it should be available for every developer.
- Add a guide on how to publish our marketplace images.
- Replace the outdated STACKIT notice in the release flow with an instruction to upload the marketplace images. The STACKIT folks watch our GitHub releases and take the image information from there since some time.

dev-docs: add guide on publishing marketplace images

---

flake.lock
flake.nix
nix/lib/by-name/constellationRepoRoot/package.nix
nix/lib/by-name/constellationRepoRootSrc/package.nix
nix/lib/by-name/constellationVersion/package.nix
nix/lib/default.nix
nix/packages/by-name/buildConstellationGoModule/package.nix
nix/packages/by-name/constellation-canonical-go-package/package.nix
nix/packages/default.nix

We want to incrementally transition Constellation's build system to Nix. To align with our other projects, we install the same (or very similar, at least) Nix build infrastructure in here in this PR. This does not yet intend to move any existing packages over, which will happen in subsequent PRs.
- Create `nix/{packages,lib}/by-name` trees, which can be used to add new packages or library functions relevant to Constellation.
- [AB#5463](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/5463)

nix: bootstrap "v2" tree

---

cli/internal/cmd/apply.go
cli/internal/cmd/recover.go
cli/internal/cmd/verify.go
internal/grpc/dialer/dialer.go
terraform-provider-constellation/internal/provider/cluster_resource.go

This adds support for using the CLI behind an http proxy.
This is "best effort" for now and won't be documented.
- use default grpc dialer
- Tested manually. Won't add an e2e test for now.

cli: support http proxy

---

bazel/toolchains/linux_kernel.bzl

It's time for a kernel update! The respective changes are in the `kernel-packaging-tools` and `constellation-kernel` repositories.
- Update the LTS kernel from `6.6.30` to `6.6.87`.
- [AB#5526](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/5526)
- [Nightly image builds](https://github.com/edgelesssys/constellation/actions/runs/14488524242)
- [Debug image builds](https://github.com/edgelesssys/constellation/actions/runs/14489701735)
- [Console image builds](https://github.com/edgelesssys/constellation/actions/runs/14489704809)
- E2E tests:
- [AWS](https://github.com/edgelesssys/constellation/actions/runs/14492229624)
- [Azure](https://github.com/edgelesssys/constellation/actions/runs/14492221820)
- …

bazel: update kernel to 6.6.87

---

.github/workflows/check-measurements-reproducibility.yml
.github/workflows/release.yml

A missing checkout step caused a [failing job in the release](https://github.com/edgelesssys/constellation/actions/runs/14748470340/job/41402365147). 
- Check out the given ref in the reproducibility check action.
- Check out the ref so that calling the action succeeds.

ci: add missing checkout step

---

CODEOWNERS

- Re-distribute files owned by derpsteb to other members of the team

codeowners: remove derpsteb

---

cli/internal/cloudcmd/iamupgrade.go
docs/docs/getting-started/install.md
docs/docs/reference/migration.md
docs/versioned_docs/version-2.23/getting-started/install.md
docs/versioned_docs/version-2.23/reference/migration.md

https://github.com/edgelesssys/constellation/pull/3770 requires an additional IAM permission on GCP. This PR documents this.
- add missing permission in getting started guide
- mention need for IAM migration
- update UpgradeRequiresIAMMigration function

docs: GCP iam migration

---

.github/actions/build_cli/action.yml
.github/actions/constellation_iam_create/action.yml
.github/actions/container_sbom/action.yml
.github/actions/e2e_test/action.yml
.github/actions/notify_teams/teams_payload_template.json
.github/actions/pick_assignee/action.yml
.github/workflows/e2e-test-release.yml
CODEOWNERS
bootstrapper/internal/kubernetes/k8sapi/k8sutil.go
cli/internal/cloudcmd/tfvars.go
cli/internal/terraform/variables.go
dev-docs/miniconstellation/setup-miniconstellation.sh
internal/cloud/azure/azure.go
internal/config/config_test.go
internal/config/migration/migration.go
internal/constellation/helm/overrides.go
s3proxy/cmd/main.go
terraform/infrastructure/aws/modules/instance_group/main.tf
terraform/infrastructure/azure/main.tf

- Remove elchead from codeowners as he doesn't work on the project anymore
- Remove TODOs from a bunch of codeowners that don't work on the project anymore
- Remove a few TODOs that don't apply anymore

Remove old codeowners

---

internal/constellation/helm/BUILD.bazel
internal/constellation/helm/charts/cilium/Chart.yaml
internal/constellation/helm/charts/cilium/README.md
internal/constellation/helm/charts/cilium/files/cilium-envoy/configmap/bootstrap-config.yaml
internal/constellation/helm/charts/cilium/templates/cilium-envoy/configmap.yaml
internal/constellation/helm/charts/cilium/templates/cilium-envoy/daemonset.yaml
internal/constellation/helm/charts/cilium/templates/hubble-ui/_nginx.tpl
internal/constellation/helm/charts/cilium/templates/hubble/tls-certmanager/relay-client-secret.yaml
internal/constellation/helm/charts/cilium/templates/hubble/tls-certmanager/relay-server-secret.yaml
internal/constellation/helm/charts/cilium/templates/hubble/tls-certmanager/server-secret.yaml
internal/constellation/helm/charts/cilium/templates/hubble/tls-certmanager/ui-client-certs.yaml
internal/constellation/helm/charts/cilium/values.yaml
internal/constellation/helm/charts/cilium/values.yaml.tmpl
internal/constellation/helm/generateCilium.sh
internal/constellation/helm/helm_test.go
internal/constellation/helm/loader.go

Cilium has released quite a number of fixes for v1.15, including security patches. Getting to the latest patch release on v1.15 is also a requirement to upgrade to v1.16, eventually.
- Bump the Cilium version to v1.15.19 on our fork.
- [AB#5955](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/5955)
- The dependency imported right now is https://github.com/edgelesssys/cilium/tree/v1.15.19-edg.

helm: bump Cilium version to v1.15.19-edg.0
