edgelesssys/constellation

.github/actions/build_cli/action.yml, .github/actions/constellation_measure/action.yml
In our v2.0.0 CLI release, all binaries except the Linux amd64 are tagged with `GitTreeState: dirty` when executing `constellation version`. Presumably, this seems to be the case due to Rekor being downloaded to the constellation root directory, which is not excluded from our git and thus taints the state. Therefore, let's specify it explicitly that we want to download to the build directory and also clean up the binary after we copied it.
It's a bit hard to test before we push another release, but testing it by running the action in act and copying the binaries out of the container seems to work and gives a clean state to the other binaries with this PR.
=> Fix dirty build tag for CLI releases != linux/amd64

cli/internal/cmd/configfetchmeasurements.go, docs/docs/workflows/trusted-launch.md, docs/versioned_docs/version-2.0/workflows/trusted-launch.md, hack/importAzure.sh
TrustedLaunchAndConfidentialVmSupported fails on my machine (latest az cli):
```
(InvalidParameter) The value 'TrustedLaunchAndConfidentialVmSupported' for feature 'SecurityType' is invalid. Allowed characters are English alphanumerical characters with spaces and commas. The length of the value cannot exceed 100 characters.
Code: InvalidParameter
Message: The value 'TrustedLaunchAndConfidentialVmSupported' for feature 'SecurityType' is invalid. Allowed characters are English alphanumerical characters with spaces and commas. The length of the value cannot exceed 100 characters.
Target: galleryImage.properties.features
```
Instead I made it configurable via env var.
=> docs: fix command in trusted launch workflow and add fetch-measurements

hack/qemu-metadata-api/main.go, hack/qemu-metadata-api/server/server.go, hack/qemu-metadata-api/server/server_test.go, terraform/libvirt/README.md, terraform/libvirt/main.tf, terraform/libvirt/variables.tf
Retrieving image measurements is done by a separate tool. We no longer need to start a QEMU cluster to do so.
This PR removes the need to mount a log directory for the metadata container when using terraform to create a QEMU based cluster, since the metadata api no longer writes anything to disk.
=> Remove exporting of PCRs from QEMU metadata API

cli/internal/cloudcmd/create.go, cli/internal/gcp/client/instances.go
- Enable GCP's serial console for VMs if the cluster was created with debug mode enabled
=> Enable GCP serial console for debug mode

.github/workflows/build-binaries.yml
- Speed up workflow run times by building macOS binaries in separate jobs
- Reduces build time from 10-12 minutes to ~7 minutes
- Fix cdbg being built for the wrong OS Arch
=> Run macos builds as separate jobs

.github/docs/release.md, hack/pseudo-version/internal/git/git.go
- Fix annotated tag detection (pseudo version script would use the hash of the annotation object instead of the tag target for annotated tags)
- Support for pre versions:
> vX.Y.Z-pre.0.yyyymmddhhmmss-abcdefabcdef is used when the base version is a pre-release version like vX.Y.Z-pre.
https://go.dev/ref/mod#pseudo-versions
The latest commit on this branch (at the time of writing) has the pseudo version `v2.1.0-pre.0.20220921123253-8e8ffe74ac46`.
=> pseudo-version: Fix annotated tag detection and support pre-versions

cli/internal/azure/loadbalancer.go, cli/internal/cmd/recover.go, cli/internal/cmd/recover_test.go, docs/docs/workflows/recovery.md, internal/grpc/retry/retry.go, internal/grpc/retry/retry_test.go
- Update the `constellation recover` command to be fully automatic
- Endpoint is read from file if not explicitly set using the `--endpoint`/`-e` flag
- Recover call is repeated until the recovery loadbalancer no longer has any "healthy" backends
- The actual changeset is rather small: We simply wrap the recover call in a for loop that terminates after a non-retriable error is encountered
- Azure's LB healthprobe frequency was increased to 5 seconds (the maximum)
- This is needed because otherwise the LB is slow to realise a node was successfully recovered
- This is no problem on GCP since the default probe frequency is 1 second
- A "service unavailable" error is retried once, this is to avoid aborting the recovery in case the LB routes our request to a node we just recovered
- For GCP we …
=> AB#2262 Automatic recovery

internal/license/checker_enterprise.go
Removed some sentences to make it less confusing and have the license file in the docs as central source of truth.
=> Make wording around license less verbose

internal/config/config_test.go
- The tests were supposed validate config, but were never updated to actually call `Validate()` function. Since we have a dedicated unit test `TestValidate`, I suggest we simply delete this test. I don't see any added value by keeping / fixing it.
=> delete unused config test

docs/docs/workflows/create.md, docs/docs/workflows/recovery.md, docs/docs/workflows/scale.md, docs/docs/workflows/ssh.md, docs/docs/workflows/storage.md, docs/docs/workflows/upgrade.md, docs/docs/workflows/verify-cli.md, docs/docs/workflows/verify-cluster.md, docs/versioned_docs/version-2.0/getting-started/first-steps.md, docs/versioned_docs/version-2.0/workflows/create.md, docs/versioned_docs/version-2.0/workflows/recovery.md, docs/versioned_docs/version-2.0/workflows/scale.md, docs/versioned_docs/version-2.0/workflows/ssh.md, docs/versioned_docs/version-2.0/workflows/storage.md, docs/versioned_docs/version-2.0/workflows/upgrade.md, docs/versioned_docs/version-2.0/workflows/verify-cli.md, docs/versioned_docs/version-2.0/workflows/verify-cluster.md
A few fixes and some wording simplifications of the workflows.
In the recovery workflow, I tried to adapt the formatting of the instructional paragraphs to recommendations from the MS style guide.
Other changes should be self-explanatory.
=> docs: fixes and rewording of workflows

cli/internal/cmd/create.go, cli/internal/cmd/init.go, cli/internal/cmd/spinner.go, cli/internal/cmd/spinner_test.go, cli/internal/cmd/terminate.go
This is my solution to #189 
- created `Spinner` class with basic functionality to reuse it later if needed
- integrated my spinner with `init` command as was proposed in the issue
- covered my spinner with several dummy tests
=> [CLI] Activity indicator for init command

CHANGELOG.md, bootstrapper/internal/kubernetes/k8sapi/kubeadm_config.go, bootstrapper/internal/kubernetes/k8sapi/resources/konnectivity.go, cli/internal/terraform/terraform/gcp/modules/loadbalancer/main.tf
- Route KubeAPI -> kubelet/pod/svc traffic over konnectivity
Note that with these settings it is possible (and likely) that the traffic will do another hop from the worker node kkonnecitivity routed the traffic to. 
As stability test I ran our e2e sonobuoy test on Azure and GCP with 3 control-plane / 3 worker nodes.
=> enable konnectivity

.github/workflows/e2e-test-azure-weekly.yml, .github/workflows/e2e-test-azure.yml, .github/workflows/e2e-test-gcp-weekly.yml, .github/workflows/e2e-test-gcp.yml, .github/workflows/e2e-test-manual-macos.yml, .github/workflows/e2e-test-manual.yml
- Before the e2e test didn't catch the konnectivity problems, increasing control control plane count to avoid regression as soon as the feature is re-implemented as well as test HA kubernetes
There are some cloud costs attached to this PR, mainly due to the "e2e Test Azure" and "e2e Test GCP" which run the whole sonobuoy suite every night (during the work week) on our default K8s version. For better cost control/overview, we could put the e2e test in their own project (at least on gcp).
=> increase control plane count during e2e tests

CMakeLists.txt, Dockerfile.build, bootstrapper/cmd/bootstrapper/run.go, joinservice/Dockerfile, kms/Dockerfile, verify/Dockerfile
- Fix version injection for CLI in cmake file, which was broken by upgrading to v2 Go module
=> Fix CLI version injection in cmake

.github/actions/constellation_create/action.yml, .github/actions/e2e_test/action.yml, .github/actions/pseudo_version/action.yml, .github/workflows/check-licenses.yml, .github/workflows/check-links.yml, .github/workflows/docs-update-reference.yml, .github/workflows/docs-vale.yml, .github/workflows/e2e-test-azure-weekly.yml, .github/workflows/e2e-test-azure.yml, .github/workflows/e2e-test-manual-macos.yml, .github/workflows/e2e-test-manual.yml, .github/workflows/generate-measurements.yml, .github/workflows/test-govulncheck.yml, .github/workflows/test-lint.yml, .github/workflows/test-shellcheck.yml, .github/workflows/test-tidy.yml, .github/workflows/update-cli-reference.yml
- GitHub deprecated `set-output` syntax for workflows/actions yesterday, see [this announcement](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/).
- Add dispatch trigger to every workflow. Sometimes workflows aren't triggered because the targeted files aren't changed.
--
Documenting the find/sed command I used here in case I need it again.
```sh
find .github -type f -name "*.yml" -exec sed -i 's/::set-output name=\([^::]*\)::\([^"]*\)/\1=\2 >> $GITHUB_OUTPUT/' {} +
```
=> Replace deprecated set-output syntax

CHANGELOG.md, go.mod, internal/cloud/aws/autoscaler.go, internal/cloud/aws/ccm.go, internal/cloud/aws/cloudnodemanager.go, internal/cloud/aws/logger.go, internal/cloud/aws/metadata.go, internal/cloud/aws/metadata_test.go, internal/role/role.go
- Add first support for AWS by implementing `metadata.Self()` and `metadata.List()`
- The parsed information *should* be compatible with the Terraform template in `terraform/aws/`, i.e. instance-roles / uids are read from instance tags, instead of parsed from the instance's name
=> AB#2474 Implement List and Self method for AWS

bootstrapper/internal/kubernetes/k8sapi/util.go
- Double CRD timeout to prevent timeouts during `mini up`.
- There is currently no way for users to overwrite this setting if necessary. A better fix would be to allow users to overwrite this value if necessary. Do we want to implement this?
=> AB#2480: Increased CRD timeout

.github/workflows/docs-vale.yml
- Downgrade vale action
- Slipped in by https://github.com/edgelesssys/constellation/pull/237
- @thomasten: 
> Seems we updated the Vale action to a new major version. In addition to treating Warnings as Errors (which may be configured somehow with the new version), it also includes a vale version that produces some FPs. So I'd suggest to downgrade the action to the previous major version.
=> Downgrade vale action

.github/workflows/build-ccm-gcp.yml, internal/versions/versions.go
- Add container image for CCM GCP v25.2.0
- Upgrade versions of kubernetes base components
=> AB#2365 Upgrade k8s base deployments (add full support for k8s 1.25)

go.mod, go.sum, internal/cloud/aws/logger.go, internal/cloud/aws/logger_test.go, internal/cloud/aws/metadata.go
- Implements Cloud Logging for AWS instances
- AWS cloud logging requires a Cloudwatch log group to be set up: https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/Working-with-log-groups-and-streams.html
- Creation of the group should be handled by Terraform
- Log group should be tagged with the Constellation UID, naming should not matter
- One log group per Constellation cluster
- Applications write their messages to a log stream, one log group can hold multiple streams
- One log stream per ec2 instance
- Log stream is named after the instance writing messages to it
=> AB#2479 Implement AWS cloud logging

go.mod, go.sum, hack/go.mod, hack/go.sum
The reason for replacing the module was waiting for https://github.com/google/go-attestation/pull/284 to be merged.
- Use upstream go-attestation
=> Use upstream go-attestation

renovate.json
- Currently, renovate doesn't tidy submodules when updating Go dependencies. This change tries to add this functionality, so you don't have to manually update submods.
=> Make renovate tidy all go modules

renovate.json
Reverts edgelesssys/constellation#296
This options is only available for self-hosted runners: https://docs.renovatebot.com/self-hosted-configuration/#allowpostupgradecommandtemplating
Error was: https://github.com/edgelesssys/constellation/pull/297#issuecomment-1281035878
=> Revert "Make renovate tidy all go modules"

cli/internal/terraform/terraform/azure/main.tf, cli/internal/terraform/terraform/azure/modules/load_balancer_backend/main.tf, cli/internal/terraform/terraform/azure/modules/load_balancer_backend/variables.tf
- We used HTTPS health probe before, but it got lost during the transition to Terraform. This change fixes the some of the recent e2e test failures on Azure, where the check for the readiness of nodes would fail because kubectl connected to an unready kubeapi server of one of the control planes that joined the cluster.
--
**Error output** that should be fixed by this test:
[e2e test Azure:](https://github.com/edgelesssys/constellation/actions/runs/3266646192/jobs/5370681136#step:6:9362)
```sh
1/5 nodes have joined.. waiting..
1/5 nodes have joined.. waiting..
1/5 nodes have joined.. waiting..
3/5 nodes have joined.. waiting..
5/5 nodes have joined
Unable to connect to the server: net/http: TLS handshake timeout …
```
=> Use HTTPS for kube lb health check on Azure

renovate.json
- Renovate shouldn't update imports of constellation in hack, as those are replaced anyway.
=> Let renovate ignore constellation module

.github/workflows/test-tfsec.yml
- Let tfsec comment, but not fail CI.
=> Let tfsec fail soft in CI

.github/workflows/generate-measurements.yml, .github/workflows/release-cli.yml
- Configured a second cosign key-pair `COSIGN_DEV_*` as action secret to be used for non-release builds
- Keypair and password was also stored in internal secrets manager
- I tried to use `KEY: ${{ github.ref_protected && 'PROD KEY' || 'DEV KEY' }}`, but `github.ref_protected` [seems to be `false` on protected tags.](https://github.com/datosh/some-action/actions/runs/3281988742/jobs/5404766209) I suspect this is because [protected tags are still in beta](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/configuring-tag-protection-rules). I [checked with GitHub folks](https://github.com/community/community/discussions/10906#discussioncomment-3915816). I don't think we need …
=> AB#2508 Use release cosign key only when releasing

disk-mapper/cmd/main.go
- Add support for AWS to the disk-mapper
The device name of the state disk is expected to be `/dev/sdb`.
Linux may not respect the selected device name and instead choose a difference prefix. E.g. `/dev/sdb` may be available as `/dev/xvdb` or `/dev/hdb`.
On Nitro instances, disks are attached over NVMe, this means disks are named using the `/dev/nvmeXnY` naming scheme.
Naming is not consistent across instance reboots.
However, AWS provides udev rules to fix this problem: https://github.com/amazonlinux/amazon-ec2-utils
When installed, these rules automatically create symlinks for the disks at the path selected as the device name.
This means regardless of where the actual device is, or on what platform we are, when we attach a disk with the device name `/dev/sdb`, and the udev rules are …
=> AB#2510 disk-mapper AWS support

bootstrapper/cmd/bootstrapper/main.go, internal/attestation/vtpm/attestation.go, internal/cloud/aws/metadata.go
- Bootstrapper no longer panics when CSP is set to `aws`
- Implement missing metadata methods (some stubs) for AWS to satisfy required interfaces 
- While this should allow booting a Constellation image with bootstrapper on AWS, `init` calls will not work and likely cause the bootstrapper to panic
- Missing features for full operation:
- TPM based attestation
- Cloud/Metadata functions required to install and run Cilium
=> AB#2511 Implement minimal feature support for bootstrapper on AWS

.gitignore, cli/internal/terraform/loader.go, cli/internal/terraform/terraform/aws/.terraform.lock.hcl, cli/internal/terraform/terraform/aws/main.tf, cli/internal/terraform/terraform/aws/modules/instance_group/main.tf, cli/internal/terraform/terraform/aws/modules/load_balancer_target/main.tf, cli/internal/terraform/terraform/aws/modules/public_private_subnet/main.tf, cli/internal/terraform/terraform/azure/.terraform.lock.hcl, cli/internal/terraform/terraform/gcp/.terraform.lock.hcl, cli/internal/terraform/terraform/qemu/.terraform.lock.hcl, hack/terraform/aws/iam/main.tf
- Pin terraform provider hashes
Manually created using:
```
terraform providers lock -platform=linux_arm64 -platform=linux_amd64 -platform=darwin_arm64 -platform=darwin_amd64 -platform=windows_amd64
```
=> AB#2533 Pin terraform provider hashes

cli/internal/helm/charts/edgeless/constellation-services/charts/join-service/templates/configmap.yaml
- Join-service helm chart: use correct casing for provider name
Node are unable to join on azure because of missing pieces in the join-service configmap:
```
[root@fedora ~]# k -n kube-system logs -f join-service-c87kd
{"level":"INFO","ts":"2022-10-25T09:10:00Z","caller":"cmd/main.go:48","msg":"Constellation Node Join Service","version":"0.0.0","cloudProvider":"Azure"}
{"level":"INFO","ts":"2022-10-25T09:10:00Z","logger":"validator","caller":"watcher/validator.go:96","msg":"Updating expected measurements"}
{"level":"INFO","ts":"2022-10-25T09:10:00Z","logger":"validator","caller":"watcher/validator.go:113","msg":"Updating encforceIdKeyDigest value"}
Usage of /joinservice:
-cloud-provider string
cloud service provider this binary is running on
-kms-endpoint string
endpoint of Constellations …
```
=> Join-service helm chart: use correct casing for provider name

cli/internal/cloudcmd/clients.go, cli/internal/cloudcmd/clients_test.go, cli/internal/cloudcmd/create.go, cli/internal/cloudcmd/create_test.go, cli/internal/cloudcmd/rollback.go, cli/internal/cloudcmd/rollback_test.go, cli/internal/cloudcmd/terminate.go, cli/internal/cloudcmd/terminate_test.go, cli/internal/cmd/cloud.go, cli/internal/cmd/cloud_test.go, cli/internal/cmd/terminate.go, cli/internal/cmd/terminate_test.go, cli/internal/terraform/loader.go, cli/internal/terraform/loader_test.go, cli/internal/terraform/terraform.go, cli/internal/terraform/terraform_test.go
If an error occurred during rollback, terraform files were deleted, resulting in dangling resources that are difficult to clean up.
This adds a check to only clean up the workspace if rollback succeeded without errors
=> AB#2532 Dont clean up workspace if rollback fails

cli/internal/cloudcmd/create.go, cli/internal/cloudcmd/create_test.go, internal/config/config.go
The azurerm provider has it's own convention of enforcing spelling which Azure itself does not enforce or even provide. This is a bit of bad design decision, but we can work around that. While #233 already had basic re-writing, I thought we can get a bit further to fix all edge-cases (at least the ones I see) plus keeping the #249 regex searchable for maintanence. The result is this lunacy of regex.ReplaceAllString :)  
@katexochen Sorry!
- Can supersede #249
=> Case-insensitive replace for every user-input that can go wrong

.github/actions/e2e_test/action.yml, .github/workflows/e2e-test-manual-macos.yml, .github/workflows/e2e-test-manual.yml
- Normalize naming: "sonobuoy fast" -> "sonobuoy quick"
- https://github.com/edgelesssys/constellation/actions/runs/3341785552/jobs/5533328067
- https://github.com/edgelesssys/constellation/actions/runs/3342423393
=> Normalize naming: "sonobuoy fast" -> "sonobuoy quick"

bootstrapper/cmd/bootstrapper/main.go
- Temporarily undefine -v flag as it collided with glogs definition. 
As far as I can see, we never used the flag in our images anyway to setting to the flag's default.
The other solution would be to revert [79f52e67cb0d078c951f7ebcff97e6a91b9253a8 ](https://github.com/edgelesssys/constellation/commit/79f52e67cb0d078c951f7ebcff97e6a91b9253a8). In my opinion this is less preferable since this will block AWS support again. 
As soon as https://github.com/google/go-sev-guest/issues/23 is merged and used downstream, we can re-enable the flag.
=> bootstrapper: undefine -v flag to avoid collision

disk-mapper/cmd/main.go, joinservice/cmd/main.go
- Undefine more -v flags due to glog collision
Need to undefine -v in disk-mapper and join-service as both import atls which depends on go tpm and so on. 
Not sure about if undefining more -v flags is the right way forward, though. Again, the flags should be unused. A user could change the join-service deployment and add the flag, but this is unlikely as they should keep their hands off our deployments anyway. Furthermore, hopefully this is a very temporary fix (tm). 
Also, the AWS support is almost finished. Only testing needed. Reverting https://github.com/edgelesssys/constellation/commit/79f52e67cb0d078c951f7ebcff97e6a91b9253a8 would block AWS, We'll probably need to decide for the next release if we want AWS or not. I guess we could also build a fork of go-tpm-tools which includes the …
=> undefine more -v flags due to glog

cli/internal/terraform/terraform/azure/modules/scale_set/main.tf
- Add needed Azure password constraints
Fixes:
```
An error occurred: exit status 1
Error: creating Linux Virtual Machine Scale Set: (Name "leo-24d2ba9f-worker" / Resource Group "XXX"): compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="The supplied password must be between 6-72 characters long and must satisfy at least 3 of password complexity requirements from the following:\r\n1) Contains an uppercase character\r\n2) Contains a lowercase character\r\n3) Contains a numeric digit\r\n4) Contains a special character\r\n5) Control characters are not allowed" Target="adminPassword"
with module.scale_set_worker.azurerm_linux_virtual_machine_scale_set.scale_set,
on modules/scale_set/main.tf line 18, …
```
=> terraform: fix azure password constraints

.github/actions/constellation_destroy/action.yml, CHANGELOG.md, cli/internal/cmd/configgenerate.go, cli/internal/cmd/create_test.go, cli/internal/cmd/terminate.go, cli/internal/cmd/terminate_test.go, docs/docs/getting-started/first-steps.md, hack/fetch-broken-e2e/find.sh
- Add a prompt to `constellation terminate` before terminating any resources
- Add a `--yes` flag to bypass this for CI and other automation scripts.
You can choose if you'd like the separate parse function (initial commits) or if we just include the check in the terminate function itself (last commit) since it's just one check. The former one is more consistent with the other CLI functions, but we don't need any other flags anyway currently so it's kinda obsolete except for consistency.
I suggested this initially in #360. 
While one could argue that if someone calls `constellation terminate` they would be doing this by intention (similar to `rm`), in my opinion, there's multiple good reasons to prompt the user before terminating:
- We prompt the user on `create` despite `terminate` being …
=> Prompt before terminate

.github/actions/e2e_test/action.yml
K-Bench's network benchmarks require two distinct worker nodes.: https://github.com/edgelesssys/k-bench/blob/feat/constellation/config/dp_network_internode/iperf_client_pod.yaml
Thanks @katexochen for the discovery in #421 
- Add check prior to running the K-Bench action to terminate early if not enough workers are scheduled.
=> fix: don't run CI K-Bench with less than 2 worker nodes

bootstrapper/cmd/bootstrapper/main.go, bootstrapper/internal/kubernetes/k8sapi/k8sutil.go, bootstrapper/internal/kubernetes/k8sapi/kubectl/client/client.go, bootstrapper/internal/kubernetes/k8sapi/kubectl/kubectl.go, bootstrapper/internal/kubernetes/k8sapi/kubectl/kubectl_test.go, bootstrapper/internal/kubernetes/kubeWaiter/waiter.go, bootstrapper/internal/kubernetes/kubeWaiter/waiter_test.go, bootstrapper/internal/kubernetes/kubernetes.go, bootstrapper/internal/kubernetes/kubernetes_test.go
- Add a kubewaiter which can be used to wait between the startup of the kubelet and the first deployment of K8s resources which both happens on the first control-plane node. 
This is mostly needed on AWS because the load balancer health checks are quite slow there. It was common to get a `connection refused` error during the first deployment of K8s resources since the load balancer has no healthy backends.
=> Wait for kube api during init

.github/actions/constellation_create/action.yml, .github/actions/constellation_measure/action.yml, .github/actions/e2e_test/action.yml, .github/actions/generate_measurements/action.yml, .github/workflows/e2e-test-daily.yml, .github/workflows/e2e-test-manual-macos.yml, .github/workflows/e2e-test-manual.yml, .github/workflows/e2e-test-weekly.yml, .github/workflows/generate-measurements.yml, .gitignore, cli/internal/cmd/configfetchmeasurements.go, cli/internal/cmd/upgradeplan.go
- Fix measurements for case-insensitive Azure
- Fix CI pipeline in general (I believe, main is broken so cannot test...)
Since the AzureRM terraform provider enforces certain spelling according to their arbitrary standards, we added image name normalisation to make this process a bit user-friendlier. However, since S3 is case-sensitive, we also need to normalise file names there, too. 
As a stop-gap measure before we completely rework the measurement fetching anyway, this PR does that plus fixes the pipeline which was broken before. 
It might still be broken as my test currently dies at the verification-service. Hope main is fixed soon so I can re-base and build a new image any try again since I don't like merging untested code.
=> Fix measurements for case-insensitive Azure 

docs/docs/architecture/orchestration.md, docs/docs/workflows/create.md, docs/docs/workflows/terminate.md
- `constellation-state.json` does not exists anymore. The infrastructure part is taken over by Terraform and the terraform.tfstate. Some background information was moved to constellation-id.json (such as the load balancer endpoint for initializing the cluster).
=> docs: remove constellation-state.json

.github/actions/constellation_create/action.yml, .github/actions/os_build_variables/action.yml, cli/internal/terraform/terraform/aws/main.tf, image/mkosi.prepare, image/mkosi.skeleton/etc/dracut.conf.d/90-networkd.conf, image/mkosi.skeleton/usr/lib/dracut/modules.d/39constellation-mount/module-setup.sh, image/mkosi.skeleton/usr/lib/dracut/modules.d/39constellation-mount/prepare-state-disk.service, image/mkosi.skeleton/usr/lib/dracut/modules.d/39constellation-mount/sysusers-dracut.conf
- Install systemd-resolved in dracut to enable DNS
- Backport fixes for systemd-resolved for Fedora 36
- Install CA certs in initramfs
- Deploy recovery LB on AWS
- Issues in older dracut:
- https://github.com/dracutdevs/dracut/pull/1658
- https://github.com/systemd/systemd/pull/22045
- Images: https://github.com/edgelesssys/constellation/actions/runs/3414152529
- e2e run Azure: https://github.com/edgelesssys/constellation/actions/runs/3414502629
- e2e run GCP: https://github.com/edgelesssys/constellation/actions/runs/3414478494
The following files will be added to the initrd by this change:
```
/usr/lib/sysusers.d/systemd-resolve.conf
/usr/lib/systemd/systemd-resolved
/usr/lib/systemd/system/systemd-resolved.service
/etc/systemd/system/multi-user.target.wants/systemd-resolved.service
```
=> Install systemd-resolved in dracut to enable DNS

cli/internal/terraform/terraform/aws/main.tf
- Apply the security group to worker nodes on AWS, too
- For a next release we should further harden down the rules for worker nodes on all CSPs. They are only reachable internally and not exposed to the internet, but could pose an issue for lateral movement.
=> AWS: Apply security group to worker nodes

debugd/internal/debugd/constants.go, image/mkosi.conf.d/selinux.conf, image/mkosi.prepare
- Enable SELinux in permissive mode
- Tested manually and verified it does not interfere with Constellation
```
[root@fedora ~]# sestatus 
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   permissive
Mode from config file:          permissive
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     actual (secure)
Max kernel policy version:      33
[root@fedora ~]# cat /proc/cmdline 
rhgb audit=0 constel.csp=qemu mitigations=auto,nosmt preempt=full selinux=1 enforcing=0 console=ttyS0 loglevel=4 roothash=bb0011e4e008ba72e41da36b173f04365600bdbb33cbe3e412fda6de775df297
[root@fedora …
```
=> AB#2546 Set SELinux from disabled to permissive

cli/internal/terraform/terraform/azure/.terraform.lock.hcl, cli/internal/terraform/terraform/gcp/.terraform.lock.hcl, hack/terraform/aws/iam/.terraform.lock.hcl
- linux_arm64
- linux_amd64
- darwin_arm64
- darwin_amd64
- windows_amd64
Created using:
```
terraform providers lock -platform=linux_arm64 -platform=linux_amd64 -platform=darwin_arm64 -platform=darwin_amd64 -platform=windows_amd64
```
=> Update terraform lock files to include hashes for all platforms:

cli/internal/cmd/configfetchmeasurements.go
- Bump timeout for fetch-measurements from 3 seconds to 60 seconds.
This should be plenty for slow connections / long-distance traffic.
- See Discord
=> Increase timeout for fetch-measurements

.github/actions/e2e_kbench/README.md, .github/actions/e2e_kbench/action.yml, .github/actions/e2e_kbench/evaluate/compare.py, .github/actions/e2e_kbench/evaluate/evaluators/default.py, .github/actions/e2e_kbench/evaluate/evaluators/fio.py, .github/actions/e2e_kbench/evaluate/evaluators/network.py, .github/actions/e2e_kbench/evaluate/graph.py, .github/actions/e2e_kbench/evaluate/parse.py
- In K-Bench benchmark runs, compare the current benchmark to the previous performance of Constellation on the same cloud provider.
- Output the performance progression in the GitHub action summary as a markdown table (see example below).
- If running on main, update the stored benchmark in S3 for future comparison.
- Generate performance charts as in the [docs](https://docs.edgeless.systems/constellation/overview/performance) and attach them to the workflow run as artifacts.
- Add documentation for benchmarks. Specifically add walk-through on updating the stored benchmark for cloud-provider managed Kubernetes clusters.
- Separated parsing and generation of graphs from K-bench results.
- Add support to parse non-Constellation benchmark results e.g. AKS / GKE.
- check the exemplary run, …
=> AB#2530 CI benchmark: compare to previous results and generate graphs

.github/workflows/e2e-test-daily.yml
- Currently, if a test job fails in the e2e-daily, other jobs are canceled. With this change, the other test jobs will continue, like it is already the case with the e2e-weekly.
=> e2e: deactivate fail-fast for e2e daily

hack/terraform/azure/iam/.terraform.lock.hcl, hack/terraform/azure/iam/README.md, hack/terraform/azure/iam/main.tf, hack/terraform/azure/iam/output.tf, hack/terraform/azure/iam/readme.md, hack/terraform/azure/iam/variables.tf
- Implement a terraform configuration which creates the necessary azure resources to run constellation, allowing to "skip" the IAM shell script.
=> AB#2578 Implement Azure IAM in terraform

CHANGELOG.md, cli/internal/terraform/terraform/gcp/main.tf, cli/internal/terraform/terraform/gcp/variables.tf, cli/internal/terraform/variables.go
- Terraform GCP: Always use local account for resource creation
=> Terraform GCP: Always use local account for resource creation

image/mkosi.postinst, image/mkosi.prepare
=> ci: use /usr/bin/env instead of /bin/env

cli/internal/cloudcmd/clients.go, cli/internal/cloudcmd/clients_test.go, cli/internal/cloudcmd/create.go, cli/internal/cloudcmd/create_test.go, cli/internal/cloudcmd/rollback.go, cli/internal/cloudcmd/rollback_test.go, cli/internal/cloudcmd/terminate.go, cli/internal/cmd/create.go, cli/internal/cmd/terminate.go, cli/internal/terraform/loader.go, cli/internal/terraform/loader_test.go, cli/internal/terraform/terraform.go, cli/internal/terraform/terraform_test.go, docs/docs/getting-started/first-steps.md, internal/constants/constants.go, internal/file/file.go
- Move Constellation Terraform workspace to `./constellation-workspace` (thus simplify cleanup code and avoid destroying random Terraform clusters)
- Make "create" on unclean states retryable by checking if file on disk == expected file to write
- Make "destroy" work with missing Terraform plugins by calling "terraform init" before trying to "terraform destroy".
When reviewing, please read the issues I was trying to solve and see if that makes sense as a whole. Practical testing with random abortions and CTRL+C hitting might be useful.
Other ideas to the issues are also greatly appreciated.
To understand the changes here, let me explain the issue(s).
Currently, when you do `constellation create` and either:
- rapidly abort with CTRL+C
- Have wonky or no internet
- Terraform fails to …
=> AB#2616: Fix "stuck" Terraform states as best as we safely can

cli/internal/cmd/spinner_test.go
`TestSpinnerInitialState` is a flaky test:
- [Failure](https://github.com/edgelesssys/constellation/actions/runs/3477963019/attempts/1)
- [Re-Run Success](https://github.com/edgelesssys/constellation/actions/runs/3477963019)
I have added some extra messages to test so we can see root cause more easily
```
=== RUN   TestSpinnerInitialState
spinner_test.go:39: 
Error Trace:    /home/datosh/code/constellation/cli/internal/cmd/spinner_test.go:39
Error:          Should be true
Test:           TestSpinnerInitialState
Messages:   
OutStr: "\x1b[?25l\r⣷ Loading.  \r⣯ Loading.. \r⣟ Loading...\r⡿ Loading.  \r⢿ Loading.. \r⣻ Loading...\rLoading...  \n\x1b[?25h"
Prefix: "\x1b[?25l\r⣷ Loading.  \r⣯ Loading.. \r⣟ Loading...\r⡿ Loading.  \r⢿ Loading.. …
```
=> reserve enough time for stable tests

Dockerfile.build
- disk-mapper was not printing any version information, this PR fixes that
Currently, all services receive the version set in `CMakeLists.txt`. Which is the latest release version (`v2.2.2` at the time of writing this)
We should consider updating this to `v<major>.<minor+1>.0-pre` when creating the `v<major>.<minor+1>.0-pre` tag on main.
This way we can more easily identify from what version the binaries were built
=> Fix disk-mapper version injection

renovate.json
- Use semantic versioning to allow upgrades between constellation container pseudo-versions
> Although suffixes in SemVer indicate pre-releases (e.g. v1.2.0-alpha.2), in Docker they typically indicate compatibility, e.g. 1.2.0-alpine. By default Renovate assumes suffixes indicate compatibility, for this reason Renovate will not change any suffixes. Renovate will update 1.2.0-alpine to 1.2.1-alpine but never updates to 1.2.1 or 1.2.1-stretch as that would change the suffix.
If this behavior does not suit a particular package you have, Renovate allows you to customize the versioning scheme it uses. For example, you have a Docker image foo/bar that sticks to SemVer versioning. This means that you need to tell Renovate that suffixes indicate pre-release versions, and not compatibility. …
=> AB#2567 Use semantic versioning to allow upgrades between constellation container pseudo-versions

package-lock.json, renovate.json
- Prioritize renovate PRs so that:
- Internal container images are upgraded first (prio 20)
- Kubernetes dependencies are upgraded preferred (prio 15)
- Dependencies with daily/frequent new versions have lowered priority (-10)
- Dev and doc dependencies (Python, JS, Node) are upgraded last (prio -20)
=> Prioritize renovate PRs

bootstrapper/internal/initserver/initserver.go, bootstrapper/internal/joinclient/client.go
Let joinclient stop initserver only when itself initializes the node.
During the initialization of the first Bootstrapper, the JoinClient used to call Clean, which called the Clean function on the JoinClient and the InitServer. If the initialization takes a few minutes, the InitServer still needs to send back the InitResponse. But the gRPC connection will be shut down since the `GracefulStop()` lets the connection idle which is then closed by the keepalive routine of the  http2 server underneath the InitServer. Therefore, the CLI never receives the InitResponse and eventually times out. 
Changes:
- Only the component which initializes the node calls `Clean()`.
=> bootstrapper: fix GracefulStop of InitServer

operators/constellation-node-operator/controllers/nodeimage_controller.go, operators/constellation-node-operator/controllers/nodeimage_controller_test.go, operators/constellation-node-operator/internal/deploy/deploy.go, operators/constellation-node-operator/internal/deploy/deploy_test.go
- I forgot to run golangci-lint on the sub packages when introducing the revive-ignore comments. This PR introduces some config structs for the missing functions.
=> Use config structs to limit nr of function args

cli/internal/helm/loader.go
There are seldom cases where the cert-manager deployment fails with the error: `timed out waiting for the condition`. To combat this we already increase the timeout from 1m to 5m. The underlying issue is most likely that CRDs or the webhook can not be installed in time as the node is only starting. However, it is not clear which component we would need to wait for. To understand the issue a bit better I propose to print verbose logs for a few days so we get a chance to debug further on failed attempts.
Relevant cert-manager issue: https://github.com/cert-manager/cert-manager/issues/4646. 
The main culprit suspected in the issue is different network configs between the control-plane and the node that the failing `Job` is scheduled on. However, I don't think that is the problem in our case …
=> Run cert-manager startupapicheck with verbose flag

renovate.json
- As discussed in #623, we wan't to avoid upgrading to vale-action v2.0.1 as we had problems with it previously.
=> deps: only upgrade to errata-ai/vale-action >2.0.1

cli/internal/helm/loader.go
#630 introduced a syntax error for the cert-manager deployment. Tested on GCP & Azure.
=> Fix type for cert-manager verbose flag

internal/watcher/validator.go, internal/watcher/validator_test.go
- Add a lock to `*Updatable.OID()` to prevent data race when calling the function in parallel to `*Updatable.Update()`, which can happen if a client connects to the server at the same time the sever is updating its validator
=> Fix potential data race when accessing a validators OID

renovate.json
Reverts edgelesssys/constellation#633, as renovate bot doesn't close the open PR for the upgrade. I'm unsure why it isn't working. I will close #623, I subscribed to releases of the action and will update by hand.
=> Revert "deps: only upgrade to errata-ai/vale-action >2.0.1"

renovate.json
There are older versions tagged like v12.0.0, but latest version is v.0.25.4.
=> deps: disable major upgrades for k8s.io/client-go

CHANGELOG.md, docs/docs/reference/config-migration.md, docs/docs/workflows/troubleshooting.md, internal/config/config.go, internal/config/config_doc.go
- Remove SSHUsers
- Remove UserKey
Both have been deprecated since v2.2.0, but since we now switch to configVersion 2, we can eventually remove them. Users are advised to `kubectl debug`.
=> Remove SSHUsers and UserKey from config v2

cli/internal/cmd/configfetchmeasurements.go, cli/internal/cmd/configfetchmeasurements_test.go, cli/internal/cmd/upgradeplan.go, cli/internal/cmd/upgradeplan_test.go, hack/pcr-reader/main.go, hack/pcr-reader/main_test.go, internal/attestation/measurements/measurements.go, internal/attestation/measurements/measurements_test.go, internal/cloud/cloudprovider/cloudprovider.go, internal/cloud/cloudprovider/cloudprovider_test.go, internal/config/config.go, internal/config/config_doc.go, internal/constants/constants.go, internal/constants/keys_enterprise.go, internal/constants/keys_oss.go, internal/image/image.go
- Only build Constellation CLI with release cosign public key if we build a release CLI
- Use dev cosign public key otherwise
- Adapt `constellation config fetch-measurements` command to work with new JSON format and our artifact CDN
- Enforce metadata validation on `fetch-measurement`
- This only works for images/measurements signed using our updated build pipeline from: https://github.com/edgelesssys/constellation/pull/641
- For fetching measurements of older images, older CLI have to be used. This is not a breaking change, since old CLIs should not be used to upgrade to newer images. New CLIs don't need to fetch measurements for old images, since downgrading is not intended or supported
- Enforce metadata validation for measurements
- Add YAML marshal and unmarshal methods to …
=> AB#2644 Fetch measurements from CDN and perform metadata validation

internal/attestation/measurements/measurements.go, internal/attestation/measurements/measurements_test.go
Previously, writing the config file caused the measurements to be randomly ordered. This PR adds a bit of custom marshaling to sort the measurements numerically.
=> config: sort measurements numerically

cli/internal/helm/charts/edgeless/constellation-services/charts/autoscaler/templates/aws-deployment.yaml, cli/internal/helm/charts/edgeless/constellation-services/charts/autoscaler/templates/azure-deployment.yaml, cli/internal/helm/charts/edgeless/constellation-services/charts/autoscaler/templates/gcp-deployment.yaml, cli/internal/helm/charts/edgeless/constellation-services/charts/ccm/templates/aws-daemonset.yaml, cli/internal/helm/charts/edgeless/constellation-services/charts/ccm/templates/azure-daemonset.yaml, cli/internal/helm/charts/edgeless/constellation-services/charts/ccm/templates/gcp-daemonset.yaml, cli/internal/helm/charts/edgeless/constellation-services/charts/cnm/templates/azure-daemonset.yaml, cli/internal/helm/charts/edgeless/constellation-services/charts/cnm/templates/clusterrolebinding.yaml, cli/internal/helm/charts/edgeless/constellation-services/charts/cnm/templates/serviceaccount.yaml, cli/internal/helm/charts/edgeless/constellation-services/charts/gcp-guest-agent/templates/daemonset.yaml, cli/internal/helm/charts/edgeless/constellation-services/charts/join-service/templates/daemonset.yaml, cli/internal/helm/charts/edgeless/constellation-services/charts/kms/templates/daemonset.yaml, cli/internal/helm/charts/edgeless/constellation-services/charts/kms/templates/mastersecret.yaml, cli/internal/helm/charts/edgeless/constellation-services/charts/konnectivity/templates/daemonset.yaml, cli/internal/helm/charts/edgeless/constellation-services/charts/verification-service/templates/daemonset.yaml, cli/internal/helm/charts/edgeless/constellation-services/charts/verification-service/templates/loadbalancer-service.yaml, cli/internal/helm/charts/edgeless/operators/charts/constellation-operator/templates/deployment.yaml, cli/internal/helm/charts/edgeless/operators/charts/constellation-operator/templates/manager-config.yaml, cli/internal/helm/charts/edgeless/operators/charts/node-maintenance-operator/templates/deployment.yaml, cli/internal/helm/charts/edgeless/operators/charts/node-maintenance-operator/templates/metrics-service.yaml, cli/internal/helm/charts/edgeless/operators/charts/node-maintenance-operator/templates/serving-cert.yaml, cli/internal/helm/charts/edgeless/operators/charts/node-maintenance-operator/templates/webhook-service.yaml, cli/internal/helm/loader_test.go, cli/internal/helm/testdata/Azure/constellation-operators/charts/constellation-operator/templates/deployment.yaml, cli/internal/helm/testdata/Azure/constellation-services/charts/konnectivity/templates/daemonset.yaml, cli/internal/helm/testdata/GCP/constellation-operators/charts/constellation-operator/templates/deployment.yaml, cli/internal/helm/testdata/GCP/constellation-services/charts/gcp-guest-agent/templates/daemonset.yaml, cli/internal/helm/testdata/GCP/constellation-services/charts/konnectivity/templates/daemonset.yaml, cli/internal/helm/testdata/QEMU/constellation-operators/charts/constellation-operator/templates/deployment.yaml, cli/internal/helm/testdata/QEMU/constellation-services/charts/konnectivity/templates/daemonset.yaml
The constellationUID is sometimes interpreted as integer if it contains 0e, as the yaml parsing interprets that as scientific notation. Since it is a [best practices](https://helm.sh/docs/chart_best_practices/values/#make-types-clear) to quote string fields anyways this patch also quotes other fields where an actual string is required.
Manually tested on Azure & GCP.
e2e test runs: [azure](https://github.com/edgelesssys/constellation/actions/runs/3546643517), [gcp](https://github.com/edgelesssys/constellation/actions/runs/3546644802), [aws](https://github.com/edgelesssys/constellation/actions/runs/3546650017).
=> Add helm's quote function to various fields

docs/versioned_docs/version-2.2/architecture/components.md
- Components has a dangling reference `D` that referenced the AccessManager before. It is currently [shown as `D` in the Diagram](https://docs.edgeless.systems/constellation/architecture/components)
- Fixes the diagram by updating the references
=> Fix components diagram

cli/internal/helm/loader.go, cli/internal/helm/loader_test.go, cli/internal/helm/testdata/Azure/constellation-operators/charts/constellation-operator/templates/deployment.yaml, cli/internal/helm/testdata/Azure/constellation-operators/charts/node-maintenance-operator/templates/deployment.yaml, cli/internal/helm/testdata/GCP/constellation-operators/charts/constellation-operator/templates/deployment.yaml, cli/internal/helm/testdata/GCP/constellation-operators/charts/node-maintenance-operator/templates/deployment.yaml
#656 showed that the operator images are set based on the versions.go file directly.
This PR allows the (operator) unittests to use dummy values instead of relying on the real image string from versions.go.
=> Use ChartLoader to set operator deployment images

csi/cryptmapper/cryptmapper.go, image/mkosi.skeleton/usr/lib/udev/rules.d/98-override-systemd.rules
* Fix an issue where CSI resize operations were using a disks volume ID instead of the disk's UID as key ID
* Add a udev rule to label disks with empty usage label
- ~~We might want to split this PR, since I would like the CSI resize fixes in main before we can release a new CSI driver version~~ Dropped the CSI chart changes for now, will update the chart once we have a new release
=> CSI driver fixes

.gitignore, README.md
This adds a link to GitLab to the demos section in the README + some rewording.
Bonus: ignores .gitpod.yml files which are auto-generated by Gitpod
=> Add GitLab to demos section

docs/docs/getting-started/first-steps.md, docs/docs/workflows/config.md
- Change the (non-existent) wrong GCP zone `europe-west1-a` to `europe-west2-a` (with `N2D` availability)
- More info [here](https://cloud.google.com/compute/docs/regions-zones)
=> Docs: Fix wrong GCP zone

renovate.json
- Renovate seems to have automatically detected we'd using semantic commit messages, see #789. https://docs.renovatebot.com/semantic-commits/ Disabling this for now.
=> deps: disable semantic commit message for renovate

.github/actions/e2e_lb/action.yml, .github/actions/e2e_lb/lb.yml, .github/actions/e2e_lb/ns.yml, .github/actions/e2e_test/action.yml, .github/workflows/e2e-test-manual-macos.yml, .github/workflows/e2e-test-manual.yml, .github/workflows/e2e-test-weekly.yml, e2e/internal/kubectl/kubectl.go, e2e/internal/lb/lb_test.go
- Implement E2E test for loadbalancer feature
- Manual run on GCP: https://github.com/edgelesssys/constellation/actions/runs/3733633919
- Let me know what you think on the discussion we had regarding go vs bash for this type of test. I started out with bash but implementing something to wait until the k8s service had an external IP was tricky. `kubectl wait` [could be used with JSONPath but this only accepts primitive fields, and the JSON is manipulated quite a bit when an external IP was generated](https://stackoverflow.com/questions/35179410/how-to-wait-until-kubernetes-assigned-an-external-ip-to-a-loadbalancer-service).
=> implement e2e test lb

cli/internal/cloudcmd/upgrade.go, cli/internal/helm/client.go, cli/internal/helm/client_test.go
- Adapts the `helm.Upgrade` method to only run upgrades for a chart if the local chart version is greater than the one currently installed in Constellation
- ~[ ] Update [docs](https://github.com/edgelesssys/constellation/tree/main/docs)~
=> Only upgrade helm releases if versions changed

bootstrapper/internal/kubernetes/k8sapi/k8sutil.go, image/mkosi.skeleton/etc/crictl.yaml
- configuring the runtime-endpoint in crictl config
Error in FixCilium function when endpoint isn't set (`journalctl -u bootstrapper`):
```
Dec 21 12:33:03 fedora bootstrapper[8985]: {"level":"ERROR","ts":"2022-12-21T12:33:03Z","logger":"bootstrapper.join-client","caller":"k8sapi/k8sutil.go:270","msg":"Getting cilium container id failed: time=\"2022-12-21T12:33:03Z\" level=warning msg=\"runtime connect using default endpoints: [unix:///var/run/dockershim.sock unix:///run/containerd/containerd.sock unix:///run/crio/crio.sock unix:///var/run/cri-dockerd.sock]. As the default settings are now deprecated, you should set the endpoint instead.\"\ntime=\"2022-12-21T12:33:03Z\" level=warning msg=\"image connect using default …
```
=> image: set runtime-endpoint in crictl config

hack/add-version/main.go, internal/versionsapi/versionsapi.go
- Fixing a bug where the cached latest object wouldn't be invalidated
- Fixing a bug where the validation of the cache invalidation couldn't happen because of a faulty path
[Add 2](https://github.com/edgelesssys/constellation/actions/runs/3758060675/jobs/6386474516#step:8:53):
```
{"level":"INFO","ts":"2022-12-22T13:47:55Z","caller":"add-version/main.go:104","msg":"Waiting for cache invalidation."}
{"level":"WARN","ts":"2022-12-22T13:48:36Z","caller":"add-version/main.go:451","msg":"Failed to ensure minor version exists: fetching versions list: versions list \"[https://cdn.confidential.cloud/constellation/v1/ref/debug/stream/major/versions/v2/main/image.json\](https://cdn.confidential.cloud/constellation/v1/ref/debug/ …
```
=> versionsapi: fix cache invalidation

.gitignore
- We download(?) an older prebuilt kernel for GCP. This folder was not ignored.
=> gitignore: add image/prebuilt/*

bootstrapper/internal/kubernetes/kubernetes.go, bootstrapper/internal/kubernetes/kubernetes_test.go, joinservice/internal/kubernetes/kubernetes.go, joinservice/internal/kubernetes/kubernetes_test.go
- Azure machine names contain upper case letters. K8s doesn't allow them for any resource. We already normalize them in the bootstrapper. With 2.3.0 we introduced the joiningnode CRD which is created by the JoinService. For worker nodes the entries are named after the node name from inside the CSR, which is the non-normalized Azure machine name.
=> join: make Azure instance names k8s compliant

bootstrapper/internal/kubernetes/k8sapi/kubeadm_config.go, bootstrapper/internal/kubernetes/k8sapi/resources/konnectivity.go
- Move Konnectivity socket from default /etc/kubernetes/konnectivity-server/konnectivity-server.socket (persistent) to /run/konnectivity-server/konnectivity-server.socket (non-persistent)
- https://github.com/kubernetes-sigs/apiserver-network-proxy/issues/443
While this is not a fix for the cause of this issue (which is still unknown), it cam serve as a mitigation as the Konnectivity server socket should not persist anymore across reboots of a node.
=> AB#2581: Move Konnectivity socket to non-persistent /run

hack/terraform/gcp/internal-loadbalancer/.terraform.lock.hcl, hack/terraform/gcp/internal-loadbalancer/main.tf, hack/terraform/gcp/internal-loadbalancer/modules/instance_group/main.tf, hack/terraform/gcp/internal-loadbalancer/modules/instance_group/outputs.tf, hack/terraform/gcp/internal-loadbalancer/modules/instance_group/variables.tf, hack/terraform/gcp/internal-loadbalancer/modules/internal_loadbalancer/main.tf, hack/terraform/gcp/internal-loadbalancer/modules/internal_loadbalancer/variables.tf, hack/terraform/gcp/internal-loadbalancer/outputs.tf, hack/terraform/gcp/internal-loadbalancer/variables.tf, internal/cloud/gcp/cloud.go, internal/cloud/gcp/cloud_test.go, internal/cloud/gcp/interface.go, internal/cloud/gcp/wrappers.go
- Scan global and now also regional forwarding rules for our Constellation endpoint. 
- Add unofficial example Terraform
I didn't want to change #806 since we gave out a link pointing to the Terraform on this branch. 
In the best scenario be could deploy the "internal" infrastructure and for normal deployments simply deploy some sort of gateway. I haven't found this possibility for internal *proxy* load balancers yet. Without such a solution the infrastructure is a bit different. How should this be tested in the future?
=> gcp: unofficial support for internal LBs

e2e/internal/lb/lb_test.go
- AWS uses hostname (DNS) based loadblancer names as opposed to ip based for GCP and Azure
=> fix e2e lb test on aws: call hostname instead of ip

.github/actions/e2e_lb/action.yml, e2e/internal/lb/lb_test.go
Fix for failing [e2e pipeline](https://github.com/edgelesssys/constellation/actions/runs/3823897353/jobs/6505552497), where two things seem to have happened:
1. `kubectl delete -f ns.yaml` was hanging which caused the 6h timeout. I added a 5min timeout to delete.
2. Load balancer was not created in time.
* Added more debug information
* Increased timeout to 15min
=> Fix failing e2e test for lb

cli/internal/cmd/create.go, cli/internal/cmd/create_test.go, cli/internal/cmd/iamcreateaws_test.go, cli/internal/cmd/iamcreateazure_test.go, cli/internal/cmd/iamcreategcp_test.go, cli/internal/cmd/init_test.go, cli/internal/cmd/spinner.go, cli/internal/cmd/terminate_test.go
- Currently, the spinner is printed at the start of multiple lines when debug logging in the CLI is enabled. This PR fixes this behavior, leading to a cleaner debug log.
=> cli: deactivate spinner for debug logging

.github/workflows/build-os-image.yml, .github/workflows/generate-measurements.yml, cli/internal/cmd/configfetchmeasurements.go, cli/internal/cmd/configfetchmeasurements_test.go, internal/versionsapi/client/client.go, internal/versionsapi/imageinfo.go, internal/versionsapi/imageinfo_test.go, internal/versionsapi/version.go, internal/versionsapi/version_test.go, rfc/apis.md, rfc/image-api.md
- As discussed in https://github.com/edgelesssys/constellation/pull/788#discussion_r1050526782, this changes the API path to an image of a version.
- Also fixing a bug where deletion of a single version wouldn't delete the artifacts in s3 bucket for that versions. This is now much easier after the API change.
- Also fixing a bug where the workflow call to add version to versions API would fail due to wrong syntax.
=> versionsapi: change image path

renovate.json
- Grouping maybe ins't working due to the outdated registry prefix of kas network proxy agent
=> deps: fix kas-network-proxy registry prefix

cli/internal/cloudcmd/upgrade.go, cli/internal/cmd/upgradeexecute.go, cli/internal/cmd/upgradeexecute_test.go, cli/internal/helm/client.go, cli/internal/helm/client_test.go
- Since cert-manager upgrades change CRDs that the user might depend on we now ask for confirmation of the step. An unintended version upgrade will delete resources (e.g. cert-manager issuer) cluster users created.
- #631
=> cli: ask user to confirm cert-manager upgrades

renovate.json
- Don't group these as they are not released together and often cause cloud provider specific problems.
=> renovate: don't group k8s contstrained versions

go.mod, go.sum, hack/go.mod, hack/go.sum, operators/constellation-node-operator/go.mod, operators/constellation-node-operator/go.sum
Reverts edgelesssys/constellation#907
Bootstrapper fails on GCP with: 
```
{"level":"FATAL","ts":"2023-01-10T09:00:35Z","logger":"bootstrapper","caller":"bootstrapper/run.go:61","msg":"Failed to create init server","error":"retrieving init secret hash: retrieving init secret hash: retrieving compute instance: proto: (line 13:13): invalid value for string type: 3"}
```
[Upstream issue](https://github.com/googleapis/google-cloud-go/issues/7228)
=> Revert "Update Google SDK"

cli/internal/cloudcmd/upgrade.go, internal/kubernetes/kubectl/kubectl_test.go, operators/constellation-node-operator/README.md, operators/constellation-node-operator/config/samples/update_v1alpha1_nodeversion.yaml, operators/constellation-node-operator/config/samples/update_v1alpha1_scalinggroup.yaml
- update nodeversion references
Should we also update constellation-os-azure|gcp? @malt3 
- /operators/constellation-node-operator/config/samples/update_v1alpha1_nodeversion.yaml
- /operators/constellation-node-operator/config/samples/update_v1alpha1_scalinggroup.yaml
=> upgrade: fix broken reference from constellation-os to constellation-version

.github/actions/e2e_mini/run-e2e.sh, cli/internal/terraform/terraform/qemu/main.tf
- Remove `registry_auth` for Docker Terraform provider
This seems to be a leftover from back when the repoistory and images were private, but causes Mini Constellation to fail when no config.json for Docker exists under the defined path `~/docker/config.json`.
Trying to run MiniConstellation on a relatively fresh Docker installation where this config file does not exist, you will get this error:
```
./constellation-linux-amd64 mini up
A config file already exists in the current workspace.
Do you want to overwrite it? [y/n]: y
Creating cluster in QEMU   
An error occurred: exit status 1
Error: Error loading registry auth config: could not open config file from filePath: /home/ubuntu/.docker/config.json. Error: open /home/ubuntu/.docker/config.json: no such file or directory
with …
```
=> cli: remove registry_auth for Docker Terraform module

.github/actions/e2e_lb/action.yml
- Increase go test timeout, which defaults to 10m
=> ci: increase Go test timeout in e2e lb

image/mkosi.files/mkosi.qemu.conf, image/mkosi.postinst, image/mkosi.skeleton/usr/lib/tmpfiles.d/constellation.conf
- image: enable serial console access for QEMU / mini Constellation
- image: print motd if serial console access is enabled
This is meant to simplify debugging in customer environments.
The change only targets QEMU / MiniConstellation and does not affect the security of real CVM images.
This is what a serial console login will look like:
```shell-session
Fedora Linux 37 (Thirty Seven)
Kernel 6.0.18-300.fc37.x86_64 on an x86_64 (ttyS0)
constellation v0.0.0
PCR state:
sha256:
0 : 0x7D08997028F34F6CCDD2ED9BD31804CF0B0C7FFF9A4D05299E33620001510281
1 : 0xEE07102D1418518024110872A713A9824BC7F6AE47D62FD0CDE0918C0E249B7E
2 : 0x72001A25201B263BC60F869ACE2F728B09DC4BE78B9C80ADCA87A013C2D26950
3 : 0x3D458CFE55CC03EA1F443F1562BEEC8DF51C75E14A9FCF9A7234A13F198E7969
4 : …
```
=> image: enable serial console access for MiniConstellation to simplify troubleshooting

.github/workflows/purge-main.yml
- After frequently building images for all streams in #977, we should also delete images of all streams.
=> ci: delete old images of all streams on ref main

operators/constellation-node-operator/controllers/joiningnode_controller_env_test.go
- Obviously the K8s node is expected to exists after the JoiningNode CR. 
Before, we raced the annotation + deletion with the check for creation of the JoiningNode CR.
Broke in: https://github.com/edgelesssys/constellation/actions/runs/3931758103/jobs/6723428260
=> operator: test JoiningNode in correct order

.github/workflows/codeql.yml, .github/workflows/scorecard.yml, keyservice/setup/setup.go, keyservice/setup/setup_test.go
- Enable CodeQL via [action](https://github.com/github/codeql-action)
- This populates the [Security -> Code Scanning](https://github.com/edgelesssys/constellation/security/code-scanning) tab in GitHub WebUI. Results are available per branch. See the [results for this branch](https://github.com/edgelesssys/constellation/security/code-scanning?query=is%3Aopen+branch%3Afeat%2Fci%2Fcodeql-and-scorecard), generated in [this workflow run](https://github.com/edgelesssys/constellation/actions/runs/3931088510/jobs/6721898087).
- Using the [default workflow file](https://github.com/github/codeql-action#usage) for CodeQL [fails in the autobuild step](https://github.com/edgelesssys/constellation/actions/runs/3930144609). As per documentation I …
=> Configure CodeQL and scorecard workflow.

image/mkosi.postinst, image/mkosi.skeleton/usr/lib/dracut/modules.d/39constellation-mount/aws-nvme-disk.sh, image/mkosi.skeleton/usr/lib/dracut/modules.d/39constellation-mount/module-setup.sh
- Fix the following warning:
```
"/usr/sbin/aws-nvme-disk: line 15: warning: command substitution: ignored null byte in input" warnings in boot logs
```
This has multiple reasons:
1. We are off by one byte (block device name starts _after_ 3072 bytes, not _on_ byte  3072 what `tail -c +3072` would achieve).
2. We still print the remaining NVMe identify response. The spaces belong to the block device name, the rest has been NULL bytes so far, which is also where that error comes from. 
Now if we take a closer look at how that struct is defined from Amazon's script, we can find that it is supposed to be 32 bytes long: https://github.com/amazonlinux/amazon-ec2-utils/blob/34294c2fbb37ffd2f2e7d0d82ee8522e7ec3c02d/ebsnvme-id#L50-L51
The remaining response is the "RESERVED" block we are hitting, …
=> image: fix "ignored null byte in input" warning on AWS

.github/workflows/release-cli.yml
- Update Syft to 0.66.1
- Update Grype to 0.55.0
- Install the two tools to `/usr/local/bin` to avoid polluting the git tree
- Build linux/amd64 CLI as reference for Syft to collect the used modules
Syft's `go-module` did not collect the package list correctly before ever since the build was separated from the SBOM generation. The alternative would be to use `go-mod-file`, which would collect every package this monorepo imports - even if it's not inside the CLI. Since we have separate SBOMs for the microservices (which look good to me), that would be somewhat undesirable.
Thus we build the linux/amd64 CLI as reference to collect all the modules. Testing between what we currently ship (Linux/macOS & amd64/arm64), the generated SBOMs hold the same packages for the CLI, so for the moment we …
=> ci: fix CLI SBOM generation

.github/actions/container_sbom/action.yml, .github/actions/install_syft_grype/action.yml, .github/workflows/release-cli.yml
- Update Syft to v0.66.2 (CLI + container SBOMs) (was released yesterday after I initially opened my previous PR: https://github.com/anchore/syft/releases/tag/v0.66.2)
- Update Grype to v0.55.0 (container SBOMs, CLI was already updated with #1005)
- Use same "download to /tmp and install to /usr/bin" install method for Syft and Grype for the container SBOMs as for the release CLI action
- Move the install into an action
This should make it easier to keep the version for the CLI and containers in sync.
Small disadvantage is that now the Checkout needs to be before the install again. The action does download to /tmp though, so it should keep the git workspace clean.
=> ci: move Syft & Grype installation into an action

.github/actions/e2e_verify/action.yml
- The formatting of the measurements of debug images on the versions API has changed ( from [this](https://cdn.confidential.cloud/constellation/v1/ref/main/stream/debug/image/v2.4.0-pre.0.20221229165011-473e16feb2cc/csp/azure/measurements.image.json) to [this](https://cdn.confidential.cloud/constellation/v1/ref/main/stream/debug/v2.5.0-pre.0.20230112150103-bcd8aa9acc25/image/csp/gcp/measurements.image.json) ) which needs to be taken into account when fetching the measurements in the test. I adapted to said changes. A successful run of the test can be seen [here](https://github.com/edgelesssys/constellation/actions/runs/3938516358/jobs/6737304444)
=> ci: adapt to new measurements format

docs/docs/getting-started/first-steps.md, docs/docs/workflows/config.md
- Adding documentation to the `--generate-config` flag of the `constellation iam create` command which automatically generates a configuration file and populates it with the created IAM values.
- The "First steps" section features the shortest way of creating a cluster, by using the 2-in-1 command. It also links to the detailed workflow page for people who are interested in separate IAM / config creation.
- The "Configure your cluster" workflow page then features the workflow of separate IAM / config creation but also explains how to do it in the 2-in-1 way.
=> docs: add docs for automatic config filling of iam values

.github/workflows/build-ccm-gcp.yml
- Fixed broken build as `"${GITHUB_WORKSPACE}/bin/bazel"` didnt exist anymore after https://github.com/edgelesssys/constellation/commit/8aa84fd7597b69dbd7f4c59c17410eae570b2b7d, but bazelisk is available on all runners.
- As described in linked issue, the bazel build is currently broken for older version, so I have removed them from CI for now.
- Build for latest version works so I have upgraded image in versions.go
=> ci: fix GCP cloud controller manager build

README.md
- Update our `Contributing` section in root `README.md` to use Githubs [native](https://github.com/community/community/discussions/16925) warning parkup.
=> docs: update security issue warning to use Github warning banner

internal/config/config.go, internal/config/validation.go
These extended error messages help users in understanding what is wrong with the current configuration and how to remediate the issue. 
Target version too new:
```
../constellation create -c 1 -w 2 -y
Problems validating config file:                                                                                                             
KubernetesVersion specifies an unsupported Kubernetes version. The configured version 1.77 is newer than the newest version supported by this CLI: 1.26                                                                                                                           
Fix the invalid entries or generate a new configuration using `constellation config generate`                                                
Error: invalid configuration
```
Target …
=> config: detailed validation errors for k8s version

.github/actions/os_build_variables/action.yml, .github/workflows/build-os-image-scheduled.yml, .github/workflows/build-os-image.yml, internal/versionsapi/cli/rm.go
- Fixing a bug where versionsapi couldn't delete images at the cloud provider because the versionsapi object was deleted first.
- Fixing a bug where the scheduled image build would build a debug image with a bootstrapper in it.
- Moving the scheduled build into an own workflow for better separation.
=> ci: move scheduled build into own workflow

cli/internal/cmd/minidown.go, cli/internal/cmd/miniup.go, cli/internal/terraform/terraform/qemu/outputs.tf, internal/constants/constants.go
- cli: set placeholder uid for QEMU / MiniConstellation
Download constellation 2.5.0 and try to use MiniConstellation:
```shell-session
constellation mini up
Creating cluster in QEMU
An error occurred: no uid output found
Attempting to roll back.
Rollback succeeded.
Error: creating cluster: no uid output found
```
Fixes a bug in ae2db08f3ae01d9cce2741d4be75df113eea0a83 where a `uid` is expected from all csps in the terraform output.
QEMU does not have a uid so parsing of the output fails.
Fixed by setting a placeholder uid.
=> cli: set placeholder uid for QEMU / MiniConstellation

cli/internal/terraform/terraform/gcp/.terraform.lock.hcl, cli/internal/terraform/terraform/gcp/main.tf, cli/internal/terraform/terraform/gcp/modules/instance_group/main.tf, cli/internal/terraform/terraform/gcp/modules/instance_group/variables.tf, hack/terraform/gcp/internal-loadbalancer/.terraform.lock.hcl, hack/terraform/gcp/internal-loadbalancer/main.tf, hack/terraform/gcp/internal-loadbalancer/modules/instance_group/main.tf, hack/terraform/gcp/internal-loadbalancer/modules/instance_group/variables.tf
- Make the control-plane instance group stateful by making the disk and internal ip stateful.
Then stopping an instance on GCP, it is automatically re-created from the template. Per default, a new state disk and IP is used. This is problematic when stopping all VMs at the same time.
To stop an instance on GCP do:
1. Go to the details view of the control-plane instance
2. Go back to the instance overview
3. Select all the instances to be stopped
4. Click the "Stop" button.
Steps 1-2 are needed since GCP normally does not really allow you to stop the instance (see greyed out button in the details view of the instance). 
Does anyone have opinions regarding if we should backport this?
=> terraform: make control-planes stateful on gcp

.github/actions/e2e_recover/action.yml, .github/actions/e2e_test/action.yml
- Wait for the control plane nodes to get back up after pushing the recovery keys to ensure control plane availability after recovering the cluster
- [Successful run with 1 CP node](https://github.com/edgelesssys/constellation/actions/runs/4015145256/jobs/6896527567)
- [Successful run with 3 CP nodes](https://github.com/edgelesssys/constellation/actions/runs/4015146173/jobs/6896526073)
=> ci: fix Constellation recover e2e test

operators/constellation-node-operator/controllers/nodeversion_controller.go
- This minor change should make debugging https://github.com/edgelesssys/constellation/actions/runs/4025356008/jobs/6918466016 clearer. I assume what happens is that 2 node are created, one still in awaitingAnnotationNodes and one in JoiningNodes.
=> operator: log awaitingAnnotationNodes

.github/actions/build_ko/action.yml, .github/actions/build_micro_service_ko/action.yml, .github/workflows/release.yml
- Currently tags can be empty when building a ko image. However, `--bare` may not work with empty `--tags`. [ko docs](https://ko.build/reference/ko_build/). This change ensures that tags is always set. Either a pushTag is given to the action or it uses a pseudo version.
=> ci: prevent empty tags field in build_ko pipeline

.github/workflows/update-cli-reference.yml
fix: https://github.com/edgelesssys/constellation/actions/runs/4063404048/jobs/6995599134
required permissions documented in https://github.com/peter-evans/create-pull-request#workflow-permissions
=> ci: allow ci reference workflow to create pr

cli/internal/terraform/terraform/gcp/main.tf
- Raise MTU from 1460 to 8896 (jumbo frames)
This enhances general network performance inside Kubernetes with Cilium by ~4x.
(From ~1 Gbit/s to ~4 Gbit/s)
Note that Terraform's documentation on the `mtu` field is not correct that the maximum setting for MTU is 1500. I'll open a PR with them later to fix this.
=> cli: enable jumbo frames for GCP VPCs

csi/cryptmapper/cryptmapper.go, disk-mapper/internal/mapper/mapper.go, internal/cryptsetup/cryptsetup.go
- Enable read/write workqueue bypass to potentially speed up encrypted disk usage
This feature should be extensively tested before we decide if we want to include it in the next release.
To achieve this I want to first run some e2e tests on this branch, and then have it in main so it gets tested by our daily and weekly e2e test, as well as developers.
As the changeset is quite small it can be easily reverted at any time
Successful run on Azure: https://github.com/edgelesssys/constellation/actions/runs/4103995386
Successful run on GCP: https://github.com/edgelesssys/constellation/actions/runs/4105197725
=> Enable cryptsetup read/write workqueue bypass

bootstrapper/internal/helm/helm.go
Sometimes cluster initilization fails on Azure with the error: `Error: init call: rpc error: code = Internal desc = initializing cluster: installing cert-manager: helm install: failed post-install: timed out waiting for the condition`.
This PR introduces a retry loop that aborts after 5 mins for all helm installations.
An alternative solution would be to wait after konnectivity installation, however this approach seems more robust to me and might mitigate other unknown race conditions.
Judging from the logs and the frequency that we see this bug 9/10 installation should not run into the retry case.
For those that do, installation should work on the second try (in the logs the api check becomes healthy seconds after the first try is aborted).
The timeout errors are most likely connected to …
=> bootstrapper: retry helm chart installation

internal/config/config.go, internal/config/validation.go, internal/versions/versions.go
- Fix incorrect string comparison by replacing it with call to semver.Compare. Also add handling to check for missing v prefix.
=> config: fix incorrect kubernetes version validation

cli/internal/cmd/init.go, cli/internal/cmd/init_test.go
Add `--merge-kubeconfig` flag to `constellation init`.
If set, automatically merges the config generated by `init` into the default configuration in `$HOME/.kube/config` and sets it as the current context.
Users are then able to connect to the cluster without having to do any extra setup.
If the `KUBECONFIG` env variable is set, the new config is still merged into the default config, but we cant reliably tell if `kubectl` will load this config, so a warning is printed in this case telling the user they might need to unset the `KUBECONFIG` env var
=> cli: add option to automatically merge kubeconfig file on init

.github/workflows/e2e-test-manual.yml, .github/workflows/e2e-test-weekly.yml, .github/workflows/release.yml
- Adapt the pipelines to use the new version format for k8s versions. This would have been fixed by #1157 but #1157 will not be merged before the weekly pipeline runs. Therefore this PR only brings in the new versions.
- The missing v in one version can be ignored as the code handles both formats transparently.
=> ci: fix k8s version format in e2e tests

.github/workflows/build-os-image.yml
Apparently quoting breaks something, I was not able to quickly figure this out so I expanded the variables instead.
failed: https://github.com/edgelesssys/constellation/actions/runs/4135811513/jobs/7149764114#step:7:610
reproduced: https://github.com/edgelesssys/constellation/actions/runs/4136536714
fixed: https://github.com/edgelesssys/constellation/actions/runs/4136561357
=> ci: fix yq command syntax

cli/cmd/root.go, cli/internal/cmd/upgradecheck.go
Adapt the command reference to our conventions and also simplify/clarify.
=> cli: adapt "upgrade check" reference to conventions

cli/internal/cloudcmd/clients.go, cli/internal/cloudcmd/clients_test.go, cli/internal/cloudcmd/create_test.go, cli/internal/cloudcmd/rollback.go, cli/internal/cloudcmd/rollback_test.go, cli/internal/cloudcmd/terminate.go, cli/internal/cloudcmd/terminate_test.go, cli/internal/cmd/iam.go, cli/internal/cmd/iam_test.go, cli/internal/terraform/terraform.go, cli/internal/terraform/terraform_test.go
- Check whether Terraform state directory already exists on the `iam create` command and if it exists, do not continue with execution
- Rename `DestroyCluster` to `DestroyResources` as it can also destroy IAM resources
- Previously, if the `iam create` command is executed twice in a row, the second execution would error because the Terraform state dir already exists. On this error, it would also rollback the existing directory which deletes the Terraform state of a previous execution of the command
=> cli: fix iam rollback

.github/actions/constellation_create/action.yml
- add quotes to the version to ensure it’s treated as a string. The MAJOR.MINOR format was treated as a float and therefore worked without quotes. Test run: https://github.com/edgelesssys/constellation/actions/runs/4160988930
=> ci: fix yq command for new k8s version format

cli/internal/cmd/init.go, cli/internal/cmd/init_test.go
- The config validation generally allows users to specify versions without "v" prefix, even though internally we need all version strings to have that prefix. As init validates the k8s version without ensuring a "v" prefix it broke for version strings that are normally accepted.
=> cli: fix init with k8s version without v prefix

.github/workflows/docs-vale.yml
Old version of the action doesn't work anymore. Use new version of the action with older version of vale. (Newer versions of vale introduce false positives.)
=> ci: update vale action

cli/internal/cmd/version.go, internal/constants/enterprise.go, internal/constants/oss.go
Looks like:
```
❯ ./constellation version
Version:        2.5.0 (Open-source software build; AGPL-3.0-only applies)
GitCommit:      b053f4e837af063bcc495e0ac442412b5a9ced53
GitTreeState:   dirty
BuildDate:      2023-02-13T17:35:30Z
GoVersion:      go1.19.5
Compiler:       gc
Platform:       linux/amd64
```
=> cli: add name of build type to version cmd output

cli/internal/cmd/upgradecheck.go
- Missing logger makes CLI panic. This PR fixes that.
=> cli: add missing logger to versionCollector object

.github/actions/e2e_recover/action.yml, .github/actions/e2e_verify/action.yml
- In the CI most configs use prerelease images. Config validation prevents this. Therefore we need to use the force flag for now.
- Discussion on UX of the flag is ongoing. Adding this to fix the pipeline for the time being.
=> ci: add force flag to remaining constellation cmds

cli/internal/helm/client.go, cli/internal/helm/client_test.go, cli/internal/helm/loader.go, cli/internal/helm/loader_test.go, internal/compatibility/compatibility.go
- This fixes multiple bugs where upgrades did not change resources in the cluster as expected. These bugs stem from the fact that the existing upgrade code did not load values locally and therefore did not render the templates correctly in some cases.
- Solve by letting go code load helm values also during upgrade. While we still want to reuse values from the cluster we need to set others. Like the images. This change therefore loads all values during an upgrade that do not depend on user input. If a value depends on user input it will not be set. Because the value is not set, the existing value from the cluster is reused.
- [Azure, 1.25, 1+2](https://github.com/edgelesssys/constellation/actions/runs/4181302080). Check that init still works as expected.
=> cli: load helm values during upgrade

cli/internal/cmd/upgradecheck.go, internal/compatibility/compatibility.go, internal/compatibility/compatibility_test.go, internal/config/config.go, internal/config/validation.go
- Improve error messages for situtation where the CLI is too old for the configured versions
- Allow newer patch versions for images. This was the intended behavior from the beginning.
- Fix a bug where the `microserviceVersion` value is always overwritten with the default during `config.New()`
- Fix a bug where `upgrade check` does not find new images because the CLI version is not correctly set in `versionCollector`
=> compatibility: various bug fixes

image/Makefile, image/mkosi.files/mkosi.azure.conf
- Upgrade to Linux kernel 6.1.11 for Azure
This includes the important network patches for netvsc for Azure.
Guess this will be the golden kernel for a while upstream figures out what to do with the slow disk issues / MTRR story.
=> image: upgrade to Linux 6.1.12 for Azure

Dockerfile.build, bootstrapper/internal/kubernetes/kubernetes.go, cli/internal/cloudcmd/upgrade.go, cli/internal/cloudcmd/upgrade_test.go, cli/internal/cmd/init_test.go, cli/internal/cmd/upgrade.go, cli/internal/cmd/upgradeapply.go, cli/internal/cmd/upgradeapply_test.go, cli/internal/cmd/upgradecheck.go, cli/internal/cmd/upgradecheck_test.go, cli/internal/image/image.go, go.mod, go.sum, hack/check-licenses.sh, hack/go.mod, hack/go.sum, internal/constants/constants.go, internal/kubernetes/configmaps.go, operators/constellation-node-operator/api/LICENSE, operators/constellation-node-operator/internal/constants/constants.go, operators/constellation-node-operator/internal/deploy/deploy.go, operators/constellation-node-operator/internal/deploy/deploy_test.go
- Replace the existing `upgrade execute` command with an extended command called `upgrade apply`. The new command complements the `upgrade check` command by applying the configured upgrades from the config. It extends the existing functionality by enabling k8s and helm upgrades. The upgrades are controlled via the config values `image`, `microserviceVersion` and `kubernetesVersion`.
- `upgrade apply` checks that the configured version C is a valid upgrade to the installed version I. That means skip cases where `C==I`, `C<I` or `C.Minor>I.Minor+1`.
-  `upgrade apply` also checks that there is currently no k8s or image upgrade in progress. If an upgrade is in progress the upgrade is skipped and a message is printed.
=> cli: refactor `upgrade execute` to `upgrade apply`

hack/qemu-metadata-api/Dockerfile
Oversaw that this is necessary when making the operator's api a submodule. Similar change is in the root's Dockerfile.build.
[Workflow run](https://github.com/edgelesssys/constellation/actions/runs/4192532685)
=> hack: add api module to container during build

cli/internal/cmd/spinner.go, cli/internal/cmd/terminate.go, internal/constants/constants.go
- Option to disable spinner via `CONSTELL_NO_SPINNER` environment variable. Main motivation is to automatically skip waiting times in asciinema recordings 
- Fix `constellation terminate` spinner to honor `debug` flag and new `CONSTELL_NO_SPINNER` environment variable
=> cli: option to disable spinner via environment variable

cli/internal/cmd/create.go
- Fix incorrect pluralization of nodes during the `constellation create` command when creating clusters with only 1 control-plane/worker node
- Fix incorrect `control-planes` string to `control-plane`
=> cli: fix incorrect output for single worker/control-plane clusters

internal/config/config.go, internal/config/config_doc.go, internal/config/validation.go
* Print deprecation warnings to `os.Stderr`
* Allow unset `name` key in config, but fallback to default name and print a warning if it does not show up
=> Allow unset 'name' key but print warning if unset

rfc/apis.md, rfc/cli-api.md, rfc/image-api.md
- Add specification for the CLI version compatibility API
- The API should be exposed via the [version API](https://github.com/edgelesssys/constellation/tree/main/internal/versionsapi) and provide information on compatibility between a specific CLI version of a Constellation version and Kubernetes versions.
=> rfc: specify cli version api

cli/internal/cmd/upgradeapply.go, internal/config/config.go
- Apply still used the obsolete upgrade key's measurements. The new, desired behavior is to use the Provider's measurements key
=> cli: upgrade apply uses correct measurements key

internal/config/config.go, internal/config/config_test.go, internal/config/validation.go
- To adhere to our compatibility goal of not breaking old configs within one version, the kubernetes patch version is automatically extended for configs in the transistional version v2.6.
=> config: allow k8s version MAJOR.MINOR  for v2.6

.github/actions/constellation_create/action.yml, .github/actions/constellation_iam_create/action.yml, .github/actions/constellation_iam_destroy/action.yml, .github/actions/e2e_test/action.yml, .github/workflows/e2e-test-manual.yml, .github/workflows/e2e-test-weekly.yml, cli/internal/cmd/iam.go
- Add e2e testing of the `iam create` command. To run the test, use the `iamcreate` payload.
- [Successful GCP run](https://github.com/edgelesssys/constellation/actions/runs/4102278056)
- [Successful AWS run](https://github.com/edgelesssys/constellation/actions/runs/4124209934)
- The Azure MI / SP used for the CI does not have the permissions needed to update / assign / (...?) IAM policies, this will be adressed in a separate ticket [here](https://dev.azure.com/Edgeless/Edgeless/_backlogs/backlog/Edgeless%20Team/Features/?workitem=2912)
=> ci: integrate automatic iam creation in e2e test

cli/internal/cmd/configgenerate.go, cli/internal/cmd/configgenerate_test.go, internal/config/validation.go
- This flag can be used to specify a Kubernetes version in format MAJOR.MINOR and let the CLI extend the
value with the patch version.
=> cli: add `--kubernetes` flag to `config generate`

cli/internal/cmd/miniup.go, internal/config/validation.go
- If there is a version mismatch in the config file, refer to the `--force` flag to ignore this behavior. 
- If there is already a `constellation-conf.yaml` in the current working directory, refer to the `--config` option to ignore this behavior.
=> cli: refer to --force and --config flags

cli/internal/terraform/terraform/iam/azure/main.tf
- Assign role at the base resource group and not the iam resource group
This bug was introduced in https://github.com/edgelesssys/constellation/commit/b8648261e3a89c69c46ec313fda6bfd16db1e415
=> iam: assign uami role to base resource group

cli/internal/cmd/config.go, cli/internal/cmd/configkubernetesversions.go, docs/docs/architecture/versions.md, docs/docs/workflows/config.md, internal/versions/versions.go
- Allows users to learn which k8s versions are supported by the current CLI. This can be helpful when creating new cluster, applying upgrades or understanding the output of `upgrade check`.
=> cli: add `config kubernetes-versions` subcommand

bootstrapper/internal/helm/helm.go, bootstrapper/internal/kubernetes/kubewaiter/kubewaiter.go
- Let the helm installer retry on "connection refused" errors
Problem: 
`constellation init` fails with:
```
Your Constellation master secret was successfully written to ./constellation-mastersecret.json
Initializing cluster   
Cluster initialization failed. This error is not recoverable.
Terminate your cluster and try again.
Error: init call: rpc error: code = Internal desc = initializing cluster: installing pod network: helm install: Kubernetes cluster unreachable: Get "https://X.X.X.X:6443/version": dial tcp X.X.X.X:6443: connect: connection refused
```
Detailed description:
What is interesting that after kubeadm init we have an explicit kubewaiter, which waits until it can list all K8s namespaces using the kubeclient and further kubeclient requests such as annotating the current node. …
=> helm: retry on connection refused

.github/actions/e2e_mini/.terraform.lock.hcl, .github/actions/e2e_mini/main.tf, cli/internal/terraform/terraform/azure/.terraform.lock.hcl, cli/internal/terraform/terraform/azure/main.tf, cli/internal/terraform/terraform/azure/modules/load_balancer_backend/main.tf, cli/internal/terraform/terraform/azure/modules/scale_set/main.tf, cli/internal/terraform/terraform/iam/azure/.terraform.lock.hcl, cli/internal/terraform/terraform/iam/azure/main.tf
Revert edgelesssys/constellation#1197
There seems to be an issue with 3.44.1: https://github.com/hashicorp/terraform-provider-azurerm/issues/20546
Fix is already on their main branch, but no release ready yet. 
Found because the mini constellation e2e pipeline failed: https://github.com/edgelesssys/constellation/actions/runs/4240682413/jobs/7370885385
=> Revert "deps: update Terraform azurerm to v3.44.1"

.github/actions/container_sbom/action.yml, .github/actions/install_syft_grype/action.yml, .github/workflows/release-cli.yml
- Upgrade Syft to 0.69.0
- Upgrade Grype to 0.56.0
Syft fixed the APK parsing issues in 0.68.1 caused by apko adding empty fields and finally added private key attestation back with 0.69.0. Let's give it a shot, since it should unblock updating the Alpine base images with newer versions of apko again.
Also updating Grype just for the sake of it. It's based on Syft 0.68.1 which should have any parsing issues fixed hopefully. Not the attestation part, but we don't care about that for Grype.
- #1017
=> ci: update Syft to 0.72.0 and Grype to 0.57.1

.github/actions/container_sbom/action.yml
- specify CycloneDX spec via URL rather than using a shortname
See: https://github.com/sigstore/cosign/issues/2596
Apparently, Syft and Cosign have different specs for CycloneDX. Cosign wants to update them in v2, but on the current release, you end up with stuff that is _slightly_ incompatible if you use attestation with these two tools.
Granted, this happened because the verification already used the "new" URL while the attestation didn't. Not sure if this is also related to the update or not... could be. Let's just use the new version.
And hopefully I won't have to deal with this again because this in-toto stuff is so early days it makes my head hurt dealing with these minor issues over multiple PRs now.
This is truly a mess, I hate it.
=> ci: specify URL predicate because shortnames are unreliable

cli/internal/cloudcmd/clients.go, cli/internal/cloudcmd/clients_test.go, cli/internal/cloudcmd/iam.go, cli/internal/cloudcmd/iam_test.go, cli/internal/cmd/cloud.go, cli/internal/cmd/cloud_test.go, cli/internal/cmd/iam.go, cli/internal/cmd/iamdestroy.go, cli/internal/cmd/iamdestroy_test.go, cli/internal/terraform/terraform.go, docs/docs/workflows/config.md
- Add the new ```iam destroy``` subcommand to destroy IAM configuration with the Constellation CLI
- Rename the ```DestroyCluster``` function in [terraform.go](https://github.com/edgelesssys/constellation/blob/feat/iam-destroy-user/cli/internal/terraform/terraform.go) to ```Destroy```
This change will allow users to delete their IAM configurations using the constellation CLI instead of the terraform CLI.
=> cli: iam destroy

disk-mapper/cmd/main.go, disk-mapper/internal/setup/setup.go, image/Makefile, image/mkosi.skeleton/usr/lib/dracut/modules.d/39constellation-mount/prepare-state-disk.service, image/mkosi.skeleton/usr/lib/dracut/modules.d/39constellation-mount/prepare-state-disk.sh, image/mkosi.skeleton/usr/lib/systemd/system-preset/30-constellation.preset, image/mkosi.skeleton/usr/lib/systemd/system/constellation-bootstrapper.service, image/mkosi.skeleton/usr/lib/systemd/system/constellation-upgrade-agent.service, image/mkosi.skeleton/usr/lib/systemd/system/export_constellation_debug.service, image/mkosi.skeleton/usr/lib/systemd/system/tpm-pcrs.service
1. Add new `systemd` unit that checks if the kernel command line option `constellation.debug` is set. If it is `true`, the following services are started with the `--debug` flag via their respective systemd unit file
2. Add `lsblk` like log that shows the information for all available block devices
=> image: verbose debugging options

.github/actions/constellation_create/action.yml, .github/workflows/e2e-test-manual.yml, .github/workflows/e2e-test-weekly.yml, .github/workflows/release.yml, internal/versions/versions.go
- use renovate to update valid k8s versions. not sure if this will work. I copied the comment from the `ClusterVersion` field.
- go back to using MAJOR.MINOR format when specifying k8s version for CI jobs by utilizing `--kubernetes` flag
- Old: [702](https://github.com/edgelesssys/constellation/actions/runs/4280805120): specified "1.25" as workflow input. shows "1.25" in config. CLI automatically extends patch version as a compatibility feature for v2.6.
- [704](https://github.com/edgelesssys/constellation/actions/runs/4281000433/jobs/7454445191): specified "1.24" as workflow input. shows "1.24.10" in config, since `--kubernetes` was used to automatically extend patch version.
=> versions: use renovate to update valid k8s versions

image/Makefile, image/mkosi.files/mkosi.azure.conf
- Use Linux 6.1.14 for Azure
Still doesn't contain a backported version of the MTRR revert commit included with 6.2.0, so we can still take "the latest and greatest" patch release in before the upcoming release.
=> image: update to Linux 6.1.14 for Azure

cli/internal/cloudcmd/upgrade.go, cli/internal/cloudcmd/upgrade_test.go, cli/internal/cmd/upgradeapply.go, cli/internal/helm/client.go, cli/internal/helm/client_test.go, internal/compatibility/compatibility.go
- Handle invalid upgrade errors similarly as for images and k8s.
=> cli: handle invalid upgrades for microservice consistently

docs/docs/architecture/orchestration.md, docs/docs/getting-started/first-steps.md, docs/docs/reference/terraform.md, docs/docs/workflows/config.md, docs/docs/workflows/create.md, docs/docs/workflows/terminate.md, docs/sidebars.js
- Our docs featured multiple references to Terraform state files, using Terraform, etc. This PR should add a general documentation page on how Terraform is being used by Constellation to manage cloud resources as stated [here](https://dev.azure.com/Edgeless/Edgeless/_workitems/edit/2935/). This includes:
- Instructions on interacting with Terraform state manually 
- Instructions on how and where to keep Terraform state files
=> docs: add docs on general Terraform usage

cli/internal/terraform/terraform/openstack/main.tf, cli/internal/terraform/terraform/openstack/modules/instance_group/main.tf, cli/internal/terraform/terraform/openstack/modules/instance_group/variables.tf
- cli: set constellation uid and role as instance metadata of OpenStack  instances
=> cli: set constellation uid and role as instance metadata of OpenStack  instances

CMakeLists.txt, Dockerfile.build, bootstrapper/cmd/bootstrapper/run.go, cli/internal/cmd/configfetchmeasurements_test.go, cli/internal/cmd/upgradecheck.go, cli/internal/cmd/upgradecheck_test.go, cli/internal/cmd/version.go, cli/internal/cmd/version_test.go, cli/internal/helm/client.go, cli/internal/helm/loader.go, disk-mapper/cmd/main.go, internal/compatibility/compatibility.go, internal/compatibility/compatibility_test.go, internal/config/config.go, internal/config/validation.go, internal/config/validation_test.go, internal/constants/constants.go, internal/semver/semver.go, joinservice/Dockerfile, joinservice/cmd/main.go, keyservice/Dockerfile, keyservice/cmd/main.go, verify/Dockerfile, verify/cmd/main.go
The variable VersionInfo is supposed to be set by `go build -X ...` during link time but should not be modified at runtime. This change ensures the underlying var is private and can only be accessed by a public getter.
- constants: make VersionInfo readonly
=> constants: make VersionInfo readonly

cli/internal/cmd/iamcreate.go
- Allow constellation-conf.yaml to exist when --generate-config is not set
- Fix the check itself: the stat check checks against the _constant_, but the config path is a possibly dynamic flag
Technically Go error strings are also kinda inconvenient to give actionable advice (due to capitalitation rules and the rule that they are not supposed to end with punctation), but let's not change this as part of this PR since there are also other parts in the code where we already do this.
=> cli: allow existing config for IAM creation without --generate-config

3rdparty/bazel/org_openssl/openssl_repositories.bzl
(This PR merges into the Bazel branch, not main)
- Update Perl for macOS & Linux arm64
Compared to yesterday's use of release version, I bumped it to the latest main so it also has support for Linux arm64 building (which I haven't tried yet at all - I trust them on this).
Still the remaining issues seem to be OpenSSL complaining about wrong ARM architecture and the Go race detector complaining about missing tsan definitions since we cross-compile tests. We can also handle this as a "add macOS / Linux arm64" support PR if you like a larger PR.
=> bazel: update Perl for macOS & Linux arm64

cli/internal/cmd/init_test.go, internal/attestation/aws/issuer.go, internal/attestation/aws/validator.go, internal/attestation/azure/snp/issuer.go, internal/attestation/azure/snp/validator.go, internal/attestation/gcp/issuer.go, internal/attestation/gcp/validator.go, internal/attestation/qemu/issuer.go, internal/attestation/qemu/validator.go, internal/oid/oid.go
- oid: add alternative string representations for attestation variants
This is the first part of a small refactor. aTLS Issuers/Validators should be selectable on a finer level than just the CSP. Adding this now simplifies adoption of more attestation variants in the future.
Next step is adding a kernel cmdline parameter indicating the wanted attestation variant using one of the string constants added here.
=> oid: add alternative string representations for attestation variants

image/mkosi.files/mkosi.aws.conf, image/mkosi.files/mkosi.azure.conf, image/mkosi.files/mkosi.gcp.conf, image/mkosi.files/mkosi.openstack.conf, image/mkosi.files/mkosi.qemu.conf, image/mkosi.skeleton/usr/lib/systemd/system/configure-constel-csp.service
- image: set attestation variant on kernel cmdline
Follow up for #1322. OS images should pass the desired attestation variant via the kernel cmdline. This is measured at boot and can be used in the future to select the aTLS Issuer/Validator.
=> image: set attestation variant on kernel cmdline

cli/internal/cmd/configgenerate.go, cli/internal/cmd/iamcreate.go, cli/internal/cmd/iamcreate_test.go
- Put K8s version parsing logic into an own function in configgenerate.go
- Add `--kubernetes` as a separate flag for IAM create using the new function (only respected when `--generate-config` is set)
This is mainly here to get both "config generate" and "iam create --generate-config" on feature parity. After v2.6.0, I hope we can refactor this a bit more to unify both config generation functions.
=> cli: add `--kubernetes` flag to `iam create` (when used with `--create-config`)

cli/internal/cloudcmd/clients.go, cli/internal/cloudcmd/upgrade.go, cli/internal/cloudcmd/upgrade_test.go, cli/internal/cmd/upgradeapply.go, cli/internal/cmd/upgradeapply_test.go, cli/internal/helm/client.go, internal/compatibility/compatibility.go
- Applies the updated NodeVersion object with one request instead of two. This makes sure that the first request does not accidentially put the cluster into a "updgrade in progress" status. Which would lead users to having to run apply twice.
- Testing manually
=> cli: restructure `upgrade apply` to change NodeVersion in one request

cli/internal/cmd/init.go
This is a measure to detect cases where an aTLS handshake is performed but the long running call is interrupted, leading to a retry of the init call. Whenever the grpc connection state reaches ready, we know that the aTLS handshake has succeeded:
> READY: The channel has successfully established a connection all the way through TLS handshake (or equivalent) and protocol-level (HTTP/2, etc) handshaking, and all subsequent attempt to communicate have succeeded (or are pending without any known failure).
- cli: log grpc connection state for init call
Logs look like this:
```
[...]
2023-03-02T12:27:18+01:00       DEBUG   cmd/init.go:181 Sending initialization request
2023-03-02T12:27:18+01:00       DEBUG   cmd/init.go:217 Making initialization call, doer is &{dialer:0xc0012e09c0 …
```
=> cli: log grpc connection state for init call

.github/actions/e2e_benchmark/evaluate/parse.py
- Change the timestamp format in the benchmark results sent to opensearch
- Allows Open search to parse and display the value correctly
=> ci: set timestamp format correctly for opensearch

cli/internal/libvirt/Dockerfile
- cli: upgrade libtpms in libvirt container
I tested this locally and it works (mini constellation still works and the container includes a fixed version of libtpms).
We also need to rebuild and bump the image in versions.go before the release @derpsteb
=> cli: upgrade libtpms in libvirt container

internal/versions/versions.go
The libvirt container is currently not automatically upgraded (it still had version v2.2.0 before this change). To ensure we update libvirt for this release, we manually upgrade the libvirt container image.
- deps: manually upgrade libvirt container for upcoming release
- #1338
- https://kb.cert.org/vuls/id/782720
We can either merge this into main before creating the release branch or cherry pick this into the release branch.
=> deps: manually upgrade libvirt container for upcoming release

.github/actions/e2e_benchmark/evaluate/evaluators/fio.py, .github/actions/e2e_benchmark/evaluate/evaluators/knb.py
- Store MTU and volume size as part of the benchmark results
- Fix typo in udp fields
=> ci: store additional data in bench results

.github/actions/e2e_test/action.yml
- ci: move aws iam create test to less utilized zone
- https://github.com/edgelesssys/constellation/actions/runs/4345520863/jobs/7602473882
The zone `eu-central-1a` is often at capacity when it comes to our requested instance type. To reduce the failure rate of e2e tests, move tests to a different zone instead.
Error from terraform:
```
Error: waiting for Auto Scaling Group (constell-e5aec073-worker) capacity satisfied: 1 error occurred:
* Scaling activity (f8e61aea-c168-31a4-af97-3460028473c3): Failed: We currently do not have sufficient m6a.xlarge capacity in the Availability Zone you requested (eu-central-1a). Our system will be working on provisioning additional capacity. You can currently get m6a.xlarge capacity by not specifying an Availability Zone in your request or choosing …
```
=> ci: move aws iam create test to less utilized zone

image/mkosi.conf.d/secure-boot-tpm.conf
- image: add systemd-boot as explicit dependency
Fedora's systemd package now does not bundle systemd-boot anymore, so we have to install it explicitly: https://bodhi.fedoraproject.org/updates/FEDORA-2023-f72fbc711a.
[Testrun](https://github.com/edgelesssys/constellation/actions/runs/4352383126)
Otherwise, `bootctl install` will fail:
```
‣    Installing boot loader…
Failed to open "/usr/lib/systemd/boot/efi": No such file or directory
```
=> image: add systemd-boot as explicit dependency

image/Makefile, image/mkosi.conf.d/mkosi.conf, image/mkosi.conf.d/secure-boot-tpm.conf, image/mkosi.files/mkosi.aws.conf, image/mkosi.files/mkosi.azure.conf, image/mkosi.files/mkosi.gcp.conf, image/mkosi.files/mkosi.openstack.conf, image/mkosi.files/mkosi.qemu.conf
We are noticing issues with dns on systemd 251.13. Downgrading systemd for now.
- image: downgrade systemd to 251.11-2
- [Build pipeline](https://github.com/edgelesssys/constellation/actions/runs/4362258906)
- [e2e on azure](https://github.com/edgelesssys/constellation/actions/runs/4362759101)
=> image: downgrade systemd to 251.11-2

renovate.json
- Currently, renovate suggests updating transitive dependencies to next minor version, which is never wanted in Go.
=> renovate: disable major updates of transitive deps

bootstrapper/cmd/bootstrapper/main.go, disk-mapper/cmd/main.go, internal/attestation/azure/azure.go, internal/attestation/choose/choose.go, internal/attestation/choose/choose_test.go, internal/constants/constants.go, verify/cmd/main.go
- Instead of relying on just the Cloud Provider to identify what Attestation Issuer we need to set up, we now use information from the Kernel command line to do so
- Add `choose.Issuer()` and `choose.Validator()` utility functions to create Issuer or Validator from a given oid
- Set up of Issuer for the VerifyService will be handled in a different PR
- Dynamic creation of Validators using `choose.Validator()` will be handled in a different PR
=> attestation: create issuer based on kernel cmd line

CMakeLists.txt, Dockerfile.build, image/Makefile, image/mkosi.conf.d/secure-boot-tpm.conf, image/mkosi.skeleton/usr/lib/systemd/system-preset/30-constellation.preset, image/mkosi.skeleton/usr/lib/systemd/system/measurements.service, image/mkosi.skeleton/usr/libexec/constellation-pcrs, internal/oid/oid.go, measurement-reader/cmd/main.go, measurement-reader/internal/sorted/sorted.go, measurement-reader/internal/tpm/tpm.go, measurement-reader/internal/tpm/tpm_test.go
Add a measurement reader to replace `tpm2_pcrread` during boot.
This tool is supposed to be easily extendable for different measurement and attestation variants
- Tested locally on QEMU
=> Add measurement-reader tool

internal/constants/enterprise.go
=> constants: use "Enterprise" for enterprise build in "constellation version"

image/Makefile, image/mkosi.files/mkosi.azure.conf, image/mkosi.files/mkosi.gcp.conf
- Update Azure & GCP kernel to 6.1.18
6.1.18 contains the [backport for the GCP disk fix](https://lore.kernel.org/all/20230310133720.407990040@linuxfoundation.org/) we reported, so we can finally get away from EOL 5.19.
The kernel also does not contain yet the backport of the MTRR fix revert that breaks Azure disks again. Wonder if this will ever happen with kernel 6.1, but 6.2 will be broken again I presume.
=> image: update Azure and GCP to kernel 6.1.18

debugd/internal/debugd/logcollector/filebeat/Dockerfile, debugd/internal/debugd/logcollector/logstash/Dockerfile, debugd/internal/debugd/logcollector/logstash/config/logstash.yml
- Enable ordered logs in Logstash
Currently, our log output in OpenSearch is not ordered even when ordered by timestamp. This makes browsing through the logs a bit tiresome and confusing as it makes it sometimes difficult to see on a glance what happened in our cluster.
This is theoretically a performance bottleneck since we need to downgrade to single-threaded log processing to use this: https://www.elastic.co/guide/en/logstash/8.6/processing.html#order-setting
However, given that each node has its own Logstash instance, I think this should be fine.
- Update Filebeat to 8.6.2
- Update Logstash to 8.6.1 (yes, not 8.6.2 because OpenSearch does not seem to ship their bundle with 8.6.2 for whatever reason).
=> debugd: Enable ordered logs in Logstash (+ update Filebeat/Logstash)

BUILD.bazel, CODEOWNERS, bazel/ci/BUILD.bazel, bazel/devbuild/BUILD.bazel, bazel/devbuild/prepare_developer_workspace.sh.in, cli/BUILD.bazel, debugd/cmd/cdbg/BUILD.bazel, dev-docs/workflows/build-test-run.md
This command symlinks all binaries into the current working directory (or the path specified by the first argument).
You can run this command repeatedly to ensure the symlinks point to up-to-date binaries.
This should simplify the development workflow!
I'm not sure about the name `devbuild`. Feel free to suggest other names.
- bazel: command to prepare development workspace
Usage:
```shell-session
mkdir my-constellation-workspace && cd my-constellation-workspace
bazel run //:devbuild
./constellation create ......
```
=> bazel: command to prepare development workspace

.github/workflows/build-binaries.yml, .github/workflows/release-cli.yml
- ci: remove Go setup steps where Bezel is used for building
Should not be needed anymore when Bazel sets up its own Go toolchain.
=> ci: remove Go setup where Bazel is used for building

WORKSPACE.bazel, bazel/toolchains/oci_deps.bzl
Release: https://github.com/bazel-contrib/rules_oci/releases/tag/v0.3.3
- deps: upgrade rules_oci to v0.3.3
=> deps: upgrade rules_oci to v0.3.3

.github/actions/constellation_create/action.yml, bootstrapper/internal/helm/helm.go, bootstrapper/internal/kubernetes/k8sapi/k8sutil.go, bootstrapper/internal/kubernetes/k8sutil.go, bootstrapper/internal/kubernetes/kubernetes.go, bootstrapper/internal/kubernetes/kubernetes_test.go
- Split FixCilium into WaitForCilium and FixCilium
- Put both directly after Cilium installation so we have a distinct error when Cilium doesn't come up instead of having the same cert-manager context deadline exceeded error
- Set a timeout for 20 minutes for WaitForCilium (pulling can sometimes be slow with ghcr.io - in local testing the worst case was ~16 minutes occasionally) -> This should likely be reduced after the next Cilium update when/if we switch repositories that have more consistent performance.
- Set a timeout for 10 minutes for Helm install instead of 5 minutes (cert-manager can sometimes take longer)
- Track duration of Cilium and cert-manager install (since both can stall)
- Minor fixes
Generally, the issue is the following:
- We try to install too many things at once …
=> bootstrapper: try to mitigate timeout issues

.bazelrc, CMakeLists.txt, bazel/devbuild/BUILD.bazel, bazel/go/platform.bzl, bootstrapper/cmd/bootstrapper/BUILD.bazel, debugd/cmd/debugd/BUILD.bazel, disk-mapper/cmd/BUILD.bazel, measurement-reader/cmd/BUILD.bazel, upgrade-agent/cmd/BUILD.bazel
- bazel: use host platform by default
When using `bazel run` on hosts that are not linux amd64, we would select tools that are incompatible to the host arch / host os.
Now we don't set a static target platform anymore. Instead, we add targets to build some go binaries explicitly for linux amd64.
=> bazel: use host platform by default

.github/workflows/build-os-image.yml
- ci: disable upload of Azure TrustedLaunch image
- [image build](https://github.com/edgelesssys/constellation/actions/runs/4445324692)
- TrustedLaunch image upload fails. This is probably due to a change in the API on Azure's side
=> ci: disable upload of Azure TrustedLaunch image

cli/internal/cloudcmd/create.go, cli/internal/cloudcmd/iam.go, cli/internal/cloudcmd/rollback.go
rollbackOnError must not be called with the ctx of the to-be-rollbacked action, so we shouldn't allow to pass a (wrong) context in.
=> cli: remove ctx parameter from rollbackOnError to prevent wrong use

.github/actions/e2e_test/action.yml, .github/workflows/e2e-test-manual.yml
- Remove Ubuntu + cache build steps for macOS e2e test
Shouldn't be required anymore as we use Bazel and we can now cross-compile correctly.
=> e2e: Remove Ubuntu builder for debug artifacts required for macOS runner

cli/internal/helm/client.go, cli/internal/helm/client_test.go, cli/internal/helm/loader.go, cli/internal/helm/loader_test.go
- Upgrade apply creates local backups of all CRDs and CRs to recover from faulty microservice upgrades. Previously these backups were created during `upgrade apply` even if no service upgrades were executed. Now they are only created if at least one service is upgraded. To allow for this change some restructuring was necessary:
- new chartInfo type that holds release name, path and chart name
- upgrade execution and version validity are checked separately
=> cli: only create resource backups if upgrade is executed

.bazelrc, .github/actions/build_bootstrapper/action.yml, .github/actions/build_cdbg/action.yml, .github/actions/build_cli/action.yml, .github/actions/build_debugd/action.yml, .github/actions/build_disk_mapper/action.yml, .github/actions/build_measurement_reader/action.yml, .github/actions/build_upgrade_agent/action.yml, .github/actions/e2e_mini/action.yml, .github/actions/e2e_test/action.yml, .github/actions/setup_bazel/action.yml, .github/workflows/build-binaries.yml, .github/workflows/build-os-image.yml, .github/workflows/e2e-mini.yml, .github/workflows/e2e-test-daily.yml, .github/workflows/e2e-test-manual.yml, .github/workflows/e2e-test-weekly.yml, .github/workflows/release-cli.yml, dev-docs/workflows/build-test-run.md, tools/workspace_status.sh
This is one step of improving build speeds with Bazel.
The other effort is caching toolchains, external dependencies and build outputs in github actions itself.
- bazel: use remote caching
- ci: cleanup go build steps
- [build binaries](https://github.com/edgelesssys/constellation/actions/runs/4466606733)
- [e2e test from linux runner](https://github.com/edgelesssys/constellation/actions/runs/4466697502)
- [e2e test from macOS runner](https://github.com/edgelesssys/constellation/actions/runs/4466823075)
=> bazel: use remote caching

cli/internal/terraform/terraform/azure/main.tf
- Fix [bug in attestation provider naming](https://github.com/edgelesssys/constellation/actions/runs/4469849456/jobs/7852552415#step:9:1089), introduced in #1375
- e2e test run, Kubernetes 1.25, nop: https://github.com/edgelesssys/constellation/actions/runs/4470212067
=> terraform: valid Azure attestation provider name

.github/actions/setup_bazel/action.yml, .github/workflows/warm-bazel-cache.yml
- ci: use github actions cache to speedup bazel build
- [run with empty cache](https://github.com/edgelesssys/constellation/actions/runs/4446625524) 11m15s
- [run with repo cache (but without remote cache)](https://github.com/edgelesssys/constellation/actions/runs/4446715094) 7m36s
- [run with repo cache and remote cache](https://github.com/edgelesssys/constellation/actions/runs/4468366094) 3m20s
- <strike>The github actions cache alone is a smaller improvement than I was hoping for. GitHub only allows uploading things to the cache if the cache key doesn't exist yet. We would want to merge the existing cache with new builds to get amazing speedups. See also: https://github.com/actions/cache/issues/342</strike>
- Combining caches and using a separate workflow to warm up the cache did the …
=> ci: use github actions cache to speedup bazel builds

debugd/internal/debugd/logcollector/logstash/templates/pipeline.conf
- Use a very basic JSON regex check before the mutation pipeline
The documentation for `skip_on_invalid_json` states:
>Allows for skipping the filter on invalid JSON (this allows you to handle JSON and non-JSON data without warnings)
Unfortunately, skipping the filter only seems to apply [to the json block itself](https://discuss.elastic.co/t/skip-on-invalid-json-skipping-all-filters/215195), and not the whole filter.
This means that if anything goes wrong inside the bootstrapper (fatal error/panic) and non-JSON output is dumped into the pipeline, our message will just be replaced with `%{[logs][msg]}"`. This of course makes it impossible to see the actual panic or fatal error, rendering this whole logging kinda useless.
This PR adds a [very …
=> debugd: Use very basic JSON regex filter before JSON filter

cli/internal/terraform/terraform/azure/main.tf
- While #1465 made the name valid, is also has to be unique. The name should use local.name instead of var.name, as first contains the uid.
- [`Attestation Provider Name: "e2etestap"): attestationproviders.AttestationProvidersClient#Create: Failure sending request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="DuplicateTenant" Message="The given service URI 'e2etestap' is already in use. Please try again with a different name."`](https://github.com/edgelesssys/constellation/actions/runs/4471281390/jobs/7855959048#step:9:929)
=> terraform: unique Azure attestation provider name

WORKSPACE.bazel, bazel/toolchains/zig_cc_deps.bzl
Apply https://github.com/uber/bazel-zig-cc/pull/23 to see if it resolves flaky `SIGILL` emitted by bazel-zig-cc launcher when using Bazel's remote caching feature.
- https://github.com/edgelesssys/constellation/actions/runs/4477922647/jobs/7870052736?pr=1464#step:4:68
- https://github.com/uber/bazel-zig-cc/issues/22
=> bazel: upgrade bazel-zig-cc to allow caching of launcher

.github/workflows/build-os-image-scheduled.yml
Super minor change so both OS build image actions don't have exactly the same name in the Actions list.
=> ci: rename scheduled OS image build action

.github/workflows/e2e-test-manual.yml
- Install Terraform in macOS e2e test runner
The GitHub Ubuntu runner has Terraform preinstalled, the macOS doesn't. This breaks downloading boot logs for AWS or GCP. This doesn't fail the e2e test, but it would be cool to have the logs for debugging any issues occurring when doing an macOS test run.
=> e2e: install Terraform for macOS runner for boot log collection

cli/internal/cloudcmd/upgrade.go, cli/internal/cloudcmd/upgrade_test.go
- This fixes a bug where `upgrade apply` fails if only the image version is upgraded. This is due to mishandling of an empty configmap. This is a bug that is only located within the CLI and does not affect the cluster's ability to upgrade.
=> cli: fix `upgrade apply` for image-only upgrades

WORKSPACE.bazel, bazel/toolchains/zig_cc_deps.bzl, cli/internal/cloudcmd/BUILD.bazel, cli/internal/cloudcmd/validators.go, cli/internal/cloudcmd/validators_test.go, cli/internal/cmd/init.go, cli/internal/cmd/init_test.go, cli/internal/cmd/recover.go, cli/internal/cmd/verify.go, internal/config/validation.go, internal/oid/oid.go, internal/versions/versions.go
- Plenty of bug fixes regarding QEMU TDX when selecting the attestation variant
- Refactor the cloudcmd validator to remove most mentions of PCRs unless we actually talk about PCRs (to generalize for TPM & TDX measurements)
- Add `constellation verify` support for TDX
Plus one cherry-pick commits to get Bazel to work since the Zig toolchain couldn't be downloaded anymore from the URL and I don't want to rebase this to the current main branch yet. Gotta love this toolchain :/
=> cli: add verify support for TDX (and various refactors + fixes regarding attesation variants for TDX)

cli/internal/cmd/upgradeapply.go, docs/docs/workflows/upgrade.md
- The constellation-operator currently doesn't support the necessary operations for node upgrades on AWS, OpenStack and QEMU. Previously `upgrade apply` just executed on the aforementioned CSPs, no error reported. However, the nodes never successfully upgraded. Now the CLI prints a warning and does not apply any upgrades.
- Mention support in the docs.
- Ran [e2e-upgrade test on azure](https://github.com/edgelesssys/constellation/actions/runs/4509186713/jobs/7939036115) to see that the upgrade is still correctly triggered. Manually initiated an upgrade for an AWS cluster and go this output:
```
$ ./build/constellation upgrade apply --debug
WARNING: the config key `attestationVariant` is not set. This key will be required in the next version.
WARNING: Skipping service & image upgrades. …
```
=> cli: warn about missing support for upgrades on AWS, OpenStack, QEMU

.github/workflows/build-os-image.yml
- This value can't be statically precomputed. 
- This solves #1411.
=> ci: fix PCR5 warnings on GCP by not statically setting it

dev-docs/workflows/release.md
- Minor addition to release docs for errors like:
```
Fetching measurements from https://cdn.confidential.cloud/constellation/v1/ref/-/stream/stable/v2.6.1/image/csp/aws/measurements.json and signature from https://cdn.confidential.cloud/constellation/v1/ref/-/stream/stable/v2.6.1/image/csp/aws/measurements.json.sig
panic: unable to verify signature: invalid signature when validating ASN.1 encoded signature [recovered]
panic: unable to verify signature: invalid signature when validating ASN.1 encoded signature
```
=> docs: add CDN cache invalidation to release docs

bootstrapper/internal/kubernetes/k8sapi/k8sutil.go
See title. Minor bug fix I noticed while debugging.
Otherwise this loop will continue even if the context is cancelled.
=> bootstrapper: return error on context cancel in WaitForCilium

cli/internal/cloudcmd/create.go, cli/internal/cloudcmd/create_test.go, cli/internal/cmd/create.go, cli/internal/image/BUILD.bazel, cli/internal/image/image.go, cli/internal/image/image_test.go, internal/config/config.go, internal/config/config_doc.go, internal/config/validation.go, internal/config/validation_test.go
- Remove usage of `confidentialVM` option in Azure provider config in favor of using `attestationVariant`
- `confidentialVM` has been marked as deprecated, setting it has no effect but will print a warning about future removal
- Should be merged to main after https://github.com/edgelesssys/constellation/pull/1538
=> config: deprecate confidentialVM option for Azure clusters in favor of using attestationVariant option 

internal/versionsapi/cli/rm.go
- Split GCP image URI to extract the image name from the information in image.json in the versionsapi CLI
Currently, image are not purged correctly on GCP:
https://github.com/edgelesssys/constellation/actions/runs/4481677681/jobs/7878710834#step:9:113
This is since our info.json encodes the image URI like this:
`projects/constellation-images/global/images/v2-6-0-stable`
But `computepb.DeleteImageRequest` expects only the name of the image, since `g.compute.Delete` does build the image URL by itself using the parameters given in `computepb.DeleteImageRequest`.
So let's split the string before.
I am giving this a quick test before merging by building an OS image that can be safely deleted: https://github.com/edgelesssys/constellation/actions/runs/4482202814 
(No special input validation …
=> versionsapi: Split GCP image URI to extract the image name

.github/workflows/e2e-test-weekly.yml
- fromVersion input was not set correctly. The string is put into the curl command without any processing.
- [Successful run](https://github.com/edgelesssys/constellation/actions/runs/4532924648) :green_circle:. At least the upgrade jobs.
=> ci: set correct fromVersion for upgrade test in weekly e2e job

docs/docs/getting-started/install.md, docs/docs/workflows/config.md, docs/styles/Vocab/constellation/accept.txt
- List the minimal permissions to be able to execute the `constellation iam` commands (`iam create` & `iam destroy`) for each CSP.
=> docs: list minimal permissions for Constellation setup

cli/internal/cmd/BUILD.bazel, cli/internal/cmd/configgenerate.go, cli/internal/cmd/configgenerate_test.go, cli/internal/cmd/create.go, internal/config/config.go, internal/config/config_doc.go, internal/config/config_test.go, internal/config/validation.go
- Remove `upgradeConfig`  from config
- This field was only partially functional in v2.5.0 and has been deprecated in v2.6.0
- Setting it in v2.7.0 will return an error
- Require `name` field
- Was optional in v2.6.0 with a warning for it to be required in the next version
- Required `microserviceVersion` field
- This field was optional in v2.6.0
- There was no hint about it being required in future versions, we might want to consider keeping it optional in v2.7.0 with a warning
- Removed a warning about unset `attestationVariant` field
- This field was not yet present in v2.6.0
- ~This field will be superseded in v2.8.0 by the `attestation` struct, as outlined in https://github.com/edgelesssys/constellation/pull/1436 and therefore won't throw a warning for not being set~
- The value is …
=> config: remove deprecated upgradeConfig and require name and microserviceVersion fields

internal/semver/semver.go, internal/semver/semver_test.go
- Add support for `v.1.19.2-pre`-type pseudoversions in the semver package as specified in the [semver standard](https://semver.org/).
- Prerelease-info is being put to respect when comparing semvers.
- [AB#3017](https://dev.azure.com/Edgeless/Edgeless/_workitems/edit/3017/)
- Implementation using `strings.Contains` is probably not perfect, but I didn't found a way to nicely scan for "optional" characters with just `fmt.Sscanf`. Maybe Regex would be the next best option if the strings check is not appropriate.
=> internal: semver support for pseudoversions

.github/actions/build_cli/action.yml, .github/actions/constellation_create/action.yml, .github/actions/select_image/action.yml, .github/workflows/e2e-mini.yml, .github/workflows/e2e-test-daily.yml, .github/workflows/e2e-test-release.yml, .github/workflows/e2e-upgrade.yml, .github/workflows/release.yml
- The new workflow is used to run e2e tests in preparation for a release.
- The new workflow is triggered by the successful completion of the release workflow. Unfortunately, as far as I understand, this mechanism can only be tested once merged to main [1]. I will test correct triggering as soon as this is merged and revert the commit if required.
- Use the same trigger mechanism for e2e-mini
- Remove e2e-mini and e2e-test-daily calls from release pipeline
- Reduced the number of parallel runs in e2e-test-weekly by one as I did not do that when adding the upgrade tests
- The renaming of release-stable/main-debug is there from an earlier version of this PR. It seemed easier to keep it.
- The executed tests for e2e-test-release are the same as e2e-test-weekly, with the exception that lb …
=> ci: add e2e-test-release workflow

renovate.json
- ci: auto-group bazel deps by base name if os and arch differ
=> ci: auto-group bazel deps by base name if os and arch differ

renovate.json
- ci: match bazel deps using packageName template parameter
- `"depName": "com_github_bufbuild_buf_linux_amd64"`
- `"packageName": "bufbuild/buf"`
- We can simply group by packageName in a single rule
=> ci: match bazel deps using packageName template parameter

.github/workflows/e2e-test-release.yml
- The `needs` key skips the tests if the trigger was successful. Remove it to get the correct behavior.
=> ci: do not skip e2e-weekly if trigger is successful

cli/internal/cmd/init.go, internal/cloud/azure/azure.go, internal/cloud/azure/azure_test.go, internal/cloud/azureshared/appcredentials.go, internal/cloud/azureshared/appcredentials_test.go
- If one chooses to use UAMI for in-cluster auth, we translate the UAMI resource ID form the config to it's client ID via listing all UAMIs assinged to the current VM.
=> azure: convert uami resource ID to clientID

bootstrapper/internal/journald/BUILD.bazel, bootstrapper/internal/journald/journald.go, bootstrapper/internal/journald/journald_test.go
- let the journald package return a pipe to the stdout of the journalctl command instead of it's output to prevent killing the process due to high RAM usage
=> bootstrapper: fix journald ram usage

cli/internal/cmd/BUILD.bazel, cli/internal/cmd/upgradecheck.go, cli/internal/cmd/upgradecheck_test.go, hack/clidocgen/BUILD.bazel, internal/versionsapi/cliinfo.go
- Add listing of valid CLI version upgrades with the `upgrade check` command
-  Upgrade is considered valid if 1) compatible with current K8s version and 2) semver is greater and has at most 1 minor version drift
- Uploading of CLI version lists and compatibility information was done in #1218 & #1377 
- Possible follow-ups
- Upgrade check command is in (urgent) need of a refactoring. Files are very large. See [this AB ticket.](https://dev.azure.com/Edgeless/Edgeless/_workitems/edit/2957/)
- Custom version type should be used eventually. See [this AB ticket](https://dev.azure.com/Edgeless/Edgeless/_workitems/edit/2956/).
Output of `constellation upgrade check` looks like:
```
The following updates are available with this CLI:
Kubernetes: v1.25.7 --> v1.26.2
CLI: v2.5.0 --> …
```
=> cli: show available cli upgrades on upgrade check command

cli/internal/cmd/verify.go, cli/internal/cmd/verify_test.go, docs/docs/reference/cli.md, hack/clidocgen/BUILD.bazel
- Show attestation info when using `constellation verify` for attestation / verification demo purposes
- Particularly the following:  
- Cluster endpoint (All CSPs)
- Expected / Actual PCR comparison (All CSPs)
- VCEK certificate (Azure only)
- Certificate chain (Azure only)
Example output for Azure:
```
Using endpoint from "constellation-id.json". Specify --node-endpoint to override this.
Using ID from "constellation-id.json". Specify --cluster-id to override this.
WARNING: the config key `attestationVariant` is not set. This key will be required in the next version.
WARNING: The config key "confidentialVM" is deprecated and will be removed in an upcoming version.
Warning: Encountered untrusted PCR value at index 5
Attestation Document:
Quote:
PCR 3 (Strict: false):
Expected: …
```
=> cli: print attestation document with constellation verify

.github/workflows/e2e-test-release.yml
- only run two tests on macOS as a simple smoketest
- Example from docs: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#example-adding-configurations
=> ci: do not run most release tests on macOS

.github/workflows/test-tidy.yml, CODEOWNERS, bazel/ci/BUILD.bazel, hack/bazel-deps-mirror/BUILD.bazel, hack/bazel-deps-mirror/bazel-deps-mirror.go, hack/bazel-deps-mirror/check.go, hack/bazel-deps-mirror/fix.go, hack/bazel-deps-mirror/internal/mirror/BUILD.bazel, hack/bazel-deps-mirror/internal/mirror/mirror.go, hack/bazel-deps-mirror/internal/mirror/mirror_test.go, hack/bazel-deps-mirror/internal/rules/rules.go, hack/bazel-deps-mirror/internal/rules/rules_test.go, hack/bazel-deps-mirror/upgrade.go
This command can be used to upgrade a dependency.
Users are supposed to replace any upstream URLs and run the upgrade command. It replaces the expected hash and uploads the new dep to the mirror.
- bazel-deps-mirror: upgrade command
- bazel-deps-mirror: improve fix command to add hash if missing
=> bazel-deps-mirror: upgrade command

.github/actions/constellation_create/action.yml, .github/actions/constellation_iam_destroy/action.yml, .github/actions/e2e_test/action.yml, .github/workflows/e2e-test-daily.yml, .github/workflows/e2e-test-manual.yml, .github/workflows/e2e-test-release.yml, .github/workflows/e2e-test-weekly.yml, .github/workflows/e2e-upgrade.yml
- Use the minimal e2e permissions (documented in #1442) in the e2e tests to be aligned with documentation and notice changes in permission requirements at test time.
- e2e permissions are now managed in [edgeless-iam](https://github.com/edgelesssys/edgeless-iam/tree/feat/seperate-iam-accounts)
- Use [ad-hoc IAM creation](https://docs.edgeless.systems/constellation/workflows/config#creating-an-iam-configuration) (the way we recommend to users in the docs) for all CSPs, including Azure. With that, manual resource group creation / deletion is obsolote.
- [Manual e2e test: AWS](https://github.com/edgelesssys/constellation/actions/runs/4561618154/jobs/8047791821)
- [Manual e2e test: Azure](https://github.com/edgelesssys/constellation/actions/runs/4561611430/jobs/8047775473)
- [Manual e2e test: …
=> ci: separate e2e permissions

.github/workflows/e2e-upgrade.yml, cli/internal/kubernetes/upgrade.go, cli/internal/kubernetes/upgrade_test.go, e2e/internal/upgrade/BUILD.bazel, e2e/internal/upgrade/image.go, e2e/internal/upgrade/upgrade_test.go, internal/attestation/measurements/measurements.go
- Currently `upgrade apply` will show a misleading error message when the config specifies an invalid image upgrade and a valid Kubernetes upgrade. In that case the upgrade is applied as expected. However, the CLI prints an error like this: `Error: upgrading NodeVersion: expected NodeVersion to contain <new image reference>, got <current image reference>`. This patch fixes the check.
- Add unittest to check the errors are actually triggered if apply responds with an unexpected message
- Do not verify measurements during e2e test. If we are upgrading to release images we can't verify the release signatures with the dev pub key in the CLI.
- Test run: [GCP, 1+1, 2.6 --> main](https://github.com/edgelesssys/constellation/actions/runs/4687145738/jobs/8306066558) :green_circle:. Executes only …
=> cli: fix misleading error while applying kubernetes-only upgrade

.github/workflows/e2e-upgrade.yml
- Remove Azure IAM env variables which overwrote the manual login during the nop e2e test
https://github.com/edgelesssys/constellation/actions/runs/4722011989
Previously it failed before that in `constellation iam create`: https://github.com/edgelesssys/constellation/actions/runs/4721824293/jobs/8375569054
=> ci: don't set IAM env for Azure

cli/internal/cmd/iamdestroy.go, cli/internal/terraform/terraform/azure/main.tf, cli/internal/terraform/terraform/iam/azure/main.tf, docs/docs/workflows/config.md
- Disable the [`prevent_deletion_if_contains_resources`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/features-block) of the Azure Terraform provider. This fixes the issues created by the failure anomaly detector. This can be changed once the [issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/18026) gets addressed by Microsoft.
- Add docs on the behaviour in the case of additional resources being added manually into the resource group (they are also deleted by `constellation iam destroy`)
- [Successful run ](https://github.com/edgelesssys/constellation/actions/runs/4720646803/jobs/8372948576)
=> cli: force-delete Azure resource group

cli/internal/helm/charts/edgeless/constellation-services/charts/azuredisk-csi-driver/Chart.yaml, cli/internal/helm/charts/edgeless/constellation-services/charts/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml, cli/internal/helm/charts/edgeless/constellation-services/charts/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml, cli/internal/helm/charts/edgeless/constellation-services/charts/azuredisk-csi-driver/values.yaml, cli/internal/helm/charts/edgeless/constellation-services/charts/gcp-compute-persistent-disk-csi-driver/Chart.yaml, cli/internal/helm/charts/edgeless/constellation-services/charts/gcp-compute-persistent-disk-csi-driver/templates/controller.yaml, cli/internal/helm/charts/edgeless/constellation-services/charts/gcp-compute-persistent-disk-csi-driver/templates/storageclass_default.yaml, cli/internal/helm/charts/edgeless/constellation-services/charts/gcp-compute-persistent-disk-csi-driver/values.yaml, cli/internal/helm/loader_test.go, cli/internal/helm/testdata/Azure/constellation-services/charts/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml, cli/internal/helm/testdata/Azure/constellation-services/charts/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml, cli/internal/helm/testdata/Azure/constellation-services/charts/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml, cli/internal/helm/testdata/Azure/constellation-services/charts/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml, cli/internal/helm/testdata/Azure/constellation-services/charts/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml, cli/internal/helm/testdata/Azure/constellation-services/charts/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml, cli/internal/helm/testdata/GCP/constellation-services/charts/gcp-compute-persistent-disk-csi-driver/templates/controller.yaml, cli/internal/helm/testdata/GCP/constellation-services/charts/gcp-compute-persistent-disk-csi-driver/templates/storageclass_default.yaml, cli/internal/helm/update-csi-charts.sh
Update CSI drivers to v1.2.0, which are based on v1.9.2 (GCP) and v1.27.1 (Azure) of their upstream counterparts.
This also enables cryptsetup read/write workqueue bypass in the drivers, which should speed up write and read speeds on encrypted disks
=> kubernetes: update CSI driver versions to v1.2.0

.github/actions/e2e_test/action.yml
- ci: login to container registry before pushing containers
- [e2e test run](https://github.com/edgelesssys/constellation/actions/runs/4763155001)
=> ci: login to container registry before pushing containers

.github/actions/e2e_test/action.yml, cli/internal/cmd/iamcreate.go
- ci: limit prefix length of AWS IAM resources
IAM create fails in the CI on AWS:
```
Error: expected length of name to be in the range (1 - 64), got e2e-4705664276-1-387ada92-9a16-40c1-8f35-adafacf04581_control_plane_role
```
So we have to shorten the prefix used for e2e tests.
=> ci: limit prefix length of AWS IAM resources

tools/workspace_status.sh
- Fix `bazel run ::/devbuild` on MacOS (aarch64) by:
- Allowing `arm64`arch
- Using the [`shasum`](https://www.linux.org/docs/man1/shasum.html) command, which should be available on Linux and MacOS systems
- Output:
```
➜  build git:(fix/bazel/darwin-builds) bazel run //:devbuild
INFO: Invocation ID: a025b43e-048c-4161-854a-b7d10fa3a17d
INFO: Analyzed target //:devbuild (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //bazel/devbuild:devbuild up-to-date:
bazel-bin/bazel/devbuild/devbuild-script.bash
bazel-bin/bazel/devbuild/devbuild
INFO: Elapsed time: 12.537s, Critical Path: 9.68s
INFO: 19 processes: 2 internal, 17 darwin-sandbox.
INFO: Build completed successfully, 19 total actions
INFO: Running command line: bazel-bin/bazel/devbuild/devbuild
```
=> bazel: fix MacOS builds

.github/actions/login_gcp/action.yml
- Set the env vars to empty before authenticating, so that the login doesn't throw a warning when doing repeated auth.
- Run without warings: https://github.com/edgelesssys/constellation/actions/runs/4817304142
=> ci: prevent google auth warnings when reauthenticating

.bazelrc, BUILD.bazel, bazel/oci/containers.bzl, bazel/oci/pin.bzl, bazel/release/BUILD.bazel, bazel/settings/BUILD.bazel, bazel/toolchains/oci_deps.bzl, bootstrapper/bootstrapper, cli/internal/helm/imageversion/BUILD.bazel, dev-docs/workflows/build-test-run.md, hack/oci-pin/codegen.go, hack/oci-pin/oci-pin.go, hack/oci-pin/sum.go, internal/config/imageversion/BUILD.bazel
- add `container_prefix` flag which where the container images of this build should be hosted.
- Automatically push the container images on `//:devbuild`
The container references in the CLI also use this value.
I'd also like to thank @malt3 for the support on this feature.
=> bazel: allow custom container_prefix

.github/actions/e2e_test/action.yml, .github/workflows/release-cli.yml
- ci: rename all usages of bazel push target from //:push to //bazel/release:push
CI would fail since it referenced an old alias for the push target that was since removed.
=> ci: rename all usages of bazel push target from //:push to //bazel/release:push

.github/actions/constellation_create/action.yml, .github/actions/constellation_destroy/action.yml, .github/actions/constellation_iam_create/action.yml, .github/actions/constellation_iam_destroy/action.yml, .github/workflows/e2e-upgrade.yml, cli/internal/helm/backup.go, cli/internal/helm/backup_test.go
- There might be cases in which a resource name is reused for multiple resources or across namespaces. In that case `upgrade apply` would fail while creating the local resource backups. This is because files are dumped into one folder with the resource name as file name. This is fixed by creating paths with this pattern: `constellation-upgrade/backups/<kind>/<namespace>/<name>.yaml`.
- [Azure, 1+1, microservice only, 2.7.0 -> 2.8.0-pre](https://github.com/edgelesssys/constellation/actions/runs/4830779572). Failure of the actual upgrade is expected. Needs #1649. But backups happen before upgrade is tried. No errors there.
=> cli: create namespaced folders for upgrade backups

image/measured-boot/precalculate_pcr_12.sh
- image: fix pcr 12 calculation
- Kernel cmdline embedded in UKIs had no null terminator before
- After upgrading mkosi in #1684, PCR12 would not match up with the precalculated value
- The UKI now contains a null-terminated version of the kernel commandline
=> image: fix pcr 12 calculation

image/measured-boot/precalculate_pcr_12.sh
Kernel cmdline embedded in UKIs had no null terminator before. With newer versions of mkosi, it is already null-terminated so we shouldn't null terminate it twice.
=> image: fix pcr 12 calculation (#1706)

.github/workflows/e2e-upgrade.yml, cli/internal/helm/BUILD.bazel, cli/internal/helm/client.go, cli/internal/helm/client_test.go, e2e/internal/upgrade/image.go, e2e/internal/upgrade/upgrade_test.go, hack/pseudo-version/pseudo-version.go
=> upgrade: fix 2.6 -> 2.7 migration for 2.7.1 patch (#1649)

cli/internal/helm/backup.go, cli/internal/helm/backup_test.go
Resource names are only unique per kind+ns. Without this patch it might happen that there are two resources with the same name in different namespaces. Upgrade might fail in that case.
=> cli: create namespaced folders for upgrade backups (#1702)

cli/internal/helm/backup.go, cli/internal/helm/backup_test.go
- During upgrade all custom resources are backed up to files on the local file system. Since old versions are also backed up, we need to reflect the version in the name. This is a fixup for #1702 .
- Tested the change locally by running against a bigger cluster.
=> cli: remove ambiguity in path for CR backups

cli/internal/helm/backup.go, cli/internal/helm/backup_test.go
During upgrade all custom resources are backed up to files on the local file system. Since old versions are also backed up, we need to reflect the version in the name.
=> cli: remove ambiguity in path for CR backups (#1719)

.github/actions/constellation_create/action.yml
- Guard removal of expected measurements in e2e tests behind a config version check
- for v2 configs the old format is used
- for v3 configs the new attestation config format is used
=> ci: guard measurement removal behind config version check

.github/workflows/e2e-test-release.yml
- The default is to use the latest main-debug image. During release we want to use the release image.
=> ci: set toImage argument in e2e-test-release

WORKSPACE.bazel, bazel/container/Containerfile, bazel/toolchains/python_deps.bzl
The actual python version used in bazel is hermetic after this PR. However, we still require a host python toolchain for bootstrapping (this will be fixed soon upstream) and host wide glibc (+ libcrypt.so.1).
- bazel: provide semi-hermetic python toolchain
- https://github.com/bazelbuild/rules_python/issues/691
- https://github.com/bazelbuild/rules_python/issues/1211
=> bazel: provide semi-hermetic python toolchain

.github/actions/e2e_test/action.yml, .github/workflows/e2e-mini.yml, .github/workflows/e2e-test-release.yml, .github/workflows/release.yml
- ci: run e2e tests as last step of release pipeline
- [e2e test run](https://github.com/edgelesssys/constellation/actions/runs/5002073500)
=> ci: run e2e tests as last step of release pipeline

cli/internal/cmd/upgradecheck.go, cli/internal/helm/loader.go, e2e/internal/upgrade/BUILD.bazel, e2e/internal/upgrade/upgrade_test.go
- We did not run a e2e test on `upgrade check` so far. This add a basic smoke test. A detailed verification of the output seems like too much effort for little gain to me. This patch only checks for existence of some strings.
- Fix a bug where the supported microservice versions are not reported correctly in `upgrade check`
- [Azure, 1+1, no upgrades](https://github.com/edgelesssys/constellation/actions/runs/4992674280) :green_circle:
=> ci: run `upgrade check` during e2e-upgrade

.github/actions/e2e_mini/action.yml, .github/workflows/build-os-image-scheduled.yml, .github/workflows/release.yml, cli/internal/cloudcmd/create.go, cli/internal/libvirt/libvirt.go, cli/internal/terraform/terraform.go, e2e/miniconstellation/BUILD.bazel, internal/config/BUILD.bazel, internal/config/image_enterprise.go, internal/config/image_oss.go
- move the "push containers before running the minicon test" dependency to bazel
- add some more error messages to more easily trace problems
- split `image.go` into `image_oss.go` and `image_enterprise.go`
=> cli: split image into oss and enterprise

.github/workflows/aws-snp-launchmeasurement.yml
- Adds a pipeline that precalculates launch measurements for AWS SNP. This measurement is distinct from the image measurement. The measurement is calculated by the CPU, while starting the CVM. It is a measurement of the initial firmware that is supplied by AWS.
- In a subsequent PR we will take the measurements, sign them and put them into the attestation API.
- [Test run](https://github.com/edgelesssys/constellation/actions/runs/5059204989/jobs/9080405102)
=> ci: add pipeline to precalc launchmeasurements

.github/workflows/aws-snp-launchmeasurement.yml
Misspelled variable name.
[testrun](https://github.com/edgelesssys/constellation/actions/runs/5077029708).
=> ci: fix aws-snp-launchmeasurement pipeline

.github/workflows/codeql.yml
Disable autobuild for go as it uses an outdated way to get the Go dependencies (see below)
```
Attempting to automatically build go code
/opt/hostedtoolcache/CodeQL/2.13.1-20230428/x64/codeql/codeql version --format=terse
2.13.1
/opt/hostedtoolcache/CodeQL/2.13.1-20230428/x64/codeql/go/tools/autobuild.sh
2023/05/24 23:09:06 Autobuilder was built with go1.20.3, environment has go1.20.4
2023/05/24 23:09:06 LGTM_SRC is /home/runner/work/constellation/constellation
2023/05/24 23:09:06 Found go.mod, enabling go modules
go: downloading github.com/google/go-sev-guest v0.4.1
go: downloading github.com/google/trillian v1.5.1
go: downloading github.com/onsi/ginkgo v1.10.3
go: downloading golang.org/x/exp v0.0.0-20230124195608-d38c7dcee874
go: downloading github.com/frankban/quicktest v1.14.3
go: …
```
=> ci: disable codeql autobuild for go

cli/internal/cloudcmd/iam.go, cli/internal/cloudcmd/iam_test.go, cli/internal/cmd/iamcreate.go, cli/internal/cmd/iamcreate_test.go, cli/internal/cmd/init.go, cli/internal/iamid/id.go, cli/internal/terraform/terraform.go, cli/internal/terraform/terraform/iam/azure/main.tf, cli/internal/terraform/terraform/iam/azure/outputs.tf, cli/internal/terraform/terraform_test.go, docs/docs/reference/config-migration.md, internal/config/config.go, internal/config/config_test.go
- Don't create App Registration anymore
- `ApplicationID` and `ApplicationClientSecretValue` are optional now, but are used for authentication if present. Also we print a deprecation warning linking to the migration guide.
- If they are not present, we assume that the config and IAM credentials were recently generated
=> cli: use uami for in-cluter authentication

internal/imagefetcher/BUILD.bazel
- The 'imagefetcher` library Bazel target was scoped to `//cli:__subpackages__`, while the file lived in `internal`. Therefore, the path could not be resolved which resulted in an error.
=> bazel: make imagefetcher visible to all subpackages

cli/internal/cmd/configgenerate.go, cli/internal/cmd/configgenerate_test.go, docs/docs/reference/cli.md, internal/cloud/cloudprovider/cloudprovider.go, internal/cloud/cloudprovider/cloudprovider_test.go, internal/config/config.go
- Add `stackit` to the list of supported cloudproviders, while using the OpenStack implementation under the hood.
- Add a `stackit` option to `constellation config generate`, which generates an OpenStack config file.
=> cli: support StackIT provider on config generate

.github/workflows/build-os-image.yml, image/Makefile
- In the spirit of keeping PRs small, I present...
- No changes to the existing AWS image are required as far as I can tell. The images have worked without modification. Only need to specify the different attestation variant on the cmdline.
- ~[testrun](https://github.com/edgelesssys/constellation/actions/runs/5088915234)~ :green_circle: 
- [testrun](https://github.com/edgelesssys/constellation/actions/runs/5129688092) :green_circle:
=> image: add aws_aws-sev-snp variant

.github/workflows/azure-snp-reporter.yml, .github/workflows/build-os-image-scheduled.yml, .github/workflows/build-versionsapi-ci-image.yml, .github/workflows/codeql.yml, .github/workflows/e2e-test-daily.yml, .github/workflows/e2e-test-manual.yml, .github/workflows/e2e-test-release.yml, .github/workflows/e2e-test-weekly.yml, .github/workflows/e2e-upgrade.yml, .github/workflows/test-tidy.yml
Runners sometimes fail because they run out of disk space. One reason this happens is a change in the setup-go action@v4:
> The V4 edition of the action offers: Enabled caching by default
To combat this, we now disable the cache if it was not enabled explicitly before. Additionally, we remove setup-go where it is no longer needed.
- ci: remove setup-go action / disable cache where applicable
- [e2e test](https://github.com/edgelesssys/constellation/actions/runs/5142586524)
=> ci: remove setup-go action / disable cache where applicable

internal/api/versions/cli/BUILD.bazel, internal/api/versions/cli/add.go, internal/api/versions/cli/list.go, internal/api/versions/cli/rm.go, internal/api/versions/client/BUILD.bazel, internal/api/versions/client/client.go
- Imported wrong error types during refactoring. This leads to checks like [this](https://github.com/edgelesssys/constellation/blob/main/internal/api/versions/cli/rm.go#L162) to not recognize errors correctly as the error returned is `client.NotFoundError`.
=> api: use correct error types in versions/cli

cli/internal/cmd/configfetchmeasurements_test.go, cli/internal/cmd/create_test.go, cli/internal/cmd/init_test.go, cli/internal/cmd/recover_test.go, cli/internal/cmd/upgradeapply_test.go, cli/internal/cmd/upgradecheck_test.go, cli/internal/cmd/verify_test.go, hack/configapi/cmd/BUILD.bazel, hack/configapi/cmd/delete.go, hack/configapi/cmd/delete_test.go, hack/configapi/cmd/root.go, internal/api/attestationconfig/azure.go, internal/api/attestationconfig/client/BUILD.bazel, internal/api/attestationconfig/client/client.go, internal/api/attestationconfig/client/client_test.go, internal/api/attestationconfig/client/test/integration_test.go, internal/api/attestationconfig/fetcher/fetcher.go, internal/api/attestationconfig/fetcher/fetcher_test.go, internal/api/client/client.go, internal/config/config_test.go, internal/sigstore/sign.go, internal/staticupload/staticupload.go
- add unit tests for attestationconfig.Client
- add delete command to tool
- refactor attestationconfig.Client to use the general apiclient
TODO: also make rest of attestation client testable?
=> config: Azure SNP tool can delete specific version from attestation API

.github/workflows/e2e-test-release.yml, .github/workflows/release.yml
Previous implementation would select the target version `""`, since `determine-version` tried to read `version.txt` without checking out the release branch first.
- ci: select correct target version for upgrade e2e test in release pipeline
=> ci: select correct target version for upgrade e2e test in release pipeline

cli/internal/terraform/terraform/gcp/modules/instance_group/main.tf
The implementation would recreate the gcp instance templates (including all instances and state disks) whenever the image tfvar changes.
Fixed by ignoring lifecycle changes on the instance templates.
Fixes 8c3b963
- cli: prevent tf apply drift when patching and re-applying existing tf deployment
Output of constellation upgrade apply:
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement
Terraform will perform the following actions:
-/+ resource "google_compute_instance_template" "template" {
name                 = "malte-08f6a599-control-plane"
+ tags_fingerprint     = (known after apply)
~ disk {
~ device_name       = "persistent-disk-0" -> (known after apply) …
```
=> cli: prevent tf apply drift when patching and re-applying existing tf deployment

internal/staticupload/staticupload.go, internal/staticupload/staticupload_test.go
- If no files have been touched, do not initiate an invalidation. Otherwise, the AWS API is unhappy.
=> staticupload: don't request empty invalidation

hack/configapi/cmd/root.go, internal/api/attestationconfig/azure.go, internal/api/attestationconfig/client/BUILD.bazel, internal/api/attestationconfig/client/client.go, internal/api/attestationconfig/fetcher/fetcher.go, internal/api/attestationconfig/fetcher/fetcher_test.go, internal/api/client/client.go
- #1863 did not yet replace the old implementation, so we use it now
Why does it matter?
COMPATIBILITY ISSUE:
In order to use the new generic fetcher (`internal/api/fetcher`) all objects need to be marshalled as JSON. This also means that the signature needs to be stored as JSON and not as raw bytes anymore.
In order to avoid backward-compatibility issues to the old raw byte format, we should ship the new JSON format in the release.
=> fix: use new UploadAzureSEVSNP impl

.github/actions/e2e_verify/action.yml, .github/workflows/build-os-image.yml, cli/internal/cmd/configfetchmeasurements.go, cli/internal/cmd/configfetchmeasurements_test.go, cli/internal/cmd/create_test.go, cli/internal/cmd/init_test.go, cli/internal/cmd/recover_test.go, cli/internal/cmd/upgradeapply_test.go, cli/internal/cmd/upgradecheck_test.go, cli/internal/cmd/verify_test.go, docs/docs/reference/cli.md
- Add `constellation config fetch-measurement --insecure` flag to be able to use the command inside the CI even for debug images which are not signed. 
- Re-enable the upload of measurements for debug images
image run: https://github.com/edgelesssys/constellation/actions/runs/5177633666
=> Add --insecure to config fetch-measurement

internal/attestation/azure/snp/validator_test.go, internal/config/attestationversion.go, internal/config/attestationversion_test.go, internal/config/config.go, internal/config/config_test.go
don't allow "latest" value and disable user-facing version fetcher for Azure SEV SNP.
REASON: v2.8 release.
Revert after release
Co-authored-by: @derpsteb
[AB#3036](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3036)
=> config: disable user-facing version fetch for Azure SEV SNP

.github/actions/build_micro_service/action.yml, .github/actions/container_registry_login/action.yml, .github/actions/e2e_mini/action.yml, .github/actions/e2e_test/action.yml, .github/workflows/build-ccm-gcp.yml, .github/workflows/build-gcp-guest-agent.yml, .github/workflows/e2e-test-manual.yml, .github/workflows/e2e-test-release.yml, .github/workflows/e2e-test-weekly.yml, .github/workflows/release-cli.yml
docker-login action fails on macOS runner since docker is not installed.
- ci: fix docker-login on macOS runner
- [e2e](https://github.com/edgelesssys/constellation/actions/runs/5186617789)
=> ci: fix docker-login on macOS runner

rfc/attestation-config.md
- Daniel and I discussed how we could keep up-to-date launchmeasurement in the attestationconfig API. And how to expose the value to the user. This is the result.
=> rfc: specify how to handle launchmeasurements

cli/internal/cmd/configfetchmeasurements_test.go, hack/configapi/cmd/root.go, internal/api/attestationconfigapi/azure.go, internal/api/attestationconfigapi/client.go, internal/api/attestationconfigapi/client_test.go, internal/api/attestationconfigapi/fetcher.go, internal/api/attestationconfigapi/fetcher_test.go, internal/attestation/azure/snp/validator_test.go, internal/config/attestationversion.go, internal/config/attestationversion_test.go, internal/config/config.go, internal/config/config_test.go, internal/sigstore/verify.go, rfc/attestation-config.md
- revert #1882 since v2.8 was released
- add a minimum age for the version value because the azure-sev-snp-report only gets the values on one machine. However, Azure does not provide official information on version rollouts, so we add a safety buffer of 2 weeks before we accept a new version update
- uploaded the current latest version with a timestamp of 2023-01-01 to be able to fetch latest versions now
#1882
[AB#3195](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3195)
[AB#3190](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3190)
- we should contact Azure to try to get official information on the version rollout
=> config: enable azure snp version fetcher again + minimum age for latest version

cli/internal/cmd/configfetchmeasurements.go, docs/docs/reference/cli.md
If I understand #1879 correctly, this doesn't need to be exposed to users, right?
=> cli: hide --insecure of config fetch-measurements

.github/actions/e2e_lb/action.yml, .github/actions/setup_bazel/action.yml, e2e/internal/lb/BUILD.bazel, e2e/internal/lb/lb.go, e2e/internal/lb/lb_test.go
- Try to migrate out of disk space errors: https://github.com/edgelesssys/constellation/actions/runs/5197845754/jobs/9373214163 by disabling the shared bazel cache on GitHub Action runners. This saves ~8 GB.
Testrun (azure, lb): https://github.com/edgelesssys/constellation/actions/runs/5221894800
=> ci: migrate e2e lb test to bazel

bootstrapper/internal/helm/helm.go, bootstrapper/internal/kubernetes/k8sapi/k8sutil.go, bootstrapper/internal/kubernetes/kubernetes.go, bootstrapper/internal/kubernetes/kubernetes_test.go, cli/internal/terraform/terraform/aws/main.tf, cli/internal/terraform/terraform/aws/modules/instance_group/main.tf, debugd/internal/debugd/constants.go, debugd/internal/debugd/metadata/scheduler.go, internal/cloud/aws/aws.go, internal/cloud/aws/aws_test.go, internal/cloud/aws/logger.go, internal/cloud/aws/logger_test.go, internal/kubernetes/kubectl/kubectl.go
- Retrieve instance tags though the ec2 API and not the IMDS API
- Correctly tag the instances according to https://cloud-provider-aws.sigs.k8s.io/getting_started/ Step 5
- let coredns run before the CCM is up, since it requires DNS to lookup tags from the ec2 api
- unrelated: make debugd less noisy by respecting the interval in all cases
image: `ref/feat-aws-correct-ccm-deployment/stream/debug/v2.8.0-pre.0.20230601144711-dacd80e4372b`
new image: `ref/feat-aws-correct-ccm-deployment/stream/debug/v2.8.0-pre.0.20230602114037-b06ddeb4026c` see: https://github.com/edgelesssys/constellation/actions/runs/5155150759
Migration:
I'm not really sure how to do migration for this, since it involves basically the steps from https://cloud-provider-aws.sigs.k8s.io/getting_started/ which are intrusive …
=> Correctly deploy the AWS CCM

shell.nix
Bazel's rules_python installs a python toolchain that depends on libcrypt.so.1. This change provides the required library on nixOS. Added a TODO to remove the dep as soon as rules_python toolchains are fully hermetic.
- nix: add python toolchain deps
=> nix: add python toolchain deps

bazel/toolchains/go_module_deps.bzl, cli/internal/cloudcmd/create.go, cli/internal/cmd/upgradeapply.go, cli/internal/terraform/BUILD.bazel, cli/internal/terraform/terraform/gcp/main.tf, cli/internal/terraform/terraform/gcp/modules/instance_group/main.tf, cli/internal/terraform/terraform/gcp/modules/instance_group/variables.tf, cli/internal/terraform/terraform/gcp/modules/loadbalancer/main.tf, cli/internal/terraform/terraform/gcp/modules/loadbalancer/variables.tf, cli/internal/terraform/terraform/gcp/variables.tf, cli/internal/terraform/terraform_test.go, cli/internal/terraform/variables.go, cli/internal/terraform/variables_test.go, go.mod, go.sum, hack/go.mod, hack/go.sum
This is the first step towards supporting multiple groups of control plane and worker nodes (with different instance configuration and zones).
Similar PRs will be opened for other CSPs.
In follow up PRs, we will address the bootstrapper-related code and make it ready for multiple node groups in different zones.
Please note that this PR should not change any behavior on its own.
Existing clusters can be migrated and (for now) we still create one group for control-plane nodes and one for workers.
- terraform: gcp node groups
- Check that an existing gcp cluster on v2.8 can be migrated to this terraform state without any resources being deleted.
- Manually add an additional node group with different settings (zone, instance type) to the terraform.tfvars file. It should be created …
=> terraform: gcp node groups

cli/internal/cmd/configfetchmeasurements.go, cli/internal/cmd/create.go, internal/config/config.go, internal/config/config_test.go
Currently there is no useful output that indicates success to the user:
```
./constellation config fetch-measurements --insecure
Configured image doesn't look like a released production image. Double check image before deploying to production.
```
We also discussed printing a diff of the updated measurements, but comparing the `measurement.M` object seems tricky and is not worth the effort.
---
We should issue a warning on cluster creation with debug image and `debugCluster: false`:
```
../constellation create --control-plane-nodes 1 --worker-nodes 1 -y
Configured image doesn't look like a released production image. Double check image before deploying to production.
Creating
Your Constellation cluster was created successfully.
15.92s user 5.14s system 16% cpu 2:06.29s total
```
Otherwise …
=> cli: improve user warning / information

cli/internal/cmd/upgradeapply.go, cli/internal/cmd/upgradecheck.go, cli/internal/cmd/upgradecheck_test.go, cli/internal/upgrade/terraform.go, cli/internal/upgrade/terraform_test.go
- The `upgrade check` command used not to take the Terraform migrations into account that would happen within the checked upgrade. This should be changed in this PR.
- The `upgrade check` command should perform a dry-run of the Terraform migrations that will be applied within the update, to show the user which actions on cloud resources will be taken upon the update.
- Right now, the `parseTerraformUpgradeVars` function is shared between both the `upgrade check` and the `upgrade apply` command. This is certainly not a great dependency model and it should likely be factored out. I was unsure about what an appropriate place might be.
=> cli: dry-run Terraform migrations on `upgrade check`

internal/cloud/gcp/gcp.go, internal/cloud/gcp/gcp_test.go, internal/cloud/gcp/interface.go, internal/cloud/gcp/wrappers.go
This is part of the larger effort to support multiple node groups.
When creating a GCP cluster across zones, newly joining nodes need to auto-discover the Constellation control-plane in order to obtain a join ticket.
Before this PR, only nodes in the same zone could be discovered. With this PR, instances across all zones of the same region can be discovered.
- cloud: fix discovery of GCP nodes across multiple zones
=> cloud: fix discovery of GCP nodes across zones

cli/internal/cmd/upgradeapply.go, cli/internal/cmd/upgradecheck.go, cli/internal/cmd/upgradecheck_test.go, cli/internal/helm/backup.go, cli/internal/helm/backup_test.go, cli/internal/helm/client.go, cli/internal/kubernetes/BUILD.bazel, cli/internal/kubernetes/upgrade.go, cli/internal/terraform/loader.go, cli/internal/terraform/loader_test.go, cli/internal/terraform/terraform.go, cli/internal/upgrade/terraform.go, cli/internal/upgrade/terraform_test.go
- Implement versioning of Constellation upgrades, so that a user can perform multiple upgrades without cleaning the `constellation-upgrade` directory. Each upgrade is marked by a timestamp string and a unique identifier and the corresponding files get placed into a unique subdirectory for their upgrade ID. (e.g. `constellation-upgrade/upgrade-20230614105831-976b92d0`)
- [Upgrade e2e test](https://github.com/edgelesssys/constellation/actions/runs/5265731418)
=> cli: store upgrade files in versioned folders

cli/internal/terraform/terraform/iam/aws/main.tf
- To use the AWS CSI driver, the corresponding storage permissions are necessary.
- Add the required storage permissions.
- Should be merged with the [driver PR](https://github.com/edgelesssys/constellation-aws-ebs-csi-driver/pull/1)
=> csi: aws csi driver policies

cli/internal/cloudcmd/create.go, cli/internal/cmd/BUILD.bazel, cli/internal/cmd/upgradeapply.go, cli/internal/terraform/terraform/aws/modules/instance_group/variables.tf, cli/internal/terraform/terraform/azure/modules/scale_set/main.tf, cli/internal/terraform/terraform/gcp/main.tf, cli/internal/terraform/terraform/gcp/modules/instance_group/main.tf, cli/internal/terraform/terraform/gcp/modules/instance_group/variables.tf, cli/internal/terraform/terraform/gcp/variables.tf, cli/internal/terraform/terraform/openstack/main.tf, cli/internal/terraform/terraform/openstack/modules/instance_group/main.tf, cli/internal/terraform/terraform/openstack/modules/instance_group/variables.tf, cli/internal/terraform/variables_test.go
terraform.tfvars should use the following role names to refer to roles:
"control-plane", "worker"
Go code uses a `Role` type that has the string constants `ControlPlane` and `Worker`. From now on, the CLI should convert the role names when writing the terraform.tfvars file.
- terraform: always use uniform role names
=> terraform: always use uniform role names

cli/internal/cmd/configgenerate.go, cli/internal/cmd/configgenerate_test.go, docs/docs/workflows/config.md, internal/api/attestationconfigapi/client.go, internal/attestation/variant/variant.go
There are some places where "attestation variant" is called "attestation type". We should use the term consistently.
- Replace "attestation type" with "attestation variant" in user-facing strings as well as in identifiers
=> Use term "attestation variant" consistently

cli/internal/cloudcmd/clients.go, cli/internal/cloudcmd/clients_test.go, cli/internal/cmd/upgradeapply.go, cli/internal/cmd/upgradecheck.go, cli/internal/terraform/terraform.go, cli/internal/upgrade/terraform.go, cli/internal/upgrade/terraform_test.go
Terraform migrations on Constellation upgrades used to target resources explicitly as otherwise Terraform would destroy non-updatable resources such as instance groups if they have been changed (e.g. due to autoscaling) outside of Terraform. The explicit targeting will fail when a user edits a non-targeted resource outside of Terraform as Terraform receives an unexpected state drift.
-  Remove the resource targeting.
- Before releasing v2.9.0, we will need to check the migrations happening with the release (most likely only node groups) thoroughly and add the required `lifecycle { ignore_changes ... }` meta-argument in the Terraform config.
=> cli: remove Terraform targets

cli/internal/cmd/miniup.go, cli/internal/featureset/featureset.go, cli/internal/featureset/featureset_enterprise.go, cli/internal/featureset/featureset_oss.go, internal/config/config.go, internal/config/config_test.go
We want to make sure that a consumer of the config can rely on it being in a valid state (as verified in `config.Validate`).
Currently, the usage is not consistent and better documentation should discourage mutation of a config object without subsequent validation.
- discourage use of config.Default + mutation
- discuss violating usage in miniup
=> config: improve usage and meaning of validate

.github/actions/constellation_iam_create/action.yml, .github/workflows/e2e-windows.yml, cli/internal/cmd/iamcreate.go, cli/internal/cmd/iamcreate_test.go, cli/internal/cmd/upgradecheck.go, docs/docs/getting-started/first-steps.md, docs/docs/reference/cli.md, docs/docs/workflows/config.md, docs/docs/workflows/upgrade.md, docs/screencasts/docker/configure-cluster.expect, docs/screencasts/generate-readme-svg.sh, rfc/updates.md
- change `--generate-config` flag to `--update-config` in the iam create subcommand
- rename `--write-config` flag to `--update-config` in the upgrade check subcommand
SInce we'd need to support the growing number of flags in `constellation config generate` for the `--generate-config` flag, we should change the workflow to scale better while preserving flexibility.
- This changes the workflow to require `constellation config generate` before `constellation iam create`
=> cli: change generate-config flag to update-config flag

cli/internal/cloudcmd/create.go, cli/internal/cmd/BUILD.bazel, cli/internal/cmd/manualtfstatemigration.go, cli/internal/cmd/upgradeapply.go, cli/internal/cmd/upgradeapply_test.go, cli/internal/cmd/upgradecheck.go, cli/internal/cmd/upgradecheck_test.go, cli/internal/kubernetes/upgrade.go, cli/internal/terraform/BUILD.bazel, cli/internal/terraform/terraform.go, cli/internal/terraform/terraform/aws/main.tf, cli/internal/terraform/terraform/aws/modules/instance_group/main.tf, cli/internal/terraform/terraform/aws/modules/instance_group/variables.tf, cli/internal/terraform/terraform/aws/modules/public_private_subnet/main.tf, cli/internal/terraform/terraform/aws/modules/public_private_subnet/output.tf, cli/internal/terraform/terraform/aws/modules/public_private_subnet/variables.tf, cli/internal/terraform/terraform/aws/outputs.tf, cli/internal/terraform/terraform/aws/variables.tf, cli/internal/terraform/terraform_test.go, cli/internal/terraform/variables.go, cli/internal/terraform/variables_test.go, internal/cloud/aws/aws.go
Refactor terraform code for AWS provider to go from two node groups (1x control plane, 1x worker) to arbitrary node groups.
On AWS, this is especially hard to do, since most network resources are zone-scoped, which means that we have to duplicate the networking resource for every zone.
This is handled differently for two categories of resources:
- Cheap resources are created for every zone in the chosen region. This ensures we can depend on those resources for loadbalancing and can add / remove node groups in every region without downtime.
- Expensive resources (nat gateways) are only created in a region when there is at least one node group in that region.
Additionally, some terraform migrations have to be performed by the cli directly. [Terraform does not yet support moving resources …
=> terraform: aws node groups

.github/actions/constellation_iam_create/action.yml
Our e2e tests also run using the CLI/image of the latest release.
Currently, the IAM creation fails because of a change in flags for the `constellation iam create` command.
- Conditionally use either the new `--update-config`, or the older `--generate-config` flag in the e2e tests for `constellation iam create` depending on which flag is supported by the CLI
GCP e2e test with release image from v2.8.0: https://github.com/edgelesssys/constellation/actions/runs/5411009653
=> ci: conditionally use generate-config flag for old versions of Constellation CLI

docs/docs/overview/clouds.md, docs/versioned_docs/version-2.8/overview/clouds.md
state that AWS SNP firmware is reviewable, but can't measure OS image itself
=> docs: update "feature status of clouds" regarding current AWS SNP offering

bootstrapper/internal/helm/helm.go, cli/internal/helm/loader.go, internal/deploy/helm/helm.go
When installing helm charts during `constellation init`, the bootstrapper will retry an installation on error.
Because of how the retry loop and installation is set up, the chart is not cleaned up if the error didn't occur immediately, but later during the installation, e.g. a startup check fails after 3 minutes into the installation.
This in turn will cause an error when the installation is retried because the name of the installation is still in use.
For example, the installation of cert-manager may fail due to timeouts during the start up check.
The retry will then fail with the following error:
```text
installing cert-manager: helm install: cannot re-use a name that is still in use
```
- Install all charts with the `Atomic` flag set
-  This causes the chart to be uninstalled on …
=> bootstraper: delete helm chart on installation failure before retrying installation

cli/internal/cmd/upgradeapply.go, cli/internal/helm/client.go, cli/internal/helm/client_test.go, cli/internal/kubernetes/upgrade.go, cli/internal/kubernetes/upgrade_test.go, internal/compatibility/compatibility.go, internal/config/config.go, internal/config/config_test.go, internal/staticupload/staticupload.go, internal/staticupload/staticupload_test.go
`constellation upgrade apply` should go over a list of all available charts and only skip a single chart if it is already up to date. Other charts should still be upgraded if one doesn't need to.
- correctly use `errors.As` to not skip other service upgrades during `upgrade apply`
- correctly use `errors.As` to not return an error (only print it) if the node version is the same as the upgrade target
- should be merged before v2.9 to not break upgrades
=> helm: fix upgrade command skipping all service upgrades

cli/internal/terraform/terraform/aws/main.tf, cli/internal/terraform/terraform/aws/modules/public_private_subnet/main.tf, internal/cloud/aws/aws.go
This change is required to ensure we have no tls handshake errors when connecting to the kubernetes api. Currently, the certificates used by kube-apiserver pods contain a SAN field with the (single) public ip of the loadbalancer. If we would allow multiple loadbalancer frontend ips, we could encounter cases where the certificate is only valid for one public ip, while we try to connect to a different ip.
To prevent this, we consciously disable support for the multi-zone loadbalancer frontend on AWS for now. This will be re-enabled in the future.
[See also](https://gist.github.com/malt3/f3c2d004ed0c046edcd218fa5dcc9652)
- terraform: use single zone loadbalancer frontend on AWS
=> terraform: use single zone loadbalancer frontend on AWS

bootstrapper/internal/kubernetes/kubernetes.go
The `constellation-services` helm chart (or more precisely the join-service) depends on the `internal-config` configmap.
Deploy the configmap before deploying the services.
- bootstrapper: install internal-config cm before constellation-services
=> bootstrapper: install internal-config cm before constellation-services

.github/workflows/build-gcp-guest-agent.yml, internal/versions/versions.go
Renovate bot isn't picking up updates of the gcp-guest-agent container image for some time.
- Making the version a valid semver should help renovate to handle it
=> ci: use strict semver for gcp guest agent image

cli/internal/cmd/iamcreate.go, cli/internal/cmd/iamcreate_test.go, docs/docs/workflows/config.md, internal/config/config.go, internal/config/config_test.go, internal/config/validation.go
**Why?**
```sh
constellation create --control-plane-nodes 1 --worker-nodes 1
Configured image doesn't look like a released production image. Double check image before deploying to production.
The following Constellation cluster will be created:
1 control-plane node of type m6a.xlarge will be created.
1 worker node of type m6a.xlarge will be created.
Do you want to create this cluster? [y/n]: y
Creating
An error occurred: terraform apply: exit status 1
Error: creating EC2 Subnet: InvalidParameterValue: Value (eu-central-1) for parameter availabilityZone is invalid. Subnets can currently only be created in the following availability zones: eu-central-1a, eu-central-1b, eu-central-1c.
status code: 400, request id: 225f1583-b2d8-4278-aacd-23113226d00d
with …
```
=> config: iam create aws check zone contains availability zone

bootstrapper/internal/nodelock/BUILD.bazel, bootstrapper/internal/nodelock/nodelock.go, bootstrapper/internal/nodelock/nodelock_test.go
The nodelock used a mutex in unintended ways (lock using `TryLock`, never unlocked).
Under the hood, mutexes use a compare and swap operation with an atomic int to perform a `TryLock`.
Atomic compare and swap is closer to the operation we want to perform so we replace the mutex with an atomic bool.
- bootstrapper: use atomics in nodelock
=> bootstrapper: use atomics in nodelock

docs/docs/architecture/attestation.md
Explain why PCR[10] is not reproducible and what components are measured into PCR[10] (Linux IMA).
- docs: explain the role of PCR[10] and why it is not reproducible
=> docs: explain the role of PCR[10] and why it is not reproducible

WORKSPACE.bazel, bazel/devbuild/BUILD.bazel, bazel/devbuild/prepare_developer_workspace.sh.in, bazel/sh/def.bzl
Constellation now requires an exact match between the version of the CLI and the version of the microservices. `bazel run //:devbuild` should take care of this to speed up the development workflow.
- Let `devbuild` replace the microservice version in the config, if present. If no config is present, just print the microservice version so it can be copied by hand.
=> bazel: fill microservice version on `devbuild` target

bazel/container/container.sh
When executing from the builder container without any changes, the container push (as used in `//:devbuild`, for example) failed since it didn't have the Docker / ghcr credentials. 
- Mount the Docker config of the host machine into the builder container so it uses the same authentication.
=> bazel: mount host's Docker config into builder container

renovate.json
Renovate tries to update containers of the CSI charts.
CSI charts should only be updated upstream, since we automatically pull in the charts.
- Let renovate ignore CSI charts
=> deps: ignore updates to CSI containers in renovate

bootstrapper/internal/helm/helm.go, cli/internal/cmd/BUILD.bazel, cli/internal/cmd/init.go, cli/internal/helm/loader.go, cli/internal/helm/loader_test.go, docs/docs/reference/cli.md, internal/deploy/helm/helm.go
This flag can be used to disable the atomic and wait flags during helm install. This is useful when debugging a failing `constellation init`, since the user gains access to the cluster even if one of the deployments is never in a ready state.
- cli: add "--skip-helm-wait" flag
- bootstrapper: fix deadlock during helm install
I tested this manually.
You can see the difference by either creating  a broken deployment on purpose or by measuring the time difference between skipping and waiting.
The skip flags makes `constellation init` a lot faster.
=> cli: add "--skip-helm-wait" flag

.github/actions/constellation_create/aws-logs.sh
The introduction of node groups also brought a naming change (i.e. change of explicit module instances to a map of an arbitrary amount of module instances) which broke the seleciton of the control plane and worker instance group name in the boot log collection. 
- Fix the boot log collection resource selectors.
=> ci: update aws asg resource selector

cli/internal/cmd/upgradeapply.go, cli/internal/helm/client.go, cli/internal/kubernetes/BUILD.bazel, cli/internal/kubernetes/upgrade.go, internal/kubernetes/kubectl/kubectl.go
Depending on the changes in a release we need migration code during upgrades to change existing cluster resources, etc. Since we force users to upgrade one minor version at a time we can remove old migration code. This PR does that.
- Remove migrations that are not required for upgrading from 2.8.
=> cli: remove old migrations

.github/workflows/e2e-test-release.yml
The current fromVersion value is outdated since the release of 2.8.
- Update the value to 2.8 so we correctly test upgrade from 2.8 to 2.9 during release tests.
=> ci: use 2.8 as fromVersion in release upgrade test

.github/actions/constellation_create/action.yml, .github/actions/e2e_test/action.yml
We are hitting our vCPU limit of 64 in eu-west-1 during release testing (needs 180 vCPUs).
Support needs manual approval and requested more details. Supplied details, but approval will probably take 1-2 more days.
We have much higher quotas in us-east-2.
- On AWS: use region us-east-2 for e2e tests
=> ci: use us-east-2 for e2e tests

cli/internal/cmd/upgradeapply.go
Every step of `constellation upgrade apply` needs to be idempotent. Currently, if there is no diff between the desired attestation config and the actual attestation config in the cluster, the upgrade will abort with the message:
```
Error: upgrading measurements: comparing attestation configs: %!w(<nil>)
```
- cli: allow upgrade to succeed if desired attestation config == actual config
=> cli: allow upgrade if desired attestation config == actual config

cli/internal/helm/client.go, internal/versions/versions.go
When upgrading, it is common that users have an older k8s patch version in their constellation-conf.yaml.
We don't want to force users to upgrade immediately.
This is why we ask the user if they want to skip the k8s version upgrade in cases where an unsupported k8s version is in the config.
However, helm upgrades should still be supported by Constellation in that case, since the deployed services only depend on the k8s minor version.
I propose a change to `ValidK8sVersion`: If the constructor returns without error, the type always contains a full, supported, known k8s version. 
If strict is set to false, the version returned may differ in the patch part of the version put in.
This ensures that `ValidK8sVersion` is actually a valid k8s version and it can be used for map lookups.
- cli: …
=> cli: allow helm upgrades with old k8s patch version

internal/config/config.go, internal/config/config_doc.go
We added the field in 2.9 but can only require it in 2.10.
- Fallback to false and warn the user if the field is not specified.
=> config: make deployCSIDriver backwards compatible

operators/constellation-node-operator/internal/cloud/aws/client/scalinggroup.go
When upgrading the default launch template version in the operator, we would pass a `*int64` to `Sprintf("%d", VAR)`.
This results in the address of the variable being used as a launch template version when setting the default version.
This prevents the operator from reconciling correctly.
- operators: correctly update launch template default version on AWS image upgrade
Kudos to @elchead for finding the root cause.
=> operators: correctly update launch template default version on AWS image upgrade

.github/workflows/build-os-image.yml
AWS SNP has a different value in PCR0. Since it involves more extensive changes to properly handle the image-independent data in PCR0 we opted for this ad-hoc fix. Those changes should be tested for a longer time than 1 day.
- Set different PCR0 value for variant `aws-sev-snp`
- Changes from https://github.com/edgelesssys/constellation/pull/2098
- [Testrun](https://github.com/edgelesssys/constellation/actions/runs/5539806876) :green_circle: 
- Manual test with the image from above run fixes the warnings. With measurements in the config (via `config fetch-measurements --insecure`).
=> ci: separate PCR0 value for aws-sev-snp variant

.github/actions/constellation_create/action.yml, .github/actions/constellation_create/aws-logs.sh, .github/actions/constellation_create/az-logs.sh, .github/actions/constellation_create/gcp-logs.sh
To download serial logs in the CI, we have to parse the cloud resources used in the run (e.g. VM instance ID) to be able to retrieve logs for the specific instances. Previously, this relied on specific Terraform resource names, which, as the recent bugs showed, are not a stable interface to rely on.
- To have a more stable interface, use `constellation-id.json` and the `UID` contained there to target the resources. 
- Furthermore, fix a bug where the serial log artifact-upload would also select Terraform logs due to a glob.
=> ci: fix resource selection for serial log downloading

dev-docs/workflows/release.md
We are building multiple images on AWS and GCP by now. But are not mentioning the fact that two images need to be deleted during pipeline cleanup.
- Mention both variants on AWS and GCP
=> docs: mention need to delete variants

.github/workflows/e2e-test-manual.yml
workflow_dispatch inputs are limited to maximum of 10 user configurable inputs.
Therefore we need to combine some of them into a single input to no go over this limit.
In the past we used a combined CLI version and image version field, which imo was somewhat hard to read, write, and fully understand the format of.
The goal of this PR is to combine simpler inputs into one
- Remove combination of cli and image version field
- Combine worker and control-plane node counts into one
- Once node groups are fully implemented, we probably want to revisit this to allow setting of multiple node groups
- This could use a similar format, e.g. controlPlaneCount="1:3:2", with a mapping of machineType="large:small:medium"
- The `keepMeasurements` can likely also be removed, since any images built will …
=> ci: combine node count inputs into one

.github/failure_project_template.md
We track repeating failures using tickets in Azure Boards.
Correlating existing failures with new ones can be difficult since this requires looking through the description of existing failures and trying to match them with a new one.
Encourage maintainers to add an Azure Boards ticket number and short description to the failure title, making correlations easy by just looking at the ticket number in the title.
This also makes it easier to eventually clean up failures once a fix is published.
=> ci: update failure tasks

cli/internal/cmd/upgradeapply.go
The `ConfidentialVM` option was never set when applying terraform migrations, leading to it being default initialized as `false`.
This in turn leads to the upgrade trying to change the settings for node groups on Azure from confidential VMs to non-confidential VMs.
- cli: set Azure ConfidentialVM option in terraform vars when migrating
=> cli: set Azure ConfidentialVM option in terraform vars when migrating

image/mkosi.skeleton/etc/dracut.conf.d/aws.conf
This allows different Kernels to be used for Constellation on EC2. For networking on AWS, the "elastic networking adapter" (ena) driver is required. Fedora's kernel builds with `CONFIG_ENA_ETHERNET=y`, while others have `CONFIG_ENA_ETHERNET=m`. With this setting, support for ena will always be available in the initrd.
- image: always copy amazon ena driver into initrd
=> image: always copy amazon ena driver into initrd

image/Makefile, image/README.md, image/mkosi.conf.d/mkosi.aws.conf
Constellation nodes on AWS SEV-SNP frequently get stuck during boot.
They are usually automatically cleaned up and replaced by AWS after a period of 5-10 minutes.
After a lot of testing, our Kernel was deemed to be the problem.
- Build images using a repackaged AWS Linux Kernel, replacing the upstream Fedora Kernel
- Fixes [AB#3259](https://dev.azure.com/Edgeless/Edgeless/_workitems/edit/3259)
This does not seem to fix all problems related to booting SEV-SNP VMs, but it seems to make things a lot more stable.
We'll need a build process for the Kernel.
The standard AWS Linux Kernel (currently `6.1.34-59.116`) does not support dm-verity and has dependencies on packages which aren't actually required.
We have a prebuilt Kernel with the required modules, but in the future we should automate …
=> image: use AWS linux kernel for AWS images to fix deadlock

bazel/toolchains/go_module_deps.bzl, bootstrapper/internal/diskencryption/diskencryption.go, bootstrapper/internal/diskencryption/diskencryption_test.go, disk-mapper/cmd/main.go, disk-mapper/internal/diskencryption/diskencryption.go, disk-mapper/internal/setup/setup_test.go, disk-mapper/internal/test/integration_test.go, go.mod, go.sum, internal/cryptsetup/cryptsetup.go
Constellation encrypts its statefull disks using cryptsetup.
For this, a node will first generate a completely random password during the initramfs stage, and then update the password for the disk once it joins a cluster using a password derived from the master secret.
If during boot a node detects its state disk to already be an encrypted LUKS2 disk, it will request a decryption key from a running cluster, instead of formatting the disk.
This allows a node to easily rejoin a cluster upon reboot.
However, this also means that a node which restarted after having first formatted its disk, but before joining a cluster for the first time, will be stuck in initramfs trying to decrypt the disk.
Use the cryptsetup [`token_json`](https://mbroz.fedorapeople.org/libcryptsetup_API/group__crypt-tokens …
=> disk-mapper: set LUKS2 token to allow reusing unintialized state disks

cli/internal/terraform/terraform/azure/main.tf
**Azure only:**
When upgrading a cluster from v2.8 to v2.9, that has been created on v2.7 and was upgraded to v2.8, you may be faced with a terraform diff that includes recreating the public IP of the cluster. This would break the cluster. 
This is due to name change of a public IP resource. The name change forces a recreate.
The bug was introduced in v2.8. The migration from v2.7 to v2.8 worked fine because of a bug in our migration code, which was fixed in v2.9. 
- Add `lifecycle.ignore_changes` to `azurerm_public_ip` resource
- Tested manually on the dogfooding cluster and a fresh Azure cluster.
=> cli: do not recreate LB IP during 2.9 upgrade on Azure

image/mkosi.skeleton/usr/lib/systemd/system-preset/30-constellation.preset, image/mkosi.skeleton/usr/lib/systemd/timesyncd.conf.d/constellation.conf
On some hypervisors, the default clock source is not available or not reliable.
To ensure synchronized clocks between all nodes of a Constellation, we enable time synchronization via ntp.
- image: synchronize time via ntp
=> image: synchronize time via ntp

cli/internal/cmd/init.go, internal/versions/versions.go
- Add the supported K8s versions to the error output when e.g. the user tries to create a Constellation with an outdated version.
=> cli: print supported k8s versions on error

cli/internal/cloudcmd/BUILD.bazel, cli/internal/cloudcmd/create.go, cli/internal/cloudcmd/create_test.go, cli/internal/cloudcmd/terraform.go, cli/internal/cmd/BUILD.bazel, cli/internal/cmd/upgradeapply.go, cli/internal/cmd/upgradecheck.go, cli/internal/terraform/variables.go, cli/internal/terraform/variables_test.go, internal/constants/constants.go, operators/constellation-node-operator/internal/cloud/aws/client/BUILD.bazel, operators/constellation-node-operator/internal/cloud/aws/client/scalinggroup.go, operators/constellation-node-operator/internal/cloud/aws/client/scalinggroup_test.go, operators/constellation-node-operator/internal/cloud/azure/client/BUILD.bazel, operators/constellation-node-operator/internal/cloud/azure/client/scalinggroup.go, operators/constellation-node-operator/internal/cloud/azure/client/scalinggroup_test.go, operators/constellation-node-operator/internal/cloud/gcp/client/BUILD.bazel, operators/constellation-node-operator/internal/cloud/gcp/client/scalinggroup.go, operators/constellation-node-operator/internal/cloud/gcp/client/scalinggroup_test.go
There was a bug in a previous release where upgrade used different terraform variables than create ([AB#3283](https://dev.azure.com/Edgeless/Edgeless/_backlogs/backlog/Edgeless%20Team/Features?showParents=false&workitem=3283)). That bug was [fixed](https://github.com/edgelesssys/constellation/pull/2113/files) by adding the missing variables to create.
To prevent the same thing from happening again this PR refactors the relevant code to use the same variables in both places.
- use constant as name for control plane and worker default node group
- get terraform variables from new functions `azure/gcp/aws/openStack/qemuTerraformVars` during create and upgrade.
- azure nop: https://github.com/edgelesssys/constellation/actions/runs/5596357804
- gcp nop: …
=> cli: unify terraform variable creation

cli/internal/helm/client.go
Fixes bug from #2090, that throws an error even if there is no error at all:
```
2023-07-24T09:12:00.7870989Z Stderr: Error: getting status: getting service versions: getting aws-load-balancer-controller version: %!w(<nil>)
```
-
=> aws: fix get version error

bazel/container/container.sh, bazel/devbuild/prepare_developer_workspace.sh.in
The bazel container enables running bazel in situations where bazel cannot executed directly on the host.
- Check for container config file when starting container. Without the file container images can't be pushed.
- Use the injected paths to the bazel cache when executing binaries that were previously build (cli). The created symlinks within the container are pointing to host fs paths and won't work.
=> bazel: check for docker config and fix cli usage in container

.github/workflows/aws-snp-launchmeasurement.yml
AWS SNP attestation should verify the launch measurement from the SNP report. The launch measurement should be configurable by the user through the constellation config. As the launch measurement differs depending on the number of vCPUs of a machine we would have to provide multiple launch measurements in the config, one for each possible VM size. To avoid this we will soon start using [this](https://github.com/edgelesssys/sev-snp-measure-go) library to pre-calculate launchmeasurements during runtime. The input for that calculation is produced as part of the pipeline changes in this PR.
- Build sev-snp-measure-go.
- Run equivalence test between sev-snp-measure-go and it's [upstream](https://github.com/IBM/sev-snp-measure).
- Generate MetadataWrapper object.
- Saving the files to the API …
=> ci: parse ovmf binaries from metadata

cli/internal/cmd/BUILD.bazel, cli/internal/cmd/status.go, cli/internal/cmd/status_test.go, cli/internal/helm/BUILD.bazel, cli/internal/helm/client.go, cli/internal/helm/loader.go, cli/internal/helm/serviceversion.go
Individual versions of the CSI chart were not printed when running `constellation status`
- Print the installed versions of the CSI chart
- Only print aws-load-balancer-controller version if it is installed
=> cli: output CSI driver versions on `status`

cli/internal/cmd/BUILD.bazel, cli/internal/cmd/verify.go, cli/internal/cmd/verify_test.go, go.mod
- Adding additional output to the verify command:
- The extensions of the VCEK are know parsed and printed.
- The AMD SEV-SNP report is now parsed and printed.
**Example output:**
```diff
diff --git a/output_old.txt b/output_new.txt
index f3894c23..5510f212 100644
--- a/output_old.txt
+++ b/output_new.txt
@@ -45,6 +45,17 @@ Attestation Document:
Not After: 2030-05-02 17:50:16 +0000 UTC
Signature Algorithm: SHA384-RSAPSS
Public Key Algorithm: ECDSA
+		Struct version: 0
+		Product name: Milan-B0
+		Secure Processor bootloader SVN: 3
+		Secure Processor operating system SVN: 0
+		SVN 4 (reserved): 0
+		SVN 5 (reserved): 0
+		SVN 6 (reserved): 0
+		SVN 7 (reserved): 0
+		SEV-SNP firmware SVN: 8
+		Microcode SVN: 115
+		Hardware ID: 0x094a46eea5fde950946e4b4743d496aa7a51ac48ad37886afcc46af66918 …
```
=> verify: print vcek certificate extensions and snp attestation report

cli/internal/terraform/terraform.go, cli/internal/terraform/terraform/azure/main.tf, cli/internal/terraform/terraform/azure/outputs.tf, cli/internal/terraform/terraform/azure/variables.tf, cli/internal/terraform/terraform/iam/azure/outputs.tf, cli/internal/terraform/terraform_test.go
#2136 introduced a bug by providing the name of the UAMI  in the `azureConfig` secret, instead of the expected client_id.
- inject the client_id correctly
=> azure: fix ccm config with correct uami client_id

.github/workflows/aws-snp-launchmeasurement.yml
Building an external pkg inside a workspace without adding it to the workspace does not work. So lets clone both repos into separate dirs.
- [Testrun](https://github.com/edgelesssys/constellation/actions/runs/5715368193/job/15484521738) :green_circle: 
- Add path arg to constellation checkout
- Leave dirs after each step
=> ci: clone constellation repo into separate dir

.github/workflows/e2e-test-manual.yml
- Remove `iamcreate` as an option to run for e2e tests. It is [not supported by the CI anymore](https://github.com/edgelesssys/constellation/blob/002c3a9a3289de79c92ad757970301d274e74e00/.github/actions/e2e_test/action.yml#L90).
=> ci: remove old incompatible test option

cli/internal/terraform/terraform/azure/main.tf
- Count from the right side of the string to ignore optional prefix values that are still part of the users config
My config contains: 
`userAssignedIdentity: subscriptions/<id>/resourceGroups/<name>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<name>`
I think that the "correct way would be to use that e.g. the resource Group name is "prefixed" with `/resourceGroup/`. The regex would be a bit complex though. Therefore I went with the simpler solution.
=> terraform: fix uami parsing

cli/internal/terraform/terraform.go
- parse every output variable the same, this e.g. removes the nested parsing
Note: this changes the behavior a slight bit, since we now error in case `tfState.Values.Outputs["project"]` is not set. But I think this is the intended behavior.
=> cli: refactor terraform output parsing

.github/actions/constellation_create/action.yml, .github/actions/e2e_test/action.yml, .github/workflows/e2e-test-daily.yml, .github/workflows/e2e-test-manual.yml, .github/workflows/e2e-test-release.yml, .github/workflows/e2e-test-weekly.yml, .github/workflows/e2e-upgrade.yml, cli/internal/cmd/configfetchmeasurements.go
Previously, the daily e2e test would overwrite the CLI's expected PCR values in the `constellation-conf.yml` independent of the image used (i.e. on both debug- and release images). This caused us to notice changes in PCR values of CSPs with a delay.
- Keep the CLI's default measurements in the daily e2e test if a stable image is used.
- [e2e run prior to this fix](https://github.com/edgelesssys/constellation/actions/runs/5550089676), notice PCR[15] = `000...` even though a stable image is used.
- [e2e run with the fix](https://github.com/edgelesssys/constellation/pull/2109#issue-1807536801) TODO see unpatched PCR values
- [e2e after @malt3 applied his proposed fix](https://github.com/edgelesssys/constellation/actions/runs/5751553291)
=> ci: keep embedded measurements if stable image is used

bootstrapper/internal/kubernetes/k8sapi/kubeadm_config.go
- Add documentation to spell out how much disk space is used by the logs. 
This should avoid confusion about the `audit-log-maxsize` parameter, which is the max size of _one_ file and not the total size.
=> kubernetes: document total log size

.github/actions/constellation_create/action.yml
The `-w` and `-c` flags for `create` are still needed to create a cluster on v2.9 in the upgrade test.
-
=> e2e: fix upgrade test by adding deprecated flags

.github/actions/constellation_create/action.yml, .github/actions/e2e_test/action.yml
-
E2E is fixed: https://github.com/edgelesssys/constellation/actions/runs/5782899866/job/15670623206
=> cli: fix upgrade test by only setting nodeGroup for >v2.9

debugd/internal/cdbg/cmd/deploy.go, debugd/internal/cdbg/cmd/root.go
Allows cdbg to be started outside the workspace.
- cdbg: implement workspace / "-C" flag and "--bindir"
Proper usage:
```shell-session
./constellation create -C path/to/workspace
./cdbg deploy -C path/to/workspace --bindir $(pwd)
```
=> cdbg: implement workspace / "-C" flag and "--bindir"

bazel/toolchains/go_module_deps.bzl, cli/internal/cmd/BUILD.bazel, cli/internal/cmd/verify.go, cli/internal/cmd/verify_test.go, go.mod, go.sum, hack/go.mod, hack/go.sum
- Adding the parsed Microsoft Azure Attestation token to the output of verify command. This is especially interesting to validate that the IDKeyDigest from the SEV-SNP report with the MAA.
- This is the first step to transition the SNP reporter from the current custom runner based workflow to a simpler verify based workflow in the CI.
=> cli: add maa token to the output of `verify` command

bazel/toolchains/go_module_deps.bzl, cli/internal/cmd/BUILD.bazel, cli/internal/cmd/status.go, cli/internal/cmd/upgradeapply.go, cli/internal/cmd/upgradeapply_test.go, cli/internal/helm/charts/edgeless/constellation-services/charts/join-service/templates/configmap.yaml, cli/internal/helm/charts/edgeless/constellation-services/charts/key-service/templates/mastersecret.yaml, cli/internal/helm/testdata/AWS/constellation-services/charts/key-service/templates/mastersecret.yaml, cli/internal/helm/testdata/Azure/constellation-services/charts/key-service/templates/mastersecret.yaml, cli/internal/helm/testdata/GCP/constellation-services/charts/key-service/templates/mastersecret.yaml, cli/internal/helm/testdata/OpenStack/constellation-services/charts/key-service/templates/mastersecret.yaml, cli/internal/helm/testdata/QEMU/constellation-services/charts/key-service/templates/mastersecret.yaml, cli/internal/kubernetes/kubernetes.go, cli/internal/kubernetes/upgrade.go, cli/internal/kubernetes/upgrade_test.go, go.mod, go.sum, hack/go.mod, hack/go.sum, operators/constellation-node-operator/go.sum
In order to make an upgrade safe that applies our entire cluster configuration, we should take precaution to not update resources that can destroy the cluster.
We found `constellation-mastersecret` and the attestation config (inside `join-config`) to be such critical resources.
We decided to not make `join-config` immutable, because we actually allow updating it. Deleting the resource during an upgrade is troublesome when the upgrade fails.
- declare `constellation-mastersecret` immutable
- attestation config can be updated, but only through explicit user confirmation (already done). We know additionally print a diff to show the user what has changed.
- the attestationConfigDiff check now fetches the resource through the shared logic from `status` cmd to start decoupling from the upgrader …
=> cli: declare mastersecret as immutable and print attestationCfg diff in warning

internal/config/attestationversion.go, internal/config/attestationversion_test.go
For Azure-SEV SNP, we currently accept attestation version values such as:
2.6
09
As a user,  such input should fail config validation.
The version logically should only allow uint values such as: 1 or "1"
- don't allow float parsings and validate valid uint8 range
- [AB#3271](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3271)
=> cli: strict input validation on attestation version numbers

.github/actions/constellation_create/action.yml, .github/actions/constellation_iam_create/action.yml, .github/actions/e2e_test/action.yml
The existingConfig field is always set to true during create, as we use the IAM create step to generate the config in all cases. Accordingly, secret injection into config isn't needed anymore in create. This fixes a bug where other parameters like Kubernetes version and cluster name wouldn't be injected into the config due to existingConfig being true.
=> e2e: remove existingConfig field

cli/internal/cmd/upgradeapply_test.go, internal/config/attestationversion.go, internal/config/attestationversion_test.go
Unmarshalling a JSON representation of an AttestationConfig fails since https://github.com/edgelesssys/constellation/pull/2180.
This is because we now always try to unmarshal a given version as a Go string.
JSON has two distinct ways to represent numbers and strings: Numbers are always given without quotation marks, while strings have to use quotation marks.
This means we cannot simply unmarshal a value to string, like we do with YAML.
Additionally, unmarshalling to `any` causes Go to unmarshal numbers to float64.
- Try to unmarshal attestation version numbers to string, and then to int, when converting from JSON
=> internal: fix unmarshalling attestation version numbers from JSON

.github/actions/e2e_recover/action.yml
- Skip to the waiting on all nodes step after at least 1 control-plane node has been recovered. 
This is probably the normal user flow anyway since all other (control-plane) nodes are recovered automatically.
This should fix flaky test, where some nodes recovered themselves. Then we didn't push a key to them and didn't count it in the `Constellation recover` step failing the test.
AWS, recover test: https://github.com/edgelesssys/constellation/actions/runs/5753138424 and https://github.com/edgelesssys/constellation/actions/runs/5753706243/job/15597486830
Since this is intended to fix a flake, I'll additionally monitor the test over the following days.
=> ci: fix recover test

cli/internal/cmd/pathprefix/BUILD.bazel, disk-mapper/internal/diskencryption/BUILD.bazel, internal/sigstore/keyselect/BUILD.bazel
Some build rules became stale after moving / deleting go packages.
This can currently not be automatically cleaned up by gazelle, since it will only update existing build rules but never remove a build rule.
I'm working on a linter test to find those cases in the CI.
- bazel: remove stale build rules
=> bazel: remove stale build rules

.github/actions/e2e_test/action.yml, .github/workflows/e2e-test-manual.yml, .github/workflows/e2e-test-release.yml, .github/workflows/e2e-test-weekly.yml, .github/workflows/e2e-upgrade.yml
We currently hardcode the region/zone we run our e2e tests in.
CSP resources in our default regions may be exhausted, causing our tests to fail, or we might want to simply test in other regions, e.g. to avoid zonal quota limits in our subscription.
- Make region/zone configurable in e2e tests
- Users can input anything right now, invalid input will result in errors during IAM create
- For empty input, our old default region/zone is used
e2e test GCP using default zone (empty regionZone field): https://github.com/edgelesssys/constellation/actions/runs/5819355990
e2e test AWS using eu-west-1b as zone: https://github.com/edgelesssys/constellation/actions/runs/5819736713
=> ci: allow setting region/zone for e2e tests

.github/workflows/e2e-upgrade.yml
- Fix default value being set to `true` for sending notifications on failure
=> ci: correctly default to false for upgrade e2e notifications

cli/internal/cmd/init.go
In https://github.com/edgelesssys/constellation/pull/2181 the output of `constellation init` was changed to include the path to a clusters kubeconfig file as an absolute path to avoid issues if a user provided their workspace as an absolute path, instead of relative to their current directory.
- Don't prefix the path of the kubeconfig with current workspace, instead just use absolute path for admin conf
=> cli: correctly print absolute path for kubeconfig

internal/cloud/aws/aws.go, internal/cloud/aws/aws_test.go
- When listing AWS instances, use the InstanceId as name. 
This aligns the behavior with the `Self()` function (line 99, same file).  
Note that this change does not break anything ans is essentially a NOP, as we currently never read the Name field after we've listed instances.
=> cloud: use instanceid as name in aws

cli/internal/helm/upgrade.go, internal/semver/semver.go
Helm upgrades never checked if the CSI chart we want to upgrade to was equal to the version of the CLI.
In practice, this should have only occurred under very rare circumstances, if ever: constellationServices and the constellationOperators charts would have to be previously successfully upgrade to the version set in a users config file. The upgrade then had to be aborted before the CSI charts could be upgrade. If a user now changes their CLI version, `constellation upgrade apply` will upgrade the CSI chart to a different version than specified in the config.
- Add a new function `isCLIVersionedRelease`, to check if a given helm release is one of the released directly versioned by the CLI.
- Fix the ordering of versions in error messages returned by the `semver` package
=> cli: fix version check for CSI chart

.github/workflows/e2e-upgrade.yml
- Remove check for `event_name`
- From what I can tell, it does not seem to do what we thought it does
- What I think is happening: When `e2e-upgrade` is called by another workflow, the variable will not be set to `workflow_call`, but inherit the value from the calling workflow, e.g. `workflow_dispatch` for manually triggered runs, or `scheduled` for scheduled runs.
- I'm not 100% sure on this, so for now I would like to keep the `inputs.scheduled` workaround
[e2e test with debug output](https://github.com/edgelesssys/constellation/actions/runs/5853425805/job/15867727552#step:23:1)
=> ci: fix notify trigger in e2e upgrade workflow

cli/internal/terraform/terraform/aws/main.tf
- Add role (worker/control-plane) to the EC2 instance as we also do on the other CSPs.
Upgrade tests: https://github.com/edgelesssys/constellation/actions/runs/5653649494
https://github.com/edgelesssys/constellation/actions/runs/5833130850/job/15819883482
=> cli: add role to aws instance name

.github/actions/setup_bazel/action.yml
- ci: set bazel build event stream timeout to 600s
[This is recommended by buildbuddy](https://www.buildbuddy.io/docs/troubleshooting-slow-upload/#the-build-event-protocol-upload-timed-out)
=> ci: set bazel build event stream timeout to 600s

cli/internal/helm/upgrade.go
A bug introduced in #2177 allowed chart upgrades with invalid upgrade errors.
-
=> cli: only allow chart upgrades with greater version

cli/internal/cloudcmd/terraform.go, cli/internal/cmd/BUILD.bazel, cli/internal/cmd/upgradeapply.go, cli/internal/cmd/upgradeapply_test.go, cli/internal/cmd/upgradecheck.go, cli/internal/cmd/upgradecheck_test.go
- we don't need to acquire and pass the imageRef to the terraform during terraform migration. Any changes to it are ignored anyway. We upgrade the VM image of the cluster through the NodeVersion and the operator.
=> upgrade: don't pass vm image

.github/actions/setup_bazel/action.yml
Most flags set in the bazelrc in CI are always applicable, so we set them with the common prefix.
- ci: set bazlrc options for "common" instead of "build" if they are common
- [Building things in Baze (`bazel build`)](https://github.com/edgelesssys/constellation/actions/runs/5864790389)
- [Running tests in Bazel (`bazel test`)](https://github.com/edgelesssys/constellation/actions/runs/5864802030)
- [Executing things with Bazel (`bazel run`)](https://github.com/edgelesssys/constellation/actions/runs/5864779742)
=> ci: set bazlrc options for "common" instead of "build" if they are common

cli/internal/cmd/upgradeapply.go, cli/internal/kubernetes/upgrade.go
Fixes a bug from #2177.
After an upgrade with wrong attestation config (i.e. no updated measurments), it is not possible to update the join-config with the correct values through another upgrade. Reason: we don't allow upgrades with the same version.
- update the join-config manually when the attestation config changes
Verified in dogfooding cluster, that the config is properly updated during upgrade
=> cli: update join-config manually during upgrade

bazel/ci/govulncheck.sh.in
- Use new -C flag from govulncheck v1.0.0 release
=> bazel: use -C flag in govulncheck ci

.bazelrc
The "common" setting is less specific and can be overwritten by later settings that have the granularity of "common" or finer (e.g. "build"). Fixes bug where disk cache wasn't disabled in GitHub runners.
- bazel: set most options to "common" in bazelrc
=> bazel: set most options to "common" in bazelrc

cli/internal/cloudcmd/serviceaccount.go, cli/internal/cmd/configfetchmeasurements.go, cli/internal/cmd/configgenerate.go, cli/internal/cmd/create.go, cli/internal/cmd/iamcreate.go, cli/internal/cmd/iamdestroy.go, cli/internal/cmd/init.go, cli/internal/cmd/init_test.go, cli/internal/cmd/miniup.go, cli/internal/cmd/pathprefix/pathprefix.go, cli/internal/cmd/recover.go, cli/internal/cmd/terminate.go, cli/internal/cmd/upgradeapply.go, cli/internal/cmd/verify.go
`PathPrefixer.PrefixPath` should only be used to prefix printable paths (paths that are not used to access files).
`constellation upgrade apply` used the `PathPrefixer` to add a workspace prefix when loading the master secret when upgrading a cluster's helm charts.
This causes errors when using the `--workspace/-C` flag during `constellation upgrade apply`.
- Remove usage of `PathPrefixer` when accessing the master secret
- Rename `PathPrefixer`'s `PrefixPath` method to `PrefixPrintablePath` and add additional warnings to further highlight this function should only be used to generate printable paths.
=> cli: fix incorrect file path for master secret during upgrades when using workspace flag

cli/internal/terraform/terraform.go
Starting with v1.6, Terraform will be licensed under BUSL. v1.5 will get critical security updates until end of 2023.
- Limit Terraform version to open-source releases until it's clear how we proceed.
=> deps: limit Terraform version to FOSS releases

cli/internal/cloudcmd/terraform.go, cli/internal/terraform/terraform/aws/variables.tf
Fixes a bug from #2211.
The current TF validation on AWS prevents an empty value set during an upgrade. Similarly, Azure also doesn't allow empty strings.
- insert placeholder values for the imageRef during an upgrade
=> cli: fix upgrade by passing placeholder values for images

CMakeLists.txt, WORKSPACE.bazel, bazel/ci/BUILD.bazel, bazel/envtest/BUILD.bazel, bazel/toolchains/k8s.bzl, csi/test/BUILD.bazel, disk-mapper/internal/test/BUILD.bazel, internal/api/attestationconfigapi/test/BUILD.bazel, internal/kms/test/BUILD.bazel, internal/license/BUILD.bazel, internal/sigstore/BUILD.bazel, operators/constellation-node-operator/BUILD.bazel, operators/constellation-node-operator/Makefile, operators/constellation-node-operator/controllers/BUILD.bazel, operators/constellation-node-operator/sgreconciler/BUILD.bazel
- operators: migrate envtests to Bazel
- [Unit test that also runs the envtests now](https://github.com/edgelesssys/constellation/actions/runs/5883407749)
=> operators: migrate envtests to Bazel

.github/actions/e2e_recover/action.yml
- Change the waiting condition for the shut-down node to `ready=Unknown` (which is the value for a node waiting to re-join the cluster)
- Add some verbosity to this step
Recover run: https://github.com/edgelesssys/constellation/actions/runs/5892097768
=> ci: fix recover wait condition

cli/internal/cloudcmd/clients.go, cli/internal/cloudcmd/clients_test.go, cli/internal/cloudcmd/create.go, cli/internal/cloudcmd/iam.go, cli/internal/terraform/terraform.go, cli/internal/terraform/terraform_test.go, cli/internal/upgrade/iammigrate.go, cli/internal/upgrade/iammigrate_test.go, cli/internal/upgrade/terraform.go, cli/internal/upgrade/terraform_test.go
Preliminary clean up of the terraform CLI package to prepare for future reworks.
- Reorder Functions in `cli/internal/terraform/terraform.go` in accordance with [our guidelines](https://github.com/edgelesssys/wiki/blob/master/company/gostyle.md#order-of-elements-in-a-source-file)
- Rename `CreateCluster` and `ApplyIAMConfig` to `ApplyCluster` and `ApplyIAM`
- reduce some code duplication
<!-- (uncomment if applicable)
@malt3 I removed some commented out code in the manual state migration function. Not sure if we want to keep this in the future, or if this part was already obsolete for a while. Please review
=> cli: clean up terraform package

bazel/devbuild/BUILD.bazel
I made Bazel stricter and now, we have to set `@@YQ@@` to point to yq that is actually guaranteed to exist.
- bazel: use yq from runfiles in devbuild
=> bazel: use yq from runfiles in devbuild

bazel/devbuild/prepare_developer_workspace.sh.in
@msanft Includes other than baselib must always be placed under the source check.
=> bazel: fix ordering of injects

dev-docs/workflows/deprecations.md
We have discussed how we want to handle deprecations in the past. IIRC we are breaking with what we discussed in v2.10.0. I think we also said that our policy is not binding for the moment. 
- Document how we handle deprecations.
=> docs: add note on how we handle deprecations

docs/docs/workflows/sbom.md, docs/docs/workflows/verify-cli.md, docs/versioned_docs/version-2.0/workflows/verify-cli.md, docs/versioned_docs/version-2.1/workflows/verify-cli.md, docs/versioned_docs/version-2.10/workflows/sbom.md, docs/versioned_docs/version-2.10/workflows/verify-cli.md, docs/versioned_docs/version-2.2/workflows/sbom.md, docs/versioned_docs/version-2.2/workflows/verify-cli.md, docs/versioned_docs/version-2.3/workflows/sbom.md, docs/versioned_docs/version-2.3/workflows/verify-cli.md, docs/versioned_docs/version-2.4/workflows/sbom.md, docs/versioned_docs/version-2.4/workflows/verify-cli.md, docs/versioned_docs/version-2.5/workflows/sbom.md, docs/versioned_docs/version-2.5/workflows/verify-cli.md, docs/versioned_docs/version-2.6/workflows/sbom.md, docs/versioned_docs/version-2.6/workflows/verify-cli.md, docs/versioned_docs/version-2.7/workflows/sbom.md, docs/versioned_docs/version-2.7/workflows/verify-cli.md, docs/versioned_docs/version-2.8/workflows/sbom.md, docs/versioned_docs/version-2.8/workflows/verify-cli.md, docs/versioned_docs/version-2.9/workflows/sbom.md, docs/versioned_docs/version-2.9/workflows/verify-cli.md
Sigstore updated their website again.
All documentation is now found under `docs.sigstore.dev/docs/<topic>` instead of the previous `docs.sigstore.dev/<topic>`, breaking all of our sigstore links.
- Update the sigstore links to include `/docs/`
=> docs: fix sigstore doc links
