edgelesssys/constellation

- cli/internal/cmd/upgradecheck.go
- cli/internal/cmd/upgradecheck_test.go
- internal/semver/semver.go
During `constellation upgrade check`, the Constellation image version, and Kubernetes version are validated to be valid semantic versions, yet we continue passing them around as regular strings.
- Enforce both versions to be semver by using the concrete data type
> cli: parse image and k8s versions as semver

- .github/actions/gcpccm_vers_to_build/findvers.sh
- .github/workflows/build-ccm-gcp.yml
Previous output of findvers.sh would be [""] in case no version were found, now the output is []. Also, GitHub cannot handle empty arrays in the matrix field, so we add an if and check if the array is empty.
> ci: fix ccm build when no new version are found

- cli/internal/cloudcmd/rollback.go
- cli/internal/cloudcmd/rollback_test.go
If `constellation create` fails due to terraform validation (the validation specified in variables.tf) triggering an abort, a constellation-terraform folder is left behind. No resources should be created at this point and thus no state folder should be left behind.
Example:
set cluster name with capital letter in gcp:
```
An error occurred: terraform apply: exit status 1
Error: "name" ("adrianGCP-5cfcb64c") doesn't match regexp "^(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)$"
```
- defer the cleanup of tf files
- [AB#3282](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3282)
> cli: cleanup terraform files when create fails

- .github/workflows/on-release.yml
- .github/workflows/release.yml
- dev-docs/workflows/release.md
The release pipeline needed manual cleanup steps to be able to retrigger it. This PR makes the pipeline retriggerable without manual steps.
- force push the release tag to overwrite the existing one
- don't fail when there is no update commit for the container images 
- missing AWS permissions for image deletion are in a PR of the respective repo.
- skip the find temporary branch step in the `on-release` workflow, which failed in all past releases.
> ci: idempotent release pipeline

- docs/versioned_docs/version-2.10/overview/performance/application.md
- docs/versioned_docs/version-2.10/overview/performance/io.md
- docs/versioned_docs/version-2.10/overview/performance/performance.md
some of the fixes made during review of #2271 haven't been applied to 2.10
> docs: publish fixes in performance section to 2.10

- cli/internal/terraform/terraform/aws/modules/instance_group/main.tf
- image/mkosi.conf.d/mkosi.conf
There are problems with VMs not booting on AWS. AWS told us that this is related to us dynamically disabling SMT inside the image. The recommended way is to disable it via the hypervisor, using `cpu_options`.
There may also be other problems that they are still investigating. 
The changes in this PR will increase our launch success rate in the meanwhile.
- Set `threads_per_core` to 1 in AWS launch_templates. Disables SMT through the VMM.
- Remove `nosmt` from kernel cmdline.
- Add `idle=poll` to cmdline. AWS recommendation.
- Best test run _ever_: https://github.com/edgelesssys/constellation/actions/runs/6008714416
- `mitigation=auto idle=poll`: https://github.com/edgelesssys/constellation/actions/runs/6021239936
- Testruns: 1/20 nodes failed. Worst run with `nosmt` I have seen: 6/10 …
> cli: disable smt on AWS via cpu_options

- .github/workflows/release-cli.yml
Since release `v2.9.0`, our releases incorrectly use our development cosign key to sign the sboms for that release, and also include the public part of that development cosign key in the release.
Update the `release-cli`  workflow to not rely on branch naming, but on workflow inputs for selecting the correct key.
* This was already done for signing the CLI binaries
Other release artifacts (CLI binaries) are not affected, as they were correctly signed using our production key
> ci: fix incorrect signing key for sbom signature and wrong public key in release artifacts

- cli/internal/cmd/verify.go
- cli/internal/cmd/verify_test.go
The code in `cli/internal/cmd/verify.go` removes a trailing newline by reslicing the certificate slice unconditionally to remove the last byte.
This panics if the given certificate is `nil`, and causes errors if the certificate does not end with a newline.
- Use `strings.TrimSpace` to correctly remove white spaces at the front and end of a given certificate
- Return an error if no certificates could be parsed
> cli: correctly trim white spaces for certificates in `verify`

- .github/failure_project_template.md
e2e tests may leave behind resources when terminating the cluster fails.
In that case, manual cleanup by a dev is required.
- Add a hint about cleaning up left over resources if terminate failed
> ci: add hint about cleaning up lingering resources on failure

- image/mkosi.conf.d/mkosi.aws.conf
- image/mkosi.conf.d/mkosi.azure.conf
- image/mkosi.conf.d/mkosi.conf
- image/mkosi.conf.d/mkosi.gcp.conf
- image/mkosi.conf.d/mkosi.openstack.conf
- image/mkosi.conf.d/mkosi.qemu.conf
Amends #2291. We don't want these options on other CSPs. This is temporary until AWS fixed some background issues.
- Move `idle=poll mitigations=auto` options to aws-only config
- Pipeline: https://github.com/edgelesssys/constellation/actions/runs/6070948107
> image: move idle and nosmt to aws-only images

- cli/internal/terraform/terraform/aws/modules/instance_group/main.tf
AWS asked us to disable these options temporarily until they resolve some internal issues that sometimes prevents these instances from starting.
- Disable nosmt via VMM for a while.
> cli: temporarily disable nosmt via VMM 

- .github/workflows/aws-snp-launchmeasurement.yml
We have added our sev-snp-measure port to the virtee org. To keep it up to date we should use it.
- Switch from our sev-snp-measure-go repo to the virtee one. Pipeline [run](https://github.com/edgelesssys/constellation/actions/runs/6086300397) :green_circle:
> ci: use virtee project for sev-snp-measure-go

- csi/cryptmapper/cryptmapper.go
- csi/cryptmapper/cryptmapper_test.go
- csi/test/BUILD.bazel
- csi/test/mount_integration_test.go
The common constructor for the `deviceMapper` interface used by the CSI package is defined in our internal package only.
This causes problems for external dependents of the CSI package.
Additionally, there is no good reason to let the caller handle setting up cryptsetup.
- Let the constructor (`cryptmapper.New()`) handle setting up cryptsetup, instead of expecting an interface which implements the required functionality.
> csi: let constructor take care of setting up cryptsetup

- cli/internal/cloudcmd/iamupgrade.go
- cli/internal/cmd/iamupgradeapply.go
- cli/internal/cmd/upgradeapply.go
cli/cloudcmd is our package to bundle CSP-specific code. In our current design all CSP-agnostic code should live in cli/cmd, csp-specific code should be bundled in cli/cloudcmd.
This separates responsibilities. User interaction & input validation <--> csp interaction.
- move remaining CSP code from `init` and `upgradeapply` to `cloudcmd`
- [AB#3286](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3286)
> cli: move CSP logic to cloudcmd

- cli/internal/cmd/BUILD.bazel
- cli/internal/cmd/verify.go
- cli/internal/cmd/verify_test.go
- internal/attestation/aws/snp/validator.go
`constellation verify` prints a list of expected and actual measurements for a Constellation cluster.
Currently, the measurements in that list are not ordered.
- Print the measurements list ordered
- Remove redundant nil check in parsing code
- Fix incorrect error check when parsing PCRs from quote
- Fix a potential panic in the AWS validator code by introducing a slice length check when checking for an image's tpm2 support
- [AB#3411](https://dev.azure.com/Edgeless/Edgeless/_workitems/edit/3411)
> cli: print ordered measurements list during `verify`

- cli/internal/cmd/init_test.go
- cli/internal/cmd/upgradeapply.go
- cli/internal/helm/BUILD.bazel
- cli/internal/helm/action.go
- cli/internal/helm/chartutil.go
- cli/internal/helm/helm.go
`constellation upgrade apply` upgrades and/or installs chart to the cluster.
What charts are used for this, and how the values look can be rather hard to determine for a user, making potential troubleshooting difficult.
Additionally, the values used to apply these upgrades are not shown or saved anywhere.
- Save the charts, values and override values used during `constellation upgrade apply` to disk before running said operation
- Adds a new `SaveCharts` method to the Helm interface
- Charts are saved to `constellation-upgrade/upgrade-<timestamp>-<uid>`
- Each action defines a `SaveChart` method that is called by the interface
- install actions save their charts to `<dir>/helm-install`
- upgrade actions save their charts to `<dir>/helm-upgrade`
- override values (values generated by our …
> cli: save Helm charts to disk before running upgrades

- cli/internal/cmd/BUILD.bazel
- cli/internal/cmd/upgradeapply.go
- cli/internal/cmd/upgradeapply_test.go
- cli/internal/kubecmd/kubecmd.go
- cli/internal/kubecmd/kubecmd_test.go
- docs/docs/reference/cli.md
Currently it is not possible to select / deselect specific upgrades (terraform, helm, k8s, node image).
- add a new `--skip-phases` flag that accepts a list of phases to skip during the upgrade
- [AB#3407](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3407)
> cli: new flag to skip phases of upgrade

- cli/internal/helm/BUILD.bazel
- cli/internal/helm/action.go
- cli/internal/helm/retryaction.go
- cli/internal/helm/retryaction_test.go
We have retry logic for installing/upgrading helm charts.
However, we have a rather restrictive check for what errors are retried in case installing/upgrading fails.
- Instead of checking for specific errors to retry, retry on any error
- If we ever encounter some error cases we definitely don't want to retry, we should just add exceptions for these errors, instead of keeping a list of errors we want to retry.
- [AB#3432](https://dev.azure.com/Edgeless/Edgeless/_workitems/edit/3432)
> cli: retry helm apply on any error

- cli/internal/helm/BUILD.bazel
- cli/internal/helm/actionfactory.go
- cli/internal/helm/actionfactory_test.go
- cli/internal/helm/helm.go
- cli/internal/helm/helm_test.go
- cli/internal/helm/loader.go
Our CLI embeds the Helm charts used for the Kubernetes cluster.
For charts we pull in from external providers, the version of these charts is dependent on the version we set for that release.
For charts we package ourselves, the version of the chart is dependent on the version of the CLI binary.
For these charts, on `constellation upgrade apply`, we should only apply an upgrade if the version specifies in the user's config is an upgrade to the version running in their cluster. And only to the version set in the config.
For this the Helm code is currently missing some checks.
- Check if config version matches CLI version when installing new charts
- Check if version specified in config is a valid upgrade to the chart running in the Kubernetes cluster
- If a chart is a valid upgrade, check …
> cli: check chart versions against target version in users config before upgrading

- docs/docs/workflows/upgrade.md
> doc: `--skip-flag` in the upgrade workflow

- operators/constellation-node-operator/internal/executor/executor.go
- operators/constellation-node-operator/internal/executor/executor_test.go
A data race was found during unit tests in the CI pipeline:
```
188WARNING: DATA RACE
189Read at 0x00c0004fdd70 by goroutine 156:
190 github.com/edgelesssys/constellation/v2/operators/constellation-node-operator/v2/internal/executor.(*Executor).Trigger()
191 operators/constellation-node-operator/internal/executor/executor.go:178 +0x44
192 github.com/edgelesssys/constellation/v2/operators/constellation-node-operator/v2/internal/executor.(*Executor).Trigger-fm()
193 <autogenerated>:1 +0x1d
194 github.com/edgelesssys/constellation/v2/operators/constellation-node-operator/v2/sgreconciler.glob..func1.2.1()
195 operators/constellation-node-operator/sgreconciler/scalinggroup_controller_env_test.go:57 +0x234
196 github.com/onsi/ginkgo/v2/internal.extractBodyFunction.func3()
197 …
```
> node-operator: fix data race in executor

- .github/actions/e2e_verify/action.yml
- internal/api/attestationconfigapi/cli/main.go
Package was renamed in #2293.
Fixes 376bc6d39fd3bbb72d962f5ebe56158f9d493638.
- Renamed remaining occurrences of `hack/configapi`.
- [failing e2e test](https://github.com/edgelesssys/constellation/actions/runs/6128529557/job/16635682883)
> api: rename references to moved hack/configapi

- bazel/ci/BUILD.bazel
While experimenting with remote execution in Bazel, I noticed that buildifier itself calls `xargs`, which is not guaranteed to be installed on the remote builder.
- bazel: never run buildifier in remote execution
> bazel: never run buildifier in remote execution

- .github/actions/deploy_logcollection/action.yml
- Helm is not installed per default on macos runners, see: https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md
fixes: https://github.com/edgelesssys/constellation/commit/60bf770e62bc989133f58edaaf2705f7db43ad88
GHA run: https://github.com/edgelesssys/constellation/actions/runs/6144612499/job/16684592795 and https://github.com/edgelesssys/constellation/actions/runs/6144612499/job/16684593051
> ci: install helm when deploying log collection

- cli/internal/cmd/configgenerate.go
- cli/internal/cmd/configgenerate_test.go
- cli/internal/cmd/init.go
- cli/internal/cmd/init_test.go
- cli/internal/cmd/upgradeapply.go
- cli/internal/cmd/upgradeapply_test.go
- cli/internal/cmd/upgradecheck.go
- cli/internal/helm/BUILD.bazel
- cli/internal/helm/helm.go
- cli/internal/helm/helm_test.go
- cli/internal/helm/loader.go
- cli/internal/helm/loader_test.go
- cli/internal/kubecmd/kubecmd.go
- cli/internal/kubecmd/kubecmd_test.go
- docs/docs/reference/cli.md
- e2e/internal/upgrade/upgrade_test.go
- internal/config/BUILD.bazel
- internal/config/config.go
- internal/config/config_doc.go
- internal/config/config_test.go
- internal/config/migration/BUILD.bazel
- internal/config/migration/migration.go
- internal/config/validation.go
- internal/versions/versions.go
Storing the K8s version as validated type saves a lot of parameter passing and centralizes the validation logic
- store K8s version as weakly validated type (ignoring patch version) in the config
- ~allow to specify K8s version without patch (e.g. 1.27) as valid config value and resolve the patch version~
- allow to specify a patch version in `config generate` (e.g. 1.27.4)
- add more unit test cases
- [AB#3374](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3374)
> cli: store kubernetes version as strong type in config

- bazel/container/container.sh
Some internal CLI tools, like the `versionsapi` client, utilize the AWS API. For some operations, it thus is necessary to have AWS credentials available in the Bazel environment. Our Bazel container didn't have the AWS credentials available previously.
- Mount the AWS credential / config directory into the Bazel container.
> bazel: mount AWS credentials file into Bazel container

- debugd/internal/debugd/metadata/cloudprovider/cloudprovider.go
- debugd/internal/debugd/metadata/cloudprovider/cloudprovider_test.go
- debugd/internal/debugd/metadata/scheduler.go
- debugd/internal/debugd/metadata/scheduler_test.go
- debugd/internal/debugd/server/server.go
- debugd/internal/debugd/server/server_test.go
- debugd/internal/filetransfer/filetransfer.go
- debugd/internal/filetransfer/filetransfer_test.go
- Remove unnecessary `CanSend()` function, as `receiveFinished` is already checked during `transfer.SendFiles()`
- Adds loadbalancer IP to the ips to try to get the bootstrapper from
The second change is necessary as in the future, all nodes in the cluster are not allowed to send out unencrypted traffic to the node CIDR.
> debugd: send requests over lb

- cli/internal/terraform/terraform/aws/modules/instance_group/main.tf
We still have boot problems on AWS SEV-SNP-enabled machines. The problem is already forwarded and AWS is working on it, but in the meantime, we want to reduce CI failures caused by this. These failures are tracked in [AB#3299](https://dev.azure.com/Edgeless/Edgeless/_workitems/edit/3299/) and [AB#3412](https://dev.azure.com/Edgeless/Edgeless/_workitems/edit/3412).
- Temporarily increase the timeout for ASG availability on SEV-SNP-enabled machines. This should allow the VMM to restart machines that fail to boot.
- E2E test runs:
1. https://github.com/edgelesssys/constellation/actions/runs/6198924762
2. https://github.com/edgelesssys/constellation/actions/runs/6198922072
3. https://github.com/edgelesssys/constellation/actions/runs/6198918897
> cli: temporarily increase AWS ASG creation timeout

- .github/actions/e2e_test/action.yml
Tests with a `nop` on non-debug clusters directly terminate after deploying the logcollection to the cluster. Even if the pods are ready, they get terminated before being able to propagate their metrics / logs to OpenSearch. 
- Add a 30 second wait after deploying the logcollection when a test has a `nop` payload.
- [E2E run](https://github.com/edgelesssys/constellation/actions/runs/6246592076)
> ci: fix racy logcollection in `nop` tests

- .github/workflows/e2e-test-daily.yml
- .github/workflows/e2e-test-weekly.yml
Our daily tests were not reporting failures of the MiniConstellation test.
Add the "Notify about failure" hook to the MiniConstellation test
- `refStream` and `kubernetesVersion` are left empty in the notification, since they are not configurable in the test.
> ci: add missing notification hook for MiniConstellation test

- bootstrapper/cmd/bootstrapper/run.go
- bootstrapper/internal/joinclient/joinclient.go
- bootstrapper/internal/joinclient/joinclient_test.go
- cli/internal/terraform/terraform/aws/main.tf
- cli/internal/terraform/terraform/azure/main.tf
- cli/internal/terraform/terraform/gcp/main.tf
- disk-mapper/internal/rejoinclient/BUILD.bazel
- disk-mapper/internal/rejoinclient/rejoinclient.go
- disk-mapper/internal/rejoinclient/rejoinclient_test.go
- disk-mapper/internal/setup/interface.go
- internal/cloud/metadata/BUILD.bazel
- internal/cloud/metadata/metadata.go
This is needed since the upcoming node-to-node strict mode does not allow traffic which is not WireGuard encrypted by Cilium (with the exception of etcd). Therefore nodes cannot join via directly talking to another node.
- add join port to all LBs
- Let rejoinclient and joinclient join over LB (if available, otherwise fallback to node VPC IPs)
The fallback is needed to still support Miniconstellation as it does not have an LB.
e2e upgrade tests: 
azure: https://github.com/edgelesssys/constellation/actions/runs/6237449241
gcp: https://github.com/edgelesssys/constellation/actions/runs/6238824048
aws: https://github.com/edgelesssys/constellation/actions/runs/6238826460
> join: join over lb if available

- .github/actions/e2e_benchmark/action.yml
- Fixes a non-fatal error in the CI: https://github.com/edgelesssys/constellation/actions/runs/6281230175/job/17059392328#step:3:3857
``` 
error: unknown flag: --short
See 'kubectl version --help' for usage.
```
kubectl deprecated and now removed the flag. The default is now `--short`. Therefore simply removing the flag referencing the new version.
e2e test: https://github.com/edgelesssys/constellation/actions/runs/6297531935
> ci: fix kubectl version retrieval

- cli/internal/cmd/init.go
- cli/internal/cmd/init_test.go
During `constellation init`, if the init request and the subsequent log collection fails, the CLI reports "Fetched bootstrapper logs are stored in ...".
This is not true, since the log collection itself failed.
Properly report log collection failed, if it did.
[AB#3272](https://dev.azure.com/Edgeless/Edgeless/_workitems/edit/3272)
> cli: report log collection failure to user

- .github/workflows/e2e-test-release.yml
- macos runners use a different `sed` therefore the verify test breaks currently on macos: https://github.com/edgelesssys/constellation/actions/runs/6184742123/job/16788978904
Since we only need one test for macos anyway, removing the verify test for now. Still, we should fix the test for macos at some point.
> ci: remove verify test for macos during release

- cli/internal/cloudcmd/clients.go
- cli/internal/cloudcmd/clients_test.go
- cli/internal/cloudcmd/clusterupgrade.go
- cli/internal/cloudcmd/clusterupgrade_test.go
- cli/internal/cloudcmd/create.go
- cli/internal/cmd/upgradeapply.go
- cli/internal/cmd/upgradeapply_test.go
- cli/internal/terraform/terraform.go
- cli/internal/terraform/terraform_test.go
This is part of the effort to support self-managed infrastructure and decouple from Terraform state.
- removes the dependency on Terraform apply output throughout the CLI. Instead the new infrastructure state is used (#2281).
- [AB#3430](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3430)
> cli: remove TF ApplyOutput dependency in CLI

- cli/internal/cmd/terminate.go
- cli/internal/cmd/terminate_test.go
- Remove dangling `constellation-state.yaml` file during `constellation terminate`.
> cli: remove state on terminate

- .github/actions/cdbg_deploy/action.yml
- .github/actions/constellation_create/action.yml
- .github/actions/deploy_debugd/action.yml
- .github/actions/e2e_test/action.yml
- .github/workflows/build-logcollector-images.yml
- debugd/filebeat/BUILD.bazel
- debugd/filebeat/Dockerfile
- debugd/filebeat/assets.go
- debugd/filebeat/inputs.yml
- debugd/filebeat/templates/filebeat.yml
- debugd/internal/debugd/logcollector/logcollector.go
- debugd/metricbeat/Dockerfile
- dev-docs/workflows/logcollection.md
- hack/logcollector/internal/filebeat.go
- internal/osimage/aws/awsupload.go
- internal/versions/versions.go
Logcollection in the debugd was not working for quite some time for various reasons, such as missing IAM permissions and broken container images. No debugd-logs are available for quite some time in [OpenSearch](https://search-e2e-logs-y46renozy42lcojbvrt3qq7csm.eu-central-1.es.amazonaws.com/_dashboards/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-3M,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'74517cf0-6442-11ed-acf1-47dda8fdfbbb',key:metadata.deployment-type,negate:!f,params:(query:debugd),type:phrase),query:(match_phrase:(metadata.deployment-type:debugd)))),index:'74517cf0-6442-11ed-acf1-47dda8fdfbbb',interval:auto,query:(language:kuery,query:''),sort:!())).
- Patch the permissions of the UAMI …
> ci: fix debugd logcollection

- .github/workflows/test-unittest.yml
This keeps the report in focus for PRs with longer discussion and repeated pushes.
> ci: recreate coverage report on push

- .github/workflows/on-release.yml
- The `complete-release-branch-transaction` step failed since it was not able to pull from a detached head state
Merged with the step after that since we don't force push anyway so there is no need to check.
> ci: don't pull from detached head

- cli/internal/cmd/BUILD.bazel
- cli/internal/cmd/init.go
- cli/internal/cmd/init_test.go
Since the bootstrapper discovers the load balancer itself and does not receives the endpoint used from the init request, it is possible that the bootstrapper "sees the world differently than the CLI". 
This is especially true for privateIP deployments. Since the lb discovers the internal load balancer but the CLI side might want to query another endpoint which redirects to the internal load balancer. Therefore the client side should always use the cluster endpoint from the `constellation-id.json` or `constellation-state.yaml` file as those are the truths for the CLI. 
The kubeconfig is generated by the cluster. Therefore it points to the endpoint used by the cluster. When we receive the kubeconfig we therefore replace it's endpoint with the endpoint from the `constellation-id.json`. 
- We …
> init: overwrite kubeconfig address

- .github/workflows/build-os-image.yml
Currently, the pipeline fails most of the time with "no space left on device".
This indicates either a full disk or a full tmpfs (memory constraint).
Using a larger runner solves this issue.
- ci: use larger runners for os image pipeline
- [pipeline run](https://github.com/edgelesssys/constellation/actions/runs/6403114423)
> ci: use larger runners for os image pipeline

- .github/actionlint.yaml
- bazel/toolchains/linux_kernel.bzl
This is currently the latest 6.1 LTS release.
- deps: update linux kernel to 6.1.55
- [build pipeline](https://github.com/edgelesssys/constellation/actions/runs/6403427526)
> deps: update linux kernel to 6.1.55

- csi/cryptmapper/cryptmapper.go
- csi/cryptmapper/cryptmapper_test.go
- csi/test/mount_integration_test.go
The `csi/cryptmapper` package currently has some problems with concurrency.
More specifically, if one application has multiple threads making use of the functions offered by the package, calling `Open` or `Close` can return errors as the device in use was not yet freed by another thread.
- Work on a fresh [`cryptsetup` instance](https://github.com/edgelesssys/constellation/blob/7e899d09c401f96cee8e3192aeb9486c2d8e4d35/internal/cryptsetup/cryptsetup.go#L52) in every function
- Allow idempotent calling of `Open`
- If a mapped device with the name already exists (and the integrity device exists) simply return without an error
- Required for a new release of the CSI drivers
- Does not affect the currently released driver versions
> csi: fix concurrent use of `cryptmapper` package

- cli/internal/terraform/terraform/aws/main.tf
- cli/internal/terraform/terraform/azure/main.tf
- cli/internal/terraform/terraform/azure/modules/load_balancer_backend/main.tf
- cli/internal/terraform/terraform/azure/modules/load_balancer_backend/variables.tf
- cli/internal/terraform/terraform/gcp/main.tf
Separated Terraform refactorings from https://github.com/edgelesssys/constellation/pull/2388
- Put all ports into a list in order to save some lines
- [AB#2767](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/2767)
- [AB#2765](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/2765)
> Refactor Terraform to have all ports in a list

- cli/internal/cloudcmd/clients_test.go
- cli/internal/cmd/create.go
- cli/internal/cmd/create_test.go
- cli/internal/cmd/iamdestroy.go
- cli/internal/cmd/iamdestroy_test.go
- cli/internal/cmd/init.go
- cli/internal/cmd/init_test.go
- cli/internal/cmd/minidown.go
- cli/internal/cmd/miniup.go
- cli/internal/cmd/recover.go
- cli/internal/cmd/recover_test.go
- cli/internal/cmd/terminate.go
- cli/internal/cmd/terminate_test.go
- cli/internal/cmd/upgradeapply.go
- cli/internal/cmd/upgradeapply_test.go
- cli/internal/cmd/verify.go
- cli/internal/cmd/verify_test.go
- cli/internal/state/state.go
- cli/internal/state/state_test.go
- cli/internal/terraform/terraform.go
- cli/internal/terraform/terraform_test.go
- debugd/internal/cdbg/cmd/deploy.go
- docs/docs/architecture/orchestration.md
- docs/docs/reference/cli.md
- docs/docs/workflows/create.md
- docs/docs/workflows/recovery.md
- docs/docs/workflows/terminate.md
- docs/docs/workflows/verify-cluster.md
- internal/file/file.go
- internal/file/file_test.go
As #2395 introduces the switch from the id-file to the more extensive state-file, the ID-file should be removed from the existing commands. (i.e. `constellation init` and `constellation upgrade apply`)
- Write to the state-file during `constellation create`
- Read / Write from / to the state-file during `constellation init`
- Move the ID-file to a backup on `constellation upgrade apply` (i.e. when upgrading from a id-file version to a state-file version)
- Read from state-file instead of ID-file in `constellation verify`
- Read from state-file instead of ID-file in `constellation mini`
- Read from state-file instead of ID-file in `constellation recover`
- Read from state-file instead of ID-file in `constellation terminate`
- Read from state-file instead of ID-file in `constellation iam …
> cli: remove id-file

- .github/actions/pick_assignee/action.yml
- .github/teams_payload_template.json
E2E failures are often not triaged in time, team of possible assignees does not reflect all engineers.
- Add `msanft` as possible e2e assignee
> ci: add msanft to list of possible e2e assignees

- .github/actions/e2e_test/action.yml
Our current default region (North Europe) seems to be having issues when creating CVM Scale sets.
- Switch to West US until the problems are resolved
- [AB#3477](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3477)
- [AB#3471](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3471)
- [e2e run on Azure](https://github.com/edgelesssys/constellation/actions/runs/6429041162/job/17457355179)
> ci: use West US region for Azure e2e test until problems are resolved

- cli/internal/cmd/BUILD.bazel
- cli/internal/cmd/verify.go
- cli/internal/cmd/verify_test.go
- docs/docs/reference/cli.md
- internal/verify/BUILD.bazel
- internal/verify/verify.go
Motivated by https://github.com/edgelesssys/constellation/pull/2357, this PR provides a JSON output format as communication interface between the CLI and the attestationconfigapi upload tool through a new flag `constellation verify --output json`.
- new internal pkg `verify` to provide the types for JSON serialization. 
- new `--output` flag to support 'json' for Azure
- moved `--raw` to `--output raw`
- [AB#3462](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3462)
~To only obtain the JSON output needed for the upload tool, some lines need to be omitted:
`./constellation verify --force --json | tail -n +3 | head -n -1`~
> cli: new flag for JSON output of `constellation verify`

- .github/actions/setup_bazel/action.yml
E2e tests fail because we run out of disk space. Let's try to free up space!
- ci: free up disk space on GitHub hosted runners
> ci: free up disk space on GitHub hosted runners

- s3proxy/cmd/main.go
- s3proxy/deploy/deployment-s3proxy.yaml
- s3proxy/internal/router/BUILD.bazel
- s3proxy/internal/router/handler.go
- s3proxy/internal/router/router.go
Currently the s3proxy MVP does not implement encryption for multipart uploads. This may lead to inadvertent data leakage, if users are not aware of this. Thus this PR changes the default behavior to a more secure one: block multipart uploads. The old behavior can still be triggered by supplying the new flag `--allow-multipart`.
- Move handler functions into separate file
- Change default behavior of s3proxy to block multipart upload requests
- Add `--allow-multipart` flag to trigger the previous default behavior
- Manually tested through mint e2e tests + filestash.
> s3proxy: add allow-multipart flag

- docs/docs/architecture/encrypted-storage.md
- docs/docs/getting-started/examples/filstash-s3proxy.md
- docs/docs/workflows/s3proxy.md
- docs/sidebars.js
- docs/styles/Vocab/constellation/accept.txt
- s3proxy/deploy/deployment-s3proxy.yaml
s3proxy is now merged to main. This PR adds user-facing docs for deployment, background information and the example application Filestash.
- Add user-facing docs for s3proxy. Includes link to instructions for example application.
> s3proxy: add new page to documentation

- .github/actions/e2e_verify/action.yml
-
- [AB#3484](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3484)
> cli: fix broken verify test due to jq usage insteaf of yq

- renovate.json5
Renovate fails to update minor versions of certain packages like filebeat-debugd.
- add `"ignoreUnstable": false` to the package Rule that matches "ghcr.io/edgelesssys" to allow updates to later prereleases.
- add comments to the renovate.json5 file that make it easier to navigate.
- This will cause renovate to want to update some packages to unstable versions
- affected packages:
- [ghcr.io/edgelesssys/gcp-guest-agent](https://github.com/edgelesssys/constellation/pkgs/container/gcp-guest-agent)
- [ghcr.io/edgelesssys/constellation/logstash-debugd](https://github.com/edgelesssys/constellation/pkgs/container/constellation%2Flogstash-debugd)
- [ghcr.io/edgelesssys/constellation/filebeat-debugd](https://github.com/edgelesssys/constellation/pkgs/container/constellation%2Ffilebeat-debugd)
- …
> renovate: relax rules to allow updates to minor versions

- docs/docs/getting-started/examples/filestash-s3proxy.md
- docs/versioned_docs/version-2.12/getting-started/examples/filestash-s3proxy.md
- s3proxy/deploy/deployment-s3proxy.yaml
Extend docs slightly. 
- Add all currently defined regions to filestash example.
- Add more explanation what to do with the example.
> docs: extend filestash example with more regions

- .github/actions/constellation_iam_create/action.yml
- .github/actions/e2e_test/action.yml
Action was missing quotation marks for the region value when creating an IAM configuration.
This causes an error when setting the region to something containing spaces, e.g. "North Europe".
- Add quotation marks
- Remove deprecated flag compatibility
- [Azure e2e test](https://github.com/edgelesssys/constellation/actions/runs/6534236026/job/17741011457) with region set to `North Europe`
> ci: add missing quotation marks for region flag

- cli/internal/cmd/configgenerate.go
- cli/internal/cmd/configgenerate_test.go
- cli/internal/cmd/create.go
- cli/internal/cmd/create_test.go
- docs/docs/getting-started/first-steps.md
- docs/docs/reference/cli.md
As a first step towards self-managed infrastructure support, it is necessary to provide the user with a way to generate a state file before the normal cluster creation would happen (as that step is not performed in the self-managed infrastructure case). 
- Generate the state file for the specific CSP during `constellation config generate <CSP>` 
- Read from the exisiting state-file during `constellation create`, this is not necessary as the file would be overwritten, but creates a more coherent flow between Constellation-managed and self-managed infrastructure.
- [AB#3490](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3490)
> cli: generate state file during `constellation config generate` 

- .github/workflows/build-os-image.yml
- image/measured-boot/cmd/BUILD.bazel
A proper solution would be parsing the EFI partition directly in Go and not shelling out to `systemd-dissect` with root privileges. This needs more time.
When using `systemd-dissect` from nixpkgs, we see the following error:
```
(10:03:53) INFO: Running command line: /bin/bash -c 'sudo -E bazel-bin/image/measured-boot/cmd/cmd_/cmd /home/runner/work/constellation/constellation/constellation.raw /home/runner/work/constellation/constellation/pcrs-aws-aws-nitro-tpm.json'
failed to extract UKI: failed to extract /efi/EFI/BOOT/BOOTX64.EFI from /home/runner/work/constellation/constellation/constellation.raw: exit status 1
Failed to open source path '/efi/EFI/BOOT/BOOTX64.EFI' in image '/home/runner/work/constellation/constellation/constellation.raw': No such file or directory
```
- image: use …
> image: use systemd-dissect from the host when calculating measurements

- .github/workflows/build-os-image.yml
- image/base/BUILD.bazel
- image/base/mkosi.conf
- image/base/mkosi.postinst
- image/initrd/mkosi.conf
- image/system/BUILD.bazel
- image/system/mkosi.conf
For reproducibility reasons, the final OS image does not ship the rpm database in sqlite format. For supply chain security and license compliance reasons, we want to keep the rpm database of os images as a detached build artifact. We now ship a reproducible, human readable manifest of installed rpms in the image under "/usr/share/constellation/packagemanifest" and upload the full rpm database as a build artifact (rpmdb.tar).
- image: add rpm database as build output
> image: add rpm database as build output

- cli/internal/cmd/create.go
- cli/internal/cmd/create_test.go
- cli/internal/state/state.go
- cli/internal/state/state_test.go
https://github.com/edgelesssys/constellation/pull/2455 adds creation of the state file to `constellation config generate`.
However, not having an empty state file during `constellation create` now causes an error once the command finish executing.
- Use a `CreateOrRead` function to either read an existing state file, or create a new one during `constellation create` to ensure there is always a valid file
> cli: create or read state file during `constellation create`

- .github/workflows/build-os-image.yml
This line was lost during a rebase.
- ci: build rpmdb explicitly
> ci: build rpmdb explicitly

- cli/internal/helm/BUILD.bazel
- cli/internal/helm/charts/edgeless/constellation-services/charts/ccm/templates/gcp-clusterrolebinding.yaml
- cli/internal/helm/testdata/GCP/constellation-services/charts/ccm/templates/gcp-clusterrolebinding.yaml
The GCP CCM hard-codes an outdated ClusterRole. We need to give it the required permissions again. See: https://github.com/kubernetes/cloud-provider-gcp/issues/611
- Add a ClusterRoleBinding linking the used service account to the role we use for the CCMs on other CSPs.
> helm: add gcp ccm permissions for internal LBs

- .github/actions/constellation_create/action.yml
- .github/actions/e2e_recover/action.yml
- .github/actions/e2e_verify/action.yml
The CI was using the `--force` flag for CLI commands for a while.
Embedding the correct pseudo version in the binary has been fixed, so we can remove the flag.
- Remove `--force` flag from CLI commands in the CI
- [e2e verify test](https://github.com/edgelesssys/constellation/actions/runs/6574988510/job/17861160374)
- [e2e recover test](https://github.com/edgelesssys/constellation/actions/runs/6575610715/job/17863166013)
> ci: remove force flag from CLI commands

- cli/internal/cmd/init_test.go
The image version is compared to the cli version. The cli version is set during link time (depending on build settings it is either "v0.0.0", a release version (like "v2.12.0") or a pseudo version (like "v2.13.0-pre.0.20231020081051-5cd70ac58aa1"). We just set the image version in this test to the same variable to ensure it is stamped to the same value to pass validation.
- cli: set image version in tests to stamped binary version
> cli: set image version in tests to stamped binary version

- flake.lock
- flake.nix
Upstream (in systemd-repart) reproducibility issues were fixed[^1][^2].
We update nixpkgs to use a patched version of systemd-repart.
- nix: flake update
On my test systems, images are now fully reproducible.
As a reviewer, you can test this using the following steps:
```
git pull
git checkout deps/nix/flake-update
git rev-parse HEAD # should return 9ca2bf574d5105b4c61015d6417d02df9cd62b0c
bazel build //image/system:qemu_qemu-vtpm_stable
sha256sum bazel-bin/image/system/qemu_qemu-vtpm_stable/constellation.raw
```
[^1]: [systemd-repart hardlink store leaks into generated OS images](https://github.com/systemd/systemd/commit/6bbb893b90e2dcb05fb310ba4608f9c9dc587845)
[^2]: [systemd-repart vfat partitions use timestamps in local timezone of the …
> nix: flake update

- cli/internal/cloudcmd/create.go
- cli/internal/cloudcmd/rollback.go
- cli/internal/cloudcmd/rollback_test.go
Terraform does not care if `destroy` is called on an empty directory.
In that case it simply returns `nil`, so we can skip the extra check during `cloudcmd.Create`.
- Remove unnecessary rollback destroy guards form QEMU rollbacker
- Setup work for [AB#3288](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3288)
> cli: remove unnecessary check from QEMU rollbacker

- cli/internal/helm/loader_test.go
- cli/internal/state/state.go
- cli/internal/state/state_doc.go
- cli/internal/state/state_test.go
- cli/internal/terraform/terraform.go
- cli/internal/terraform/terraform/aws/main.tf
- cli/internal/terraform/terraform/aws/outputs.tf
- cli/internal/terraform/terraform/azure/main.tf
- cli/internal/terraform/terraform/azure/outputs.tf
- cli/internal/terraform/terraform/openstack/outputs.tf
- cli/internal/terraform/terraform/qemu/main.tf
- cli/internal/terraform/terraform/qemu/outputs.tf
- cli/internal/terraform/terraform_test.go
We need to expose the node CIDR of the Constellation so that we can use the value later (in https://github.com/edgelesssys/constellation/pull/2462) as a strict CIDR in the Cilium helm values.
- Always output the node CIDR and write into our state file
Upgrade test gcp: https://github.com/edgelesssys/constellation/actions/runs/6576667618
> terraform: always output node cidr

- cli/internal/kubecmd/kubecmd.go
- cli/internal/kubecmd/kubecmd_test.go
When initializing or upgrading a cluster we check if an an attestation config already exists.
For that we try to fetch it from the Kubernetes API with a retry limit.
On AWS we sometimes hit that limit after just creating the cluster.
- Increase retry limit from 5 to 20
- Fix range to display correct log message for retries
- [e2e failure ticket](https://github.com/orgs/edgelesssys/projects/3?pane=issue&itemId=42248164)
> cli: increase kubecmd retry limit

- internal/validation/BUILD.bazel
- internal/validation/constraints.go
- internal/validation/errors.go
- internal/validation/errors_test.go
- internal/validation/validation.go
- internal/validation/validation_test.go
We want to have a generic framework for document validation in Constellation, for use on the config and state file.
- Add a framework for config validation. A usage example can be found in [`validation_test.go`](https://github.com/edgelesssys/constellation/blob/0ee82ee88c6b0d1ebb52915881c502be7034e45c/internal/validation/validation_test.go)  and in the Go doc comments of the exported functions. If more thorough documentation on this is required, I can also prepare a page in the dev-docs.
- This PR uses quite hacky reflection to implement JSONPath traces of fields that fail validation. This approach is quite prone to errors, but is verified to work for all types tested in the unit tests. In case any type that you might want to validate is not covered by this, please let me know.
- …
> validation: add generic validation framework

- .github/workflows/test-tidy.yml
- .github/workflows/test-unittest.yml
Reverts edgelesssys/constellation#2452
This caused problems with the fix commits on renovate PRs. Reverting for now, needs revisit.
> Revert "ci: execute unit tests and tidy check against merge of PR branch and main"

- cli/internal/cloudcmd/clients.go
- cli/internal/cloudcmd/clusterupgrade.go
- cli/internal/cloudcmd/clusterupgrade_test.go
- cli/internal/cloudcmd/create.go
- cli/internal/cloudcmd/iam.go
- cli/internal/cloudcmd/iamupgrade.go
- cli/internal/cloudcmd/tfupgrade.go
- cli/internal/cloudcmd/tfupgrade_test.go
- cli/internal/cmd/create.go
- cli/internal/cmd/create_test.go
- cli/internal/terraform/loader.go
- cli/internal/terraform/loader_test.go
- cli/internal/terraform/terraform.go
- cli/internal/terraform/terraform_test.go
- internal/constants/constants.go
Our Terraform code currently only differs between upgrades and new creations when setting up the workspace.
To allow creating or upgrading a workspace using the same code, this PR aims to fix this difference by moving relevant code out of the Terraform package.
- Move backup creation of Terraform workspace from `terraform` package to `cloudcmd`
- Always allow overwriting files when setting up the Terraform workspace
- In case of upgrades, this is the behavior we want regardless
- In case of new creations, we ensure correct behavior by first checking that no Terraform state exists in the workspace during `constellation create`
- Use a constant to set the path of embedded Terraform files
- Preparation for [AB#3383](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitem …
> cli: refactor terraform code to be update/create agnostic

- .github/actions/constellation_create/action.yml
- .github/workflows/e2e-windows.yml
- cli/cmd/root.go
- cli/internal/cmd/apply.go
- cli/internal/cmd/apply_test.go
- cli/internal/cmd/init.go
- cli/internal/cmd/upgradeapply.go
- docs/docs/reference/cli.md
- e2e/internal/upgrade/upgrade_test.go
https://github.com/edgelesssys/constellation/pull/2449 replaces the backend code for `init` and `upgrade apply` with one common implementation.
This PR adds a new command to replace both `init` and `upgrade apply` with a single command.
- Add `constellation apply` command
- Mark `constellation init` and `constellation upgrade apply` as deprecated
- Use `constellation apply` in CI
- [AB#3494](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3494)
- [GCP e2e test](https://github.com/edgelesssys/constellation/actions/runs/6584992230)
- [e2e upgrade test](https://github.com/edgelesssys/constellation/actions/runs/6585561665)
- See [AB#3499](https://dev.azure.com/Edgeless/Edgeless/_workitems/edit/3499)
> cli: add `constellation apply` command to replace `init` and `upgrade apply`

- cli/internal/terraform/terraform/gcp/.terraform.lock.hcl
- cli/internal/terraform/terraform/gcp/main.tf
- cli/internal/terraform/terraform/gcp/modules/instance_group/main.tf
- cli/internal/terraform/terraform/gcp/modules/internal_load_balancer/main.tf
- cli/internal/terraform/terraform/gcp/modules/jump_host/main.tf
- cli/internal/terraform/terraform/gcp/modules/loadbalancer/main.tf
- cli/internal/terraform/terraform/iam/gcp/.terraform.lock.hcl
- cli/internal/terraform/terraform/iam/gcp/main.tf
Provider version `5.3.0` currently breaks upgrades from `v4`, so we can't use it without breaking upgrades from Constellation `v2.12` to `v2.13`.
- Revert provider from `v5.3.0` to `v4.83.0`
> terraform: revert GCP provider upgrade

- hack/logcollector/internal/templates/metricbeat/values-all-nodes.yml
- hack/logcollector/internal/templates/metricbeat/values-control-plane.yml
We recently ran into OOM kills on the metricbeat deployment (since metricbeat seems to be quite memory-hungry), causing issues when updating a cluster with metricbeat deployed.
- Remove the 200MiB default limit on the daemonset.
- [AB#3508](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3508)
> hack: don't limit memory in Metricbeat daemonset

- cli/internal/cmd/applyterraform.go
- cli/internal/terraform/terraform/azure/main.tf
Planning the Terraform migrations takes a decent amount of time, locking the terminal with no feedback to the user.
- Add a spinner to the planning of Terraform changes
- Remove the mention of "changes below" that are actually printed above the message
> cli: spinner for planning Terraform migrations

- cli/internal/cmd/apply.go
- cli/internal/cmd/apply_test.go
- cli/internal/cmd/upgradeapply_test.go
K8s and image skip flags were in the wrong order.
Init, certSANs, and AttestationConfig flags were not parsed by the command.
- Put flags in the correct order
- Parse missing flags
> cli: fix apply flag issues

- docs/docs/workflows/create.md
Self-managed infrastructure docs missed a few outputs that have to be present in the state file before `constellation apply`, as well as the necessary patch of the MAA provider policy.
- Update the docs to be aligned with what we do in our e2e workflow.
- [AB#3507](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3507)
> docs: align self-managed infrastructure docs with e2e worfklow

- image/base/mkosi.skeleton/usr/lib/sysctl.d/10-cilium.conf
- image/base/mkosi.skeleton/usr/lib/sysctl.d/99-zzz-override_cilium.conf
- Move the overrides to the place where cilium would write them (if we didn't have a read-only fs)
- Use all of ciliums sysctl overrides
Note that this moves the config from before the `50-default...` files in the directory to after it. 
Image build: https://github.com/edgelesssys/constellation/actions/runs/6667663251
This change is required for cilium's node-to-node encryption.
> image: use all of cilium's sysctl overrides

- cli/internal/cmd/apply.go
- cli/internal/cmd/applyterraform.go
- cli/internal/cmd/init_test.go
- cli/internal/cmd/upgradeapply_test.go
The apply command checks if a Terraform state exists in the current working directory, and if not, skips the Terraform phase.
However, during set up of the command, the directory is automatically created by `cloudcmd.NewClusterUpgrader`, meaning this check is always false, and we never skip the phase.
This causes problems with th self-managed infrastructure deployment when the phase is not manually skipped.
- Create the Terraform client on demand when the phase is not skipped.
> cli: only create Terraform client when needed

- debugd/metricbeat/templates/metricbeat.yml
To decrease Memory demands in our OpenSearch, we want to decrease the overall document count in our indices. Therefore, we can increase the period in which metrics are sent to OpenSearch by Metricbeat to sent documents less regularly.
- Decrease the period for OpenSearch collection to 60 seconds.
> ci: increase collection period for Metricbeat

- debugd/internal/debugd/logcollector/fields.go
The fields need to be allowed explicitly in the debugd, otherwise causing a [failure](https://github.com/edgelesssys/constellation/actions/runs/6701530441/job/18209115731#step:3:4793).
- Add the missing field.
> debugd: add missing `self-managed-infra` field

- debugd/internal/debugd/logcollector/logcollector.go
- debugd/logstash/templates/pipeline.conf
- hack/logcollector/cmd/template.go
- hack/logcollector/internal/logstash.go
OpenSearch cluster health was in a bad state previously, hence some improvements and optimizations are necessary. One of this is using bigger indices, which can impact search performance, but should drastically reduce needed JVM heap size.
- Seperate the Metrics and Logs indices, but only rotate them on a weekly basis. Ideally, we want to get between [10-30GB index size](https://opensearch.org/blog/optimize-opensearch-index-shard-size/). Possibly, follow-up adjustments to reach that will be necessary after an initial testing period. 
- Re-enable the Metricbeat deployment.
- [AB#3511](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3511)
> ci: separate logs and metrics indices

- .github/actions/constellation_destroy/action.yml
Self-managed `constellation_destroy` action fails if the state or the config file don't exist in the working directory.
Since the action should just be a NOP if no resources were created, we want to fix that
- use `rm -f` to ignore non existent files on destroy
> ci: force delete files on self-managed destroy

- cli/internal/terraform/terraform/aws/variables.tf
- internal/config/config.go
- internal/config/config_test.go
- internal/config/validation.go
On AWS, the bootstrapper crashes when the cluster name has an upper case name due to recent changes related to DNS cluster reference instead of IP.
This only happens on nightly images and not on v2.12.0.
```
Failed to collect logs from bootstrapper: rpc error: code = Unknown desc = kubeadm init: kubeadm init phase preflight failed (code 1) with: I1031 15:15:11.139446    5161
│ initconfiguration.go:255] loading configuration from "/tmp/kubeadm-init.546194692.yaml"
│ I1031 15:15:11.154487    5161 interface.go:432] Looking for default routes with IPv4 addresses
│ I1031 15:15:11.154503    5161 interface.go:437] Default route transits interface "ens5"
│ I1031 15:15:11.155331    5161 interface.go:209] Interface ens5 is up
│ I1031 15:15:11.155385    5161 interface.go:257] Interface "ens5" has 2 …
```
> cli: fix invalid upper case name on AWS

- cli/internal/state/state.go
`ownerID` is currently unused as functionality for it are not implemented
- don't run validation on the `ownerID` field of the state file
> cli: don't validate unused ownerID field

- image/measured-boot/cmd/BUILD.bazel
- image/measured-boot/cmd/main.go
Since systemd 254, the efi partition is expected to be mounted under `/boot` (if both mount points `/boot` and `/efi` exist in the image).
After accounting for this new behavior, we can use `systemd-dissect` from nixpkgs.
- image: use dissect from nix
> image: use dissect from nix

- .github/actions/e2e_malicious_join/action.yml
- e2e/malicious-join/BUILD.bazel
- e2e/malicious-join/job.yaml
- e2e/malicious-join/job_template.sh.in
- e2e/malicious-join/malicious-join.go
The malicious join test was using structured logging for some parts, and relied on structured output to parse the final result.
However, large parts of the test used simple `fmt.Print` style logging.
This could result in some inconsistencies depending when the logs are flushed.
- Use structured logging for all output
- Correctly build, tag, upload and use malicious-join images from the branch the test is run on
- [e2e failure](https://github.com/orgs/edgelesssys/projects/3/views/1?pane=issue&itemId=43626559)
- [e2e test](https://github.com/edgelesssys/constellation/actions/runs/6772885265)
> ci: use structured logging for all parts of the malicious-join test

- internal/file/file.go
- Fix incorrect usage of `path.Dir()` (instead of `filepath.Dir()`) that breaks directory backups for the Constellation CLI on Windows.
- This effectively made the CLI unable to run `constellation upgrade apply` on Windows systems
- Detected because we run the Terraform state backup as part of `constellation apply`, which is called during the initialization process
- [e2e test Windows](https://github.com/edgelesssys/constellation/actions/runs/6786682549)
> [Windows] cli: fix incorrect filepath separator causing upgrades to fail

- internal/attestation/azure/snp/BUILD.bazel
- internal/attestation/azure/snp/validator_test.go
The unittest was flacky as testcases with valid certs in the getter property lead to those certs being cached inside the go-sev-guest/trust pkg. Other testcases however, want to explicitly use invalid certs. The cache interferes with this by serving the valid certs from other testcases.
The fact that current main is broken can be seen by running: `bazel test --runs_per_test=100 //internal/attestation/azure/snp:snp_test`
Running the same command on this PR should succeed.
- Clear certificate cache during each test
- Move shared required object into test body
> attestation: clear certificate cache in azure snp unittest

- internal/validation/constraints.go
Doing a DNS lookup may fail for domain names that are valid but currently not assigned.
The old test also breaks inside the bazel sandbox.
Investigation for why this did not break the pipeline is underway ([AB#3530](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3530)).
- Use a regex instead of doing a DNS lookup to validate DNS names.
> validation: use regex instead of dns lookup for DNSName validation

- .github/actions/constellation_create/action.yml
- .github/actions/e2e_test/action.yml
- .github/workflows/e2e-upgrade.yml
- .github/workflows/e2e-windows.yml
Windows e2e test was missing a bazel set-up action in the notify-failure job, causing a failure when creating an issue for a failed test.
- Add a "set up bazel" action to the job
- Enable buildbuddy cache for upgrade e2e-test
- Remove whitespace
- [Windows e2e test failure](https://github.com/edgelesssys/constellation/actions/runs/6797084954)
- [failure issue](https://github.com/orgs/edgelesssys/projects/3?pane=issue&itemId=44005076)
> ci: fix failure issue creation for Windows e2e test

- .github/actions/e2e_verify/action.yml
The sev-guest library used in v2.12.0 of Constellation included a debug `fmt.Println` statement in the verification code for SNP values. This breaks the SNP version upload since the stdout output of `constellation verify -o json` is no longer valid json.
Since v2.12.0 also didn't properly marshal all certificates, I opted to not fix the output file in case we are running a test with a v2.12 CLI, but simply not run the version upload
- Don't upload TCB versions from Azure e2e verify tests for CLI versions v2.12
- [Here](https://github.com/edgelesssys/constellation/actions/runs/6799481770/job/18486776613#step:6:4825) is the error in a run on main using `v2.12.0` CLI
- [Here](https://github.com/edgelesssys/constellation/actions/runs/6752370284/job/18357662122#step:3:5102) we can see the …
> ci: dont run SNP version upload on v2.12.0 CLI tests

- .github/actions/upload_terraform_module/action.yml
- terraform/aws-constellation/variables.tf
- terraform/azure-constellation/variables.tf
- terraform/constellation-cluster/variables.tf
- terraform/gcp-constellation/variables.tf
#2566 added stamping for the image version as a default for the Terraform variable when the Terraform module is packaged to be released.
- Add default values to the image variables in the convenience modules, making them optional inputs. Leaving them empty will then cause the stamped image version to be selected.
> terraform: allow image to be empty

- operators/constellation-node-operator/controllers/pendingnode_controller.go
This reverts commit 5267ad0f08de57e67c2713d8ec45ad2f8041ee3e.
- We need to revert this. With this patch we've observed 30+ nodes being scheduled during the upgrade of a 1:1 cluster on GCP. This presumably happens because if a node is not found then it's state within the operator is "Terminated". This likely happens in the first seconds of the new node being created. With is patch the "Terminated" node already has reached its goal. It's true goal was joining the cluster though. 
The idea before (and after) this patch is that the joiningNode has a deadline set until it must join the cluster. Otherwise it's goal is set to "Leaving" which is reached if the node never joined the cluster because it was shut down. This should've already handled the AWS case.
> Revert "operator: always delete terminated pending nodes (#2545)"

- cli/internal/cmd/apply.go
- cli/internal/state/BUILD.bazel
- cli/internal/state/state.go
We added validation for the statefile after I implemented changes which depended on there being no validation (at least before the state is updated/re-crated from the new terrafom).
- Add a `Migrate` function to the state file to implement all future migrations.
- Add migrations to pass the validation for the new fields.
- We need to also revert https://github.com/edgelesssys/constellation/pull/2545. Otherwise we schedule 30+ nodes during the upgrade of a 1:1 cluster.
> state: add migration for `IPCidrNode` and `InClusterEndpoint`

- .github/actions/notify_e2e_failure/action.yml
- .github/actions/notify_teams/action.yml
- .github/teams_payload_template.json
- .github/workflows/build-os-image-scheduled.yml
- .github/workflows/e2e-test-daily.yml
- .github/workflows/e2e-test-weekly.yml
- .github/workflows/e2e-upgrade.yml
- .github/workflows/e2e-windows.yml
- Scheduled image build failures require manual actions to be noticed
- Teams notifications should be a bit more modular
- Separate the teams notification into its own action
- By itself, the action send a notification with some very structure
- Title
- Subtitle
- Name of the assignee and ping in Teams. (Assignee should be chosen by the caller)
- Clickable button that links to the workflow run triggering the notification
- Additional fields may be set by the caller
- Additional buttons may be added by the caller
- Call teams notification action if scheduled image build fails
- [AB#3329](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3329)
- [AB#3362](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3362)
- Looks like …
> ci: refactor teams notification action

- .github/workflows/e2e-test-release.yml
The release pipeline failed due to a missing `runner` value, which left the matrix at "waiting for pending jobs" even though it should be started in parallel. Once all other jobs were finished, the error `Error when evaluating 'runs-on' for job 'e2e-tests'. edgelesssys/constellation/.github/workflows/e2e-test-release.yml@246b9ce069acb0933ea8d2c786383b3e46d26936 (Line: 191, Col: 14): Unexpected value ''` was thrown.
- Add the missing `runner` value to the matrix.
- [E2E Test (Pre-Fix)](https://github.com/edgelesssys/constellation/actions/runs/6874144304)
- [E2E Test (Post-Fix)](https://github.com/edgelesssys/constellation/actions/runs/6874179262)
> ci: add missing `runner` value to s3proxy test

- .github/actions/setup_bazel_nix/action.yml
We often need additional tools in GitHub Actions Workflow jobs. This extension to the `setup_bazel_nix` action adds a new parameter `nixTools` which (if provided) will install a list of tools for the duration of the job and add their store paths to the `GITHUB_PATH` env.
- ci: allow jobs to install tools from pinned nixpkgs
- [test run](https://github.com/edgelesssys/constellation/actions/runs/6891198755/job/18745750123) (prints cowsay and ponysay output)
> ci: allow jobs to install tools from pinned nixpkgs

- .github/actions/constellation_create/action.yml
- cli/internal/cloudcmd/apply.go
- cli/internal/cloudcmd/tfplan.go
- cli/internal/cloudcmd/tfplan_test.go
- cli/internal/cmd/apply.go
- cli/internal/cmd/apply_test.go
- cli/internal/cmd/applyterraform.go
- cli/internal/cmd/cloud.go
- cli/internal/cmd/cloud_test.go
- cli/internal/cmd/create.go
- cli/internal/cmd/create_test.go
- cli/internal/cmd/init_test.go
- cli/internal/cmd/recover_test.go
- cli/internal/cmd/upgradeapply_test.go
- cli/internal/cmd/verify_test.go
- cli/internal/state/BUILD.bazel
- cli/internal/state/state.go
- docs/docs/architecture/attestation.md
- docs/docs/architecture/orchestration.md
- docs/docs/getting-started/first-steps-local.md
- docs/docs/getting-started/first-steps.md
- docs/docs/getting-started/install.md
- docs/docs/reference/terraform.md
- docs/docs/workflows/create.md
- docs/docs/workflows/lb.md
- docs/docs/workflows/terminate.md
- docs/docs/workflows/troubleshooting.md
- docs/docs/workflows/trusted-launch.md
The `constellation apply` command should be the one command to manage a Constellation cluster.
This PR brings the functionality of another command (`constellation create`) to `apply`.
- Use the logic of the `constellation apply` for creating new cluster, replacing `constellation create`
- [AB#3288](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3288)
- Unchanged for now, should be adapted to use just `constellation apply` in the future
- https://github.com/edgelesssys/constellation/pull/2551
> cli: enable `constellation apply` to create new clusters

- cli/internal/cmd/minidown.go
- cli/internal/cmd/miniup.go
- cli/internal/libvirt/libvirt.go
- internal/constants/constants.go
`mini up` was still using separate code to create and initialize the cluster.
- Use `constellation apply` to set up and initialize miniConstellation clusters
- We could think about deprecating `mini up` and `mini down` as a whole, and simply add a miniConstellation target for `config generate`, since `apply` now takes care of creating and initializing a cluster in one command.
> cli: use apply command to start mini cluster

- bazel/release/BUILD.bazel
- bazel/toolchains/oci_deps.bzl
- e2e/malicious-join/BUILD.bazel
Reverts edgelesssys/constellation#2616
The change breaks building the CLI for windows.
See https://github.com/bazel-contrib/rules_oci/issues/420 for the upstream issue.
> Revert "deps: update rules_oci to 1.4.2"

- cli/internal/cloudcmd/apply_test.go
Executing the unit tests on Mac fails because of 
```
creating terraform variables: creation of a QEMU based Constellation is not supported for darwin/arm64
```
- change provider to Azure
> ci: fix unsupported qemu in tests on mac

- cli/internal/cmd/status.go
- cli/internal/cmd/status_test.go
- internal/config/config_test.go
When executing `constellation status` without a present config file, the command panics because the config reading error is not caught.
This issue occurs on 2.13 and also 2.12.
- return config read error
> cli: fix panic in status cmd without conf file

- .github/workflows/e2e-test.yml
Resources were not cleaned up correctly since the destroy action was not configured for self-managed infrastructure
- Correctly clean up resources
- closes https://github.com/edgelesssys/issues/issues/79
- [e2e test](https://github.com/edgelesssys/constellation/actions/runs/6968930299)
> ci: correctly clean up resource in self-managed infra tests

- .bazelrc
- .github/workflows/test-integration.yml
- CMakeLists.txt
- internal/license/BUILD.bazel
- internal/license/integration/BUILD.bazel
- internal/license/integration/license_integration_test.go
Our integration tests are currently executed with CMake, but we would like to consolidate everything to Bazel.
Integration test Bazel targets are tagged with `integration`. Tests tagged with `intregration` are not run in the standard configuration, but we introduce a new Bazel config (`integration`) which also includes these tests. For compatibility with legacy `go test`, the new config also applies the `integration` gotag. A second config (`integration-only`) can be used if only integration tests should be run.
This PR also migrates a first integration test, `//internal/license:license_integration_test`, to the new format.
- [AB#3067](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3067)
> ci: prepare Bazel for integration testing

- internal/api/fetcher/fetcher.go
We create a custom `*http.Transport`, which, per default, uses a `nil` proxy (i.e. no proxy). In contrast to the `http.DefaultClient`, which uses the `http.ProxyFromEnvironment` proxy. Therefore, it does not respect the `HTTP_PROXY` and `HTTPS_PROXY` environment variables, as seen in #2634.
- Set the proxy to `http.ProxyFromEnvironment`.
The fix can be verified by setting `HTTPS_PROXY=http://8.8.8.8` or something else which does not proxy. Then, navigate to a directory with a Constellation workspace, and executing `bazel run //hack/image-fetch`. Prior to this change, this would run normally as the traffic is not routed through the proxy. With the change, it will timeout as `8.8.8.8` does not proxy.
> api: respect `HTTP(S)_PROXY` environment variable

- rfc/001-key-derivation.md
- rfc/002-proof-of-ownership.md
- rfc/003-secure-software-distribution.md
- rfc/004-updates.md
- rfc/005-external-kms.md
- rfc/006-reproducible-builds.md
- rfc/007-version-api.md
- rfc/008-apis.md
- rfc/009-image-api.md
- rfc/010-cli-api.md
- rfc/011-attestation-config.md
- rfc/012-canonical-endpoint-dns.md
- rfc/013-state-file.md
- rfc/014-terraform-provider.md
Now that we have a growing number of RFCs, having numeric identifiers for them makes it easier to refer to them and allows an intuitive understanding of the history of changes, without resorting to `git blame`.
Assign a numeric ID to all existing RFCs. IDs are handed out incrementally, starting from 001, to the RFCs sorted by first appearance in the repo. 999 RFC IDs should be enough for anybody.
This change was generated by the following script:
```bash
cd rfc
birthday() {
git log --reverse --format=%at -- "$1" | head -n1
}
order() {
while read -r line
do
echo "$(birthday $line) $line"
done | sort -n | cut -f 2 -d' '
}
n=1
find . -type f | order | \
while read -r line
do
file="$(basename "$line")"
sed -i "1s/# /# RFC $(printf "%03d" $n): /" "$file"
git mv "$file" "$(printf "%03d" …
```
> rfc: add numeric ids to existing RFCs

- internal/helm/actionfactory.go
- internal/helm/helm_test.go
- internal/kubecmd/BUILD.bazel
- internal/kubecmd/kubecmd.go
- internal/kubecmd/kubecmd_test.go
- Allow Cilium to jump minor versions from v1.12 to v1.15
- If a nodeversion upgrade takes place (from v2.13.x) then remove all the konnectivity setting from the kubeadm config map. Otherwise the KubeAPI pods try to mount e.g. the Konnectivity UDS which we no longer provider through the bootstrapper
> Fix Konnectivity migration

- .github/workflows/e2e-test-daily.yml
- .github/workflows/e2e-test-release.yml
- .github/workflows/e2e-test-tf-module.yml
- .github/workflows/e2e-test-weekly.yml
- .github/workflows/e2e-test.yml
- .github/workflows/e2e-upgrade.yml
https://github.com/edgelesssys/constellation/pull/2601 moved around some service accounts.
https://github.com/edgelesssys/constellation/pull/2629 was not rebased on these changes.
This caused now deleted service accounts to still be used by the CI
- Swap outdated service accounts for new ones
- Remove placeholders for the `GCP_E2E_PROJECT` secret. We decided to not use a hardcoded secret for this in the future as it makes updating the CI difficult
> ci: fix serivce accounts introduced by merge

- .github/actions/gh_create_issue/create_issue.sh
- .github/workflows/e2e-test-tf-module.yml
Terraform module e2e test was missing a notification on failure
- Add notification to Terraform module e2e test
- Fix an issue with the gh issue creation that would stop the script on empty values for project ticket tags
- Empty values are now ignored
- [Failing workflow run](https://github.com/edgelesssys/constellation/actions/runs/7017785595/job/19091809291#step:23:1)
- [The issue that was created by the workflow](https://github.com/edgelesssys/issues/issues/98)
- [project ticket tagging problem in a workflow](https://github.com/edgelesssys/constellation/actions/runs/7017244480/job/19090140725#step:23:170)
> ci: add notify hook to Terraform module test

- .github/actions/constellation_create/action.yml
- .github/actions/e2e_verify/action.yml
v2.13 doesnt support JSON flag for `constellation verify` on AWS yet.
So we shouldnt run the e2e verify test with that flag set.
- Don't use JSON output if CLI version == v2.13
- [e2e verify AWS with v2.13 CLI/image](https://github.com/edgelesssys/constellation/actions/runs/7005955389)
> ci: only run verify with JSON on v2.14 or newer

- .github/actions/find_latest_image/action.yml
If an image reference is specified in the E2E test, we want to use it instead of finding an image through the versionsapi. This was intended, but not correctly implemented previously.
- Use the given image reference if set.
> ci: use given image if set

- cli/internal/cmd/apply.go
- cli/internal/cmd/apply_test.go
- cli/internal/cmd/applyhelm.go
- internal/helm/action.go
- internal/helm/actionfactory.go
- internal/helm/actionfactory_test.go
- internal/helm/helm.go
- internal/helm/loader.go
- internal/helm/loader_test.go
- internal/helm/release.go
- internal/helm/versionlister.go
The CLI, more specifically the `apply` command, has a (hidden) "--timeout" flag which was originally used to configure the timeout when upgrading helm charts.
This flag has been nonfunctional for some time now.
- re-enable the "--timeout" flag for `constellation apply`
- rename "--timeout" to "--helm-timeout" to more accurately indicate what it is used for
- Set the only internally used `Release` struct to private
- [AB#3357](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3357)
- Not sure if we want to add this to the changelog as the flag was, and still is, hidden by default
> helm: re-enable timeout flag

- cli/internal/cmd/miniup.go
The (hidden) `--timeout` flag for `constellation apply` was renamed to `--helm-timeout` in https://github.com/edgelesssys/constellation/pull/2658
This was not reflected for `constellation mini up`
- Fix flag naming for `constellation mini up`
- [e2e test](https://github.com/edgelesssys/constellation/actions/runs/7043956979)
- Fixes https://github.com/edgelesssys/issues/issues/102
> cli: fix renamed flag for mini-constellation

- cli/internal/cmd/create.go
- cli/internal/cmd/init.go
- cli/internal/cmd/upgradeapply.go
- Add `helm-timeout` flag to the cmd wrappers for `create`, `init`, and `upgrade apply`
- fixes https://github.com/edgelesssys/issues/issues/106
> cli: fix helm-timeout flags for deprecated commands

- .github/actions/build_cli/action.yml
- .github/actions/self_managed_create/action.yml
After https://github.com/edgelesssys/constellation/blob/eea36d2669527ef3a4ca5a5a34695cdfe0db9901/.github/actions/e2e_test/action.yml#L151 the CLI should be in the PATH. Either via downloading or by building it.
- Don't call local constellation `./constellation` but global `constellation`.
- Failed test on main: https://github.com/edgelesssys/constellation/actions/runs/7082838671/job/19274233541
- (Hopefully) successful test on this branch: https://github.com/edgelesssys/constellation/actions/runs/7085412241
> ci: fix constellation cli path

- internal/helm/values.go
By default, Cilium's tc filters are added add the highest priority, which makes it impossible to add any tc filters of our own (because the Cilium eBPF programs don't return to the filter chain).
Two near-future use cases would benefit from changing this:
* Network testing could add counting filters to interfaces and observe e.g. violations of encryption policy.
* The VPN Helm chart could add a filter policy that drops packets on the "physical" interface before they can leak to the CSP.
- Drop the priority of Cilium tc programs to 50.
> helm: deprioritize Cilium tc filters

- CODEOWNERS
- bazel/ci/BUILD.bazel
- bazel/ci/version_info_gen.sh.in
- docs/docs/architecture/versions.md
- hack/versioninfogen/BUILD.bazel
- hack/versioninfogen/main.go
We would like to offer a table displaying which versions of Kubernetes are supported in any given Constellation release.
- Add a new section to `/architecture/versions.md`  which contains a list of supported Kubernetes versions for a given Constellation release
- Automatically update the supported version list on `bazel run //:generate`
- [AB#3198](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3198)
- [AB#3199](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3199)
> docs: add Kubernetes version support list

- .github/workflows/sync-terraform-docs.yml
Publishing a Terraform provider in the hashicorp Terraform registry requires a specially set up GitHub repo containing docs and releases of the provider binaries.
Since we want to keep our source code in the mono-repo, we want to only sync the docs to the provider repo, and publish release binaries whenever we create new releases for Constellation.
- Automatically keep docs in the provider repo in sync with the provider docs in the mono-repo
- [AB#3593](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3593)
- [Pull request created by this action](https://github.com/edgelesssys/terraform-provider-constellation/pull/1)
> terraform-provider: sync provider docs to Terraform provider repository

- .github/workflows/test-integration.yml
- CMakeLists.txt
- WORKSPACE.bazel
- csi/test/BUILD.bazel
- csi/test/mount_integration_test.go
- disk-mapper/internal/test/BUILD.bazel
- disk-mapper/internal/test/integration_test.go
This is a follow-up for #2631. Now, we can finally retire CMake completely.
- bazel: migrate all integration tests (and retire CMakeLists.txt)
- [AB#3067](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3067)
> bazel: migrate all integration tests (and retire CMakeLists.txt)

- docs/docs/reference/slsa.md
- docs/styles/Vocab/constellation/accept.txt
- docs/versioned_docs/version-2.10/reference/slsa.md
- docs/versioned_docs/version-2.11/reference/slsa.md
- docs/versioned_docs/version-2.12/reference/slsa.md
- docs/versioned_docs/version-2.13/reference/slsa.md
- docs/versioned_docs/version-2.3/reference/slsa.md
- docs/versioned_docs/version-2.4/reference/slsa.md
- docs/versioned_docs/version-2.5/reference/slsa.md
- docs/versioned_docs/version-2.6/reference/slsa.md
- docs/versioned_docs/version-2.7/reference/slsa.md
- docs/versioned_docs/version-2.8/reference/slsa.md
- docs/versioned_docs/version-2.9/reference/slsa.md
We removed our CMakeLists.txt file on main, yet our docs still had a link to said file on our main branch.
- Replace the link to CMakeLists.txt on main with either a versioned link (v2.7 or older), or a reference to our bazel CI folder
> docs: replace reference to CMakeList on main branch with versioned link or Bazel

- cli/internal/cloudcmd/tfvars.go
- cli/internal/terraform/variables.go
- cli/internal/terraform/variables_test.go
- internal/config/config.go
Multiple of the weekly e2e tests failed due to the Azure marketplace image being set to an object with empty fields, but not an null object, which breaks the assumptions of the Terraform infrastructure module.
- (Unrelated) Make the Config default to `false` instead of `null` for `useMarketplaceImage`, which makes more sense for the user.
- Use a pointer for the marketplace image variable, making it default to `nil` / `null` in Terraform, which satisfies:
https://github.com/edgelesssys/constellation/blob/0247f4f6baa57b19e51bcffd62a26577b7e21a8e/terraform/infrastructure/azure/modules/scale_set/main.tf#L76-L93
- [Post-fix E2E Test](https://github.com/edgelesssys/constellation/actions/runs/7153418937)
> terraform: fix Azure marketplace image defaults

- .github/actions/e2e_test/action.yml
- Remove invalid input (masterSecret) when calling e2e recover test
- See [any e2e recover test](https://github.com/edgelesssys/constellation/actions/runs/7148627410/job/19469856168#step:3:9638). Note that this doesnt cause a failure, just prints a warning
> ci: remove invalid input for recover action

- bazel/bazelrc/ci.bazelrc
Comparison of output for a failed build. Old setup produces >3k lines of unhelpful messages:
https://github.com/edgelesssys/constellation/actions/runs/7165242775/job/19506817413
Without curses support, we get <400 lines with relevant details:
https://github.com/edgelesssys/constellation/actions/runs/7166031624/job/19509201790
> ci: disable curses support

- internal/installer/installer.go
- internal/installer/installer_test.go
RFC 015 proposes adding a new type of KubernetesComponent in the form of data URLs. As the content of these is deterministic, it does not make sense to also generate a hash for them and then check it in the installer.
- Omit the file hash check if the expected hash is empty. This does not change existing behaviour, but will be used by data URLs (to be introduced).
> installer: make hash checking optional

- upgrade-agent/internal/server/server.go
`kubeadm upgrade plan` takes an optional positional argument for the target Kubernetes version [1], which is documented as
> To skip the internet check, pass in the optional [version] parameter
In light of RFC 015, we should not do an "internet check" for latest versions, but stick to the version we're actually targeting with the upgrade. Thus, we explicitly pass the version as an argument.
[1]: https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-upgrade/#cmd-upgrade-plan
RFC 015
- explicitly pass target version to `kubeadm upgrade plan`
> upgrade-agent: set explicit k8s version for kubeadm

- WORKSPACE.bazel
- bazel/devbuild/BUILD.bazel
- bazel/devbuild/prepare_developer_workspace.sh.in
Fixed `devbuild` error on MacOS:
```
sed: 1: "./terraform/config.tfrc": invalid command code .
ERROR: bazel/devbuild/devbuild: 'sed -i "s|@@TERRAFORM_PROVIDER_PATH@@|$(dirname "${terraform_provider}")|g" "${TF_PROVIDER_DIR}/config.tfrc"' failed at line 73
ERROR: bazel/devbuild/devbuild: exit status 1
```
- Use `sed` from GNU Coreutils, which ensures purity and thus common behaviour on all platforms.
> ci: use `sed` from GNU Coreutils

- .github/workflows/draft-release.yml
Terraform expects the provider **binaries** to have a `v` prefix in their version. The packaged file must only have the version number.
The format is the following:
```
terraform-provider-${name}_${version}_${os}_${arch}.zip
│
└─ terraform-provider-${name}_v${version}[.exe]
```
- Fix binaries not being created with version number including v prefix in their name
> ci: add v prefix to packaged Terraform provider binary

- internal/constellation/applyinit.go
`ClusterID` and `OwnerID` were swapped and not correctly hex encoded when returned from the Constellation-lib's Init method.
- Correctly set `ClusterID` and `OwnerID` in the Init response
- Correctly hex encode both IDs
> constellation-lib: fix incorrect encoding and ordering of Init response

- bazel/ci/shellcheck.sh.in
- bazel/ci/shfmt.sh.in
- bazel/ci/terraform.sh.in
- dev-docs/workflows/terraform-provider.md
- internal/constants/constants.go
- terraform-provider-constellation/docs/resources/cluster.md
- terraform-provider-constellation/examples/resources/constellation_cluster/import.sh
- terraform-provider-constellation/internal/provider/BUILD.bazel
- terraform-provider-constellation/internal/provider/cluster_resource.go
- terraform-provider-constellation/internal/provider/cluster_resource_test.go
We want to be able to import legacy, possibly non-Terraform clusters into Terraform by specifying KubeConfig, Master Secret (& Salt), as well as the cluster endpoint, so that their future lifecycle can be managed with Terraform.
- Implement state importing for the `constellation_cluster` resource.
- [AB#3605](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3605)
> terraform-provider: support importing Constellation clusters

- internal/constellation/helm/values.go
Reverts edgelesssys/constellation#2664
Reverting since upgrading cilium with the new value results in network disruptions which cannot be reconciled.
> Revert "helm: deprioritize Cilium tc filters"

- bazel/toolchains/go_module_deps.bzl
- go.mod
- go.sum
- internal/installer/BUILD.bazel
- internal/installer/installer.go
- internal/installer/installer_test.go
RFC 015 proposes the introduction of data URLs to materialize static content to files on disk. This commit adds support for data URLs to the installer. The corresponding content will be added to versions.go in a subsequent commit.
RFC 015
- handle `data:` and `http(s):` URLs separately
> installer: add support for data URLs

- terraform/infrastructure/aws/main.tf
- terraform/infrastructure/aws/modules/jump_host/main.tf
- terraform/infrastructure/aws/modules/jump_host/variables.tf
- Align security group naming for jump host
- use `vpc_security_group_ids` to set the security group since this is the correct setting (cf: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#security_groups)
Otherwise on every `constellation apply` the are terraform changes which are applied, forcing the re-creating of the jump host.
> terraform: use correct security group option for jump host

- .github/workflows/reproducible-builds.yml
- flake.lock
- flake.nix
- image/base/mkosi.conf
- image/base/mkosi.postinst
This is the final step for reproducible OS image builds. I found some minor reproducibility issues and added a test to ensure regressions do not go unnoticed.
- Update flake and mkosi
- Use compression binaries (zstd, xz) and cpio tools from nixpkgs
- Add an automated test for reproducible builds
- [AB#3519](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3519)
- [Test run](https://github.com/edgelesssys/constellation/actions/runs/7180476605)
- PR title for release: `OS images are now reproducible`
> image: reproducible builds test

- bazel/devbuild/BUILD.bazel
- bazel/devbuild/prepare_developer_workspace.sh.in
- dev-docs/workflows/terraform-provider.md
Thought I would move this to its own PR since we have multiple PRs depending on it now.
The `devbuild` target currently creates a config file that can be used as `.terraformrc` which overrides the provider when running Terraform commands with a local path.
However, this does not work when the provider is not available in the registry at all and one needs to run `terraform init` to initializes provides others than the Constellation provider.
Which is the case for use currently, and probably will always be when working on pseudo versions.
Instead, we can simply place the provider binary (or a symlink to it) in the local registry cache.
That way, Terraform will see the binary is already downloaded and will skip looking for it in the registry.
- Update Bazel `devbuild` target to automatically …
> bazel: place Terraform provider binaries in local registry path on devbuild

- bazel/toolchains/linux_kernel.bzl
- flake.nix
Changelogs:
https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.65 https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.66 https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.67 https://cdn.kernel.org/pub/linux/kernel/v6.x/ChangeLog-6.1.68
- as a reviewer, please also look at https://github.com/edgelesssys/constellation-kernel/pull/8
- image: update Linux to 6.1.68
- images for testing
- `ref/deps-kernel-6-1-68/stream/debug/v2.14.0-pre.0.20231214162651-e26c3c990040`
- `ref/deps-kernel-6-1-68/stream/nightly/v2.14.0-pre.0.20231214162651-e26c3c990040`
- includes [patch](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=b82a8dbd3d2f4563156f7150c6f2ecab6e960b30) for disabling 32 bit emulation on affected systems
- [e2e …
> image: update Linux to 6.1.68

- .github/actions/cdbg_deploy/action.yml
- .github/actions/constellation_create/action.yml
- .github/actions/constellation_destroy/action.yml
- .github/actions/deploy_logcollection/action.yml
- .github/actions/e2e_test/action.yml
- .github/actions/notify_e2e_failure/action.yml
- .github/actions/terraform_apply/action.yml
- .github/workflows/e2e-test-daily.yml
- .github/workflows/e2e-test-release.yml
- .github/workflows/e2e-test-terraform-provider.yml
- .github/workflows/e2e-test-weekly.yml
- .github/workflows/e2e-test.yml
- .github/workflows/e2e-upgrade.yml
- debugd/internal/debugd/logcollector/fields.go
- terraform-provider-constellation/docs/data-sources/attestation.md
- terraform-provider-constellation/internal/provider/attestation_data_source.go
We want to test our Terraform provider the same way we test the CLI.
Instead of writing new test, we want to adapt the existing tests to allow creation of the Constellation cluster using Terraform.
- Add a new GitHub workflow: Terraform e2e test
- Same as manual e2e test (or self-managed-infra e2e test), but uses Terraform for cluster initialization
- Uses the same e2e test template as other tests, which allows us to easily add Terraform provider tests to daily/weekly test runs
- [AB#3547](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3547)
- [quick e2e test](https://github.com/edgelesssys/constellation/actions/runs/7195061381)
- [e2e gcp](https://github.com/edgelesssys/constellation/actions/runs/7195429715)
- [e2e …
> ci: Terraform provider e2e tests

- cli/internal/cmd/apply.go
- cli/internal/cmd/apply_test.go
- internal/versions/components/BUILD.bazel
- internal/versions/components/components.go
- internal/versions/components/components_test.go
Users may choose to not upgrade their Kubernetes version when running a Constellation upgrade.
This includes not upgrading a patch version of Kubernetes.
We use the Kubernetes version set in a user's config to determine which image to use for the Constellation deployed cloud-controller-manager and cluster-autoscaler.
Currently, the CLI incorrectly sets the k8s version to an empty string if a user chooses to apply an upgrade with a no longer supported Kubernetes patch version.
- Fix the issue by translating an outdated user's Kubernetes version to a currently supported Kubernetes version
- Kubernetes upgrades are still skipped
- This version is only used to determine which image to use for the cloud-controller-manager and cluster-autoscaler. Both of which are independent of the Kubernetes …
> cli: fix upgrades when using outdated Kubernetes patch version

- .github/actions/terraform_apply/action.yml
- terraform-provider-constellation/docs/data-sources/attestation.md
- terraform-provider-constellation/docs/data-sources/image.md
- terraform-provider-constellation/docs/resources/cluster.md
- terraform-provider-constellation/examples/full/aws_cluster.tf
- terraform-provider-constellation/examples/full/azure_cluster.tf
- terraform-provider-constellation/examples/full/gcp_cluster.tf
- terraform-provider-constellation/examples/resources/constellation_cluster/resource.tf
- terraform-provider-constellation/internal/provider/BUILD.bazel
- terraform-provider-constellation/internal/provider/attestation_data_source.go
- terraform-provider-constellation/internal/provider/attestation_data_source_test.go
- terraform-provider-constellation/internal/provider/cluster_resource.go
- terraform-provider-constellation/internal/provider/convert.go
- terraform-provider-constellation/internal/provider/convert_test.go
- terraform-provider-constellation/internal/provider/image_data_source.go
- terraform-provider-constellation/internal/provider/image_data_source_test.go
- terraform-provider-constellation/internal/provider/shared_attributes.go
We can improve the UX of the Terraform provider by unifying the passing of OS image information to one nested attribute that comprises all the information about a Constellation OS image (Semantic version, CSP-reference, Versionsapi short-path).
- Create an `image` attribute that comprises all of the aforementioned information.
- (Unrelated) Mark the `kubeconfig` output as sensitive.
- [E2E Test](https://github.com/edgelesssys/constellation/actions/runs/7224107793)
> terraform-provider: unify image in-/output

- internal/constellation/helm/overrides.go
- internal/constellation/helm/values.go
- Enable Cilium bpf masquerading in order to be able to configure masquerading through a configmap (see: https://docs.cilium.io/en/stable/network/concepts/masquerading/#ebpf-based)
This also enables full eBPF host routing:
Before:
```
root@fedora:/home/cilium# cilium status
KVStore:                 Ok   Disabled
Kubernetes:              Ok   1.28 (v1.28.3) [linux/amd64]
Kubernetes APIs:         ["cilium/v2::CiliumClusterwideNetworkPolicy", "cilium/v2::CiliumNetworkPolicy", "cilium/v2::CiliumNode", "cilium/v2alpha1::CiliumEndpointSlice", "core/v1::Namespace", "core/v1::Node", "core/v1::Pods", "core/v1::Service", "discovery/v1::EndpointSlice", "networking.k8s.io/v1::NetworkPolicy"]
KubeProxyReplacement:    Strict   [eth0 10.9.0.6]
Host firewall:           Disabled
CNI Chaining: …
```
> cilium: enable bpf masquerading

- internal/constellation/helm/charts/cert-manager/values.yaml
- internal/constellation/helm/generateCertManager.sh
Pin the cert-manager related images to their sha256 checksum. 
How I tested it:
upgraded a GCP, v2.13 cluster with
```
./constellation apply --debug --skip-phases infrastructure,k8s,image --force
```
-
-  [AB#3612](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3612)
Had to rebase and cherry pick to be able to test it locally.
> feat: pin cert-manager image to sha256 checksum

- .github/actions/e2e_verify/action.yml
Verify e2e test was not authorized to upload TCBs for AWS, since the login was ran only with csp == azure
- Remove the CSP conditional for the login action, since the upload step is already restricted to only run on specific inputs
- fixes https://github.com/edgelesssys/issues/issues/109
> ci: remove conditional from AWS login in e2e verify test

- terraform-provider-constellation/docs/resources/cluster.md
- terraform-provider-constellation/examples/full/aws_cluster.tf
- terraform-provider-constellation/examples/full/azure_cluster.tf
- terraform-provider-constellation/examples/full/gcp_cluster.tf
- terraform-provider-constellation/examples/resources/constellation_cluster/resource.tf
- terraform-provider-constellation/internal/data/BUILD.bazel
- terraform-provider-constellation/internal/data/providerdata.go
- terraform-provider-constellation/internal/provider/attestation_data_source.go
- terraform-provider-constellation/internal/provider/cluster_resource.go
- terraform-provider-constellation/internal/provider/image_data_source.go
- terraform-provider-constellation/internal/provider/provider.go
We want to have the `microserviceVersion` be in lock-step with the provider version, since a normal user will always be in sync between "Constellation version" and microservice version.
- Default the microservice version to the provider version if not set.
- Remove the microservice version from the examples for simplicity.
-  [E2E Test](https://github.com/edgelesssys/constellation/actions/runs/7247698551)
> terraform-provider: lock-step microservice version

- bazel/release/BUILD.bazel
- bazel/toolchains/oci_deps.bzl
- e2e/malicious-join/BUILD.bazel
`rules_oci` spawns local container registry processes and in the past, those would not be cleaned up explicitly, leading to an accumulation of processes when using remote execution with buildbarn. This pre-release contains a fix: https://github.com/bazel-contrib/rules_oci/pull/421 Additionally, windows support for rules_oci was removed in this fork, since it is currently broken.
- deps: update rules_oci to a pre-release version to fix memory leak
- [AB#3566](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3566)
> deps: update rules_oci to a pre-release version to fix memory leak

- .github/actions/pick_assignee/action.yml
I should be included in the list of assignees for failed tests.
- Add myself to the list.
> ci: add burgerdev to e2e failure assignees

- .github/workflows/test-integration.yml
The `integration` config runs all tests - unit and integration. Since we already have a workflow for unit tests, we should not be running these again in the integration test workflow. There's a dedicated config for running only integration tests: `integration-only`.
- Use the `integration-only` config in the integration test workflow.
> ci: don't run unit tests in integration test workflow

- .github/workflows/on-release.yml
* The on-release workflow did not succeed for v2.14.0 due to permission errors. 
* The later part of the workflow seems not to be using the Github outputs correctly.
* The branches created were not correctly named (expected `release/v2.14`, got `release/v2.14.0`).
https://github.com/edgelesssys/constellation/actions/runs/7263610857
- Give repo write permission to the jobs that manipulate remote branches.
- Use job outputs to determine working branch.
- Fix branch name.
Run with fixes: https://github.com/edgelesssys/constellation/actions/runs/7266599601.
> ci: repair on-release workflow

- terraform-provider-constellation/docs/resources/cluster.md
- terraform-provider-constellation/internal/provider/attestation_data_source.go
- terraform-provider-constellation/internal/provider/cluster_resource.go
- terraform-provider-constellation/internal/provider/cluster_resource_test.go
- terraform-provider-constellation/internal/provider/image_data_source.go
- terraform-provider-constellation/internal/provider/image_data_source_test.go
- terraform-provider-constellation/internal/provider/shared_attributes.go
There are a lot of inputs that we can validate without further configuration in the Terraform provider, to catch errors early.
- Add input validation for `constellation_image` and `constellation_cluster`. `constellation_attestation` already has input validation.
- [AB#3613](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3613)
- [E2E Test](https://github.com/edgelesssys/constellation/actions/runs/7273881323)
> terraform-provider: add input validation

- .github/actions/artifact_download/action.yml
This reverts commit b550c92ac930d4b5a757aa04c865f9442f6b119a.
* Download v4 requires upload v4
* Upload v4 contains breaking changes that require time to work around in our CI
* Limit of 10 uploads per job
* Cant upload artifacts with names that already exist
> Revert "deps: update actions/download-artifact action to v4 (#2753)"

- .github/actions/artifact_download/action.yml
- .github/actions/artifact_upload/action.yml
- .github/actions/download_release_binaries/action.yml
- .github/workflows/draft-release.yml
We decided to not encrypt the artifacts we pass around in the release workflow (since they will be published anyways).
The grouped download action was still expecting them to be encrypted tho.
- Don't try to decrypt unencrypted artifacts when downloading Constellation artifacts during the release draft workflow
- Pin upload and download actions by hash
> ci: fix artifacts download/upload for release draft workflow

- .github/actions/artifact_download/action.yml
- .github/actions/artifact_upload/action.yml
- .github/actions/constellation_create/action.yml
- .github/actions/e2e_benchmark/action.yml
- .github/actions/e2e_sonobuoy/action.yml
- .github/actions/e2e_test/action.yml
- .github/actions/upload_terraform_module/action.yml
- .github/workflows/build-os-image.yml
- .github/workflows/draft-release.yml
- .github/workflows/e2e-test-daily.yml
- .github/workflows/e2e-test-release.yml
- .github/workflows/e2e-test-weekly.yml
- .github/workflows/e2e-test.yml
- .github/workflows/e2e-upgrade.yml
- .github/workflows/e2e-windows.yml
- .github/workflows/reproducible-builds.yml
- .github/workflows/scorecard.yml
https://github.com/edgelesssys/constellation/pull/2567 introduced some minor issues in the image build pipeline.
This PR aims to fix the issues and clean up some things
- Fix encrypted uploading of multiple artifacts in one action
- Fix downloading of encrypted artifacts if the directory we want to extract to does not yet exist on the actions runner
- Fix archives containing directory structure that shouldn't be there
- If we specify we want a file at `someDir/someSubDir/targetFile`, the action would not create an archive containing `targetFile`, but `someDir/someSubDir/targetFile`. This is different behavior from the regular artifact upload action
- We can't use the `-j` (junk paths) option from `unzip`, because that would destroy **all** directory structure on unpacking. This is a …
> ci: fix artifact upload in image build pipeline

- bazel/toolchains/go_module_deps.bzl
- go.mod
- go.sum
- hack/go.mod
- hack/go.sum
- internal/versions/hash-generator/BUILD.bazel
- internal/versions/hash-generator/generate.go
- internal/versions/versions.go
- internal/versions/versions_test.go
- terraform-provider-constellation/go.mod
- terraform-provider-constellation/go.sum
#2719 introduced Kubernetes component patches that are to be passed to `kubeadm` during init and upgrade. These patches were manually generated and did not include the `etcd` component.
- Add library support for fetching image hashes and generating JSON patches.
- Use the kubeadm Golang libraries to derive the etcd version for a given k8s version.
- Include patches in  `hash-generator`.
- [AB#3616](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3616)
- RFC 015
> versions: generate k8s image patches (incl etcd)

- bazel/devbuild/BUILD.bazel
- bazel/devbuild/prepare_developer_workspace.sh.in
We want to make it explicit in the build process that the Terraform provider is under the enterprise license terms.
-
How to test:
`bazel run //:devbuild --cli_edition=oss`
should not build the TF provider binary and link it under `~/.terraform.d/plugins/registry.terraform.io/edgelesssys/constellationc`.
> terraform-provider: only build as enterprise user

- .github/workflows/scorecard.yml
The Scorecard uploading workflow broke (on main), causing CI checks to fail and our scorecard not to update. This got caused by the artifact encryption, which is a wrapper to GitHub's `upload_artifact` action, that was previously used directly in the scorecard workflow. The scorecard workflow has a restrictive [set of actions](https://github.com/ossf/scorecard-action#restrictions-on-the-job-containing-ossfscorecard-action) that may be called in the workflow the scorecard is created in, which includes the `upload_artifact` action from GitHub, but naturally not our custom wrapper around it. Therefore, we can fix the problem by going back to using GitHub's action for this workflow.
- Use GitHub's `upload_artifact` action in the scorecard workflow, instead of our custom wrapper.
- Unsure how …
> ci: don't use disallowed action when uploading scorecard

- .github/workflows/build-os-image.yml
- .github/workflows/reproducible-builds.yml
The encrypted artifact actions introduced in #2567 are not drop-in replacements for the regular actions: if you use the artifact upload action multiple times for the same artifact, the default action will append to the outputs, while our action replaces the artifact.
This is only a problem when we actually upload multiple times to the same artifact, usually from matrix runs. I did a quick search for call sites of the upload action, and the only places where the artifact name is fixed but the paths are matrix-dependent were `build-os-image` and `reproducible-builds`. This PR fixes these call sites.
cc @miampf 
- Revert problematic call sites to the default upload action.
- Revert consumers of the problematic artifacts to the default download action.
I don't see an issue with keeping the …
> ci: selectively remove artifact encryption

- terraform-provider-constellation/examples/full/aws_cluster.tf
- terraform-provider-constellation/examples/full/azure_cluster.tf
- terraform-provider-constellation/examples/full/gcp_cluster.tf
- terraform-provider-constellation/internal/provider/cluster_resource.go
- Don't double quote cert sans
- Improve Terraform provider examples
> terraform-provider: fix parsing `api_server_cert_sans`

- .github/workflows/draft-release.yml
The current Terraform provider release is broken because of wrong zipping.
Terraform expects the zip files to only contain the binary file, but our zip inflates to a directory. This leads to TF not finding the binary:
https://github.com/edgelesssys/constellation/actions/runs/7339043840/job/19982584425#step:18:62
See the relevant zipping line:
https://github.com/edgelesssys/constellation/blob/48343dde4b64d03db6d9c352c854d5d739e543ab/.github/workflows/draft-release.yml#L465
You can check that this is done correctly for the edgelesstest, which works:
```bash
unzip terraform-provider-edgelesstest_1.0.0_linux_amd64.zip
Archive:  terraform-provider-edgelesstest_1.0.0_linux_amd64.zip
inflating: CHANGELOG.md
inflating: LICENSE.txt
inflating: README.md
inflating: …
```
> ci: fix provider release through correct zipping

- .github/workflows/draft-release.yml
The provider binaries need execution permissions. In the current v2.14.1 release, it is necessary to manually provide the permission after `terraform init`:
```bash
chmod +x .terraform/providers/registry.terraform.io/edgelesssys/constellation/2.14.1/darwin_arm64/terraform-provider-constellation_v2.14.1
````
- add x permission to the provider binary
> ci: give exec permission to provider binaries

- .github/actions/upload_terraform_module/action.yml
- .github/workflows/build-os-image.yml
- .github/workflows/draft-release.yml
- .github/workflows/e2e-windows.yml
- bazel/ci/unused_gh_actions.sh.in
- Remove artifact encryption/decryption where the artifacts might as well be public (e.g. the windows Constellation CLI)
- Remove artifact encryption/decryption where it just didn't make sense (the Terraform modules)
This should fix our build-os-image pipeline so the images are also usable. Currently, the pipeline is green but misses all-1 entries in the v2.15.0.pre-... --> CSP image ref lookup table.
Test: https://github.com/edgelesssys/constellation/actions/runs/7338017372
Note that the uploaded map (https://cdn.confidential.cloud/constellation/v2/ref/fix-ci-remove-artifact-encryption/stream/debug/v2.15.0-pre.0.20231227125133-35eca6437c37/image/info.json) now contains all image references again.
> ci: remove artifact encryption for public artifacts

- e2e/miniconstellation/test-remote.sh
- internal/constellation/helm/overrides.go
- Masquerade traffic to the qemu metadata docker container running inside the node CIDR.
Fixes: https://github.com/edgelesssys/constellation/issues/2780
This bug was introduced in: https://github.com/edgelesssys/constellation/pull/2723
The e2e miniconstellation test was supposed to catch that (e.g. in the release pipeline) but the check that all nodes have joined was wrong.
> helm: masq traffic to the mini-qemu-metadata container so that the join-service can retrieve it's metadata

- operators/constellation-node-operator/internal/cloud/azure/client/scalinggroup.go
- operators/constellation-node-operator/internal/cloud/azure/client/scalinggroup_test.go
The Azure upgrade is currently broken in both the CLI and the Terraform provider. Azure must have recently changed its API spec, basically requiring to set the community image ID in the communityID field. This path is however broken, since the image path /communityGalleries/... does not match the case:
https://github.com/edgelesssys/constellation/blob/c15e4efef6844aad55d344089d5e40ab1a75b184/operators/constellation-node-operator/internal/cloud/azure/client/scalinggroup.go#L168
This led to this error in the operator:
```
ERROR    Unable to set ScalingGroup NodeImage    {"controller": "scalinggroup", "controllerGroup": "update.
edgeless.systems", "controllerKind": "ScalingGroup", "ScalingGroup": {"name":"e2e-222-7d279332-worker-44bdb38a"}, "namespace": "", "name": …
```
> node-operator: fix setting Azure node image

- .github/workflows/e2e-test-provider-example.yml
- terraform-provider-constellation/docs/resources/cluster.md
- terraform-provider-constellation/examples/full/aws/main.tf
- terraform-provider-constellation/examples/full/azure/main.tf
- terraform-provider-constellation/examples/full/gcp/main.tf
- terraform-provider-constellation/internal/provider/BUILD.bazel
- terraform-provider-constellation/internal/provider/cluster_resource.go
- terraform-provider-constellation/internal/provider/cluster_resource_test.go
The provider is currently using a default when no version is specified for these fields. This however leads to an unexpected upgrade state, because new versions defaults, as part of provider upgrades, are not seen as state change by Terraform. Consequently, the new defaults are not applied. This is especially undesired for the microservice version, which should always coincide with the provider version.
- marking as `breaking change` to make users aware
- make fields required
- adjust provider e2e test
> terraform-provider: require kubernetes and microservice version

- .github/workflows/check-links.yml
- .gitignore
- .lychee.toml
- .lycheeignore
- docs/docs/overview/performance/io.md
We're using Lychee to check links. The configuration is currently split between `.lycheeignore` and arguments.
- Unify lychee configuration in one file.
- Remove the GITHUB_TOKEN from the lychee action - it's not needed.
- Ignore Wireguard pdf.
- Fix invalid fragment in a user docs URL.
* Fixes edgelesssys/issues#142.
> ci: ignore Wireguard pdf in lychee

- .github/workflows/reproducible-builds.yml
GitHub Actions [has changed the API for Artifacts](https://github.com/actions/toolkit/tree/main/packages/artifact#v2---whats-new). This limits the amount of artifacts per workflow, doesn't allow overwriting artifacts in a Workflow run and changed the way globs are handled.
Since the old API will likely be disabled soon, we have to refactor the reproducible builds test.
- upgrade reproducible builds test to new artifacts api (see what breaks)
- fix matrix up/downloads using `pattern` field
- [CI run](https://github.com/edgelesssys/constellation/actions/runs/7423223631)
> ci: reproducible builds test on artifacts v2

- terraform/legacy-module/README.md
With Constellation v2.14.0, we introduced the Constellation Terraform provider, which is now the recommended way to manage Constellation clusters through Terraform. With that, the legacy modules can be deprecated (our docs don't link to them anymore anyways) and should be removed with or before v2.15.0.
- Add a deprecation notice in the directory of the legacy module. 
- ~~TODO: Leave a link to the import-docs of the `constellation_cluster` resource, once provider documentation is published.~~
> terraform: add module deprecation notice

- .github/actions/terraform_apply/action.yml
- terraform-provider-constellation/docs/resources/cluster.md
- terraform-provider-constellation/examples/resources/constellation_cluster/resource.tf
Required field was missing
- Add the required field using value from config
- Add the required field to the example in our Terraform docs
- [e2e test](https://github.com/edgelesssys/constellation/actions/runs/7447154608)
> ci: fix empty Kubernetes version attribute in Terraform provider e2e test

- .github/actions/deploy_logcollection/action.yml
- .github/actions/login_gcp/action.yml
- .github/workflows/build-os-image.yml
- .github/workflows/on-release.yml
- .github/workflows/reproducible-builds.yml
- bootstrapper/cmd/bootstrapper/main.go
- cli/internal/cmd/configfetchmeasurements.go
- hack/cli-k8s-compatibility/BUILD.bazel
- hack/cli-k8s-compatibility/main.go
- image/upload/internal/cmd/BUILD.bazel
- image/upload/internal/cmd/image.go
- image/upload/internal/cmd/info.go
- image/upload/internal/cmd/measurementsupload.go
- internal/api/versionsapi/cli/list.go
- internal/attestation/measurements/measurement-generator/BUILD.bazel
- internal/attestation/measurements/measurement-generator/generate.go
- internal/constellation/helm/generateCertManager.sh
- internal/constellation/helm/generateCilium.sh
- internal/constellation/helm/update-csi-charts.sh
- internal/osimage/measurementsuploader/measurementsuploader.go
While browsing the code base, I stumbled over some minor opportunities that don't justify a dedicated PR each. This is a bulk submission of such findings.
See also individual commits.
- remove obsolete docs, add fresh docs
- prettify versionsapi-list output
- use explicit Helm version in GH action
- use constants instead of literals
- check integrity of rekor-cli
- make `rm` invocation more robust
- Minor correctness and simplification tweaks.
> Fix various small things throughout the codebase

- .github/actions/versionsapi/Dockerfile
- .github/actions/versionsapi/action.yml
- .github/workflows/build-versionsapi-ci-image.yml
`operators/constellation-node-operator/api/go.mod` was removed in #2769, but is still referenced in Github actions, causing [CI failures](https://github.com/edgelesssys/constellation/actions/runs/7465442722).
- Remove explicit reference to obsolete file.
- Add go.mod to workflow triggers to avoid this problem in the future.
> ci: remove reference to absent go.mod file

- internal/config/aws.go
- internal/config/azure.go
- internal/config/config.go
When setting "latest" for the SNP versions, the numerical values should be persisted in the `join-config` on `apply`, so that the user knows the currently deployed latest version value.
This was missing in AWS SEV-SNP, because of a hidden code path.
- make the need for latest version resolution more visible through an interface, which needs to be assigned to every new SEV-SNP type
Tested that `constellation status` shows the resolved versions after `constellation apply`
> cli: fix AWS SEV-SNP latest version resolution in cluster

- image/base/mkosi.skeleton/usr/lib/systemd/system/containerd.service.d/local.conf
Until https://github.com/containerd/containerd/pull/8924 lands in our
containerd version, we need to decrease the default ulimit that
is set in the upstream containerd service of infinity which newer
systemd versions resolve to 2**30 which is way too large and
results in various inspecific errors such as excessive resource (e.g., memory)
usage.
- set LimitNOFILE=524288 for containerd
debug image: https://github.com/edgelesssys/constellation/actions/runs/7482948530
How to test:
* create a Constellation with this image
* execute ulimit -a and verify that the file limit is LimitNOFILE=524288
> image: lower file limit for containerd

- .github/actions/pick_assignee/action.yml
@derpsteb is not actively working on Constellation - remove the stone of e2e debugging.
> ci: remove derpsteb from e2e assignee list

- debugd/internal/debugd/logcollector/credentials.go
Our e2e tests moved to a different GCP project. We need to tell the logcollection to also fetch the password from the new project.
- Use OpenSearch password from constellation-e2e.
- Fixes edgelesssys/issues#243
- [AB#3750](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3750)
> ci: fetch OpenSearch password from e2e test project

- .github/workflows/on-release.yml
When we do a release, we need to mirror the released GCP image into the public project that hosts our marketplace images. This PR automates this process.
- Add a CI job that is ran upon an release and takes the latest GCP release image, and mirrors it to our public project.
- [AB#3757](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3757)
- [Test Run](https://github.com/edgelesssys/constellation/actions/runs/7528575107)
> ci: automate GCP MPI mirroring

- .lychee.toml
The Wireguard website sporadically serves error 500 on all pages, not only on the PDF download. Examples from the last days:
* https://github.com/edgelesssys/constellation/actions/runs/7529507475/job/20493858220
* https://github.com/edgelesssys/constellation/actions/runs/7529133518/job/20492744374
* https://github.com/edgelesssys/constellation/actions/runs/7491445446/job/20392674195
* https://github.com/edgelesssys/constellation/actions/runs/7447431073/job/20259729210
- Ignore all of `www.wireguard.com` when checking links.
> ci: don't check Wireguard weblinks

- .github/actions/e2e_sonobuoy/action.yml
- .github/actions/e2e_test/action.yml
While this doesn't seem to resolve all issues, it does improve the situation and makes remaining issue easily discoverable.
- use sonobuoy 0.57.1 
- print test failures more prominently
- skip conformance test that is [known to be broken with cilium and k8s 1.29](https://github.com/cilium/cilium/issues/29913)
- [e2e](https://github.com/edgelesssys/constellation/actions/runs/7528645597/job/20491290770)
> ci: use sonobuoy 0.57.1 and skip cilium conformance problem

- internal/constellation/helm/BUILD.bazel
- internal/constellation/helm/charts/cilium/Chart.yaml
- internal/constellation/helm/charts/cilium/README.md
- internal/constellation/helm/charts/cilium/files/cilium-envoy/configmap/bootstrap-config.json
- internal/constellation/helm/charts/cilium/files/hubble/dashboards/hubble-dashboard.json
- internal/constellation/helm/charts/cilium/templates/cilium-agent/daemonset.yaml
- internal/constellation/helm/charts/cilium/templates/cilium-agent/serviceaccount.yaml
- internal/constellation/helm/charts/cilium/templates/cilium-configmap.yaml
- internal/constellation/helm/charts/cilium/templates/cilium-envoy/daemonset.yaml
- internal/constellation/helm/charts/cilium/templates/cilium-envoy/service.yaml
- internal/constellation/helm/charts/cilium/templates/cilium-flowlog-configmap.yaml
- internal/constellation/helm/charts/cilium/templates/cilium-operator/dashboards-configmap.yaml
- internal/constellation/helm/charts/cilium/templates/clustermesh-apiserver/deployment.yaml
- internal/constellation/helm/charts/cilium/templates/hubble-relay/deployment.yaml
- internal/constellation/helm/charts/cilium/templates/spire/agent/daemonset.yaml
- internal/constellation/helm/charts/cilium/templates/validate.yaml
- internal/constellation/helm/charts/cilium/values.yaml
- internal/constellation/helm/charts/cilium/values.yaml.tmpl
- internal/constellation/helm/generateCilium.sh
- internal/constellation/helm/helm_test.go
We upgraded our images to Cilium pre-release v1.15.0-pre.3, but did not upgrade the Helm chart.
- Upgrade the Helm chart.
- Fixes edgelesssys/issues#258
- Test runs
**FAILED**
> helm: bump Cilium chart version

- internal/osimage/uplosi/uplosiupload.go
When uploading images to AWS, they need to be uploaded to S3 first. Since blob names were not unique between attestation variants, there was a possibility for one S3 upload to be used for the wrong AMI.
- [image upload: use unique blob name for AWS images uploaded to S3](https://github.com/edgelesssys/constellation/commit/db645ee4adee89877f5628166979050f184f1683)
- Fixes https://github.com/edgelesssys/issues/issues/272
> image upload: use unique blob name for AWS images uploaded to S3

- internal/constellation/helm/loader.go
- Set `routingMode` to `native` for GCP. The `tunnel` option was fully removed in https://github.com/edgelesssys/constellation/pull/2808 which included https://github.com/cilium/cilium/pull/29053
This change did not hit any released Constellation version yet.
> helm: re-enable native routing for gcp

- operators/constellation-node-operator/internal/cloud/azure/client/nodeimage.go
- operators/constellation-node-operator/internal/cloud/azure/client/nodeimage_test.go
- operators/constellation-node-operator/internal/cloud/azure/client/scalinggroup.go
- operators/constellation-node-operator/internal/cloud/azure/client/scalinggroup_test.go
Cluster creation and upgrades with Azure marketplace images were broken due to an unimplemented operation in the operator (i.e. getting VMSS state and Node state), that caused the reconcile loop to fail, resulting in indefinitely hanging upgrades and cluster creation.
- Implement the getting of the affected statuses in the operator by formatting the image to a marketplace image URI if a marketplace image is used.
- [E2E Test](https://github.com/edgelesssys/constellation/actions/runs/7636758892)
> operator: fix get-handling of Azure marketplace images

- internal/constellation/helm/charts/edgeless/operators/charts/constellation-operator/templates/deployment.yaml
- internal/constellation/helm/charts/edgeless/operators/charts/constellation-operator/values.yaml
- internal/constellation/helm/testdata/AWS/constellation-operators/charts/constellation-operator/templates/deployment.yaml
- internal/constellation/helm/testdata/Azure/constellation-operators/charts/constellation-operator/templates/deployment.yaml
- internal/constellation/helm/testdata/GCP/constellation-operators/charts/constellation-operator/templates/deployment.yaml
- internal/constellation/helm/testdata/OpenStack/constellation-operators/charts/constellation-operator/templates/deployment.yaml
- internal/constellation/helm/testdata/QEMU/constellation-operators/charts/constellation-operator/templates/deployment.yaml
This is the quick alternative to #2837 that only removes kube-rbac-proxy while ignoring all of the kubebuilder legacy.
- Remove kube-rbac-proxy sidecar from the constellation operator. We don't have any sensitive metrics to guard.
- There are a lot of defunct resources lying around (some new, some existing) that should be cleaned up as part of #2837.
- [AB#3611](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3611)
> helm: remove kube-rbac-proxy

- .github/workflows/e2e-test-weekly.yml
We do not run the Terraform provider example tests regularly yet, though they replicate the user's path the best. Hence, they should be run in any of the regularly run pipelines. (i.e. daily or weekly)
- Run the E2E test using the Terraform provider examples in the weekly E2E pipeline.
> ci: add TF provider example test to weekly

- .github/actions/e2e_benchmark/.gitignore
- .github/actions/e2e_benchmark/action.yml
- .github/actions/e2e_benchmark/evaluate/compare.py
The e2e_benchmark test correctly compares the current benchmark with the previous one.
However, there are two problems:
1. The comparison results do not lead to a failed test due to wrong/missing error handling
2. The test ALWAYS overwrites the stored results in the S3 bucket with the new results, leading to a degradation of our baseline
- Update comparison to fail when the new values are outside the threshold (80% of the previous benchmark)
- Only upload new results if the comparison succeeds -> Baseline can still slowly degrade, but I'd suspect the performance to either be stable or drop significantly in a single step
- https://github.com/edgelesssys/constellation/actions/runs/7637200058
- Keeping a longer history of results is out of scope for this PR
- We could introduce fixed …
> ci: fix e2e_benchmark comparison

- e2e/provider-upgrade/BUILD.bazel
[Terraform provider ugrade tests are run with our default Go test policy of `count=3`](https://github.com/edgelesssys/constellation/blob/6d4a8d594eed031246ef1c0283a1e600b81bf14e/e2e/internal/upgrade/BUILD.bazel#L35)
This causes them to run for ~6 hours in case of failures.
- Run the test only once
> ci: run provider upgrade test only once

- internal/osimage/uplosi/uplosi.conf.in
Images for AWS Marketplace publishing need to be present in us-east-1
- Add us-east-1 to AWS image replication
> image: replicate to us-east-1 for aws marketplace

- .github/actions/e2e_test/action.yml
The kube-bench definitions are currently pulled from the master branch of the sonobuoy-plugins repo. This makes our CI susceptible for regressions due to uncoordinated upstream changes. One such change was the upstream bump to https://hub.docker.com/layers/sonobuoy/kube-bench/v0.6.17/images/sha256-e031ba8457a8e2c5823533dd8aa7c57b67de0c9298cba949669bd4a4edd022c9?context=explore, which is only available on arm64.
- Refer to plugins via concrete commit hash.
- This may have caused problems in benchmarking or the sonobuoy execution, but it's not entirely clear to me how this would have manifested.
> ci: pin the kube-bench plugin definitions for sonobuoy

- terraform-provider-constellation/internal/provider/cluster_resource.go
The output is duplicated at the moment:
```
╷
│ Warning: Constellation license not found.
│ 
│   with constellation_cluster.aws_example,
│   on main.tf line 96, in resource "constellation_cluster" "aws_example":
│   96: resource "constellation_cluster" "aws_example" {
│ 
│ Using community license.
│ For details, see
│ https://docs.edgeless.systems/constellation/overview/license
│ 
│ (and one more similar warning elsewhere)
╵
╷
│ Warning: Using community license.
│ 
│   with constellation_cluster.aws_example,
│   on main.tf line 96, in resource "constellation_cluster" "aws_example":
│   96: resource "constellation_cluster" "aws_example" {
│ 
│ For details, see
│ https://docs.edgeless.systems/constellation/overview/license
╵
```
- Only print one of the warnings.
> terraform-provider: only print license warning once in provider

- .github/actions/notify_e2e_failure/action.yml
Field was missing
- Fix empty run-id in OpenSearch URL
- Re-add `cloudProvider` field to Issue board items
- Technically not needed anymore since we have `attestationVariant`, but leaving it empty doesn't look very nice, and I don't want to remove the field from the project since we still have a bunch of open Issues using that field
> ci: fix empty run-id in OpenSearch URL

- .github/workflows/draft-release.yml
The action for encrypting artifacts merged in #2567 and it's reversal introduced a bug here, as one requires multiple upload targets to split by spaces, and one by newlines. The reversal only changed the action path, but not the operator concatenating multiple lines in the upload targets, causing the upload to [fail](https://github.com/edgelesssys/constellation/actions/runs/7707757698).
- Use the previously used operator `|`, which concatenates the lines with `\n`s, as required by [actions/upload-artifact](https://github.com/actions/upload-artifact?tab=readme-ov-file#upload-using-multiple-paths-and-exclusions).
> ci: fix upload CLI path line splitting

- terraform/infrastructure/gcp/.terraform.lock.hcl
- terraform/infrastructure/gcp/main.tf
- terraform/infrastructure/gcp/modules/instance_group/main.tf
- terraform/infrastructure/gcp/modules/internal_load_balancer/main.tf
- terraform/infrastructure/gcp/modules/jump_host/main.tf
- terraform/infrastructure/gcp/modules/loadbalancer/main.tf
- terraform/infrastructure/iam/gcp/.terraform.lock.hcl
- terraform/infrastructure/iam/gcp/main.tf
We recently received a lot of failures in the tidy-check-generate due to Terraform not being able to query `google-beta:4.83.0`. I assume this to be related to some kind of (not-) caching which might make the download slow, as `4.83.0` is quite old, but this is just my uneducated guess.
- Update the GCP Terraform provider, and take out the `google-beta` provider, as it's not required anymore.
- [E2E Test](https://github.com/edgelesssys/constellation/actions/runs/7698074274)
> deps: update `hashicorp/google` to 5.13.0

- .github/actions/constellation_create/action.yml
Upload the terraform state of E2E tests (and other actions that use `constellation_create/action.yml`) as a github artifact. This allows to manually clean up resources and makes automation later on easy.
- add a step to upload `constellation-terraform` and `constellation-iam-terraform` in `.github/actions/constellation_create/action.yml`
> ci: Upload e2e terraform state as artifact

- .github/actions/constellation_create/action.yml
To allow for easier debugging and clean-up, we upload the terraform state/files used by the CI to create clusters.
To reduce the size of the artifacts we remove the cached providers before upload.
This causes problems for tests on GCP, since the CLI performs some actions depending on the providers still being present after we upload the state (which deletes the providers).
This is not an issue for AWS and Azure, since they will implicitly run `terraform init` before performing any action depending on the Terraform state. 
- Move files to upload to temporary directory and delete the providers from said temp dir before uploading it.
- Fixes https://github.com/edgelesssys/issues/issues/347
- [GCP e2e test](https://github.com/edgelesssys/constellation/actions/runs/7738258938/job/21098731334#st …
> ci: don't delete local cached providers when uploading Terraform state

- .github/actions/constellation_create/action.yml
- .github/workflows/e2e-upgrade.yml
- internal/atls/atls.go
- internal/constellation/kubecmd/kubecmd.go
- joinservice/internal/server/server.go
I collected some smaller issues while debugging failing e2e tests - this PR fixes some.
See also commit messages.
- atls: report cert extension OIDs on mismatch
- ci: correctly notify on e2e upgrade error
- cleanup: use NodeVersionResourceName constant
- ci: improve constellation_create error message
> cleanup: various minor debugging improvements

- .github/workflows/e2e-test-provider-example.yml
Determining the default Kubernetes version for the test failed, which was no caught by the test, since the relevant command was executed in a subshell.
- Properly fail if the command in the subshell failed
- Replace relative paths with github workspace absolute paths
- Fixes https://github.com/edgelesssys/issues/issues/352
Terraform e2e tests:
- [GCP](https://github.com/edgelesssys/constellation/actions/runs/7781986706)
- [Azure SEV-SNP](https://github.com/edgelesssys/constellation/actions/runs/7783895875)
- TDX test non functional since it selects the wrong instance type. Will fix in separate PR
- [AWS SEV-SNP](https://github.com/edgelesssys/constellation/actions/runs/7783906335)
> ci: fix workspace related errors when setting up k8s version for test

- .github/workflows/e2e-test-provider-example.yml
- terraform-provider-constellation/examples/full/aws/main.tf
- terraform-provider-constellation/examples/full/azure/main.tf
- terraform-provider-constellation/examples/full/gcp/main.tf
1. Terraform provider test for Azure TDX was using the default instance type for SEV-SNP resulting in failed initialization of the cluster.
2. Terraform provider test tries to upgrade TDX images to SEV-SNP images
- Make instance type configurable for provider sample
- Select the correct instance type for TDX e2e test
- TODO: Fix image upgrade issue
- [Azure e2e TDX](https://github.com/edgelesssys/constellation/actions/runs/7785773077)
> ci: make instance type configurable for provider sample

- .github/workflows/e2e-test-provider-example.yml
- .github/workflows/e2e-upgrade.yml
Our weekly tests had multiple different workflows that uploaded to the same artifact name, overwriting it for all workflows, which was not intended behavior.
Additionally, the actions/upload-artifact@v4 action now throws an error when uploading artifacts with the same name in one workflow run.
- Use workflow unique name for CLI binary in upgrade workflow
- Skip unnecessary Terraform module upload in provider example test
- Fixes https://github.com/edgelesssys/issues/issues/376
- [Terraform provider example test](https://github.com/edgelesssys/constellation/actions/runs/7868855242)
- [e2e upgrade test](https://github.com/edgelesssys/constellation/actions/runs/7868866271)
> ci: prevent duplicate artifact naming in same workflow

- internal/constellation/helm/action.go
We recently switched our logging from `Log(format string, args ...any)` to `Log(message string, args ...any)`.
This causes problems with the helm library which expects format strings.
- Add a wrapping function to provide helm a logger with format strings
- [e2e test with fixed logging](https://github.com/edgelesssys/constellation/actions/runs/7883947085/job/21511909342)
> helm: fix log formatting

- .github/workflows/e2e-upgrade.yml
In v4 of the artifact-upload action, which is used in the upgrade E2E test, it is no longer possible to [upload multiple artifacts with the same name](https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes). This caused race conditions when running multiple upgrade tests in parallel, and tests would [occasionally get artifacts that aren't meant for them](https://github.com/edgelesssys/constellation/actions/runs/7914280183/job/21642199733). 
- Give each of the uploaded artifacts individual names.
> ci: fix artifact overwriting in upgrade test

- debugd/internal/debugd/deploy/service.go
- debugd/internal/debugd/deploy/service_test.go
- Expose debug options to systemd overrides provided by debugd. The `--debug` is supported by upgrade-agent and bootstrapper.
- Fixes edgelesssys/issues#133.
> debugd: enable debug logging for systemd units

- .github/actions/constellation_create/aws-logs.sh
When we collect serial console logs of EC2 instances, we usually get truncated logs (e.g., somewhere around the disk-mapper 80% completion log). This is confusing during debugging, because it's unclear at which point a failing machine actually failed, and sometimes serial logs are the only thing we have about an instance. 
The [AWS docs](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/troubleshoot-unreachable-instance.html#instance-console-console-output) state:
> The console output returns buffered information that was posted shortly after an instance transition state (start, stop, reboot, and terminate). The posted output is not continuously updated; only when it is likely to be of the most value.
> You can optionally retrieve the latest serial console output at any time during the …
> ci: fetch latest console logs on aws

- .github/actions/e2e_benchmark/action.yml
The performance benchmark used a non unique name to upload the benchmark results as a GitHub artifact.
This causes unseen problems with upload@v3, since results from concurrent benchmark runs in the same workflow get overwritten, and causes hard errors with upload@v4.
- Append attestation variant to artifact name in GitHub
- Fixes https://github.com/edgelesssys/issues/issues/399
> ci: fix duplicate benchmark artificat name

- .github/actions/e2e_benchmark/action.yml
- .github/actions/e2e_test/action.yml
- .github/workflows/e2e-upgrade.yml
Fixes another issue in regards to duplicate artifact naming, discovered by using upload@v4
- Use workflow unique artifact for e2e upgrade log
- Use `artifactNameSuffix` variable for e2e benchmark artifacts naming
> ci: fix artifact naming problems in e2e test

- docs/docs/workflows/config.md
- internal/config/config.go
- terraform/infrastructure/openstack/modules/instance_group/main.tf
We are currently testing with the `m1a.8d-sev` instance type (2715eabe-3ffc-4c36-b02a-efa8c141a96a) and we know that this will be replaced by the following flavors:
| name     | vCPUs | GB RAM |
|----------|-------|--------|
| m1a.2cd  | 2     | 16     |
| m1a.4cd  | 4     | 32     |
| m1a.8cd  | 8     | 64     |
| m1a.16cd | 16    | 120    |
| m1a.30cd | 30    | 238    |
Since we do not know the flavor UUIDs today, we need to also accept instance type names.
This change allows the terraform code to accept either a flavor name or UUID and derive the correct UUID in any case.
- terraform: allow STACKIT / OpenStack instance type to be UUID or name
> terraform: allow STACKIT / OpenStack instance type to be UUID or name

- .github/workflows/draft-release.yml
Release breaks since slsa generator uses v3 of upload action, while we use v4 of download action.
References: [failed run](https://github.com/edgelesssys/constellation/actions/runs/8083325581/job/22114196641), [upstream issue](https://github.com/slsa-framework/slsa-github-generator/issues/3068)
- ci: match version of actions/download-artifact for slsa provenance
> ci: match version of actions/download-artifact for slsa provenance

- .github/workflows/e2e-test-provider-example.yml
- terraform-provider-constellation/examples/full/azure/main.tf
- terraform-provider-constellation/examples/full/gcp/main.tf
The Terraform e2e test uses the last 3 digits of the workflow run for various resource names.
This causes issues when running more than one test on the same CSP in the same workflow.
Notably this occurs for `azure-tdx` and `azure-sev-snp` in our weekly tests.
- Use the same collision resistant naming scheme as used by our other e2e tests
- Fixes https://github.com/edgelesssys/issues/issues/423
> ci: use collision resistant name for Terraform e2e test

- disk-mapper/cmd/main.go
- image/system/mkosi.conf
- image/system/variants.bzl
- internal/cloud/openstack/imds.go
- internal/cloud/openstack/imds_test.go
- internal/imagefetcher/imagefetcher.go
The disk-mapper can fail for various reasons. One that is hard to detect is currently the IMDS endpoint on OpenStack.
This change makes the error easily detectable using the serial console.
- Write boot log to all serial consoles on OpenStack (ttyS1 was missing)
- Let disk mapper also write to syslog on failure (this is in addition to the log of the unit itself and makes the logging more robust across cloud providers / virtualization solutions)
- improve the error message in cases where the OpenStack imds API returns errors
> disk-mapper: write to syslog

- internal/grpc/retry/retry.go
- internal/grpc/retry/retry_test.go
CLI (and also our Terraform provider) uses gRPC to talk with different services on Constellation.
We have a retry logic for these calls that make sure transient errors don't cause the entire action to fail.
In the past we have observed "authentication handshake failed: context deadline exceeded" during these rpcs.
Since we do not set a deadline for some of our CLI commands (e.g. `constellation recover`) but we have observed these errors nonetheless, I believe that gRPC/Go TLS uses a custom deadline at some point during the handshake.
This deadline may be exceeded by transient connection errors and should be retried by our code.
- add `authentication handshake failed: context deadline exceeded` to the list of retriable rpc errors
This PR may resolve the following issues, though we should …
> cli: retry auth handshake deadline exceeded errors in CLI and Terraform

- docs/docs/getting-started/first-steps.md
- docs/versioned_docs/version-2.16/getting-started/first-steps.md
The OpenStack credentials (username and password) can now be retrieved from the "clouds.yaml" by the Constellation CLI and terraform code. This simplifies the configuration for end users.
- docs: remove steps for STACKIT credentials in config
> docs: remove steps for STACKIT credentials in config

- bootstrapper/cmd/bootstrapper/run.go
- bootstrapper/internal/diskencryption/diskencryption.go
- bootstrapper/internal/initserver/BUILD.bazel
- bootstrapper/internal/initserver/initserver.go
- bootstrapper/internal/initserver/initserver_test.go
- bootstrapper/internal/joinclient/BUILD.bazel
- bootstrapper/internal/joinclient/joinclient.go
- bootstrapper/internal/joinclient/joinclient_test.go
- csi/test/mount_integration_test.go
- disk-mapper/internal/test/integration_test.go
Constellation's bootstrapper may fail at multiple stages.
Some of these failures are transient, like joining an existing cluster using `kubeadm` and may be retried.
Others are not recoverable, meaning one can no longer re-run `constellation apply` on the same node, or the node can no longer retry joining an existing cluster.
To "fix" a VM that is in this failed state, the VM needs to be rebooted, and the state-disk wiped.
- Change how `joinClient` and `initServer` are run
- Both routines now have return values and are run in parallel
- If any error occurs in `run()`, the VM is rebooted
- Adapt the flow of `joinClient` to more easily differentiate between transient and non recoverable errors
- In both `joinClient` and `initServer`, mark the state disk as not initialized if a non …
> bootstrapper: wipe disk and reboot on non-recoverable error

- internal/constellation/helm/action.go
- internal/constellation/helm/actionfactory.go
Helm installations can fail halfway through due to transient problems (e.g. edgelesssys/issues#30). If we're unlucky, the subsequent uninstall also fails, which makes future installation attempts fail because there is already an existing release.
- After a failure in `helm install`, check whether uninstalling worked and uninstall manually if not.
- Fixes edgelesssys/issues#367
1. Created a cluster on Azure from `main` and applied up to excluding the `helm` phase.
2. Added an iptables rule to drop all etcd traffic.
3. Ran the `helm` phase, which expectedly failed with the symptoms of edgelesssys/issues#367.
4. Removed the iptables rule, confirmed that Kubernetes is serving again.
5. Re-ran the `helm` phase, expectedly observing the same failure.
6. Built from this PRs HEAD and ran the …
> helm: manually retry uninstalling a failed release

- operators/constellation-node-operator/internal/cloud/gcp/client/disks.go
- operators/constellation-node-operator/internal/cloud/gcp/client/disks_test.go
Since the regex is used for values that are provided by GCP's IMDS API they (and nobody else) has control over those values. Since they can provide arbitrary values for the disk information anyway, there's no threat.
- escape url dots in regex
> operator: escape dots in url

- .github/actions/cdbg_deploy/action.yml
Azure AD suffers from a propagation delay: a managed identity created in a far location may not show up in `az identity list` for a couple of minutes, which is long enough to break our tests, which assume read-after-write consistency. Using `az identity show` seems to circumvent the cache, and it also happens to be the cleaner solution.
- Use `az identity show` instead of `az identity list`.
- Add debugging information if the principal id is still not found.
- Fixes edgelesssys/issues#408
> ci: query identity directly instead of searching in list

- .github/actions/constellation_destroy/action.yml
"default" and "kube-system" are protected namespaces in Kubernetes and can't be deleted.
This causes problems if a PVC was create in one of those namespaces and the `constellation_destroy` action tries to clean up the cluster, since that action just tries to delete any namespace with a PVC in it.
- Don't try to delete non deletable namespaces ("default", "kube-system")
- Instead, just try to delete all pvcs in that namespace
- Don't abort the `constellation_destroy` action if pvc deletion fails
- Lingering PVCs are annoying and costs money, but lingering clusters even more so
- See https://github.com/edgelesssys/issues/issues/465 for an e2e run that caused this failure
- Fixes https://github.com/edgelesssys/issues/issues/402
> ci: fix pvc clean-up on non deletable namespaces

- .github/actions/e2e_test/action.yml
- .github/workflows/e2e-test-provider-example.yml
- .github/workflows/e2e-upgrade.yml
License check is supposed to be disabled for e2e tests, but it wasn't for some test configs, e.g., TF provider.
> ci: fix unwanted license checks for some e2e test configs

- e2e/miniconstellation/test-remote.sh
> ci: disable license check for minicon e2e

- 3rdparty/bazel/org_golang/BUILD.bazel
- 3rdparty/bazel/org_golang/go_tls_max_handshake_size.patch
- WORKSPACE.bazel
Go has a very small default for the maximum handshake size in TLS (65536 bytes), while the protocol specifies a maximum of 16 MB.
Since aTLS adds a lot of additional data to TLS certificates, an increase of this handshake size is needed.
Currently, this requires a patch of the Go SDK.
- bazel: patch Go SDK to increase tls maxHandshake size
- Upstream proposal for making this limit configurable: https://github.com/golang/go/issues/50773
> bazel: patch Go SDK to increase tls maxHandshake size

- .github/workflows/e2e-test-release.yml
- .github/workflows/e2e-test-weekly.yml
New release, new default version for upgrade tests
- Bump `fromVersion` to v2.16.2`
- Wait for v2.16.2 release to finish before merging
- https://github.com/edgelesssys/constellation/actions/runs/8570539093
> ci: bump `fromVersion` for e2e tests to v2.16.2

- internal/constellation/helm/helm_test.go
550798279a8bb625e3b0b34f2b3eefa1a76b4c32 broke the Helm tests because it updated the Cilium version without updating the expected version in the test.
- Bump version in test.
- [AB#4002](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/4002)
> helm: unbreak helm test after Cilium version bump

- .github/workflows/e2e-windows.yml
The Windows e2e never uploaded the container images that were built for the CLI that is used in the test.
This causes the cluster to never fully come up.
- Upload container images when building the CLI in the Windows e2e test
- Generate unique resource group names in Windows e2e test so more than one test can run in parallel
- Print the `kubectl` output when waiting for nodes to come up
- [Windows e2e test](https://github.com/edgelesssys/constellation/actions/runs/8631320963/job/23659874252)
> ci: fix Windows e2e test not pushing required container images

- .github/workflows/e2e-windows.yml
The liveness probe should not print "All nodes are ready!" after an unsuccessful call to kubectl. Instead, it should retry the command after the specified time.
- Check the exit status of kubectl command and continue the retry loop if the execution failed.
- Add check to not wait another 30 seconds after last retry has finished.
- https://github.com/edgelesssys/issues/issues/506
- [AB#4027](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/4027)
- [windows-e2e-test](https://github.com/edgelesssys/constellation/actions/runs/8616718469)
> ci: add error handling to e2e windows liveness probe

- internal/constellation/kubecmd/backup.go
- internal/constellation/kubecmd/kubecmd.go
- internal/constellation/kubecmd/kubecmd_test.go
Interaction with Kubernetes may fail due to intermittent failures, e.g. etcd timeouts or network failures.
Since not all of our code handles retrying these failures well, Constellation CLI commands may fail mid execution because of this.
- Use the already existing retry logic in all places interacting with the Kubernetes API in `internal/constellation/kubecmd` to increase reliability of CLI commands and the Terraform provider during cluster creation and upgrades
- fixes https://github.com/edgelesssys/issues/issues/522
> kubecmd: retry any K8s errors in CLI and Terraform

- .github/workflows/assign_reviewer.yml
Constellation receives a considerable amount of maintenance PRs, which are usually assigned to code owners for review. This is an attempt to increase fairness and distribute the review load.
- Assign one of the Constellation maintainers to dependecy PRs at random.
- [AB#4062](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/4062)
> deps: auto-assign reviewer for deps PRs

- .github/workflows/e2e-test-weekly.yml
weekly runs were broken for 1.5 weeks due to a missing permission when calling the e2e-windows workflow
- Add `check: write` permission when calling e2e-windows from weekly test
[e2e test](https://github.com/edgelesssys/constellation/actions/runs/8782453540)
> ci: add missing permission for e2e-windows test in weekly run

- .github/actions/constellation_iam_create/action.yml
- .github/actions/e2e_test/action.yml
- .github/workflows/e2e-windows.yml
If cleanups fail, it should be easier to locate resources created by an e2e test.
- add an input to `constellation_iam_create/action.yml` that allows the addition of additional tags.
- tag all resources created through `e2e_test/action.yml` with the generated prefix
- Since windows e2e tests don't use `e2e_test/action.yml`, resources are tagged with the resource group name instead.
> ci: tag resources created by e2e tests with the run name

- .github/actions/constellation_iam_create/action.yml
- .github/actions/e2e_test/action.yml
- .github/workflows/e2e-windows.yml
The new `--tags` flag was set unconditionally for all e2e runs, which breaks runs on stable releases or upgrade tests.
- Only set `--tags` if the CLI supports it
- Use `github.run_id` instead of `github.workflow`
- Tagging runs with the run ID was the intended behavior of the action
- Fixes https://github.com/edgelesssys/issues/issues/537
- Fixes https://github.com/edgelesssys/issues/issues/540
- [Azure stable image](https://github.com/edgelesssys/constellation/actions/runs/8844438019)
- [Azure debug image](https://github.com/edgelesssys/constellation/actions/runs/8844430632)
> ci: ensure `--tags` flag is only set if the CLI supports it

- dev-docs/howto/kubeconfigs.md
There's currently no documentation on how to generate new kubeconfigs for an existing Constellation.
This PR is the first step towards a documented procedure.
The mechanism described could be integrated into the CLI, or published as a user facing doc.
- Describe the kubeconfig generation process in dev-docs.
- [AB#4093](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/4093)
> dev-docs: howto generate kubeconfigs

- .github/actions/e2e_verify/action.yml
- .github/workflows/e2e-test-daily.yml
gcp-sev-snp was disabled on daily e2e tests since we currently don't have stable images for this variant.
However, we the test was disabled for both debug and stable images.
- Enable gcp-sev-snp for daily test runs
- Currently excludes stable images from the test
- Fix verify e2e test for gcp-sev-snp
- Properly create the JSON file for gcp-sev-snp and upload it
- Remove a check for backwards compatibility with old CLI versions (v2.13)
- [e2e test](https://github.com/edgelesssys/constellation/actions/runs/8922428735/job/24504575569)
- Fixes https://github.com/edgelesssys/issues/issues/547
> ci: enable gcp-sev-snp for daily tests

- .github/workflows/e2e-test.yml
- terraform/infrastructure/aws/variables.tf
- terraform/infrastructure/azure/variables.tf
- terraform/infrastructure/gcp/variables.tf
- terraform/infrastructure/openstack/variables.tf
Since no default value was given for `additional_tags` / `additional_labels`, Terraform interprets the variable as required, causing issues when running our Terraform provider example test, which calls the Terraform infrastructure files used by the CLI as a module:
```
│ Error: Missing required argument
│ 
│   on main.tf line 51, in module "azure_infrastructure":
│   51: module "azure_infrastructure" {
│ 
│ The argument "additional_tags" is required, but no definition was found.
```
- Provide default values (empty map) for the `additional_tags` field
- I went with this option rather than setting a default in the example `main.tf`, since the additional tags are supposed to be optional. A user should not need to set any additional tags if they don't wish to do so
- Fixes …
> terraform: set empty default value for `additional_tags`

- .github/workflows/e2e-windows.yml
Failed Windows E2E tests may not be cleaned up correctly.
- If termination of the cluster/destruction of the IAM configuration using terraform fails, delete all resource groups using the azure CLI
- Clean up if `constellation terminate` fails: https://github.com/edgelesssys/constellation/actions/runs/8924646002/job/24511751671
- Clean up if `constellation iam destroy` fails: https://github.com/edgelesssys/constellation/actions/runs/8925134979/job/24513391935
- If neither `constellation terminate` nor `constellation iam destroy` fails: https://github.com/edgelesssys/constellation/actions/runs/8925624928
> ci: correctly clean up failed windows e2e tests

- terraform/infrastructure/aws/main.tf
- terraform/infrastructure/aws/modules/jump_host/main.tf
- terraform/infrastructure/azure/main.tf
- terraform/infrastructure/gcp/main.tf
```
May 03 12:39:20 fedora bootstrapper[3378]: {"time":"2024-05-03T12:39:20.374587495Z","level":"ERROR","source":{"function":"github.com/edgelesssys/constellation/v2/bootstrapper/internal/joinclient.(*JoinClient).getControlPlaneIPs","file":"bootstrapper/internal/joinclient/joinclient.go","line":357},"msg":"Failed to list instances from metadata API","bootstrapper":{"join-client":{"error":"retrieving tag for instance i-03976588af8c28747: tag \"constellation-role\" not found"}}}
```
- Remove the `constellation-uid` tag from the jump host since the tag signals that the instance belongs to the Constellation cluster which the jump host does not.
Note that the jump host is only ever applied when using a load balancer and the debug mode.
> terraform: Allow nodes to join the cluster when using a jump host by removing the `constellation-uid` tag

- .github/actions/versionsapi/Dockerfile
- .github/workflows/build-ccm-gcp.yml
- .github/workflows/build-os-image-scheduled.yml
- .github/workflows/codeql.yml
- .github/workflows/release.yml
- .github/workflows/test-operator-codegen.yml
- 3rdparty/gcp-guest-agent/Dockerfile
- WORKSPACE.bazel
- dev-docs/workflows/bump-go-version.md
- go.work
- renovate.json5
New Go v1.22.3 released with v1.22.2 causing errors in `govulncheck`
- Update to Go 1.22.3
- Replace deprecated renovate syntax
> deps: update to Go 1.22.3

- .github/workflows/e2e-attestationconfigapi.yml
This workflow touches shared state by deleting all objects of a bucket and then
uploading a signed blob of data to that S3 bucket under a fixed name.
It also does so multiple times in a row, while invalidating the cloudfront
cache and checking if the uploaded object exists.
All runs of this workflow share the same bucket.
Since this pipeline runs on any modification of go.mod, it is very prone
to race condition between PRs (or PRs and main).
- ci: disable e2e-attestationconfigapi on PRs
> ci: disable e2e-attestationconfigapi on PRs

- internal/constellation/helm/overrides.go
- disable Cilium's ip masq agent when running in conformance mode since the ip masq agent requires bpf masquerading
I tested this on AWS.
> helm: Restore the ability to start a cluster in conformance mode by disabling the cilium ipmasq agent when in conformance mode

- .github/actions/e2e_lb/action.yml
- .github/actions/e2e_lb/aws-ingress.yml
- .github/actions/e2e_test/action.yml
- docs/docs/workflows/lb.md
- terraform/BUILD.bazel
- terraform/infrastructure/iam/aws/alb_policy.json
- terraform/infrastructure/iam/aws/main.tf
Node role permissions are currently handcrafted to allow the set of use cases we identified so far. We did not consider the use of AWS LBC as an Ingress provisioner, though, and thus never checked whether the policies are sufficient.
- Apply the [recommended policy](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.7/deploy/installation/#option-b-attach-iam-policies-to-nodes).
- Add a test to ensure ALB Ingresses can be created.
- Document considerations for using ALB Ingress with Constellation.
- Fixes #3056 
* https://github.com/edgelesssys/constellation/actions/runs/8938280204/job/24552109686 (intermediate state)
* https://github.com/edgelesssys/constellation/actions/runs/8968562872 (current HEAD)
> terraform: add missing policies for AWS ALB

- bazel/toolchains/go_module_deps.bzl
- go.mod
- go.sum
We skipped this package because it failed when upgrading.
With this change, everything should be working.
- deps: update bazel buildtools
> deps: update bazel buildtools

- internal/cloud/azure/BUILD.bazel
- internal/cloud/azure/azure.go
- internal/cloud/azure/iptables_cross.go
- internal/cloud/azure/iptables_linux.go
Kubernetes v1.30 hides most of the [`k8s.io/kubernetes/pkg/util/iptables`](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/iptables) package behind `linux` build tags, breaking builds if we directly import variables from that package.
- Hide usage of `iptables` package behind build tags so we can upgrade `k8s.io/kubernetes` to `0.30.0`
- https://github.com/edgelesssys/constellation/actions/runs/9060041327/job/24891295717
> cloud: hide kubernetes iptables usage behind linux build tag

- .github/workflows/assign_reviewer.yml
CI currently assigns reviewers to all PRs with the `dependencies` label. The label can and should be used by humans, though, where manual reviewer assignment is preferrable. This also avoids the assignment failing if author == reviewer.
- Only assign a reviewer automatically to renovate PRs.
> ci: only assign reviewer to bot PRs

- .github/actions/e2e_lb/action.yml
- .github/actions/e2e_malicious_join/action.yml
- .github/actions/e2e_mini/action.yml
- .github/workflows/e2e-test-provider-example.yml
- .github/workflows/e2e-upgrade.yml
The default test timeout was five minutes. Due to an upgrade of rules_go, this timeout is now enforced.
- ci: explicitly set bazel test timeout to four hours for e2e tests
> ci: explicitly set bazel test timeout to four hours for e2e tests

- .github/workflows/release.yml
On release, we modify the Helm chart, package it and update the source tree with the new versions. We forgot to commit `values.yaml`, though.
Note: this is not an issue in released Helm charts, because they are packaged from the dirty working tree.
- Also commit `values.yaml`.
> s3proxy: commit image version on release, too

- terraform/infrastructure/gcp/modules/instance_group/main.tf
Upgrades of existing GCP SEV-ES clusters are failing because setting `confidential_instance_type` makes Terraform want to re-create the instance templates, which does not work because they are still in use by instances.
- Only set `confidential_instance_type` if `cc_technology` is `SEV_SNP`
- When this feature is introduced into the mainline GCP Terraform provider, we will likely have to introduce some form of migration, but I would hold of on that until the provider maintainers decide on how this will look like
- Fixes https://github.com/edgelesssys/issues/issues/545
> terraform: only set `confidential_instance_type` if `cc_technology` is `SEV_SNP`

- renovate.json5
Trying to keep our dependencies up to date, I noticed that Terraform dependencies are not grouped, taking up most of the space in our renovate dashboard.
Lets group the updates for easier maintenance.
- Group all Terraform dependecy updates in one PR
> renovate: group all Terraform dependency updates into one PR

- bazel/toolchains/go_module_deps.bzl
- go.mod
- go.sum
- internal/attestation/aws/snp/BUILD.bazel
- internal/attestation/aws/snp/issuer.go
- internal/attestation/azure/snp/validator_test.go
- internal/attestation/gcp/snp/BUILD.bazel
- internal/attestation/gcp/snp/issuer.go
- internal/attestation/snp/BUILD.bazel
- internal/attestation/snp/snp.go
- internal/verify/verify.go
Our `go.mod` file had a replace statement for `github.com/google/go-sev-guest` which prevented us from actually upgrading the dependency
- Remove the replace statement and replace usage of deprecated functions
- Fixes https://github.com/edgelesssys/issues/issues/583
> deps: remove obsolete Go replace to upgrade go-sev-guest

- bootstrapper/cmd/bootstrapper/main.go
- bootstrapper/cmd/bootstrapper/test.go
- bootstrapper/internal/etcdio/BUILD.bazel
- bootstrapper/internal/etcdio/etcdio.go
- bootstrapper/internal/initserver/initserver.go
- bootstrapper/internal/initserver/initserver_test.go
- bootstrapper/internal/joinclient/joinclient.go
- bootstrapper/internal/joinclient/joinclient_test.go
- bootstrapper/internal/kubernetes/BUILD.bazel
- bootstrapper/internal/kubernetes/kubernetes.go
- bootstrapper/internal/kubernetes/kubernetes_test.go
The etcd issues like the notorious "etcdserver: leader changed" are most likely caused due to etcd's disk activity conflicting with other disk-heavy operations during cluster initialization / joining such as the pulling of container images. To mitigate this, we can prioritize the disk operations of the etcd process over those of other processes by giving it an I/O priority in the kernel. It will not consider pod restarts of etcd, which are out of scope for this PR.
**How to move forward:**
We'll need to see (over a course of, say, 2 weeks) if this change is enough to get rid of the issues. If not, we'll probably need to use faster disks per default on Azure. This would probably require switching to the (~90€/M) 512Gb P20 disk, which satisfies the [requirements of …
> bootstrapper: prioritize etcd disk I/O

- .github/actions/artifact_download/action.yml
- .github/actions/artifact_upload/action.yml
During our e2e tests, we have a pre-configured list of files we plan to upload.
If some of these files don't exist, our artifact upload action fails, and we never upload an archive.
This can happen if the CLI fails during creation of the infrastructure, and then fails to clean up said infrastructure.
In this case, no `constellation-mastersecret.json` was ever created and the archive creation fails.
This causes problems for the clean-up action of the upgrade test.
- Only add files to the archive if they actually exist
- Reduce noise of archive creation and extraction
> ci: ignore missing files when creating archive

- .github/actions/artifact_upload/action.yml
Upload action accepts files, directories, or patterns as input.
This is a problem if we only check for file existence when creating the archive.
- Check for pattern completion instead of file existence
- Fixes https://github.com/edgelesssys/issues/issues/618
> ci: check for pattern completion instead of file when creating archive

- .github/actions/e2e_mini/action.yml
- .github/workflows/e2e-mini.yml
- .github/workflows/e2e-test-daily.yml
- .github/workflows/e2e-test-weekly.yml
- e2e/miniconstellation/main.sh.in
- e2e/miniconstellation/output.tf
Currently, if a QEMU/miniconstellation e2e test fails or is cancelled, the created resources won't be cleaned up automatically.
- If a test fails or is cancelled, delete the created resource group using the azure CLI.
- A successful run can be seen [here](https://github.com/edgelesssys/constellation/actions/runs/9113876753/job/25056476083) (The cleanup happens at the very bottom of "Run e2e MiniConstellation")
> ci: clean up failed miniconstellation e2e tests

- flake.lock
- flake.nix
We updated Bazel to v7.1.2 in #3136, but Bazel is still on v7.1.0 in `nixpkgs-unstable`, where we source it from. Therefore, we need to pin the nixpkgs version against the exact commit that updated Bazel to v7.1.2 in nixpkgs, until that commit lands in `nixpkgs-unstable`.
- Source Bazel from a pinned nixpkgs.
- Update the Nix flake.
> flake: pin bazel to 7.1.2

- .github/workflows/assign_reviewer.yml
Lots of dependency PRs don't get assigned a reviewer.
I hope this PR fixes some of the cases where the review assignment  is skipped.
- Add more triggers to the assign_reviewer workflow
- Only run the workflow if no reviewers are assigned
- Update the name we check against to `renovate[bot]` following this comment: https://github.com/renovatebot/renovate/discussions/13704#discussioncomment-7079564
> Update conditions on when to pick reviewer

- bootstrapper/cmd/bootstrapper/main.go
- image/base/mkosi.skeleton/usr/lib/systemd/system/constellation-bootstrapper.service
- image/base/mkosi.skeleton/usr/lib/systemd/system/constellation-upgrade-agent.service
- upgrade-agent/cmd/main.go
The bootstrapper vomits out a whole lot of gRPC debug logs, which don't seem very useful.
- Remove the `debug` flag.
> bootstrapper: disable gRPC logging

- rfc/016-node-access.md
This RFC proposes a mechanism for accessing Constellation nodes for maintenance.
> rfc: node access

- bazel/ci/BUILD.bazel
Since we introduced bzlmod, using `@io_bazel_rules_go//go` as Go binary for CI scripts does not work anymore. Example:
```raw
$ bazel run //bazel/ci:govulncheck
Starting local Bazel server and connecting to it...
INFO: Analyzed target //bazel/ci:govulncheck (146 packages loaded, 12854 targets configured).
INFO: Found 1 target...
Target //bazel/ci:govulncheck up-to-date:
bazel-bin/bazel/ci/govulncheck-script.bash
bazel-bin/bazel/ci/govulncheck
INFO: Elapsed time: 4.579s, Critical Path: 0.44s
INFO: 6 processes: 6 internal.
INFO: Build completed successfully, 6 total actions
INFO: Running command line: bazel-bin/bazel/ci/govulncheck
2024/06/05 14:13:47 runfiles: no runfiles found
ERROR: /home/burger/.cache/bazel/_bazel_burger/71bc3bb25a3aa4f6aac591d8b4f36d9e/execroot/_main/bazel-out/k8-opt/bi …
```
> bazel: use go_bin_for_host for all CI scripts

- bazel/ci/govulncheck.sh.in
We have a unix pipeline for filtering the output of govulncheck. It seems like the output format changed since it was introduced, because the filtered output does not make much sense at the moment.
- Don't filter the output, trading in beauty for lower maintenance effort.
- Example output: https://github.com/edgelesssys/constellation/actions/runs/9383762951/job/25838113072#step:12:196
> ci: don't filter output of govulncheck

- debugd/internal/debugd/deploy/service.go
- debugd/internal/debugd/deploy/service_test.go
The `--debug` flag was removed from the bootstrapper, yet the debugd still sets it when creating the service unit.
- remove `--debug` from the service created by debugd
- https://github.com/edgelesssys/issues/issues/658
- Will built a new debug image once this is merged to main
> debugd: remove `--debug` flag from bootstrapper service created by debugd

- docs/docs/getting-started/install.md
- docs/docs/workflows/create.md
- docs/versioned_docs/version-2.10/getting-started/install.md
- docs/versioned_docs/version-2.11/getting-started/install.md
- docs/versioned_docs/version-2.12/getting-started/install.md
- docs/versioned_docs/version-2.13/getting-started/install.md
- docs/versioned_docs/version-2.13/workflows/create.md
- docs/versioned_docs/version-2.14/getting-started/install.md
- docs/versioned_docs/version-2.14/workflows/create.md
- docs/versioned_docs/version-2.15/getting-started/install.md
- docs/versioned_docs/version-2.15/workflows/create.md
- docs/versioned_docs/version-2.16/getting-started/install.md
- docs/versioned_docs/version-2.16/workflows/create.md
- docs/versioned_docs/version-2.7/getting-started/install.md
- docs/versioned_docs/version-2.8/getting-started/install.md
- docs/versioned_docs/version-2.9/getting-started/install.md
The docs said that the permissions for updating the MAA policy are only required if the enforcement policy is set to use the MAA. However, this does not reflect our current code, which creates and patches the MAA unconditionally. This is necessary to ensure that a cluster created without using the MAA can switch to using the MAA later on.
- Remove the parts of the docs saying that the MAA-related permissions are only necessary if the enforcement policy is set to `MAAFallback`.
> docs: adjust MAA updating

- internal/maa/patch.go
The updating of the MAA policy is not done via Terraform, hence failures cannot be debugged through the Terraform logs. We only return the status code currently, which is not very helpful for users running into a failure here. The response body should inform the user about which permissions are missing, hence it should also be shown to the user.
- Return both status code and response body in case of a policy patching failure.
> cli: return a more helpful error message on MAA patch failure

- .github/workflows/e2e-test-release.yml
- .github/workflows/e2e-test-weekly.yml
The latest patch versions seem to have missed the version bumps in the CI, causing TDX upgrade tests to [fail](https://github.com/edgelesssys/constellation/actions/runs/9425683025/job/25969543555), as they miss #3038. 
Fixes: https://github.com/edgelesssys/issues/issues/664
- Bump the versions.
> ci: bump origin versions of upgrade tests

- internal/constellation/helm/charts/cilium/Chart.yaml
- internal/constellation/helm/charts/cilium/README.md
- internal/constellation/helm/charts/cilium/files/agent/poststart-eni.bash
- internal/constellation/helm/charts/cilium/files/cilium-agent/dashboards/cilium-dashboard.json
- internal/constellation/helm/charts/cilium/files/nodeinit/startup.bash
- internal/constellation/helm/charts/cilium/templates/cilium-agent/daemonset.yaml
- internal/constellation/helm/charts/cilium/templates/cilium-agent/servicemonitor.yaml
- internal/constellation/helm/charts/cilium/templates/cilium-configmap.yaml
- internal/constellation/helm/charts/cilium/templates/cilium-envoy/daemonset.yaml
- internal/constellation/helm/charts/cilium/templates/cilium-envoy/servicemonitor.yaml
- internal/constellation/helm/charts/cilium/templates/cilium-nodeinit/daemonset.yaml
- internal/constellation/helm/charts/cilium/templates/cilium-preflight/daemonset.yaml
- internal/constellation/helm/charts/cilium/templates/cilium-preflight/deployment.yaml
- internal/constellation/helm/charts/cilium/templates/clustermesh-apiserver/deployment.yaml
- internal/constellation/helm/charts/cilium/templates/hubble-relay/deployment.yaml
- internal/constellation/helm/charts/cilium/templates/spire/agent/daemonset.yaml
- internal/constellation/helm/charts/cilium/templates/spire/namespace.yaml
- internal/constellation/helm/charts/cilium/values.yaml
- internal/constellation/helm/charts/cilium/values.yaml.tmpl
- internal/constellation/helm/cilium.patch
- internal/constellation/helm/generateCilium.sh
- internal/constellation/helm/helm_test.go
- internal/constellation/helm/loader.go
[Cilium v1.15.5](https://github.com/cilium/cilium/releases/tag/v1.15.5) was released on 2024-05-15.
- Upgrade upstream base from `v1.15.0-pre.3` to `v1.15.5`.
- [AB#4180](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/4180)
> helm: upgrade Cilium to v1.15.5-edg.1

- go.mod
Constellation consumes some of its dependencies from edgeless-related forks. Inspecting these forks, some turned out not to be needed anymore:
* `tink-go` updated  Bazel visibility in v2.1.0
* (2024-06-11: the rest was resolved elsewhere)
- Upgrade `tink-go`.
> deps: upgrade to tink-go v2.1.0

- debugd/internal/debugd/deploy/service.go
- debugd/internal/debugd/deploy/service_test.go
- debugd/internal/debugd/deploy/wrappers.go
- debugd/internal/debugd/logcollector/logcollector.go
We have observed multiple cases of `debugd` failing when the `bootstrapper` unit should be restarted.
This is tracked in https://github.com/edgelesssys/issues/issues/609
Since this happens rather early in the deployment process, we don't have any logs pushed to OpenSearch at this point
- Read and return systemd logs of the unit that failed to be restarted on failure
- Wait until logcollection containers are running before continuing
- This doesn't really solve the issue of no logs being pushed to OpenSearch since logs are not pushed on creation, but aggregated every 30 seconds and then pushed to OpenSearch, but I think its a good practice regardless
> debugd: return systemd logs if restarting a unit fails

- internal/attestation/azure/tdx/validator.go
Azure updated their Intel TDX firmware, so its now actually compatible with the TCB info returned by Intel's PCS.
This means we can use the PCS to perform CRL checks on the TDX certificates.
- Enable collateral retrieval and CRL checking for Azure TDX
- [Azure TDX e2e test](https://github.com/edgelesssys/constellation/actions/runs/9462669036)
> attetstation: enable Azure TDX CRL checking

- cli/internal/cmd/BUILD.bazel
- cli/internal/cmd/verify.go
- cli/internal/cmd/verify_test.go
- internal/attestation/azure/tdx/issuer.go
- internal/attestation/azure/tdx/tdx.go
- internal/attestation/azure/tdx/validator.go
- internal/verify/verify.go
Our CI parses the JSON output of `constellation verify` in order to upload the latest CC claims to Constellation's CDN.
For now, this was only enabled for SEV-SNP attestation variants.
- Enabled JSON output for Azure TDX
- The TDX library we use also handles JSON marshalling of the quote, so I didn't implement any extra methods, unlike we did for SNP. This means we won't have pretty formatted text output for TDX variants, but this can always be added at a later date since it doesn't have high priority: [AB#4266](https://dev.azure.com/Edgeless/Edgeless/_workitems/edit/4266)
- Simplify the `constellation verify` code a bit by removing the formatter factory
- [AB#3798](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3798)
> cli: enable JSON output for `constellation verify` on Azure TDX

- .github/actions/cdbg_deploy/action.yml
We had a couple of failed `cdbg deploy` steps recently, which are incredibly hard to spot in the logs because they are hidden in the log group. Adding an explicit `::error::` should highlight them. 
- Write an error message if `cdbg deploy` failed.
> ci: make cdbg deploy errors easier to spot

- .github/actions/pick_assignee/action.yml
> ci: don't assign 3u13r for e2e failures

- .github/workflows/test-tidy.yml
The Github step summary for tidy-check-generate renders badly if there are code fences in the diff: https://github.com/edgelesssys/constellation/actions/runs/9578991258.
- Use quadruple fences ([docs](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks)).
> ci: better fence around tidy-check-generate summary

- .github/actions/gcpccm_vers_to_build/findvers.sh
Due to a small mistake in the script, it only ever worked correctly if there were 0 or 1 images to build. Last week saw 3 new tags published on the repo, which triggered the failure: https://github.com/edgelesssys/constellation/actions/runs/9582767025/job/26422530403.
- Print one tag per line before handling with `jq`.
> ci: fix GCP CCM findvers.sh script

- .github/actions/cdbg_deploy/action.yml
The attempted fix of error logging in #3168 is incomplete, because the shell (started with `-e`) exits before it even reaches the return code check: https://github.com/edgelesssys/constellation/actions/runs/9590976869/job/26447189061#step:4:3609.
- Use an `ERR` trap to report the error.
> ci: fix cdbg_deploy error reporting

- debugd/internal/debugd/deploy/service.go
- debugd/internal/debugd/deploy/service_test.go
- debugd/internal/debugd/deploy/wrappers.go
On debug images, our bootstrapper and upgrade-agent systemd units continuously fail until the binaries are uploaded using `cdbg deploy`.
Once this is done, the `debugd` issues a `systemctl restart` command to those units.
Under some circumstances, this restart can fall into the timeout period from our units being rate limited in restarting by systemd.
We can use `systemctl reset-failed` to reset the failed counter and by this way bypass the timeout.
See https://bugzilla.redhat.com/show_bug.cgi?id=1016548 for some more details about the issue.
See [the man page](https://www.freedesktop.org/software/systemd/man/latest/systemctl.html#reset-failed%20%5BPATTERN%E2%80%A6%5D) for `systemctl reset-failed`.
- Run `systemctl reset-failed` before restarting a unit in `debugd`
- (should) fix …
> debugd: reset unit failed status before restarting

- cli/internal/cmd/verify.go
- cli/internal/cmd/verify_test.go
- docs/docs/workflows/verify-cluster.md
- docs/versioned_docs/version-2.15/workflows/verify-cluster.md
- docs/versioned_docs/version-2.16/workflows/verify-cluster.md
`constellation verify` should be usable with only a config file, the IP of the service, and the cluster ID of a Constellation cluster
- Remove dependency on an initialized `constellation-state.yaml` when executing `constellation verify` with `--endpoint` and `--cluster-id` flags set
- More prominently mention requirement for `constellation-conf.yaml` for `constellation verify` in our docs
- fixes https://github.com/edgelesssys/constellation/issues/3181
> cli: fix `constellation verify` depending on an initialized `constellation-state.yaml` file

- bazel/ci/BUILD.bazel
Our CI occasionally failed when running `bazel run //:generate` because some sub commands of the target could interfere with each other. 
- Ensure more stable `bazel run //:generate` by not running all commands in parallel
> ci: make bazel generate more stable

- operators/constellation-node-operator/internal/upgrade/BUILD.bazel
- operators/constellation-node-operator/internal/upgrade/upgrade.go
- operators/constellation-node-operator/internal/upgrade/upgrade_test.go
`grpc.NewClient` uses DNS as default resolver. This does not work for UDS, so we need to specify the resolver explicitly.
- Dial UDS with `unix:` prefix (see https://github.com/grpc/grpc/blob/master/doc/naming.md).
- Fixes edgelesssys/issues#711
> operator: fix gRPC dialing over UDS

- debugd/filebeat/Dockerfile
- debugd/internal/debugd/logcollector/logcollector.go
The logcollection deployed by debugd is not working since ~2024-06-08. Investigating a debug cluster, it turns out that `podman`  commands fail because of an absent `crun` runtime. A change in defaults might have been introduced by 0a3f77e92634fd9b3434172000e13fc2f23129d7.
- Explicitly use `runc` runtime.
- Fixes edgelesssys/issues#700
> debugd: use runc as podman runtime

- debugd/internal/debugd/logcollector/logcollector.go
There is a race condition between starting the logcollection pods and waiting for them to become ready. If the `cmd.Start()` is not fast enough to create the container, `podman wait` will error out because it does not know about the container.
- Daemonize the logcollection containers and wait for the podman command to run through.
- Add a restart policy to ensure they keep running (or crash-looping).
Note that the logs of the podman containers either end up in OpenSearch (if everything is fine), or are not accessible (if logcollection is broken). Either way, the outcome is the same as before this change.
- [AB#4335](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/4335)
> debugd: daemonize logstash containers

- renovate.json5
Some action dependencies are not upgrade as frequently as they should be because our renovate config does not group updates to major versions with other action dependencies
- Allow major version upgrades for the GitHub action dependency group
> renovate: allow major version upgrades of GitHub action dependencies

- .github/actions/upload_terraform_module/action.yml
https://github.com/edgelesssys/constellation/commit/edc0c7068ef4527efeaf584a2a35e0f51f58c426 changed the deletion flags of `terraform-module` (directory) from `-r` to `-f`, causing it to fail.
- Change deletion flags to `-rf`.
> ci: fix directory deletion

- .github/workflows/build-ccm-gcp.yml
- .github/workflows/build-os-image-scheduled.yml
- .github/workflows/codeql.yml
- .github/workflows/release.yml
- .github/workflows/test-operator-codegen.yml
- MODULE.bazel
- dev-docs/workflows/bump-go-version.md
- go.mod
- go.work
A new Go version was released which addresses https://pkg.go.dev/vuln/GO-2024-2963
- Bump Go version to v1.22.5
- Add instructions to update version in `go.mod` and `go.work` files
> deps: bump Go version to v1.22.5

- internal/attestation/gcp/es/issuer_test.go
- internal/attestation/gcp/metadata.go
- internal/attestation/gcp/snp/issuer.go
The GCP metadata SDK now has functions that accept context.
We can pass down context from the callers to these functions
- Pass down context from callers into gcp metadata SDK functions instead of creating a new `context.Background()` for each
> gcp: pass context to metadata functions

- .github/workflows/e2e-attestationconfigapi.yml
I originally increased it to 2 during testing and did not experience any issues.
However, the test just failed after merging a PR. Lets decrease it back to 1 for stability reasons
- Reduce max parallel to 1
- https://github.com/edgelesssys/constellation/actions/runs/9692223251/attempts/1
> ci: reduce max parallel attestationconfig e2e tests back to 1 for stability

- dev-docs/howto/vpn/helm/templates/_helpers.tpl
- dev-docs/howto/vpn/helm/values.yaml
- nix/container/vpn/sidecar.sh
In a test setup with Constellation on GCP and a VM on Azure, I observed failures when trying to connect via TLS from the VM to the API server. The issue turned out to be packets dropped in XFRM, because they were too large for the 1500 MTU of the tunnel connection. 
Enabling path MTU over the GCP load balancer is likely impossible, so I'm adding a config knob to set the MTU manually. The conservative default setting should be enough to work with MTU 1500.
- [AB#4384](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/4384)
> dev-docs: set an MTU on the VPN route

- .github/actions/e2e_verify/action.yml
- internal/api/attestationconfigapi/cli/BUILD.bazel
- internal/api/attestationconfigapi/cli/client/reporter.go
- internal/api/attestationconfigapi/cli/compare.go
- internal/api/attestationconfigapi/cli/delete.go
- internal/api/attestationconfigapi/cli/main.go
- internal/api/attestationconfigapi/cli/upload.go
- internal/api/attestationconfigapi/cli/validargs.go
SVNs are getting promoted to stable more quickly than we intended.
The main issue comes from uploading to many reports from the weekly tests.
- Add a `compare` command to the attestationconfigapi CLI
- Compares two or more SNP/TDX reports and returns the one with the lowest SVNs
- Use `compare` command to only upload the report with the lowest SVNs during the `e2e verify` test
- Adjust the window for promoting cached versions to stable from 15 to 6 to keep the intended behavior of updating a version after it has been stable for 3 weeks.
- [AB#4382](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/4382)
- Before merging, I will go over the existing cached versions and see to removing all but the 2 lowest versions from the past 6 weeks
> attestationconfigapi: revise upload frequency

- renovate.json5
The stackit provider introduced a bug in `v0.24.0` and we'd like to avoid renovate bundling this version with the other Terraform providers. Excluding it from the group should result in a dedicated upgrade PR, which we can then ignore.
> renovate: exclude stackit from Terraform group

- internal/constellation/helm/overrides.go
- Add trick for cilium conformance
```
I0711 11:06:39.110216      23 e2e.go:117] Starting e2e run "7636fa51-bd4b-4b3c-823f-7324ca8c88eb" on Ginkgo node 1
Running Suite: Kubernetes e2e suite - /usr/local/bin
====================================================
Random Seed: 1720695998 - will randomize all specs
Will run 388 of 7408 specs
SS•S•SSSSSSSSSSSSSSSSSSS•SSS•SSSSSSSSSSSSSSS•SSSSS•SSSSSSSSSSSSSSSS•SSSSSSSSSSSSSSSSSSS•SSSSSSSSSSSSSSSSS•SS•SSSSSSSSSSSSSSSSSSSSSSSSSS•SSSSS•SSSS•SSSSSSSSSSSSSSSS•SSSSSSSSSS•SSSSSSS•SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS•SSSSSSSSSSS•SSSSSSSSSSSSSSSSSSS•SS•SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS•SSSSSSSSSSSSSSSSSSSSS•SSSSSSSSSSSSSSSSSSSS•SS•SSSSSSSS•SSSSSSSSSSSS•SS …
```
> helm: add serviceProxyName to conformance values

- .github/workflows/e2e-test-weekly.yml
Since debug images deploy additional software before the cluster is started which might impact performance, performance e2e tests should use our nightly images to better reflect the actual performance of our Constellation cluster.
I thought there was more to be done to enable this, but seems like we already implemented most things to use nightly images.
- Run performance e2e tests using nightly images
- [AB#4392](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/4392)
- Fixes https://github.com/edgelesssys/issues/issues/707
> ci: run performance e2e tests using nightly image

- .github/actions/constellation_create/action.yml
- .github/actions/e2e_sonobuoy/action.yml
- .github/actions/e2e_test/action.yml
- .github/workflows/e2e-test-weekly.yml
- .github/workflows/e2e-test.yml
We want to periodically test the conformance mode to stay compliant.
- add 'sonobuoy conformance' to test options
- add to weekly tests
- [AB#4145](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/4145)
This was the last manual run for comparison: 
https://github.com/cncf/k8s-conformance/pull/3200
[Successful run](https://github.com/edgelesssys/constellation/actions/runs/10091432763/job/27903156084)
> ci: add conformance test to weekly

- terraform/infrastructure/azure/main.tf
This is a prerequisite for ignoring changes to the load balancer backends attached to the NICs of the VMs in  https://github.com/edgelesssys/constellation/pull/3257
They need to be ignored since K8s LBs also creates a new backend which is attached to the NICs of the VMs. See https://github.com/edgelesssys/constellation/actions/runs/10032636133 for the error currently occurring on the other PR.
- Remove unused load balancer backends
upgrade test, azure: 
~https://github.com/edgelesssys/constellation/actions/runs/10067834089~
https://github.com/edgelesssys/constellation/actions/runs/10086213264
This is part of a larger story, where we fix the issue that K8s LBs change the state of the cloud resources tracked in Terraform, which results in a diff of the state and issues when upgrading …
> terraform: azure remove unused lb backends

- .github/actions/select_image/action.yml
I thought I tested this correctly, but turns out weekly and daily e2e tests use a different action to select their image than the manual e2e test.
That action did not recognize `ref/main/stream/nightly/?` as refStream, instead assuming it was a full os image shortpath.
- Correctly fetch the latest nightly image when `refStream==ref/main/stream/nightly/?`
- https://github.com/edgelesssys/issues/issues/776
> ci: correctly fetch image on nightly image ref

- renovate.json5
We already grouped core bazel dependency updates into one renovate PR.
To reduce the load of dependency PRs we want to group other dependencies tracked through bazel as well.
- Group non-core dependency updates for `bazel` and `bazel-module`
> renovate: group non-core bazel dependency updates

- .github/workflows/build-os-image-scheduled.yml
We have repeatedly seen scheduled image builds being cancelled because of concurrency limitations on the workflow.
To avoid this issue, lets give the image builds a bit more time before we start the next one.
- Give scheduled image builds 20 minutes downtime before starting the next workflow
- https://github.com/edgelesssys/constellation/actions/runs/10274133698/attempts/1
- https://github.com/edgelesssys/constellation/actions/runs/10169956084/attempts/1
> ci: give scheduled image builds more time between executions

- renovate.json5
Keeping our dependencies up to date is not easy.
Putting updates of our larger dependency groups on a schedule should help once we get the pending PR list down
- Put Go, GitHub actions, Terraform, and Constellation container updates on a schedule
- Stop ignoring StackIT Terraform updates since the issues in `v0.24.1` have been resolved upstream
> renovate: schedule dependency updates

- image/README.md
Building the Constellation OS image requires the setuid binaries `newuidmap` and `newgidmap` to be on the PATH. These cannot be sourced through Nix, as one cannot have setuid binaries in the Nix store.
- Document that the programs need to be available on the build machine.
> image: document uidmap dependency

- docs/docs/overview/clouds.md
- docs/versioned_docs/version-2.17/overview/clouds.md
We often forget to update it and it's not that valuable.
> docs: remove date from "feature status of clouds" page

- bootstrapper/cmd/bootstrapper/main.go
- bootstrapper/internal/initserver/initserver.go
- debugd/internal/debugd/server/server.go
- disk-mapper/internal/recoveryserver/recoveryserver.go
- internal/logger/grpclogger.go
- internal/logger/levelhandler.go
- internal/logger/log.go
- joinservice/internal/server/server.go
- keyservice/internal/server/server.go
- upgrade-agent/cmd/main.go
- upgrade-agent/internal/server/server.go
- verify/server/server.go
Our gRPC logging solution was producing a lot of noise.
This had two causes:
1. The bootstrapper, and upgrade-agent were setting their grpc log level to the same value as their default logging. We had previously decided to enforce a warn log level for grpc related log entries. It was missing here
2. Our grpc logging implementation was not enforcing log levels. This means that even if the grpc logger was configured to only log at error level, all records were printed.
- Add `logger.GRPCLogger` to normalize set up of the grpc logger across all Constellation components
- Fix our `grpclog.LoggerV2` implementation to actually respect log levels by adding an `Enabled` check before writing the record
- Un-export functions and types that were exclusively used by `/internal/logger`
> logging: reduce grpc logging noise

- terraform-provider-constellation/docs/resources/cluster.md
- terraform-provider-constellation/internal/provider/BUILD.bazel
- terraform-provider-constellation/internal/provider/cluster_resource.go
To directly plug in the Constellation Terraform provider into the `kubernetes` and `helm` providers, we need fine-grained outputs for cluster address, client certificate, key, etc.
To test this, consider the following Terraform snippet, which can be plugged into the AWS Terraform example configuration:
```hcl
provider "kubernetes" {
host = constellation_cluster.aws_example.host
client_certificate     = constellation_cluster.aws_example.client_certificate
client_key             = constellation_cluster.aws_example.client_key
cluster_ca_certificate = constellation_cluster.aws_example.cluster_ca_certificate
}
data "kubernetes_nodes" "example" {}
output "node-ids" {
value = [for node in data.kubernetes_nodes.example.nodes : node.spec.0.provider_id]
}
```
- Parse the kubeconfig returned through …
> terraform-provider-constellation: make kubeconfig output fine-grained

- flake.lock
- flake.nix
- image/base/mkosi.conf
- image/base/mkosi.postinst
- image/initrd/mkosi.conf
- image/system/mkosi.conf
This updates mkosi to a next-version of v24.3, which is now available in nixpkgs. This removes the non-hermetic `uidmap` dependency, which is a great advantage. It will also be less of an effort to upgrade to v25 going forward.
- Update mkosi to v24.3, making changes to its configuration files as necessary.
- Changes required are keeping `/var/cache` around (which is reproducible for our images, so no problem), as mkosi needs files from it in the build process. mkosi now additionally requires an explicit option to fetch the signing keys for the package repositories from the internet. A hack was required to satisfy the Bazel package, which should probably be solved properly at some point.
- [AB#4553](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/4553) …
> image: update mkosi to 24.3

- .github/workflows/build-ccm-gcp.yml
- .github/workflows/build-os-image-scheduled.yml
- .github/workflows/codeql.yml
- .github/workflows/release.yml
- .github/workflows/test-operator-codegen.yml
- MODULE.bazel
- go.mod
- go.work
Changelog: https://go.dev/doc/devel/release#go1.22.0
> go1.22.7 (released 2024-09-05) includes security fixes to the encoding/gob, go/build/constraint, and go/parser packages, as well as bug fixes to the fix command and the runtime. See the [Go 1.22.7 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.22.7+label%3ACherryPickApproved) on our issue tracker for details.
- Update the Go toolchain to v1.22.7
> treewide: update Go toolchain to 1.22.7

- internal/constellation/helm/charts/cilium/templates/cilium-agent/daemonset.yaml
- internal/constellation/helm/cilium.patch
Our Cilium hardening scripts assume that there is only one default route configured on the host. However, this turned out to be wrong for some environments, breaking Cilium.
- Apply [hardening](https://github.com/edgelesssys/constellation/blob/0aeda78089905d87dccbfa5e2c2ef0a02725df3f/internal/constellation/helm/charts/cilium/templates/cilium-agent/daemonset.yaml#L766-L774) to all interfaces used for default routes.
- Fixes #3294
> helm: cilium: allow multiple default routes

- e2e/internal/upgrade/upgrade.go
The upgrade test interleaves stdout messages and test logs, making the output harder to read than necessary.
https://github.com/edgelesssys/constellation/actions/runs/10791721941/job/29952302050#step:19:20029
- Don't print to stdout, only to log.
> e2e: remove immediate node status printing

- cli/internal/cmd/apply.go
- cli/internal/cmd/apply_test.go
- cli/internal/cmd/init_test.go
- cli/internal/cmd/upgradeapply_test.go
- internal/constellation/helm.go
- internal/constellation/helm/charts/coredns/templates/configmap.yaml
- internal/constellation/helm/charts/coredns/templates/deployment.yaml
- internal/constellation/helm/corednsgen/corednsgen.go
- terraform-provider-constellation/internal/provider/cluster_resource.go
- upgrade-agent/internal/server/server.go
Putting the CoreDNS deployment under Helm management (#3236) introduced two bugs:
1. The `kubeadm upgrade` preflight checks started to fail because the version can't be parsed from the pinned image (see kubernetes/kubernetes#122967).
2. `kubeadm upgrade` overwrites the Helm chart resources because there's no way to skip the addon phase (see kubernetes/kubeadm#1318).
Both of these issues arise because Helm charts are installed before the Kubernetes upgrade, and both issues have not been caught because the upgrade process ignores errors from kubeadm (see edgelesssys/issues#134).
- Ignore CoreDNS-related preflight errors.
- Rename the CoreDNS ConfigMap during upgrades. This is working around the missing kubeadm phase feature: if there's no `kube-system/coredns` ConfigMap, kubeadm does not …
> helm: fix kubeadm bugs caused by CoreDNS installation

- bazel/mkosi/mkosi_image.bzl
- image/sysroot-tree/usr/lib/systemd/system-preset/20-constellation-base.preset
- image/sysroot-tree/usr/lib/systemd/system/serial-getty@ttyS0.service.d/autologin.conf
- image/system/BUILD.bazel
- image/system/variants.bzl
In mkosi v24 --autologin no longer works for ttyS consoles. Since the CSPs use those exclusively for their serial consoles, we need to replace this with another solution. Since it seems the simplest, I just created the systemd unit myself and made it conditional on the kernel cmdline.
Console:
~https://github.com/edgelesssys/constellation/actions/runs/10856407864~
~https://github.com/edgelesssys/constellation/actions/runs/10874367218~
~https://github.com/edgelesssys/constellation/actions/runs/10874697856~
https://github.com/edgelesssys/constellation/actions/runs/10892773346
Debug:
~https://github.com/edgelesssys/constellation/actions/runs/10856416476~
~https://github.com/edgelesssys/constellation/actions/runs/10874954823~
https://github.com/edgelesssys/constellation/actions/runs/1089278266 …
> image: re-enable autologin for debug and console images

- .github/actions/constellation_iam_create/action.yml
https://github.com/edgelesssys/constellation/pull/3328 added a new flag to `constellation iam create azure` and enabled use of it in our e2e tests. However, our stable releases do not yet support this flag. This is currently causing our ci workflows to fail for stable releases.
- Check if the CLI supports the `--subscriptionID` flag before using it
- fixes https://github.com/edgelesssys/issues/issues/872
> ci: check if CLI version supports `--subscriptionID` flag before using it

- .github/actions/e2e_mini/action.yml
- e2e/miniconstellation/.terraform.lock.hcl
- e2e/miniconstellation/BUILD.bazel
- e2e/miniconstellation/main.sh.in
- e2e/miniconstellation/main.tf
- e2e/miniconstellation/output.tf
- e2e/miniconstellation/variables.tf
The `rgname` variable set by `e2e/miniconstellation/main.sh.in` is not parsed back to the GitHub workflow if `terraform apply` failed
- Define resource group name outside of terraform to ensure there is always a valid value, even if `terraform apply` fails
- Only run tests in West Europe to get around potential quota issues
- Resource group is now [correctly set](https://github.com/edgelesssys/constellation/actions/runs/11008951631/job/30567585420#step:5:2918) on delete
- [e2e test](https://github.com/edgelesssys/constellation/actions/runs/11010915855/job/30573868498)
- Fixes https://github.com/edgelesssys/issues/issues/888
> ci: update incorrect variable naming in mini e2e test

- image/system/variants.bzl
The Linux command line parameter `idle=poll` was introduced mid-2023 to work around a hypervisor issue at AWS. This issue has been fixed since end of 2023.
`idle=poll` has some negative consequences, see the kernel docs linked below. For example, it basically prevents the CPU from going idle at all under light load, resulting in the symptoms explained in #3383. I took these measurements on `m6a.xlarge` machines before and after the change proposed here:
```shell-session
/ # cat /proc/cmdline
roothash=de436e547b918bf0411d9738485c431918e068a051241db88bc099c0782da5e4 preempt=full rd.shell=0 rd.emergency=reboot loglevel=8 selinux=1 enforcing=0 audit=0 constellation.debug console=ttyS0 constel.csp=aws idle=poll mitigations=auto constel.attestation-variant=aws-sev-snp
/ # sysbench --threads=1 …
```
> image: improve AWS performance by retiring idle=poll option

- dev-docs/security-overview.md
- dev-docs/workflows/github-actions.md
- dev-docs/workflows/qemu.md
- Link to the website hosting the docs instead of using local links
- Link to new libvirt docs URL
See CI failures: https://github.com/edgelesssys/constellation/actions/runs/11218452983/job/31182252488?pr=3257#step:3:9549
The CI still fails because of sonobuoy. This should be fixed when https://github.com/vmware-tanzu/sonobuoy/pull/1987 is merged, but the PR is already 4 weeks old so we might link against v0.57.1 instead of latest.
> dev-docs: link to docs website instead of to local files

- docs/docs/reference/migration.md
- internal/constellation/helm/overrides.go
- terraform/infrastructure/aws/main.tf
- terraform/infrastructure/azure/main.tf
- terraform/infrastructure/azure/modules/scale_set/main.tf
- terraform/infrastructure/gcp/main.tf
- terraform/infrastructure/openstack/main.tf
- terraform/infrastructure/qemu/main.tf
- Remove worker nodes from any existing load balancer backend, since any VM NIC can only be attached to one backend group. Also the worker backends were unused anyway.
- Let the cloud-controller-manager create a separate "kubernetes-lb" to create LBs for Kubernetes services.
- Don't inline (most) of the network security rules
- Sadly, we cannot fix the upgrade process in one go, as we need 2 state changes on the same resource. So the upgrade to this release still removes the network security rules added by the cloud controller manager, but which should heal itself in the upgrade process one it's restarted. After we execute the instructions mentioned in the TODO, there will finally be no terraform changes after "constellation create" -> "create LB svc" -> "terraform plan". 
Azure, snp, …
> Allow upgrades on azure without Terraform changes on LBs created from within Kubernetes

- MODULE.bazel
- bazel/ci/BUILD.bazel
- bazel/ci/govulncheck.sh.in
`govulncheck` shows a finding in a transitive dependency of `sigstore/rekor`. According to https://github.com/sigstore/rekor/issues/2237, this is a false-positive. Unfortunately, `govulncheck` does not support ignoring findings. 
- Parse the findings manually from JSON output, ignoring known false-positives.
> ci: ignore GO-2024-3166 in govulncheck

- CODEOWNERS
The Helm chart directory frequently gets PRs from renovate. Renovate PRs are auto-assigned unless they have requested assignee, so PRs may only be assigned to CODEOWNERS. 
- Move ownership of `/internal/constellation/helm` to @burgerdev.
> CODEOWNERS: move ownership of Helm charts to burgerdev

- .github/workflows/build-ccm-gcp.yml
- .github/workflows/build-os-image-scheduled.yml
- .github/workflows/codeql.yml
- .github/workflows/release.yml
- .github/workflows/test-operator-codegen.yml
- 3rdparty/bazel/org_golang/go_tls_max_handshake_size.patch
- MODULE.bazel
- bazel/toolchains/ci_deps.bzl
- go.mod
- go.work
- hack/tools/go.mod
- renovate.json5
Go 1.23 is a requirement for keep-sorted, blocking our Go dependency bump. 
- Upgrade to Go 1.23.2.
- [AB#4757](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/4757)
> treewide: upgrade to Go 1.23.2

- e2e/malicious-join/malicious-join.go
For some reason, the `IssueJoinTicket` returns a `nil` response now in a failure case, while it seemed not to do so a while ago(?). 
- Only log after getting the response, where `(res != nil) == true`.
- [AB#4773](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/4773)
- [Malicious join](https://github.com/edgelesssys/constellation/actions/runs/11383992071)
> e2e: fix malicious join test

- internal/constellation/helm/charts/edgeless/operators/charts/node-maintenance-operator/templates/manager-rbac.yaml
- internal/constellation/helm/testdata/AWS/constellation-operators/charts/node-maintenance-operator/templates/manager-rbac.yaml
- internal/constellation/helm/testdata/Azure/constellation-operators/charts/node-maintenance-operator/templates/manager-rbac.yaml
- internal/constellation/helm/testdata/GCP/constellation-operators/charts/node-maintenance-operator/templates/manager-rbac.yaml
- internal/constellation/helm/testdata/OpenStack/constellation-operators/charts/node-maintenance-operator/templates/manager-rbac.yaml
- internal/constellation/helm/testdata/QEMU/constellation-operators/charts/node-maintenance-operator/templates/manager-rbac.yaml
https://github.com/edgelesssys/constellation/pull/3425 broke the node-maintenance-operator by not updating the Helm chart accordingly. The operator now wants to handle namespaces, for which its clusterRole was missing the required permissions for.
- Add the new required permissions to the Helm chart.
- [AB#4791](https://dev.azure.com/Edgeless/Edgeless/_workitems/edit/4791)
- Needs to be backported into v2.19.0
> helm: allow namespace handling for node-maintenance-operator

- terraform/infrastructure/gcp/.terraform.lock.hcl
- terraform/infrastructure/gcp/main.tf
- terraform/infrastructure/gcp/modules/instance_group/main.tf
- terraform/infrastructure/gcp/modules/internal_load_balancer/main.tf
- terraform/infrastructure/gcp/modules/jump_host/main.tf
- terraform/infrastructure/gcp/modules/loadbalancer/main.tf
- terraform/infrastructure/iam/gcp/.terraform.lock.hcl
- terraform/infrastructure/iam/gcp/main.tf
CI jobs have been running into GCP IAM inconsistencies, which are caused by a bad waiting condition in the Google Terraform provider. The issue has been fixed, but not backported to 5.x.
- Upgrade major version of Terraform provider
- Fixes https://github.com/edgelesssys/issues/issues/635
- [AB#4686](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/4686)
> terraform: upgrade hashicorp/google to 6.7.0

- bazel/bazelrc/ci.bazelrc
Golang builds use a module proxy to fetch dependencies. The default configuration is `GOPROXY=https://proxy.golang.org,direct`, which means "always use proxy.golang.org, and fall back to direct if the result is a 404". If the proxy fails differently (network disconnect, 502, ...), fetching fails.
- Use fallbacks on all proxy errors (this is done by using `|` instead of `,`).
- Add goproxy.io as additional fallback.
- Fixes edgelesssys/issues#1004
> ci: use GOPROXY fallbacks

- cli/internal/cmd/apply.go
Currenlty, when the coordinator is not reachable, the last log line is
```
{"time":"2024-10-18T11:59:38.778068783+02:00","level":"DEBUG","source":{"function":"github.com/edgelesssys/constellation/v2/cli/internal/cmd.(*applyCmd).runInit","file":"cli/internal/cmd/applyinit.go","line":38},"msg":"Running init RPC"}
<nothing else here, next line only if init is successful>
{"time":"2024-10-18T12:01:08.364242086+02:00","level":"DEBUG","source":{"function":"github.com/edgelesssys/constellation/v2/cli/internal/cmd.(*applyCmd).runInit","file":"cli/internal/cmd/applyinit.go","line":77},"msg":"Initialization request successful"}
```
- Use existing debugLogger, that logs both to a file and to stderr, in the applier that makes the init call to the coordinator. 
Now the logs also containt he following …
> cli: also log applier debug messages to debug log file

- docs/docs/workflows/terraform-provider.md
- docs/versioned_docs/version-2.19/workflows/terraform-provider.md
- terraform-provider-constellation/examples/full/azure/main.tf
The current provider docs don't distinguish Azure SEV-SNP and TDX, even though the steps are not the same.
Also, I noticed that the TF code doesn't validate the instance type for the given attestation variant. Thus, a user might forget to change this field when using TDX. The validation cannot be easily included because infra and constellation resources are strictly separated in TF, but a comment seems like a good enough hint.
- add a comment to adjust the instance type for the TDX variant
- separate the instructions for Azure SEV-SNP and TDX
> docs: clarify for Azure TDX with Terraform provider

- .github/workflows/e2e-test-provider-example.yml
The weekly Terraform provider test failed multiple times without reporting a failure.
This was due to the provider being unable to complete the `apply` step, causing GitHub to cancel the workflow after 6 hours.
Terraform does not support running `apply` with a timeout itself, therefore we need another solution to report these failures.
- Also report a failure on cancelled runs
- Since failures are only reported for scheduled runs on main, they should never be cancelled by a user. If they were cancelled, it was most likely the GitHub CI itself, which we should be notified about
See 
* https://github.com/edgelesssys/constellation/actions/runs/11528371745/job/32095423964
* https://github.com/edgelesssys/constellation/actions/runs/11414034720/job/31762412086
* …
> ci: report failure in scheduled Terraform provider tests on cancel

- internal/config/config_test.go
- internal/config/validation.go
When creating a confidential Kubernetes cluster on Stackit, customers have occasionally confused confidential flavor IDs with non-confidential ones which resulted in a "stuck" creation period.
I have implemented an instance type check for the Stackit cloud provider to prevent this confusion.
[#3438](https://github.com/edgelesssys/constellation/issues/3438)
I have rebuilt the Constellation CLI and confirmed that the change works correctly on a Linux x86 machine.
Using ```bazel build //cli:cli_oss```
> config: only allow confidential instances on stackit

- .github/workflows/reproducible-builds.yml
- docs/docs/workflows/reproducible-builds.md
- docs/sidebars.js
- nix/cc/cryptsetup.nix
- nix/cc/libvirt.nix
- renovate.json5
There's an implicit assumption that our release artifacts are reproducible, but the exact requirements are unclear. According to reproducible-builds.org, a reproducible build needs to come with a build environment definition.
A user found an issue where the local Nix store state influences build outcomes. This was not caught by our tests because they are only testing a narrow build environment.
* Fix the issue and add a test for it.
* Document our reproducibility claims, in particular that
- Artifacts are expected to be reproducible (and it's a bug if not).
- Set a baseline for reasonable host environments.
- Our supported and tested environment for reproduction is defined by the workflow.
- [AB#4797](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/4797) …
> docs: how to reproduce released artifacts

- image/base/BUILD.bazel
- image/base/mkosi.finalize
As part of our `mkosi` build, we add a system user `etcd` using the `systemctl-sysusers` mechanism. The tool [should understand `SOURCE_DATE_EPOCH`](https://github.com/systemd/systemd/commit/3fa8a1148a46b40b2a7ebac4007a95b4d0abab17), but does not apply it for some reason ~(maybe missing env propagation in mkosi)~. 
- Manually reset the "last changed" date in a finalize step.
- #3465 
- [AB#4815](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/4815)
> image: unset password reset date to ensure reprodicibility

- docs/docs/overview/confidential-kubernetes.md
- docs/versioned_docs/version-2.0/overview/confidential-kubernetes.md
- docs/versioned_docs/version-2.1/overview/confidential-kubernetes.md
- docs/versioned_docs/version-2.10/overview/confidential-kubernetes.md
- docs/versioned_docs/version-2.11/overview/confidential-kubernetes.md
- docs/versioned_docs/version-2.12/overview/confidential-kubernetes.md
- docs/versioned_docs/version-2.13/overview/confidential-kubernetes.md
- docs/versioned_docs/version-2.14/overview/confidential-kubernetes.md
- docs/versioned_docs/version-2.15/overview/confidential-kubernetes.md
- docs/versioned_docs/version-2.16/overview/confidential-kubernetes.md
- docs/versioned_docs/version-2.17/overview/confidential-kubernetes.md
- docs/versioned_docs/version-2.18/overview/confidential-kubernetes.md
- docs/versioned_docs/version-2.19/overview/confidential-kubernetes.md
- docs/versioned_docs/version-2.2/overview/confidential-kubernetes.md
- docs/versioned_docs/version-2.3/overview/confidential-kubernetes.md
- docs/versioned_docs/version-2.4/overview/confidential-kubernetes.md
- docs/versioned_docs/version-2.5/overview/confidential-kubernetes.md
- docs/versioned_docs/version-2.6/overview/confidential-kubernetes.md
- docs/versioned_docs/version-2.7/overview/confidential-kubernetes.md
- docs/versioned_docs/version-2.8/overview/confidential-kubernetes.md
- docs/versioned_docs/version-2.9/overview/confidential-kubernetes.md
The word "Contrast" is confusing in that context.
- Use "comparison" instead
> docs: change wording contrast with comparison

- .github/actions/setup_bazel_nix/action.yml
- MODULE.bazel.lock
There's a nix bug that sporadically fails CI builds with
```
error: opening Git repository '"/home/runner/.cache/nix/tarball-cache"': could not find repository at '/home/runner/.cache/nix/tarball-cache'
```
This has been [fixed upstream](https://github.com/NixOS/nix/pull/11581), but the Cachix installer does not yet use a version with this fix.
- Explicitly specify the version to install.
- Fixes edgelesssys/issues#788
> ci: pin nix version to 2.25.2

- go.mod
- go.sum
AWS already updated their firmware to issue v3 attestation reports.
This breaks the go-sev-guest library which has a hard check for the reports to be in version 2 format.
I have already [opened a PR upstream](https://github.com/google/go-sev-guest/pull/141) to address the issue.
To stop at least our non-release image e2e tests from failing, this PR updates the library used by Constellation to the forked version including the required changes.
- Use forked version of google/go-sev-guest to support v3 AMD SEV-SNP attestation reports
- [AB#4867](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/4867)
> deps: use forked google/go-sev-guest to support v3 AMD SEV-SNP attestation reports

- .github/workflows/build-ccm-gcp.yml
- .github/workflows/release.yml
- docs/.gitignore
- docs/README.md
- docs/package-lock.json
- docs/package.json
- docs/versioned_docs/version-2.6/overview/performance.md
- docs/versioned_docs/version-2.7/overview/performance.md
- docs/versioned_docs/version-2.8/overview/performance.md
OpenSSF's scorecard found 2 places where dependencies are not pinned. This fixes those places.
- Pin crane install by latest release commit
- Use package lock to pin npm dependencies, use `npm ci` to not override the package lock.
> Pin crane and npm dependencies

- go.mod
- go.sum
Upstream PRs were merged, we can drop the fork again
- Update go-sev-guest to v0.11.2-0.20241122022416-97a55186df28 for AMD SEV-SNP attestation report v3 support
- We should create a patch release with these changes for v2.19 soon to fix new deployments on AWS
> deps: update google/go-sev-guest to v0.11.2-0.20241122022416-97a55186df28

- bootstrapper/internal/joinclient/joinclient.go
Previously we errored out of the entire join if retrieval of either LB IP or control plane public IP failed. This resulted in the entire "use either IP" logic not working as intended.
This also fixes the problem encountered by STACKIT folks, where public IP retrieval fails and thus no nodes can join the cluster.
- Log a warning only if the IP retrievals fail, and only errors out of the join if no IP can be found at all.
> bootstrapper: only err if no control plane IPs available

- bazel/ci/BUILD.bazel
Our tidy/check/generate CI job fails intermittently during `bazel run //:check` due to memory constraints on our CI runners, when more than one job runs at the same time on our cluster.
- Run the two most memory intensive targets of `check` sequentially to avoid issues with single jobs taking up more than 20GB of RAM
- `govulncheck` requires around 12GB of RAM on my local machine
- `golang-ci-lint` requires 8-10GB on my local machine
> ci: run memory intensive `check` targets sequentially

- docs/versioned_docs/version-2.19/architecture/versions.md
- internal/versions/versions.go
Some upgrade (possibly due to a too-eagerly merged PR) missed upgrading certain parts of the K8s versions. This fixes that by manually aligning to the newest version.
- Update {kubelet,kubeadm,...} versions to latest.
> versions: manually pull in new Kubernetes versions

- operators/constellation-node-operator/internal/cloud/gcp/client/scalinggroup.go
- operators/constellation-node-operator/internal/cloud/gcp/client/scalinggroup_test.go
If the GCP project has scaling groups for which our checks can't be performed (which is the case for regional scaling groups, as they "don't exist" for the operator, if deployed in another region) . In that case, we should not bail out directly but go on with the next group. An error should only be thrown if there are no matching groups at all.
- Don't error directly, but only if no scaling groups are found.
> constellation-node-operator: don't bail out on listing errors

- flake.lock
- flake.nix
Previously, we supplied Bazel 7.1.2 through our Nix flake, which was insufficient to build Constellation for quite some time. Now, we can finally have a matching version on Bazel 7.4.1 again, so update to that in our Flake, allowing us to drop a fork!
Requires #3531 
- Update to Bazel 7.4.1
> flake: update to Bazel 7.4.1

- renovate.json5
The CoreDNS Helm chart is synthesised from and updated with Kubernetes source dependencies, so we don't want automated upgrades of the CoreDNS image. 
- Ignore the CoreDNS Helm chart for renovation.
> ci: exclude CoreDNS chart from renovate

- flake.lock
- flake.nix
- internal/osimage/uplosi/uplosi.conf.in
uplosi on main tightened checks, which our image build setup fails. While this is being reverted (https://github.com/edgelesssys/uplosi/pull/102), we should not depend on an unreleased uplosi here.
- Use uplosi from nixpkgs-unstable.
> image: use uplosi from nixpkgs-unstable

- docs/docs/getting-started/first-steps.md
- docs/docs/getting-started/install.md
- docs/versioned_docs/version-2.19/getting-started/first-steps.md
- docs/versioned_docs/version-2.19/getting-started/install.md
- docs/versioned_docs/version-2.20/getting-started/first-steps.md
- docs/versioned_docs/version-2.20/getting-started/install.md
We got OpenStack and STACKIT IDs mixed up in our documentation previously. The OpenStack project ID is required in the `clouds.yaml` file [^1], while the STACKIT project ID is required in the Constellation config [^2]. This fixes the warning for the OpenStack project ID in `clouds.yaml`, and adds an additional warning for the STACKIT project ID in the configuration section.
[^1]: https://github.com/edgelesssys/wiki/blob/master/documentation/constellation/stackit.md#cloudsyaml
[^2]: https://github.com/edgelesssys/wiki/blob/master/documentation/constellation/stackit.md#constellation-confyaml
- Fix OpenStack project ID warning (said STACKIT previously).
- Add an additional warning for the STACKIT project ID.
> docs: correct STACKIT IDs

- image/BUILD.bazel
- image/base/BUILD.bazel
- image/initrd/BUILD.bazel
Our image build includes source files from git. Since git respects the users `umask`, the files in the image might have different permissions depending on the system executing the build.
- Add a new Bazel rule `reproducible_tar` that normalizes git subtrees for image inclusion.
The added rule depends on gnutar and is unlikely to work on vanilla darwin (cc @elchead). This trades off portability for correctness of the rootfs. Some alternatives:
* Use[ `pkg_tar`](https://github.com/bazelbuild/rules_pkg/blob/main/docs/1.0.1/reference.md#pkg_tar) with a mode `0555`. Downside: our config files are now executable.
* Split sources for inclusion into two subtrees by desired permission bits. Downside: more rules, unintuitive layout.
* Explicitly list the files that should be executable in …
> image: include files from git reproducibly

- .github/actions/constellation_create/action.yml
- .github/actions/constellation_iam_create/action.yml
- .github/actions/e2e_test/action.yml
- .github/actions/login_stackit/action.yml
- .github/actions/notify_stackit/action.yml
- .github/actions/terraform_apply/action.yml
- .github/workflows/e2e-test-stackit.yml
- .github/workflows/e2e-test.yml
We set up a shared test environment with STACKIT to regularly test Constellation deployments on STACKIT. This now enables integration of said testing in our CI. It only tests release images so far, as we currently don't have the means of getting non-release images into the testing STACKIT project.
- Add a STACKIT-specific E2E test. It tests:
- All Kubernetes versions
- Terraform & CLI deployments
- Small Sonobuoy payload (for now)
- [AB#3035](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/3035)
- [Test Run](https://github.com/edgelesssys/constellation/actions/runs/12389200944)
> ci: enable STACKIT e2e tests

- .github/actions/constellation_iam_create/action.yml
In #3556, we unconditionally write the STACKIT configuration to the config file used to create the cluster in the e2e tests. This causes all non-STACKIT tests to fail, as 2 CSPs will be defined in the configuration. An example can be seen [here](https://github.com/edgelesssys/constellation/actions/runs/12424824871).
- Only write the STACKIT configuration if a STACKIT test should run.
- [E2E test daily](https://github.com/edgelesssys/constellation/actions/runs/12427595179)
- [E2E test STACKIT](https://github.com/edgelesssys/constellation/actions/runs/12427597422)
> ci: only write STACKIT configuration if STACKIT test runs

- .github/workflows/build-os-image.yml
Since Ubuntu 23.10, creating namespaces, e.g. via `unshare`, requires privileges. Since `unshare` is used by `mkosi` in our image build pipeline, we need to re-enable them explicitly here before building the image, aligning with the behavior before Ubuntu 23.10.
- Explicitly enable unprivileged user namespaces in the image build action.
- [Action before this update](https://github.com/edgelesssys/constellation/actions/runs/12818102529)
- [Action after this update](https://github.com/edgelesssys/constellation/actions/runs/12825033842)
> ci: allow unrestricted user namespaces in image builds

- .github/workflows/build-ccm-gcp.yml
- .github/workflows/build-os-image-scheduled.yml
- .github/workflows/codeql.yml
- .github/workflows/release.yml
- .github/workflows/test-operator-codegen.yml
- 3rdparty/gcp-guest-agent/Dockerfile
- MODULE.bazel
- dev-docs/workflows/bump-go-version.md
- go.mod
- go.work
- hack/tools/go.mod
Go v1.23.5 was released to address `CVE-2024-45341` and `CVE-2024-45336`.
As far as I can tell, these do not affect Constellation in any way, but newer versions of our dependencies are already requiring the new release as the minimum supported Go version.
Soft requirement for https://github.com/edgelesssys/constellation/pull/3586
- Bump Go to `v1.23.5`
- Update the "How to update Go version" guide to include the `go.mod` file in `hack/tools/` and the `gcpguestagent` Dockerfile in `3rdparty/gcp-guest-agent/`
> dependencies: bump Go to v1.23.5

- go.mod
- go.sum
On Azure, getting the token from MAA currently fails with an error regarding PCR11, probably because of a change/bug in MAA.
- Update go-azguestattestation, which only sends required PCRs to MAA. (The actual verification of all PCRs happens in the Validator as before.)
- https://github.com/edgelesssys/constellation/actions/runs/13267027857
> attestation: fix Azure SNP attestation issuing caused by a bug in MAA PCR11 handling

- .github/actions/e2e_cleanup_timeframe/action.yml
- .github/workflows/e2e-cleanup-weekly.yml
The cleanup job failed previously due to the missing `clouds.yaml` file for OpenStack / STACKIT.
- Login to OpenStack in the cleanup job.
- [AB#5280](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/5280)
- [Workflow run](https://github.com/edgelesssys/constellation/actions/runs/13372168786)
> ci: supply STACKIT credentials to cleanup job

- operators/constellation-node-operator/controllers/nodeversion_controller.go
- operators/constellation-node-operator/controllers/nodeversion_controller_test.go
Since Kubernetes v1.31, the requirement that Kubeletes of version `n` are incompatible with outdated (version `n-1`) Kube-API servers / control planes is actually enforced / errors if not fulfilled. Thus, we need to make sure during the upgrade that this case doesn't occur in a Constellation cluster.
- Sort the nodes in the upgrade process of the operator, such that control plane nodes get upgraded first.
- Also, workers now wait during the upgrade if there are still outdated control plane nodes.
- [AB#5311](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/5311)
- [GCP 2:8 Upgrade Test](https://github.com/edgelesssys/constellation/actions/runs/13496779987). The high worker count ensures that the probability for a worker node being upgraded before a …
> constellation-node-operator: upgrade control plane nodes first

- .golangci.yml
The `tenv` linter has been replaced with the `usetesting` linter, as can be seen [here](https://github.com/edgelesssys/constellation/actions/runs/13584440815/job/38152319087?pr=3670#step:12:285).
- Replace the `tenv` linter with `usetesting`  in the golangci-lint config.
> ci: replace tenv linter with usetesting

- 3rdparty/bazel/com_github_kubernetes_sigs_aws_load_balancer_controller/BUILD.bazel
- 3rdparty/bazel/com_github_kubernetes_sigs_aws_load_balancer_controller/pull_files.sh
- 3rdparty/bazel/com_github_kubernetes_sigs_aws_load_balancer_controller/source.bzl
- WORKSPACE.bzlmod
- bazel/ci/BUILD.bazel
- docs/docs/reference/migration.md
- terraform/infrastructure/iam/aws/alb_policy.json
AWS [updated the permissions necessary for the `aws-load-balancer-controller`](https://github.com/kubernetes-sigs/aws-load-balancer-controller/releases/tag/v2.11.0), which resulted in [a failing LB E2E test](https://github.com/edgelesssys/constellation/actions/runs/13600461402) for us, as well as the general symptom of AWS LBs not working.
Fixes https://github.com/edgelesssys/issues/issues/1300
- Update the permissions to incorporate the new requirements.
- Update the docs to mention that an IAM migration is necessary.
- [AB#5361](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/5361)
- [LB E2E Test (post-fix)](https://github.com/edgelesssys/constellation/actions/runs/13698350318)
IAM Upgrade tested manually via:
```sh
git checkout …
```
> terraform: update AWS LB permissions

- .github/workflows/e2e-test-stackit.yml
This was forgotten when upgrading the Kubernetes versions, and we didn't notice because the e2e tests weren't running
- Remove Kubernetes v1.28 from stackit e2e tests
- Add Kubernetes v1.31 to stackit e2e tests
- Closes https://github.com/edgelesssys/issues/issues/1449
- Closes https://github.com/edgelesssys/issues/issues/1450
> ci: add k8s v1.31 and remove v1.28 from stackit e2e test

- go.mod
- go.sum
Our current version of the module has a published vulnerability: https://pkg.go.dev/vuln/GO-2025-3528. Although we're unaffected (not using the library to spawn containers), updating the version should make our vuln scanner happy.
- Manually upgrade transitive dependency github.com/containerd/containerd to v1.7.27
> deps: bump github.com/containerd/containerd to v1.7.27

- .github/workflows/draft-release.yml
The old version throws the following error in the release pipeline:
```
euler@work:/tmp/tmp.JU0IjLCB1T$ ./slsa-verifier-linux-amd64 verify-artifact constellation-darwin-amd64/constellation-darwin-amd64 --provenance-path multiple.intoto.jsonl/multiple.intoto.jsonl --source-uri github.com/edgelesssys/constellation
No certificate provided, trying Redis search index to find entries by subject digest
Verifying artifact constellation-darwin-amd64/constellation-darwin-amd64: FAILED: could not find a matching valid signature entry: got unexpected errors unexpected tlog entry type: extracting certificate from 108e9186e8c5677ade5ca56cc9a3b5df4ccda2a39b94d698a9d2f5d570822f672379566c34238d3a, unexpected tlog entry type: extracting certificate from …
```
> ci: bump slsa verifier

- bazel/ci/govulncheck.sh.in
These vulns don't affect our usage of the k8s library:
* https://pkg.go.dev/vuln/GO-2025-3521
* https://pkg.go.dev/vuln/GO-2025-3547
- exclude those
- convert list of exclusions to a commented bash array
- remove unnecessary exclusions
> ci: exclude go vulns that don't affect library usage

- .github/actions/setup_bazel_nix/action.yml
Forgot to rename a reference to the `nixpkgsUnstable` input in the CI in #3740, causing the [libvirtd build workflow](https://github.com/edgelesssys/constellation/actions/runs/14261151544/job/39972852647) to fail.
- Refer to the correct input.
- [Workflow run after the fix](https://github.com/edgelesssys/constellation/actions/runs/14261846784)
> ci: rename nixpkgs input

- terraform/infrastructure/openstack/main.tf
The STACKIT Terraform provider emits a warning when `region` is used, as it got replaced with `default_region`.
- Update the option name.
> terraform: rename deprecated field for STACKIT

- bazel/toolchains/container_images.bzl
- nix/container/libvirtd_base.nix
https://github.com/edgelesssys/constellation/pull/3752 updated our libvirt base package to include swtpm at [v0.10.0](https://github.com/stefanberger/swtpm/releases/tag/v0.10.0). This in turn caused our e2e tests for [MiniConstellation to fail](https://github.com/edgelesssys/constellation/actions/runs/14394849916/job/40368623919).
I was able to track down the issue to https://github.com/stefanberger/swtpm/pull/896, but as far as I can tell, resolving this issue would require changes in either libvirt or the libvirt terraform provider.
Both solutions are a lot more effort than just keeping swtpm at v0.8.2 for MiniConstellation.
- Pin swtpm to v0.8.2 in our libvirt base image used by MiniConstellation
- Fixes https://github.com/edgelesssys/issues/issues/1558
- [libvirt container …
> mini-constellation: pin swtpm to v0.8.2

- terraform/infrastructure/iam/gcp/main.tf
Certain GCP projects don't have this permission in their SAs, see #3766.
- Add the `compute.forwardingRules.list` permission to the GCP VM SA.
> terraform: add missing GCP IAM permission to VM SA

- terraform/infrastructure/iam/gcp/variables.tf
#3656 missed to add a default value for the `service_account_id` when removing / deprecating it. This caused [a bug](https://github.com/edgelesssys/issues/issues/1584) in the E2E test. 
- Add a default value to the variable, which makes it optional.
> terraform: make GCP SA id optional

- terraform-provider-constellation/internal/provider/cluster_resource.go
The CoreDNS Helm chart needs to be configured with an explicit cluster IP address for the kube-dns service. This IP is derived from the service CIDR, thus the service CIDR is required as an input to the Helm chart loader. #3388 added the CIDR to the CLI code path, but forgot to update the Terraform codepath, preventing customisation of the service CIDR using the Terraform provider.
- Forward service CIDR from Terraform data to Helm chart loader.
- [AB#5594](https://dev.azure.com/Edgeless/ae37573d-ccde-4af2-ab1e-001e587197d1/_workitems/edit/5594)
> terraform-provider: pass ServiceCIDR from resource to chart loader

- renovate.json5
- s3proxy/deploy/deployment-s3proxy.yaml
- s3proxy/deploy/s3proxy/values.yaml
Renovate kept giving us updates for the s3proxy container image.
We don't need these updates for our tests, nor do we make any larger changes to the s3proxy that warrant frequent updates to said image.
Furthermore, a lot of unrelated changes trigger a rebuild of the container image, causing many unrelated PRs to trigger a dependency update
- Exclude s3proxy pseudo version updates from renovate
> renovate: exclude s3proxy pseudo-versions upgrades

- .github/actions/e2e_cleanup_timeframe/e2e-cleanup.sh
- .github/workflows/e2e-cleanup.yml
No reason to only run this once a week. Resources should be cleaned up as quick as possible
- Run clean up once a day
- Don't abort a clean up run if a step fails, instead continue to the end
- Clean up resources from release runs
> ci: run e2e cleanup daily

- internal/constellation/helm/charts/edgeless/constellation-services/charts/ccm/templates/gcp-cm.yaml
- internal/constellation/helm/testdata/GCP/constellation-services/charts/ccm/templates/gcp-cm.yaml
The GCP Cloud Controller Manager should be using the Constellation service account (`google_service_account.service_account`). However, with the current configuration we end up using the ambient service account attached to VMs (`google_service_account.vm`). This is due to its unintuitive token-choosing logic 
1. Default is the metadata server token source: https://github.com/kubernetes/cloud-provider-gcp/blob/ccm/v30.1.4/providers/gce/gce.go#L335.
2. If the config key `token-url` is set to the special string `"nil"`, the default is removed again: https://github.com/kubernetes/cloud-provider-gcp/blob/ccm/v30.1.4/providers/gce/gce.go#L350.
3. When there is no token source configured, a new `google.DefaultTokenSource` is created: https://github.com/kubernetes/cloud-provider-gcp/blob/ccm/v30.1 …
> helm: force app creds in GCP CCM

- .github/actions/e2e_cleanup_timeframe/e2e-cleanup.sh
Our daily cleanup jobs fail if they try to clean up resources on Azure that were already deleted through other means.
This is caused by us including a data source (`azurerm_user_assigned_identity.uaid`) which is only used to generate an output value.
Since Terraform evaluates the file and outputs before running a destroy operation, Terraform tries to evaluate the data source, fails, and then aborts the destroy operation.
- Remove the data source from the Terraform files before running `terraform destroy`
- This data source is only required to generate an ouput value, it has no effect on our other resources, and can be safely ignored
- [test run](https://github.com/edgelesssys/constellation/actions/runs/14966809165/job/42038480420)
> ci: dont fail if Azure resources were already deleted

- go.mod
- go.sum
- renovate.json5
AMD published a new v5 SEV-SNP attestation format in May. AWS has now rolled out updates on their infrastructure to serve reports at v5.
- Update google/go-sev-guest library to support parsing v5 AMD SEV-SNP attestation reports
- [upstream PR](https://github.com/google/go-sev-guest/pull/173)
> deps: update go-sev-guest to support v5 reports

- .github/workflows/e2e-test-daily.yml
- dev-docs/workflows/upgrade-kubernetes.md
We need to do a bunch of version replacements in e2e files when updating k8s. This is error prone and should be easier to do. 
- Suggest a script for updating the versions in the workflow yaml. 
- Fix the version in the daily workflow, which probably escaped grep due to the missing `v` prefix.
> dev-docs: add script for updating k8s versions in workflow files

- go.mod
- go.sum
- renovate.json5
We have a fork of go-sev-guest maintained by the team
- Switch to `edgelesssys/go-sev-guest`
- Remove obsolete renovate ignore rules
- Since the `edgeless` forks have their changes on the `main`/`master` branch, renovate shouldn't try to downgrade the replace directives anymore. This also notifies us in case we update the forks
- Tested this manually on AWS
> deps: switch to edgeless go-sev-guest fork
